/*
 * Software Risk Manager API Guide
 * Software Risk Manager provides a variety of REST APIs, allowing external applications and scripts to interface with core functionality. This guide documents the various REST resources provided by Software Risk Manager.  ## Authentication  Authentication is a requirement when accessing API endpoints. There are two methods by which authentication may be performed.  ### API Keys  The primary method for authentication is passing an `API-Key` header containing a valid API key with all requests, i.e.  `API-Key: <key goes here>`  API Keys come in two possible forms:   - `api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24` - latest format  - `550e8400-e29b-41d4-a716-44665544000` - legacy format  For example:  `API-Key: api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24`  `API-Key: 550e8400-e29b-41d4-a716-44665544000`  API keys may be generated by Software Risk Manager admins. Once they are generated, in most cases, they behave like regular users. They will need to be assigned user roles for any projects they will be used with. Although it is possible to assign the *admin* [role](../user_guide/Project-Management/user_role_configuration.html) to an API key, the recommendation is to avoid doing so unless absolutely necessary.  See the user guide for an overview about how to create and manage [API keys](../user_guide/Settings/api_keys_administration.html).  ### Personal Access Tokens  Personal Access Tokens can be used as [bearer tokens](https://swagger.io/docs/specification/authentication/bearer-authentication/), e.g.  `Authorization: Bearer secret-token:qRuXr1BqgoTWXNxUhYQ8H_Yl2zfy6vxuqMIRnkGO`  Personal Access Tokens can be created by any user, and represent a subset of that user's permissions.   ### HTTP Basic Authentication  HTTP Basic authentication may be used to authenticate with the API as a regular user. This is accomplished by including an `Authorization` header containing a typical authorization credential.  ## Error Handling  ### Bad Requests  For API calls that accept input, invalid values will trigger an HTTP 400 Bad Request status code.  ### Server Errors  For any API call, if an unexpected error occurs, an HTTP 500 Internal Server Error status code will be returned. If an error message is available, the response will include a basic message body describing the error:  ` {   \"error\": \"error message\" } `  The error property will contain a string message indicating the nature of the error.  ### Errors with Third-Party Applications  Sometimes Software Risk Manager must communicate with third-party applications like JIRA, Git, and certain enterprise tools. Some users may have in-house versions of these with self-signed certificates which may not be \"trusted\". In these cases, the API will respond with an HTTP 502 BAD GATEWAY status. If this happens, refer to [Trusting Certificates](../install_guide/Installation/trusting-certs.html) in the install guide.  ### API Unavailable  In special circumstances, particularly during the installation and update phases, the API will be unavailable. When the API is unavailable, all calls will return an HTTP 503 Service Unavailable status, and no actions or side effects will occur as a result of the calls.  ## Examples  Software Risk Manager's API uses REST over HTTP. As such, you can use any language/utility that supports making HTTP requests to interact with the API. The examples below use <a href=\"https://curl.haxx.se/\" target=\"_blank\">curl</a>, a popular command-line utility, to do so.  First, you'll need to [generate an API Key](../user_guide/Settings/api_keys_administration.html). Second, while you can create projects through the API, these examples will assume that you've already created one. You'll need to know its project id number, which you can find by looking at the URL for the [Findings Page](../user_guide/Findings/findings_overview.html), which will end in a number.  **Note:** Many API endpoints require a JSON body in the request. Most JSON will contain double-quotes (`\"`) and spaces, which have special meaning when used on the command line. In order to ensure your JSON body is interpreted as a single argument, you must <a href=\"https://en.wikipedia.org/wiki/Escape_character\" target=\"_blank\">escape</a> it properly. For example, if you wanted to `POST` the following JSON body:  ```{ \"name\": \"John Doe\" }```  You would put a backslash (`\\`) before each double-quote (`\"`), and surround the whole thing with double-quotes:  ```\"{ \\\"name\\\": \\\"John Doe\\\" }\"```  The outermost double-quotes tell the command-line interpreter that everything within them is to be treated as a single argument (as opposed to the usual space-separated behavior). The backslash before each inner double-quote tells the command-line interpreter that you mean the literal double-quote character, and not the end of the quoted argument.  In many *non-Windows* operating systems, you can also use a single-quote (`'`) to surround the argument, and skip the backslashes:  ```'{ \"name\": \"John Doe\" }'```  The examples below will use the double-quotes and backslashes style, as it works on most (if not all) operating systems.  ### Running an Analysis  To start an analysis, you can run  ```curl -F file1=@src.zip -H \"API-Key: api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24\" https://<yoursrmserver>/srm/api/projects/<project id>/analysis```  Make sure you use your own values for the `src.zip` file, the API Key, the hostname for your Software Risk Manager server, and the project id.  ### Retrieving Finding Data  There is a wide variety of data available for the findings of a project after running an analysis. Two examples are provided here.  ### Findings Table Data  You can retrieve the data that's used to populate the [findings table](../user_guide/Findings/findings_table.html):  ```curl -H \"Content-Type: application/json\" -X POST -d \"{\\\"filter\\\":{},\\\"sort\\\":{\\\"by\\\":\\\"id\\\",\\\"direction\\\":\\\"ascending\\\"},\\\"pagination\\\":{\\\"page\\\":1,\\\"perPage\\\":10}}\" -H \"API-Key: api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24\" https://<yoursrmserver>/srm/api/projects/<project id>/findings/table```  Additional information about how to construct more useful filter and sort requests can be found in the documentation.  ### Finding Metadata  You can retrieve metadata for a finding, if you know the finding ID. You can take the ID for a finding from the Findings Table:  ```curl -H \"API-Key: api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24\" https://<yoursrmserver>/srm/api/findings/<finding id>```  ### Generating a Report  You can use the API to generate a PDF [report](../user_guide/Findings/generate_report.html).  ```curl -H \"Content-Type: application/json\" -X POST -d \"{\\\"filter\\\":{},\\\"config\\\":{\\\"summaryMode\\\":\\\"simple\\\",\\\"detailsMode\\\":\\\"simple\\\",\\\"includeResultDetails\\\":true,\\\"includeComments\\\":false}}\" -H \"API-Key: api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24\" https://<yoursrmserver>/srm/api/projects/<project id>/report/pdf```  ## Generating a Client SDK  If you require a client SDK for Software Risk Manager, you can generate one using [OpenAPI Generator](https://openapi-generator.tech/). Detailed instructions are available on the [GitHub page](https://github.com/OpenAPITools/openapi-generator) and our OpenAPI spec can be found [here](swagger/swagger.json). 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.codedx.client.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.codedx.client.model.SimpleIntegration;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.codedx.client.JSON;


/**
 * AllIntegrations
 */
@JsonPropertyOrder({
  AllIntegrations.JSON_PROPERTY_TOOL_CONNECTOR,
  AllIntegrations.JSON_PROPERTY_BUNDLED_TOOL,
  AllIntegrations.JSON_PROPERTY_TOOL_READER,
  AllIntegrations.JSON_PROPERTY_SBOM,
  AllIntegrations.JSON_PROPERTY_PLUGIN,
  AllIntegrations.JSON_PROPERTY_ISSUE_TRACKER,
  AllIntegrations.JSON_PROPERTY_SCM,
  AllIntegrations.JSON_PROPERTY_CI,
  AllIntegrations.JSON_PROPERTY_IDE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-02T11:55:06.722228-04:00[America/New_York]", comments = "Generator version: 7.21.0")
public class AllIntegrations {
  public static final String JSON_PROPERTY_TOOL_CONNECTOR = "tool-connector";
  @jakarta.annotation.Nullable
  private List<SimpleIntegration> toolConnector = new ArrayList<>();

  public static final String JSON_PROPERTY_BUNDLED_TOOL = "bundled-tool";
  @jakarta.annotation.Nullable
  private List<SimpleIntegration> bundledTool = new ArrayList<>();

  public static final String JSON_PROPERTY_TOOL_READER = "tool-reader";
  @jakarta.annotation.Nullable
  private List<SimpleIntegration> toolReader = new ArrayList<>();

  public static final String JSON_PROPERTY_SBOM = "sbom";
  @jakarta.annotation.Nullable
  private List<SimpleIntegration> sbom = new ArrayList<>();

  public static final String JSON_PROPERTY_PLUGIN = "plugin";
  @jakarta.annotation.Nullable
  private List<SimpleIntegration> plugin = new ArrayList<>();

  public static final String JSON_PROPERTY_ISSUE_TRACKER = "issue-tracker";
  @jakarta.annotation.Nullable
  private List<SimpleIntegration> issueTracker = new ArrayList<>();

  public static final String JSON_PROPERTY_SCM = "scm";
  @jakarta.annotation.Nullable
  private List<SimpleIntegration> scm = new ArrayList<>();

  public static final String JSON_PROPERTY_CI = "ci";
  @jakarta.annotation.Nullable
  private List<SimpleIntegration> ci = new ArrayList<>();

  public static final String JSON_PROPERTY_IDE = "ide";
  @jakarta.annotation.Nullable
  private List<SimpleIntegration> ide = new ArrayList<>();

  public AllIntegrations() { 
  }

  public AllIntegrations toolConnector(@jakarta.annotation.Nullable List<SimpleIntegration> toolConnector) {
    this.toolConnector = toolConnector;
    return this;
  }

  public AllIntegrations addToolConnectorItem(SimpleIntegration toolConnectorItem) {
    if (this.toolConnector == null) {
      this.toolConnector = new ArrayList<>();
    }
    this.toolConnector.add(toolConnectorItem);
    return this;
  }

  /**
   * Get toolConnector
   * @return toolConnector
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TOOL_CONNECTOR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<SimpleIntegration> getToolConnector() {
    return toolConnector;
  }


  @JsonProperty(value = JSON_PROPERTY_TOOL_CONNECTOR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setToolConnector(@jakarta.annotation.Nullable List<SimpleIntegration> toolConnector) {
    this.toolConnector = toolConnector;
  }


  public AllIntegrations bundledTool(@jakarta.annotation.Nullable List<SimpleIntegration> bundledTool) {
    this.bundledTool = bundledTool;
    return this;
  }

  public AllIntegrations addBundledToolItem(SimpleIntegration bundledToolItem) {
    if (this.bundledTool == null) {
      this.bundledTool = new ArrayList<>();
    }
    this.bundledTool.add(bundledToolItem);
    return this;
  }

  /**
   * Get bundledTool
   * @return bundledTool
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BUNDLED_TOOL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<SimpleIntegration> getBundledTool() {
    return bundledTool;
  }


  @JsonProperty(value = JSON_PROPERTY_BUNDLED_TOOL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBundledTool(@jakarta.annotation.Nullable List<SimpleIntegration> bundledTool) {
    this.bundledTool = bundledTool;
  }


  public AllIntegrations toolReader(@jakarta.annotation.Nullable List<SimpleIntegration> toolReader) {
    this.toolReader = toolReader;
    return this;
  }

  public AllIntegrations addToolReaderItem(SimpleIntegration toolReaderItem) {
    if (this.toolReader == null) {
      this.toolReader = new ArrayList<>();
    }
    this.toolReader.add(toolReaderItem);
    return this;
  }

  /**
   * Get toolReader
   * @return toolReader
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TOOL_READER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<SimpleIntegration> getToolReader() {
    return toolReader;
  }


  @JsonProperty(value = JSON_PROPERTY_TOOL_READER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setToolReader(@jakarta.annotation.Nullable List<SimpleIntegration> toolReader) {
    this.toolReader = toolReader;
  }


  public AllIntegrations sbom(@jakarta.annotation.Nullable List<SimpleIntegration> sbom) {
    this.sbom = sbom;
    return this;
  }

  public AllIntegrations addSbomItem(SimpleIntegration sbomItem) {
    if (this.sbom == null) {
      this.sbom = new ArrayList<>();
    }
    this.sbom.add(sbomItem);
    return this;
  }

  /**
   * Get sbom
   * @return sbom
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SBOM, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<SimpleIntegration> getSbom() {
    return sbom;
  }


  @JsonProperty(value = JSON_PROPERTY_SBOM, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSbom(@jakarta.annotation.Nullable List<SimpleIntegration> sbom) {
    this.sbom = sbom;
  }


  public AllIntegrations plugin(@jakarta.annotation.Nullable List<SimpleIntegration> plugin) {
    this.plugin = plugin;
    return this;
  }

  public AllIntegrations addPluginItem(SimpleIntegration pluginItem) {
    if (this.plugin == null) {
      this.plugin = new ArrayList<>();
    }
    this.plugin.add(pluginItem);
    return this;
  }

  /**
   * Get plugin
   * @return plugin
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PLUGIN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<SimpleIntegration> getPlugin() {
    return plugin;
  }


  @JsonProperty(value = JSON_PROPERTY_PLUGIN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPlugin(@jakarta.annotation.Nullable List<SimpleIntegration> plugin) {
    this.plugin = plugin;
  }


  public AllIntegrations issueTracker(@jakarta.annotation.Nullable List<SimpleIntegration> issueTracker) {
    this.issueTracker = issueTracker;
    return this;
  }

  public AllIntegrations addIssueTrackerItem(SimpleIntegration issueTrackerItem) {
    if (this.issueTracker == null) {
      this.issueTracker = new ArrayList<>();
    }
    this.issueTracker.add(issueTrackerItem);
    return this;
  }

  /**
   * Get issueTracker
   * @return issueTracker
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ISSUE_TRACKER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<SimpleIntegration> getIssueTracker() {
    return issueTracker;
  }


  @JsonProperty(value = JSON_PROPERTY_ISSUE_TRACKER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIssueTracker(@jakarta.annotation.Nullable List<SimpleIntegration> issueTracker) {
    this.issueTracker = issueTracker;
  }


  public AllIntegrations scm(@jakarta.annotation.Nullable List<SimpleIntegration> scm) {
    this.scm = scm;
    return this;
  }

  public AllIntegrations addScmItem(SimpleIntegration scmItem) {
    if (this.scm == null) {
      this.scm = new ArrayList<>();
    }
    this.scm.add(scmItem);
    return this;
  }

  /**
   * Get scm
   * @return scm
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SCM, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<SimpleIntegration> getScm() {
    return scm;
  }


  @JsonProperty(value = JSON_PROPERTY_SCM, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setScm(@jakarta.annotation.Nullable List<SimpleIntegration> scm) {
    this.scm = scm;
  }


  public AllIntegrations ci(@jakarta.annotation.Nullable List<SimpleIntegration> ci) {
    this.ci = ci;
    return this;
  }

  public AllIntegrations addCiItem(SimpleIntegration ciItem) {
    if (this.ci == null) {
      this.ci = new ArrayList<>();
    }
    this.ci.add(ciItem);
    return this;
  }

  /**
   * Get ci
   * @return ci
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CI, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<SimpleIntegration> getCi() {
    return ci;
  }


  @JsonProperty(value = JSON_PROPERTY_CI, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCi(@jakarta.annotation.Nullable List<SimpleIntegration> ci) {
    this.ci = ci;
  }


  public AllIntegrations ide(@jakarta.annotation.Nullable List<SimpleIntegration> ide) {
    this.ide = ide;
    return this;
  }

  public AllIntegrations addIdeItem(SimpleIntegration ideItem) {
    if (this.ide == null) {
      this.ide = new ArrayList<>();
    }
    this.ide.add(ideItem);
    return this;
  }

  /**
   * Get ide
   * @return ide
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_IDE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<SimpleIntegration> getIde() {
    return ide;
  }


  @JsonProperty(value = JSON_PROPERTY_IDE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIde(@jakarta.annotation.Nullable List<SimpleIntegration> ide) {
    this.ide = ide;
  }


  /**
   * Return true if this AllIntegrations object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AllIntegrations allIntegrations = (AllIntegrations) o;
    return Objects.equals(this.toolConnector, allIntegrations.toolConnector) &&
        Objects.equals(this.bundledTool, allIntegrations.bundledTool) &&
        Objects.equals(this.toolReader, allIntegrations.toolReader) &&
        Objects.equals(this.sbom, allIntegrations.sbom) &&
        Objects.equals(this.plugin, allIntegrations.plugin) &&
        Objects.equals(this.issueTracker, allIntegrations.issueTracker) &&
        Objects.equals(this.scm, allIntegrations.scm) &&
        Objects.equals(this.ci, allIntegrations.ci) &&
        Objects.equals(this.ide, allIntegrations.ide);
  }

  @Override
  public int hashCode() {
    return Objects.hash(toolConnector, bundledTool, toolReader, sbom, plugin, issueTracker, scm, ci, ide);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AllIntegrations {\n");
    sb.append("    toolConnector: ").append(toIndentedString(toolConnector)).append("\n");
    sb.append("    bundledTool: ").append(toIndentedString(bundledTool)).append("\n");
    sb.append("    toolReader: ").append(toIndentedString(toolReader)).append("\n");
    sb.append("    sbom: ").append(toIndentedString(sbom)).append("\n");
    sb.append("    plugin: ").append(toIndentedString(plugin)).append("\n");
    sb.append("    issueTracker: ").append(toIndentedString(issueTracker)).append("\n");
    sb.append("    scm: ").append(toIndentedString(scm)).append("\n");
    sb.append("    ci: ").append(toIndentedString(ci)).append("\n");
    sb.append("    ide: ").append(toIndentedString(ide)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

