/*
 * Software Risk Manager API Guide
 * Software Risk Manager provides a variety of REST APIs, allowing external applications and scripts to interface with core functionality. This guide documents the various REST resources provided by Software Risk Manager.  ## Authentication  Authentication is a requirement when accessing API endpoints. There are two methods by which authentication may be performed.  ### API Keys  The primary method for authentication is passing an `API-Key` header containing a valid API key with all requests, i.e.  `API-Key: <key goes here>`  API Keys come in two possible forms:   - `api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24` - latest format  - `550e8400-e29b-41d4-a716-44665544000` - legacy format  For example:  `API-Key: api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24`  `API-Key: 550e8400-e29b-41d4-a716-44665544000`  API keys may be generated by Software Risk Manager admins. Once they are generated, in most cases, they behave like regular users. They will need to be assigned user roles for any projects they will be used with. Although it is possible to assign the *admin* [role](../user_guide/Project-Management/user_role_configuration.html) to an API key, the recommendation is to avoid doing so unless absolutely necessary.  See the user guide for an overview about how to create and manage [API keys](../user_guide/Settings/api_keys_administration.html).  ### Personal Access Tokens  Personal Access Tokens can be used as [bearer tokens](https://swagger.io/docs/specification/authentication/bearer-authentication/), e.g.  `Authorization: Bearer secret-token:qRuXr1BqgoTWXNxUhYQ8H_Yl2zfy6vxuqMIRnkGO`  Personal Access Tokens can be created by any user, and represent a subset of that user's permissions.   ### HTTP Basic Authentication  HTTP Basic authentication may be used to authenticate with the API as a regular user. This is accomplished by including an `Authorization` header containing a typical authorization credential.  ## Error Handling  ### Bad Requests  For API calls that accept input, invalid values will trigger an HTTP 400 Bad Request status code.  ### Server Errors  For any API call, if an unexpected error occurs, an HTTP 500 Internal Server Error status code will be returned. If an error message is available, the response will include a basic message body describing the error:  ` {   \"error\": \"error message\" } `  The error property will contain a string message indicating the nature of the error.  ### Errors with Third-Party Applications  Sometimes Software Risk Manager must communicate with third-party applications like JIRA, Git, and certain enterprise tools. Some users may have in-house versions of these with self-signed certificates which may not be \"trusted\". In these cases, the API will respond with an HTTP 502 BAD GATEWAY status. If this happens, refer to [Trusting Certificates](../install_guide/Installation/trusting-certs.html) in the install guide.  ### API Unavailable  In special circumstances, particularly during the installation and update phases, the API will be unavailable. When the API is unavailable, all calls will return an HTTP 503 Service Unavailable status, and no actions or side effects will occur as a result of the calls.  ## Examples  Software Risk Manager's API uses REST over HTTP. As such, you can use any language/utility that supports making HTTP requests to interact with the API. The examples below use <a href=\"https://curl.haxx.se/\" target=\"_blank\">curl</a>, a popular command-line utility, to do so.  First, you'll need to [generate an API Key](../user_guide/Settings/api_keys_administration.html). Second, while you can create projects through the API, these examples will assume that you've already created one. You'll need to know its project id number, which you can find by looking at the URL for the [Findings Page](../user_guide/Findings/findings_overview.html), which will end in a number.  **Note:** Many API endpoints require a JSON body in the request. Most JSON will contain double-quotes (`\"`) and spaces, which have special meaning when used on the command line. In order to ensure your JSON body is interpreted as a single argument, you must <a href=\"https://en.wikipedia.org/wiki/Escape_character\" target=\"_blank\">escape</a> it properly. For example, if you wanted to `POST` the following JSON body:  ```{ \"name\": \"John Doe\" }```  You would put a backslash (`\\`) before each double-quote (`\"`), and surround the whole thing with double-quotes:  ```\"{ \\\"name\\\": \\\"John Doe\\\" }\"```  The outermost double-quotes tell the command-line interpreter that everything within them is to be treated as a single argument (as opposed to the usual space-separated behavior). The backslash before each inner double-quote tells the command-line interpreter that you mean the literal double-quote character, and not the end of the quoted argument.  In many *non-Windows* operating systems, you can also use a single-quote (`'`) to surround the argument, and skip the backslashes:  ```'{ \"name\": \"John Doe\" }'```  The examples below will use the double-quotes and backslashes style, as it works on most (if not all) operating systems.  ### Running an Analysis  To start an analysis, you can run  ```curl -F file1=@src.zip -H \"API-Key: api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24\" https://<yoursrmserver>/srm/api/projects/<project id>/analysis```  Make sure you use your own values for the `src.zip` file, the API Key, the hostname for your Software Risk Manager server, and the project id.  ### Retrieving Finding Data  There is a wide variety of data available for the findings of a project after running an analysis. Two examples are provided here.  ### Findings Table Data  You can retrieve the data that's used to populate the [findings table](../user_guide/Findings/findings_table.html):  ```curl -H \"Content-Type: application/json\" -X POST -d \"{\\\"filter\\\":{},\\\"sort\\\":{\\\"by\\\":\\\"id\\\",\\\"direction\\\":\\\"ascending\\\"},\\\"pagination\\\":{\\\"page\\\":1,\\\"perPage\\\":10}}\" -H \"API-Key: api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24\" https://<yoursrmserver>/srm/api/projects/<project id>/findings/table```  Additional information about how to construct more useful filter and sort requests can be found in the documentation.  ### Finding Metadata  You can retrieve metadata for a finding, if you know the finding ID. You can take the ID for a finding from the Findings Table:  ```curl -H \"API-Key: api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24\" https://<yoursrmserver>/srm/api/findings/<finding id>```  ### Generating a Report  You can use the API to generate a PDF [report](../user_guide/Findings/generate_report.html).  ```curl -H \"Content-Type: application/json\" -X POST -d \"{\\\"filter\\\":{},\\\"config\\\":{\\\"summaryMode\\\":\\\"simple\\\",\\\"detailsMode\\\":\\\"simple\\\",\\\"includeResultDetails\\\":true,\\\"includeComments\\\":false}}\" -H \"API-Key: api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24\" https://<yoursrmserver>/srm/api/projects/<project id>/report/pdf```  ## Generating a Client SDK  If you require a client SDK for Software Risk Manager, you can generate one using [OpenAPI Generator](https://openapi-generator.tech/). Detailed instructions are available on the [GitHub page](https://github.com/OpenAPITools/openapi-generator) and our OpenAPI spec can be found [here](swagger/swagger.json). 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.codedx.client.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.codedx.client.model.IssueTrackerUser;
import com.codedx.client.model.ToolOverlapsFilter;
import com.codedx.client.model.TriageConfidenceFilter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.codedx.client.JSON;


/**
 * AutoCreateConfig
 */
@JsonPropertyOrder({
  AutoCreateConfig.JSON_PROPERTY_ASSIGNEE_USER,
  AutoCreateConfig.JSON_PROPERTY_BRANCH_FILTER,
  AutoCreateConfig.JSON_PROPERTY_CWE_FILTER,
  AutoCreateConfig.JSON_PROPERTY_DETECTION_METHOD_FILTER,
  AutoCreateConfig.JSON_PROPERTY_GROUPING_TYPE,
  AutoCreateConfig.JSON_PROPERTY_ISSUE_TYPE,
  AutoCreateConfig.JSON_PROPERTY_ONLY_NEW,
  AutoCreateConfig.JSON_PROPERTY_RULE_FILTER,
  AutoCreateConfig.JSON_PROPERTY_SEVERITY_FILTER,
  AutoCreateConfig.JSON_PROPERTY_STANDARD_FILTER,
  AutoCreateConfig.JSON_PROPERTY_TITLE_TEMPLATE,
  AutoCreateConfig.JSON_PROPERTY_TOOL_FILTER,
  AutoCreateConfig.JSON_PROPERTY_TOOL_OVERLAPS_FILTER,
  AutoCreateConfig.JSON_PROPERTY_TRIAGE_CONFIDENCE_FILTER
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-02T11:55:06.722228-04:00[America/New_York]", comments = "Generator version: 7.21.0")
public class AutoCreateConfig {
  public static final String JSON_PROPERTY_ASSIGNEE_USER = "assigneeUser";
  @jakarta.annotation.Nullable
  private IssueTrackerUser assigneeUser;

  public static final String JSON_PROPERTY_BRANCH_FILTER = "branchFilter";
  private JsonNullable<List<Integer>> branchFilter = JsonNullable.<List<Integer>>undefined();

  public static final String JSON_PROPERTY_CWE_FILTER = "cweFilter";
  @jakarta.annotation.Nullable
  private List<Integer> cweFilter = new ArrayList<>();

  public static final String JSON_PROPERTY_DETECTION_METHOD_FILTER = "detectionMethodFilter";
  @jakarta.annotation.Nullable
  private List<String> detectionMethodFilter = new ArrayList<>();

  public static final String JSON_PROPERTY_GROUPING_TYPE = "groupingType";
  @jakarta.annotation.Nullable
  private List<String> groupingType = new ArrayList<>();

  public static final String JSON_PROPERTY_ISSUE_TYPE = "issueType";
  @jakarta.annotation.Nullable
  private String issueType;

  public static final String JSON_PROPERTY_ONLY_NEW = "onlyNew";
  @jakarta.annotation.Nullable
  private Boolean onlyNew;

  public static final String JSON_PROPERTY_RULE_FILTER = "ruleFilter";
  @jakarta.annotation.Nullable
  private List<Integer> ruleFilter = new ArrayList<>();

  public static final String JSON_PROPERTY_SEVERITY_FILTER = "severityFilter";
  @jakarta.annotation.Nullable
  private List<String> severityFilter = new ArrayList<>();

  public static final String JSON_PROPERTY_STANDARD_FILTER = "standardFilter";
  @jakarta.annotation.Nullable
  private List<String> standardFilter = new ArrayList<>();

  public static final String JSON_PROPERTY_TITLE_TEMPLATE = "titleTemplate";
  @jakarta.annotation.Nullable
  private String titleTemplate;

  public static final String JSON_PROPERTY_TOOL_FILTER = "toolFilter";
  @jakarta.annotation.Nullable
  private List<Integer> toolFilter = new ArrayList<>();

  public static final String JSON_PROPERTY_TOOL_OVERLAPS_FILTER = "toolOverlapsFilter";
  @jakarta.annotation.Nullable
  private ToolOverlapsFilter toolOverlapsFilter;

  public static final String JSON_PROPERTY_TRIAGE_CONFIDENCE_FILTER = "triageConfidenceFilter";
  @jakarta.annotation.Nullable
  private TriageConfidenceFilter triageConfidenceFilter;

  public AutoCreateConfig() { 
  }

  public AutoCreateConfig assigneeUser(@jakarta.annotation.Nullable IssueTrackerUser assigneeUser) {
    this.assigneeUser = assigneeUser;
    return this;
  }

  /**
   * Get assigneeUser
   * @return assigneeUser
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ASSIGNEE_USER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public IssueTrackerUser getAssigneeUser() {
    return assigneeUser;
  }


  @JsonProperty(value = JSON_PROPERTY_ASSIGNEE_USER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAssigneeUser(@jakarta.annotation.Nullable IssueTrackerUser assigneeUser) {
    this.assigneeUser = assigneeUser;
  }


  public AutoCreateConfig branchFilter(@jakarta.annotation.Nullable List<Integer> branchFilter) {
    this.branchFilter = JsonNullable.<List<Integer>>of(branchFilter);
    return this;
  }

  public AutoCreateConfig addBranchFilterItem(Integer branchFilterItem) {
    if (this.branchFilter == null || !this.branchFilter.isPresent()) {
      this.branchFilter = JsonNullable.<List<Integer>>of(new ArrayList<>());
    }
    try {
      this.branchFilter.get().add(branchFilterItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Get branchFilter
   * @return branchFilter
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public List<Integer> getBranchFilter() {
        return branchFilter.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_BRANCH_FILTER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<List<Integer>> getBranchFilter_JsonNullable() {
    return branchFilter;
  }
  
  @JsonProperty(JSON_PROPERTY_BRANCH_FILTER)
  public void setBranchFilter_JsonNullable(JsonNullable<List<Integer>> branchFilter) {
    this.branchFilter = branchFilter;
  }

  public void setBranchFilter(@jakarta.annotation.Nullable List<Integer> branchFilter) {
    this.branchFilter = JsonNullable.<List<Integer>>of(branchFilter);
  }


  public AutoCreateConfig cweFilter(@jakarta.annotation.Nullable List<Integer> cweFilter) {
    this.cweFilter = cweFilter;
    return this;
  }

  public AutoCreateConfig addCweFilterItem(Integer cweFilterItem) {
    if (this.cweFilter == null) {
      this.cweFilter = new ArrayList<>();
    }
    this.cweFilter.add(cweFilterItem);
    return this;
  }

  /**
   * Get cweFilter
   * @return cweFilter
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CWE_FILTER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Integer> getCweFilter() {
    return cweFilter;
  }


  @JsonProperty(value = JSON_PROPERTY_CWE_FILTER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCweFilter(@jakarta.annotation.Nullable List<Integer> cweFilter) {
    this.cweFilter = cweFilter;
  }


  public AutoCreateConfig detectionMethodFilter(@jakarta.annotation.Nullable List<String> detectionMethodFilter) {
    this.detectionMethodFilter = detectionMethodFilter;
    return this;
  }

  public AutoCreateConfig addDetectionMethodFilterItem(String detectionMethodFilterItem) {
    if (this.detectionMethodFilter == null) {
      this.detectionMethodFilter = new ArrayList<>();
    }
    this.detectionMethodFilter.add(detectionMethodFilterItem);
    return this;
  }

  /**
   * Get detectionMethodFilter
   * @return detectionMethodFilter
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DETECTION_METHOD_FILTER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getDetectionMethodFilter() {
    return detectionMethodFilter;
  }


  @JsonProperty(value = JSON_PROPERTY_DETECTION_METHOD_FILTER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDetectionMethodFilter(@jakarta.annotation.Nullable List<String> detectionMethodFilter) {
    this.detectionMethodFilter = detectionMethodFilter;
  }


  public AutoCreateConfig groupingType(@jakarta.annotation.Nullable List<String> groupingType) {
    this.groupingType = groupingType;
    return this;
  }

  public AutoCreateConfig addGroupingTypeItem(String groupingTypeItem) {
    if (this.groupingType == null) {
      this.groupingType = new ArrayList<>();
    }
    this.groupingType.add(groupingTypeItem);
    return this;
  }

  /**
   * Get groupingType
   * @return groupingType
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_GROUPING_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getGroupingType() {
    return groupingType;
  }


  @JsonProperty(value = JSON_PROPERTY_GROUPING_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGroupingType(@jakarta.annotation.Nullable List<String> groupingType) {
    this.groupingType = groupingType;
  }


  public AutoCreateConfig issueType(@jakarta.annotation.Nullable String issueType) {
    this.issueType = issueType;
    return this;
  }

  /**
   * Get issueType
   * @return issueType
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ISSUE_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getIssueType() {
    return issueType;
  }


  @JsonProperty(value = JSON_PROPERTY_ISSUE_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIssueType(@jakarta.annotation.Nullable String issueType) {
    this.issueType = issueType;
  }


  public AutoCreateConfig onlyNew(@jakarta.annotation.Nullable Boolean onlyNew) {
    this.onlyNew = onlyNew;
    return this;
  }

  /**
   * Get onlyNew
   * @return onlyNew
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ONLY_NEW, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getOnlyNew() {
    return onlyNew;
  }


  @JsonProperty(value = JSON_PROPERTY_ONLY_NEW, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOnlyNew(@jakarta.annotation.Nullable Boolean onlyNew) {
    this.onlyNew = onlyNew;
  }


  public AutoCreateConfig ruleFilter(@jakarta.annotation.Nullable List<Integer> ruleFilter) {
    this.ruleFilter = ruleFilter;
    return this;
  }

  public AutoCreateConfig addRuleFilterItem(Integer ruleFilterItem) {
    if (this.ruleFilter == null) {
      this.ruleFilter = new ArrayList<>();
    }
    this.ruleFilter.add(ruleFilterItem);
    return this;
  }

  /**
   * Get ruleFilter
   * @return ruleFilter
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_RULE_FILTER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Integer> getRuleFilter() {
    return ruleFilter;
  }


  @JsonProperty(value = JSON_PROPERTY_RULE_FILTER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRuleFilter(@jakarta.annotation.Nullable List<Integer> ruleFilter) {
    this.ruleFilter = ruleFilter;
  }


  public AutoCreateConfig severityFilter(@jakarta.annotation.Nullable List<String> severityFilter) {
    this.severityFilter = severityFilter;
    return this;
  }

  public AutoCreateConfig addSeverityFilterItem(String severityFilterItem) {
    if (this.severityFilter == null) {
      this.severityFilter = new ArrayList<>();
    }
    this.severityFilter.add(severityFilterItem);
    return this;
  }

  /**
   * Get severityFilter
   * @return severityFilter
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SEVERITY_FILTER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getSeverityFilter() {
    return severityFilter;
  }


  @JsonProperty(value = JSON_PROPERTY_SEVERITY_FILTER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSeverityFilter(@jakarta.annotation.Nullable List<String> severityFilter) {
    this.severityFilter = severityFilter;
  }


  public AutoCreateConfig standardFilter(@jakarta.annotation.Nullable List<String> standardFilter) {
    this.standardFilter = standardFilter;
    return this;
  }

  public AutoCreateConfig addStandardFilterItem(String standardFilterItem) {
    if (this.standardFilter == null) {
      this.standardFilter = new ArrayList<>();
    }
    this.standardFilter.add(standardFilterItem);
    return this;
  }

  /**
   * Get standardFilter
   * @return standardFilter
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_STANDARD_FILTER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getStandardFilter() {
    return standardFilter;
  }


  @JsonProperty(value = JSON_PROPERTY_STANDARD_FILTER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStandardFilter(@jakarta.annotation.Nullable List<String> standardFilter) {
    this.standardFilter = standardFilter;
  }


  public AutoCreateConfig titleTemplate(@jakarta.annotation.Nullable String titleTemplate) {
    this.titleTemplate = titleTemplate;
    return this;
  }

  /**
   * Get titleTemplate
   * @return titleTemplate
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TITLE_TEMPLATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTitleTemplate() {
    return titleTemplate;
  }


  @JsonProperty(value = JSON_PROPERTY_TITLE_TEMPLATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTitleTemplate(@jakarta.annotation.Nullable String titleTemplate) {
    this.titleTemplate = titleTemplate;
  }


  public AutoCreateConfig toolFilter(@jakarta.annotation.Nullable List<Integer> toolFilter) {
    this.toolFilter = toolFilter;
    return this;
  }

  public AutoCreateConfig addToolFilterItem(Integer toolFilterItem) {
    if (this.toolFilter == null) {
      this.toolFilter = new ArrayList<>();
    }
    this.toolFilter.add(toolFilterItem);
    return this;
  }

  /**
   * Get toolFilter
   * @return toolFilter
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TOOL_FILTER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Integer> getToolFilter() {
    return toolFilter;
  }


  @JsonProperty(value = JSON_PROPERTY_TOOL_FILTER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setToolFilter(@jakarta.annotation.Nullable List<Integer> toolFilter) {
    this.toolFilter = toolFilter;
  }


  public AutoCreateConfig toolOverlapsFilter(@jakarta.annotation.Nullable ToolOverlapsFilter toolOverlapsFilter) {
    this.toolOverlapsFilter = toolOverlapsFilter;
    return this;
  }

  /**
   * Get toolOverlapsFilter
   * @return toolOverlapsFilter
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TOOL_OVERLAPS_FILTER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ToolOverlapsFilter getToolOverlapsFilter() {
    return toolOverlapsFilter;
  }


  @JsonProperty(value = JSON_PROPERTY_TOOL_OVERLAPS_FILTER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setToolOverlapsFilter(@jakarta.annotation.Nullable ToolOverlapsFilter toolOverlapsFilter) {
    this.toolOverlapsFilter = toolOverlapsFilter;
  }


  public AutoCreateConfig triageConfidenceFilter(@jakarta.annotation.Nullable TriageConfidenceFilter triageConfidenceFilter) {
    this.triageConfidenceFilter = triageConfidenceFilter;
    return this;
  }

  /**
   * Get triageConfidenceFilter
   * @return triageConfidenceFilter
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TRIAGE_CONFIDENCE_FILTER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public TriageConfidenceFilter getTriageConfidenceFilter() {
    return triageConfidenceFilter;
  }


  @JsonProperty(value = JSON_PROPERTY_TRIAGE_CONFIDENCE_FILTER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTriageConfidenceFilter(@jakarta.annotation.Nullable TriageConfidenceFilter triageConfidenceFilter) {
    this.triageConfidenceFilter = triageConfidenceFilter;
  }


  /**
   * Return true if this AutoCreateConfig object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AutoCreateConfig autoCreateConfig = (AutoCreateConfig) o;
    return Objects.equals(this.assigneeUser, autoCreateConfig.assigneeUser) &&
        equalsNullable(this.branchFilter, autoCreateConfig.branchFilter) &&
        Objects.equals(this.cweFilter, autoCreateConfig.cweFilter) &&
        Objects.equals(this.detectionMethodFilter, autoCreateConfig.detectionMethodFilter) &&
        Objects.equals(this.groupingType, autoCreateConfig.groupingType) &&
        Objects.equals(this.issueType, autoCreateConfig.issueType) &&
        Objects.equals(this.onlyNew, autoCreateConfig.onlyNew) &&
        Objects.equals(this.ruleFilter, autoCreateConfig.ruleFilter) &&
        Objects.equals(this.severityFilter, autoCreateConfig.severityFilter) &&
        Objects.equals(this.standardFilter, autoCreateConfig.standardFilter) &&
        Objects.equals(this.titleTemplate, autoCreateConfig.titleTemplate) &&
        Objects.equals(this.toolFilter, autoCreateConfig.toolFilter) &&
        Objects.equals(this.toolOverlapsFilter, autoCreateConfig.toolOverlapsFilter) &&
        Objects.equals(this.triageConfidenceFilter, autoCreateConfig.triageConfidenceFilter);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(assigneeUser, hashCodeNullable(branchFilter), cweFilter, detectionMethodFilter, groupingType, issueType, onlyNew, ruleFilter, severityFilter, standardFilter, titleTemplate, toolFilter, toolOverlapsFilter, triageConfidenceFilter);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AutoCreateConfig {\n");
    sb.append("    assigneeUser: ").append(toIndentedString(assigneeUser)).append("\n");
    sb.append("    branchFilter: ").append(toIndentedString(branchFilter)).append("\n");
    sb.append("    cweFilter: ").append(toIndentedString(cweFilter)).append("\n");
    sb.append("    detectionMethodFilter: ").append(toIndentedString(detectionMethodFilter)).append("\n");
    sb.append("    groupingType: ").append(toIndentedString(groupingType)).append("\n");
    sb.append("    issueType: ").append(toIndentedString(issueType)).append("\n");
    sb.append("    onlyNew: ").append(toIndentedString(onlyNew)).append("\n");
    sb.append("    ruleFilter: ").append(toIndentedString(ruleFilter)).append("\n");
    sb.append("    severityFilter: ").append(toIndentedString(severityFilter)).append("\n");
    sb.append("    standardFilter: ").append(toIndentedString(standardFilter)).append("\n");
    sb.append("    titleTemplate: ").append(toIndentedString(titleTemplate)).append("\n");
    sb.append("    toolFilter: ").append(toIndentedString(toolFilter)).append("\n");
    sb.append("    toolOverlapsFilter: ").append(toIndentedString(toolOverlapsFilter)).append("\n");
    sb.append("    triageConfidenceFilter: ").append(toIndentedString(triageConfidenceFilter)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

