/*
 * Software Risk Manager API Guide
 * Software Risk Manager provides a variety of REST APIs, allowing external applications and scripts to interface with core functionality. This guide documents the various REST resources provided by Software Risk Manager.  ## Authentication  Authentication is a requirement when accessing API endpoints. There are two methods by which authentication may be performed.  ### API Keys  The primary method for authentication is passing an `API-Key` header containing a valid API key with all requests, i.e.  `API-Key: <key goes here>`  API Keys come in two possible forms:   - `api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24` - latest format  - `550e8400-e29b-41d4-a716-44665544000` - legacy format  For example:  `API-Key: api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24`  `API-Key: 550e8400-e29b-41d4-a716-44665544000`  API keys may be generated by Software Risk Manager admins. Once they are generated, in most cases, they behave like regular users. They will need to be assigned user roles for any projects they will be used with. Although it is possible to assign the *admin* [role](../user_guide/Project-Management/user_role_configuration.html) to an API key, the recommendation is to avoid doing so unless absolutely necessary.  See the user guide for an overview about how to create and manage [API keys](../user_guide/Settings/api_keys_administration.html).  ### Personal Access Tokens  Personal Access Tokens can be used as [bearer tokens](https://swagger.io/docs/specification/authentication/bearer-authentication/), e.g.  `Authorization: Bearer secret-token:qRuXr1BqgoTWXNxUhYQ8H_Yl2zfy6vxuqMIRnkGO`  Personal Access Tokens can be created by any user, and represent a subset of that user's permissions.   ### HTTP Basic Authentication  HTTP Basic authentication may be used to authenticate with the API as a regular user. This is accomplished by including an `Authorization` header containing a typical authorization credential.  ## Error Handling  ### Bad Requests  For API calls that accept input, invalid values will trigger an HTTP 400 Bad Request status code.  ### Server Errors  For any API call, if an unexpected error occurs, an HTTP 500 Internal Server Error status code will be returned. If an error message is available, the response will include a basic message body describing the error:  ` {   \"error\": \"error message\" } `  The error property will contain a string message indicating the nature of the error.  ### Errors with Third-Party Applications  Sometimes Software Risk Manager must communicate with third-party applications like JIRA, Git, and certain enterprise tools. Some users may have in-house versions of these with self-signed certificates which may not be \"trusted\". In these cases, the API will respond with an HTTP 502 BAD GATEWAY status. If this happens, refer to [Trusting Certificates](../install_guide/Installation/trusting-certs.html) in the install guide.  ### API Unavailable  In special circumstances, particularly during the installation and update phases, the API will be unavailable. When the API is unavailable, all calls will return an HTTP 503 Service Unavailable status, and no actions or side effects will occur as a result of the calls.  ## Examples  Software Risk Manager's API uses REST over HTTP. As such, you can use any language/utility that supports making HTTP requests to interact with the API. The examples below use <a href=\"https://curl.haxx.se/\" target=\"_blank\">curl</a>, a popular command-line utility, to do so.  First, you'll need to [generate an API Key](../user_guide/Settings/api_keys_administration.html). Second, while you can create projects through the API, these examples will assume that you've already created one. You'll need to know its project id number, which you can find by looking at the URL for the [Findings Page](../user_guide/Findings/findings_overview.html), which will end in a number.  **Note:** Many API endpoints require a JSON body in the request. Most JSON will contain double-quotes (`\"`) and spaces, which have special meaning when used on the command line. In order to ensure your JSON body is interpreted as a single argument, you must <a href=\"https://en.wikipedia.org/wiki/Escape_character\" target=\"_blank\">escape</a> it properly. For example, if you wanted to `POST` the following JSON body:  ```{ \"name\": \"John Doe\" }```  You would put a backslash (`\\`) before each double-quote (`\"`), and surround the whole thing with double-quotes:  ```\"{ \\\"name\\\": \\\"John Doe\\\" }\"```  The outermost double-quotes tell the command-line interpreter that everything within them is to be treated as a single argument (as opposed to the usual space-separated behavior). The backslash before each inner double-quote tells the command-line interpreter that you mean the literal double-quote character, and not the end of the quoted argument.  In many *non-Windows* operating systems, you can also use a single-quote (`'`) to surround the argument, and skip the backslashes:  ```'{ \"name\": \"John Doe\" }'```  The examples below will use the double-quotes and backslashes style, as it works on most (if not all) operating systems.  ### Running an Analysis  To start an analysis, you can run  ```curl -F file1=@src.zip -H \"API-Key: api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24\" https://<yoursrmserver>/srm/api/projects/<project id>/analysis```  Make sure you use your own values for the `src.zip` file, the API Key, the hostname for your Software Risk Manager server, and the project id.  ### Retrieving Finding Data  There is a wide variety of data available for the findings of a project after running an analysis. Two examples are provided here.  ### Findings Table Data  You can retrieve the data that's used to populate the [findings table](../user_guide/Findings/findings_table.html):  ```curl -H \"Content-Type: application/json\" -X POST -d \"{\\\"filter\\\":{},\\\"sort\\\":{\\\"by\\\":\\\"id\\\",\\\"direction\\\":\\\"ascending\\\"},\\\"pagination\\\":{\\\"page\\\":1,\\\"perPage\\\":10}}\" -H \"API-Key: api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24\" https://<yoursrmserver>/srm/api/projects/<project id>/findings/table```  Additional information about how to construct more useful filter and sort requests can be found in the documentation.  ### Finding Metadata  You can retrieve metadata for a finding, if you know the finding ID. You can take the ID for a finding from the Findings Table:  ```curl -H \"API-Key: api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24\" https://<yoursrmserver>/srm/api/findings/<finding id>```  ### Generating a Report  You can use the API to generate a PDF [report](../user_guide/Findings/generate_report.html).  ```curl -H \"Content-Type: application/json\" -X POST -d \"{\\\"filter\\\":{},\\\"config\\\":{\\\"summaryMode\\\":\\\"simple\\\",\\\"detailsMode\\\":\\\"simple\\\",\\\"includeResultDetails\\\":true,\\\"includeComments\\\":false}}\" -H \"API-Key: api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24\" https://<yoursrmserver>/srm/api/projects/<project id>/report/pdf```  ## Generating a Client SDK  If you require a client SDK for Software Risk Manager, you can generate one using [OpenAPI Generator](https://openapi-generator.tech/). Detailed instructions are available on the [GitHub page](https://github.com/OpenAPITools/openapi-generator) and our OpenAPI spec can be found [here](swagger/swagger.json). 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.codedx.client.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.codedx.client.model.BranchSyncConfigError;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.codedx.client.JSON;


/**
 * CentrallyConfiguredConnector
 */
@JsonPropertyOrder({
  CentrallyConfiguredConnector.JSON_PROPERTY_ID,
  CentrallyConfiguredConnector.JSON_PROPERTY_TOOL,
  CentrallyConfiguredConnector.JSON_PROPERTY_NAME,
  CentrallyConfiguredConnector.JSON_PROPERTY_AVAILABLE_DURING_ANALYSIS,
  CentrallyConfiguredConnector.JSON_PROPERTY_HAS_AUTO_UPDATE_ENABLED,
  CentrallyConfiguredConnector.JSON_PROPERTY_BRANCH_SYNC_TARGET,
  CentrallyConfiguredConnector.JSON_PROPERTY_BRANCH_SYNC_CONFIG_ERROR,
  CentrallyConfiguredConnector.JSON_PROPERTY_USE_DYNAMIC_VERSION,
  CentrallyConfiguredConnector.JSON_PROPERTY_CONNECTION_ENTITY_ID,
  CentrallyConfiguredConnector.JSON_PROPERTY_SCHEDULE_ENTITY_ID,
  CentrallyConfiguredConnector.JSON_PROPERTY_OPTION_ENTITY_ID,
  CentrallyConfiguredConnector.JSON_PROPERTY_PROJECT_ENTITY_ID,
  CentrallyConfiguredConnector.JSON_PROPERTY_VERSION_ENTITY_ID
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-02T11:55:06.722228-04:00[America/New_York]", comments = "Generator version: 7.21.0")
public class CentrallyConfiguredConnector {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nullable
  private Integer id;

  public static final String JSON_PROPERTY_TOOL = "tool";
  @jakarta.annotation.Nullable
  private String tool;

  public static final String JSON_PROPERTY_NAME = "name";
  @jakarta.annotation.Nullable
  private String name;

  public static final String JSON_PROPERTY_AVAILABLE_DURING_ANALYSIS = "availableDuringAnalysis";
  @jakarta.annotation.Nullable
  private Boolean availableDuringAnalysis;

  public static final String JSON_PROPERTY_HAS_AUTO_UPDATE_ENABLED = "hasAutoUpdateEnabled";
  @jakarta.annotation.Nullable
  private Boolean hasAutoUpdateEnabled;

  public static final String JSON_PROPERTY_BRANCH_SYNC_TARGET = "branchSyncTarget";
  @jakarta.annotation.Nullable
  private String branchSyncTarget;

  public static final String JSON_PROPERTY_BRANCH_SYNC_CONFIG_ERROR = "branchSyncConfigError";
  @jakarta.annotation.Nullable
  private BranchSyncConfigError branchSyncConfigError;

  public static final String JSON_PROPERTY_USE_DYNAMIC_VERSION = "useDynamicVersion";
  @jakarta.annotation.Nullable
  private Boolean useDynamicVersion;

  public static final String JSON_PROPERTY_CONNECTION_ENTITY_ID = "connectionEntityId";
  @jakarta.annotation.Nullable
  private Integer connectionEntityId;

  public static final String JSON_PROPERTY_SCHEDULE_ENTITY_ID = "scheduleEntityId";
  @jakarta.annotation.Nullable
  private Integer scheduleEntityId;

  public static final String JSON_PROPERTY_OPTION_ENTITY_ID = "optionEntityId";
  @jakarta.annotation.Nullable
  private Integer optionEntityId;

  public static final String JSON_PROPERTY_PROJECT_ENTITY_ID = "projectEntityId";
  @jakarta.annotation.Nullable
  private Integer projectEntityId;

  public static final String JSON_PROPERTY_VERSION_ENTITY_ID = "versionEntityId";
  @jakarta.annotation.Nullable
  private Integer versionEntityId;

  public CentrallyConfiguredConnector() { 
  }

  public CentrallyConfiguredConnector id(@jakarta.annotation.Nullable Integer id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@jakarta.annotation.Nullable Integer id) {
    this.id = id;
  }


  public CentrallyConfiguredConnector tool(@jakarta.annotation.Nullable String tool) {
    this.tool = tool;
    return this;
  }

  /**
   * The name of the tool this connector configuration is for
   * @return tool
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TOOL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTool() {
    return tool;
  }


  @JsonProperty(value = JSON_PROPERTY_TOOL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTool(@jakarta.annotation.Nullable String tool) {
    this.tool = tool;
  }


  public CentrallyConfiguredConnector name(@jakarta.annotation.Nullable String name) {
    this.name = name;
    return this;
  }

  /**
   * The name of the connector
   * @return name
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(@jakarta.annotation.Nullable String name) {
    this.name = name;
  }


  public CentrallyConfiguredConnector availableDuringAnalysis(@jakarta.annotation.Nullable Boolean availableDuringAnalysis) {
    this.availableDuringAnalysis = availableDuringAnalysis;
    return this;
  }

  /**
   * Provided as a convenience, this field mirrors the value of the &#39;available-during-analysis&#39; field for the associated tool connector configuration
   * @return availableDuringAnalysis
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_AVAILABLE_DURING_ANALYSIS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getAvailableDuringAnalysis() {
    return availableDuringAnalysis;
  }


  @JsonProperty(value = JSON_PROPERTY_AVAILABLE_DURING_ANALYSIS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAvailableDuringAnalysis(@jakarta.annotation.Nullable Boolean availableDuringAnalysis) {
    this.availableDuringAnalysis = availableDuringAnalysis;
  }


  public CentrallyConfiguredConnector hasAutoUpdateEnabled(@jakarta.annotation.Nullable Boolean hasAutoUpdateEnabled) {
    this.hasAutoUpdateEnabled = hasAutoUpdateEnabled;
    return this;
  }

  /**
   * Provided as a convenience, this field will be true if the &#39;auto-refresh-interval&#39; field has a value in the associated tool connector configuration
   * @return hasAutoUpdateEnabled
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_HAS_AUTO_UPDATE_ENABLED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getHasAutoUpdateEnabled() {
    return hasAutoUpdateEnabled;
  }


  @JsonProperty(value = JSON_PROPERTY_HAS_AUTO_UPDATE_ENABLED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHasAutoUpdateEnabled(@jakarta.annotation.Nullable Boolean hasAutoUpdateEnabled) {
    this.hasAutoUpdateEnabled = hasAutoUpdateEnabled;
  }


  public CentrallyConfiguredConnector branchSyncTarget(@jakarta.annotation.Nullable String branchSyncTarget) {
    this.branchSyncTarget = branchSyncTarget;
    return this;
  }

  /**
   * If the connector is configured to sync with a particular branch, and there is no error related to that branch, this field will contain the name of that branch
   * @return branchSyncTarget
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BRANCH_SYNC_TARGET, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getBranchSyncTarget() {
    return branchSyncTarget;
  }


  @JsonProperty(value = JSON_PROPERTY_BRANCH_SYNC_TARGET, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBranchSyncTarget(@jakarta.annotation.Nullable String branchSyncTarget) {
    this.branchSyncTarget = branchSyncTarget;
  }


  public CentrallyConfiguredConnector branchSyncConfigError(@jakarta.annotation.Nullable BranchSyncConfigError branchSyncConfigError) {
    this.branchSyncConfigError = branchSyncConfigError;
    return this;
  }

  /**
   * Get branchSyncConfigError
   * @return branchSyncConfigError
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BRANCH_SYNC_CONFIG_ERROR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BranchSyncConfigError getBranchSyncConfigError() {
    return branchSyncConfigError;
  }


  @JsonProperty(value = JSON_PROPERTY_BRANCH_SYNC_CONFIG_ERROR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBranchSyncConfigError(@jakarta.annotation.Nullable BranchSyncConfigError branchSyncConfigError) {
    this.branchSyncConfigError = branchSyncConfigError;
  }


  public CentrallyConfiguredConnector useDynamicVersion(@jakarta.annotation.Nullable Boolean useDynamicVersion) {
    this.useDynamicVersion = useDynamicVersion;
    return this;
  }

  /**
   * When set as &#x60;true&#x60;, analyses using this tool connector will derive the Version form section information based on the analysis branch name.
   * @return useDynamicVersion
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_USE_DYNAMIC_VERSION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getUseDynamicVersion() {
    return useDynamicVersion;
  }


  @JsonProperty(value = JSON_PROPERTY_USE_DYNAMIC_VERSION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUseDynamicVersion(@jakarta.annotation.Nullable Boolean useDynamicVersion) {
    this.useDynamicVersion = useDynamicVersion;
  }


  public CentrallyConfiguredConnector connectionEntityId(@jakarta.annotation.Nullable Integer connectionEntityId) {
    this.connectionEntityId = connectionEntityId;
    return this;
  }

  /**
   * Get connectionEntityId
   * @return connectionEntityId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CONNECTION_ENTITY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getConnectionEntityId() {
    return connectionEntityId;
  }


  @JsonProperty(value = JSON_PROPERTY_CONNECTION_ENTITY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setConnectionEntityId(@jakarta.annotation.Nullable Integer connectionEntityId) {
    this.connectionEntityId = connectionEntityId;
  }


  public CentrallyConfiguredConnector scheduleEntityId(@jakarta.annotation.Nullable Integer scheduleEntityId) {
    this.scheduleEntityId = scheduleEntityId;
    return this;
  }

  /**
   * Get scheduleEntityId
   * @return scheduleEntityId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SCHEDULE_ENTITY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getScheduleEntityId() {
    return scheduleEntityId;
  }


  @JsonProperty(value = JSON_PROPERTY_SCHEDULE_ENTITY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setScheduleEntityId(@jakarta.annotation.Nullable Integer scheduleEntityId) {
    this.scheduleEntityId = scheduleEntityId;
  }


  public CentrallyConfiguredConnector optionEntityId(@jakarta.annotation.Nullable Integer optionEntityId) {
    this.optionEntityId = optionEntityId;
    return this;
  }

  /**
   * Get optionEntityId
   * @return optionEntityId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_OPTION_ENTITY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getOptionEntityId() {
    return optionEntityId;
  }


  @JsonProperty(value = JSON_PROPERTY_OPTION_ENTITY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOptionEntityId(@jakarta.annotation.Nullable Integer optionEntityId) {
    this.optionEntityId = optionEntityId;
  }


  public CentrallyConfiguredConnector projectEntityId(@jakarta.annotation.Nullable Integer projectEntityId) {
    this.projectEntityId = projectEntityId;
    return this;
  }

  /**
   * Get projectEntityId
   * @return projectEntityId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PROJECT_ENTITY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getProjectEntityId() {
    return projectEntityId;
  }


  @JsonProperty(value = JSON_PROPERTY_PROJECT_ENTITY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProjectEntityId(@jakarta.annotation.Nullable Integer projectEntityId) {
    this.projectEntityId = projectEntityId;
  }


  public CentrallyConfiguredConnector versionEntityId(@jakarta.annotation.Nullable Integer versionEntityId) {
    this.versionEntityId = versionEntityId;
    return this;
  }

  /**
   * Get versionEntityId
   * @return versionEntityId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_VERSION_ENTITY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getVersionEntityId() {
    return versionEntityId;
  }


  @JsonProperty(value = JSON_PROPERTY_VERSION_ENTITY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVersionEntityId(@jakarta.annotation.Nullable Integer versionEntityId) {
    this.versionEntityId = versionEntityId;
  }


  /**
   * Return true if this CentrallyConfiguredConnector object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CentrallyConfiguredConnector centrallyConfiguredConnector = (CentrallyConfiguredConnector) o;
    return Objects.equals(this.id, centrallyConfiguredConnector.id) &&
        Objects.equals(this.tool, centrallyConfiguredConnector.tool) &&
        Objects.equals(this.name, centrallyConfiguredConnector.name) &&
        Objects.equals(this.availableDuringAnalysis, centrallyConfiguredConnector.availableDuringAnalysis) &&
        Objects.equals(this.hasAutoUpdateEnabled, centrallyConfiguredConnector.hasAutoUpdateEnabled) &&
        Objects.equals(this.branchSyncTarget, centrallyConfiguredConnector.branchSyncTarget) &&
        Objects.equals(this.branchSyncConfigError, centrallyConfiguredConnector.branchSyncConfigError) &&
        Objects.equals(this.useDynamicVersion, centrallyConfiguredConnector.useDynamicVersion) &&
        Objects.equals(this.connectionEntityId, centrallyConfiguredConnector.connectionEntityId) &&
        Objects.equals(this.scheduleEntityId, centrallyConfiguredConnector.scheduleEntityId) &&
        Objects.equals(this.optionEntityId, centrallyConfiguredConnector.optionEntityId) &&
        Objects.equals(this.projectEntityId, centrallyConfiguredConnector.projectEntityId) &&
        Objects.equals(this.versionEntityId, centrallyConfiguredConnector.versionEntityId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, tool, name, availableDuringAnalysis, hasAutoUpdateEnabled, branchSyncTarget, branchSyncConfigError, useDynamicVersion, connectionEntityId, scheduleEntityId, optionEntityId, projectEntityId, versionEntityId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CentrallyConfiguredConnector {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    tool: ").append(toIndentedString(tool)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    availableDuringAnalysis: ").append(toIndentedString(availableDuringAnalysis)).append("\n");
    sb.append("    hasAutoUpdateEnabled: ").append(toIndentedString(hasAutoUpdateEnabled)).append("\n");
    sb.append("    branchSyncTarget: ").append(toIndentedString(branchSyncTarget)).append("\n");
    sb.append("    branchSyncConfigError: ").append(toIndentedString(branchSyncConfigError)).append("\n");
    sb.append("    useDynamicVersion: ").append(toIndentedString(useDynamicVersion)).append("\n");
    sb.append("    connectionEntityId: ").append(toIndentedString(connectionEntityId)).append("\n");
    sb.append("    scheduleEntityId: ").append(toIndentedString(scheduleEntityId)).append("\n");
    sb.append("    optionEntityId: ").append(toIndentedString(optionEntityId)).append("\n");
    sb.append("    projectEntityId: ").append(toIndentedString(projectEntityId)).append("\n");
    sb.append("    versionEntityId: ").append(toIndentedString(versionEntityId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

