/*
 * Software Risk Manager API Guide
 * Software Risk Manager provides a variety of REST APIs, allowing external applications and scripts to interface with core functionality. This guide documents the various REST resources provided by Software Risk Manager.  ## Authentication  Authentication is a requirement when accessing API endpoints. There are two methods by which authentication may be performed.  ### API Keys  The primary method for authentication is passing an `API-Key` header containing a valid API key with all requests, i.e.  `API-Key: <key goes here>`  API Keys come in two possible forms:   - `api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24` - latest format  - `550e8400-e29b-41d4-a716-44665544000` - legacy format  For example:  `API-Key: api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24`  `API-Key: 550e8400-e29b-41d4-a716-44665544000`  API keys may be generated by Software Risk Manager admins. Once they are generated, in most cases, they behave like regular users. They will need to be assigned user roles for any projects they will be used with. Although it is possible to assign the *admin* [role](../user_guide/Project-Management/user_role_configuration.html) to an API key, the recommendation is to avoid doing so unless absolutely necessary.  See the user guide for an overview about how to create and manage [API keys](../user_guide/Settings/api_keys_administration.html).  ### Personal Access Tokens  Personal Access Tokens can be used as [bearer tokens](https://swagger.io/docs/specification/authentication/bearer-authentication/), e.g.  `Authorization: Bearer secret-token:qRuXr1BqgoTWXNxUhYQ8H_Yl2zfy6vxuqMIRnkGO`  Personal Access Tokens can be created by any user, and represent a subset of that user's permissions.   ### HTTP Basic Authentication  HTTP Basic authentication may be used to authenticate with the API as a regular user. This is accomplished by including an `Authorization` header containing a typical authorization credential.  ## Error Handling  ### Bad Requests  For API calls that accept input, invalid values will trigger an HTTP 400 Bad Request status code.  ### Server Errors  For any API call, if an unexpected error occurs, an HTTP 500 Internal Server Error status code will be returned. If an error message is available, the response will include a basic message body describing the error:  ` {   \"error\": \"error message\" } `  The error property will contain a string message indicating the nature of the error.  ### Errors with Third-Party Applications  Sometimes Software Risk Manager must communicate with third-party applications like JIRA, Git, and certain enterprise tools. Some users may have in-house versions of these with self-signed certificates which may not be \"trusted\". In these cases, the API will respond with an HTTP 502 BAD GATEWAY status. If this happens, refer to [Trusting Certificates](../install_guide/Installation/trusting-certs.html) in the install guide.  ### API Unavailable  In special circumstances, particularly during the installation and update phases, the API will be unavailable. When the API is unavailable, all calls will return an HTTP 503 Service Unavailable status, and no actions or side effects will occur as a result of the calls.  ## Examples  Software Risk Manager's API uses REST over HTTP. As such, you can use any language/utility that supports making HTTP requests to interact with the API. The examples below use <a href=\"https://curl.haxx.se/\" target=\"_blank\">curl</a>, a popular command-line utility, to do so.  First, you'll need to [generate an API Key](../user_guide/Settings/api_keys_administration.html). Second, while you can create projects through the API, these examples will assume that you've already created one. You'll need to know its project id number, which you can find by looking at the URL for the [Findings Page](../user_guide/Findings/findings_overview.html), which will end in a number.  **Note:** Many API endpoints require a JSON body in the request. Most JSON will contain double-quotes (`\"`) and spaces, which have special meaning when used on the command line. In order to ensure your JSON body is interpreted as a single argument, you must <a href=\"https://en.wikipedia.org/wiki/Escape_character\" target=\"_blank\">escape</a> it properly. For example, if you wanted to `POST` the following JSON body:  ```{ \"name\": \"John Doe\" }```  You would put a backslash (`\\`) before each double-quote (`\"`), and surround the whole thing with double-quotes:  ```\"{ \\\"name\\\": \\\"John Doe\\\" }\"```  The outermost double-quotes tell the command-line interpreter that everything within them is to be treated as a single argument (as opposed to the usual space-separated behavior). The backslash before each inner double-quote tells the command-line interpreter that you mean the literal double-quote character, and not the end of the quoted argument.  In many *non-Windows* operating systems, you can also use a single-quote (`'`) to surround the argument, and skip the backslashes:  ```'{ \"name\": \"John Doe\" }'```  The examples below will use the double-quotes and backslashes style, as it works on most (if not all) operating systems.  ### Running an Analysis  To start an analysis, you can run  ```curl -F file1=@src.zip -H \"API-Key: api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24\" https://<yoursrmserver>/srm/api/projects/<project id>/analysis```  Make sure you use your own values for the `src.zip` file, the API Key, the hostname for your Software Risk Manager server, and the project id.  ### Retrieving Finding Data  There is a wide variety of data available for the findings of a project after running an analysis. Two examples are provided here.  ### Findings Table Data  You can retrieve the data that's used to populate the [findings table](../user_guide/Findings/findings_table.html):  ```curl -H \"Content-Type: application/json\" -X POST -d \"{\\\"filter\\\":{},\\\"sort\\\":{\\\"by\\\":\\\"id\\\",\\\"direction\\\":\\\"ascending\\\"},\\\"pagination\\\":{\\\"page\\\":1,\\\"perPage\\\":10}}\" -H \"API-Key: api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24\" https://<yoursrmserver>/srm/api/projects/<project id>/findings/table```  Additional information about how to construct more useful filter and sort requests can be found in the documentation.  ### Finding Metadata  You can retrieve metadata for a finding, if you know the finding ID. You can take the ID for a finding from the Findings Table:  ```curl -H \"API-Key: api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24\" https://<yoursrmserver>/srm/api/findings/<finding id>```  ### Generating a Report  You can use the API to generate a PDF [report](../user_guide/Findings/generate_report.html).  ```curl -H \"Content-Type: application/json\" -X POST -d \"{\\\"filter\\\":{},\\\"config\\\":{\\\"summaryMode\\\":\\\"simple\\\",\\\"detailsMode\\\":\\\"simple\\\",\\\"includeResultDetails\\\":true,\\\"includeComments\\\":false}}\" -H \"API-Key: api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24\" https://<yoursrmserver>/srm/api/projects/<project id>/report/pdf```  ## Generating a Client SDK  If you require a client SDK for Software Risk Manager, you can generate one using [OpenAPI Generator](https://openapi-generator.tech/). Detailed instructions are available on the [GitHub page](https://github.com/OpenAPITools/openapi-generator) and our OpenAPI spec can be found [here](swagger/swagger.json). 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.codedx.client.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.codedx.client.JSON;


/**
 * CSV report form values
 */
@JsonPropertyOrder({
  CreateReportTemplateRequestFormValuesOneOf1.JSON_PROPERTY_PROJECT_HIERARCHY,
  CreateReportTemplateRequestFormValuesOneOf1.JSON_PROPERTY_ID,
  CreateReportTemplateRequestFormValuesOneOf1.JSON_PROPERTY_CREATION_TIME,
  CreateReportTemplateRequestFormValuesOneOf1.JSON_PROPERTY_UPDATE_TIME,
  CreateReportTemplateRequestFormValuesOneOf1.JSON_PROPERTY_SEVERITY,
  CreateReportTemplateRequestFormValuesOneOf1.JSON_PROPERTY_TRIAGE_STATUS,
  CreateReportTemplateRequestFormValuesOneOf1.JSON_PROPERTY_FINDING_STATUS,
  CreateReportTemplateRequestFormValuesOneOf1.JSON_PROPERTY_ASSIGNEE,
  CreateReportTemplateRequestFormValuesOneOf1.JSON_PROPERTY_CWE,
  CreateReportTemplateRequestFormValuesOneOf1.JSON_PROPERTY_TYPE,
  CreateReportTemplateRequestFormValuesOneOf1.JSON_PROPERTY_TOOL,
  CreateReportTemplateRequestFormValuesOneOf1.JSON_PROPERTY_LOCATION,
  CreateReportTemplateRequestFormValuesOneOf1.JSON_PROPERTY_TAG,
  CreateReportTemplateRequestFormValuesOneOf1.JSON_PROPERTY_ELEMENT,
  CreateReportTemplateRequestFormValuesOneOf1.JSON_PROPERTY_PATH,
  CreateReportTemplateRequestFormValuesOneOf1.JSON_PROPERTY_LINE,
  CreateReportTemplateRequestFormValuesOneOf1.JSON_PROPERTY_HOST_IDENTIFIER,
  CreateReportTemplateRequestFormValuesOneOf1.JSON_PROPERTY_CONTAINER_NORMALIZED_IMAGE_ALIAS,
  CreateReportTemplateRequestFormValuesOneOf1.JSON_PROPERTY_CONTAINER_IMAGE_DIGEST,
  CreateReportTemplateRequestFormValuesOneOf1.JSON_PROPERTY_PREDICTED_STATUS,
  CreateReportTemplateRequestFormValuesOneOf1.JSON_PROPERTY_RESULT_CVE,
  CreateReportTemplateRequestFormValuesOneOf1.JSON_PROPERTY_RESULT_VULN,
  CreateReportTemplateRequestFormValuesOneOf1.JSON_PROPERTY_ALL_ADDITIONAL_VALUES,
  CreateReportTemplateRequestFormValuesOneOf1.JSON_PROPERTY_ALL_ISSUE_TRACKER
})
@JsonTypeName("createReportTemplate_request_formValues_oneOf_1")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-02T11:55:06.722228-04:00[America/New_York]", comments = "Generator version: 7.21.0")
public class CreateReportTemplateRequestFormValuesOneOf1 {
  public static final String JSON_PROPERTY_PROJECT_HIERARCHY = "project-hierarchy";
  @jakarta.annotation.Nullable
  private Boolean projectHierarchy;

  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nullable
  private Boolean id;

  public static final String JSON_PROPERTY_CREATION_TIME = "creation-time";
  @jakarta.annotation.Nullable
  private Boolean creationTime;

  public static final String JSON_PROPERTY_UPDATE_TIME = "update-time";
  @jakarta.annotation.Nullable
  private Boolean updateTime;

  public static final String JSON_PROPERTY_SEVERITY = "severity";
  @jakarta.annotation.Nullable
  private Boolean severity;

  public static final String JSON_PROPERTY_TRIAGE_STATUS = "triage-status";
  @jakarta.annotation.Nullable
  private Boolean triageStatus;

  public static final String JSON_PROPERTY_FINDING_STATUS = "finding-status";
  @jakarta.annotation.Nullable
  private Boolean findingStatus;

  public static final String JSON_PROPERTY_ASSIGNEE = "assignee";
  @jakarta.annotation.Nullable
  private Boolean assignee;

  public static final String JSON_PROPERTY_CWE = "cwe";
  @jakarta.annotation.Nullable
  private Boolean cwe;

  public static final String JSON_PROPERTY_TYPE = "type";
  @jakarta.annotation.Nullable
  private Boolean type;

  public static final String JSON_PROPERTY_TOOL = "tool";
  @jakarta.annotation.Nullable
  private Boolean tool;

  public static final String JSON_PROPERTY_LOCATION = "location";
  @jakarta.annotation.Nullable
  private Boolean location;

  public static final String JSON_PROPERTY_TAG = "tag";
  @jakarta.annotation.Nullable
  private Boolean tag;

  public static final String JSON_PROPERTY_ELEMENT = "element";
  @jakarta.annotation.Nullable
  private Boolean element;

  public static final String JSON_PROPERTY_PATH = "path";
  @jakarta.annotation.Nullable
  private Boolean path;

  public static final String JSON_PROPERTY_LINE = "line";
  @jakarta.annotation.Nullable
  private Boolean line;

  public static final String JSON_PROPERTY_HOST_IDENTIFIER = "host-identifier";
  @jakarta.annotation.Nullable
  private Boolean hostIdentifier;

  public static final String JSON_PROPERTY_CONTAINER_NORMALIZED_IMAGE_ALIAS = "container-normalized-image-alias";
  @jakarta.annotation.Nullable
  private Boolean containerNormalizedImageAlias;

  public static final String JSON_PROPERTY_CONTAINER_IMAGE_DIGEST = "container-image-digest";
  @jakarta.annotation.Nullable
  private Boolean containerImageDigest;

  public static final String JSON_PROPERTY_PREDICTED_STATUS = "predicted-status";
  @jakarta.annotation.Nullable
  private Boolean predictedStatus;

  public static final String JSON_PROPERTY_RESULT_CVE = "result-cve";
  @jakarta.annotation.Nullable
  private Boolean resultCve;

  public static final String JSON_PROPERTY_RESULT_VULN = "result-vuln";
  @jakarta.annotation.Nullable
  private Boolean resultVuln;

  public static final String JSON_PROPERTY_ALL_ADDITIONAL_VALUES = "all-additional-values";
  @jakarta.annotation.Nullable
  private Boolean allAdditionalValues;

  public static final String JSON_PROPERTY_ALL_ISSUE_TRACKER = "all-issue-tracker";
  @jakarta.annotation.Nullable
  private Boolean allIssueTracker;

  public CreateReportTemplateRequestFormValuesOneOf1() { 
  }

  public CreateReportTemplateRequestFormValuesOneOf1 projectHierarchy(@jakarta.annotation.Nullable Boolean projectHierarchy) {
    this.projectHierarchy = projectHierarchy;
    return this;
  }

  /**
   * Get projectHierarchy
   * @return projectHierarchy
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PROJECT_HIERARCHY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getProjectHierarchy() {
    return projectHierarchy;
  }


  @JsonProperty(value = JSON_PROPERTY_PROJECT_HIERARCHY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProjectHierarchy(@jakarta.annotation.Nullable Boolean projectHierarchy) {
    this.projectHierarchy = projectHierarchy;
  }


  public CreateReportTemplateRequestFormValuesOneOf1 id(@jakarta.annotation.Nullable Boolean id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@jakarta.annotation.Nullable Boolean id) {
    this.id = id;
  }


  public CreateReportTemplateRequestFormValuesOneOf1 creationTime(@jakarta.annotation.Nullable Boolean creationTime) {
    this.creationTime = creationTime;
    return this;
  }

  /**
   * Get creationTime
   * @return creationTime
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CREATION_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getCreationTime() {
    return creationTime;
  }


  @JsonProperty(value = JSON_PROPERTY_CREATION_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreationTime(@jakarta.annotation.Nullable Boolean creationTime) {
    this.creationTime = creationTime;
  }


  public CreateReportTemplateRequestFormValuesOneOf1 updateTime(@jakarta.annotation.Nullable Boolean updateTime) {
    this.updateTime = updateTime;
    return this;
  }

  /**
   * Get updateTime
   * @return updateTime
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_UPDATE_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getUpdateTime() {
    return updateTime;
  }


  @JsonProperty(value = JSON_PROPERTY_UPDATE_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpdateTime(@jakarta.annotation.Nullable Boolean updateTime) {
    this.updateTime = updateTime;
  }


  public CreateReportTemplateRequestFormValuesOneOf1 severity(@jakarta.annotation.Nullable Boolean severity) {
    this.severity = severity;
    return this;
  }

  /**
   * Get severity
   * @return severity
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SEVERITY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getSeverity() {
    return severity;
  }


  @JsonProperty(value = JSON_PROPERTY_SEVERITY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSeverity(@jakarta.annotation.Nullable Boolean severity) {
    this.severity = severity;
  }


  public CreateReportTemplateRequestFormValuesOneOf1 triageStatus(@jakarta.annotation.Nullable Boolean triageStatus) {
    this.triageStatus = triageStatus;
    return this;
  }

  /**
   * Get triageStatus
   * @return triageStatus
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TRIAGE_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getTriageStatus() {
    return triageStatus;
  }


  @JsonProperty(value = JSON_PROPERTY_TRIAGE_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTriageStatus(@jakarta.annotation.Nullable Boolean triageStatus) {
    this.triageStatus = triageStatus;
  }


  public CreateReportTemplateRequestFormValuesOneOf1 findingStatus(@jakarta.annotation.Nullable Boolean findingStatus) {
    this.findingStatus = findingStatus;
    return this;
  }

  /**
   * Get findingStatus
   * @return findingStatus
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FINDING_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getFindingStatus() {
    return findingStatus;
  }


  @JsonProperty(value = JSON_PROPERTY_FINDING_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFindingStatus(@jakarta.annotation.Nullable Boolean findingStatus) {
    this.findingStatus = findingStatus;
  }


  public CreateReportTemplateRequestFormValuesOneOf1 assignee(@jakarta.annotation.Nullable Boolean assignee) {
    this.assignee = assignee;
    return this;
  }

  /**
   * Get assignee
   * @return assignee
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ASSIGNEE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getAssignee() {
    return assignee;
  }


  @JsonProperty(value = JSON_PROPERTY_ASSIGNEE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAssignee(@jakarta.annotation.Nullable Boolean assignee) {
    this.assignee = assignee;
  }


  public CreateReportTemplateRequestFormValuesOneOf1 cwe(@jakarta.annotation.Nullable Boolean cwe) {
    this.cwe = cwe;
    return this;
  }

  /**
   * Get cwe
   * @return cwe
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CWE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getCwe() {
    return cwe;
  }


  @JsonProperty(value = JSON_PROPERTY_CWE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCwe(@jakarta.annotation.Nullable Boolean cwe) {
    this.cwe = cwe;
  }


  public CreateReportTemplateRequestFormValuesOneOf1 type(@jakarta.annotation.Nullable Boolean type) {
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getType() {
    return type;
  }


  @JsonProperty(value = JSON_PROPERTY_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setType(@jakarta.annotation.Nullable Boolean type) {
    this.type = type;
  }


  public CreateReportTemplateRequestFormValuesOneOf1 tool(@jakarta.annotation.Nullable Boolean tool) {
    this.tool = tool;
    return this;
  }

  /**
   * Get tool
   * @return tool
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TOOL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getTool() {
    return tool;
  }


  @JsonProperty(value = JSON_PROPERTY_TOOL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTool(@jakarta.annotation.Nullable Boolean tool) {
    this.tool = tool;
  }


  public CreateReportTemplateRequestFormValuesOneOf1 location(@jakarta.annotation.Nullable Boolean location) {
    this.location = location;
    return this;
  }

  /**
   * Get location
   * @return location
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LOCATION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getLocation() {
    return location;
  }


  @JsonProperty(value = JSON_PROPERTY_LOCATION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLocation(@jakarta.annotation.Nullable Boolean location) {
    this.location = location;
  }


  public CreateReportTemplateRequestFormValuesOneOf1 tag(@jakarta.annotation.Nullable Boolean tag) {
    this.tag = tag;
    return this;
  }

  /**
   * Get tag
   * @return tag
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TAG, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getTag() {
    return tag;
  }


  @JsonProperty(value = JSON_PROPERTY_TAG, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTag(@jakarta.annotation.Nullable Boolean tag) {
    this.tag = tag;
  }


  public CreateReportTemplateRequestFormValuesOneOf1 element(@jakarta.annotation.Nullable Boolean element) {
    this.element = element;
    return this;
  }

  /**
   * Get element
   * @return element
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ELEMENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getElement() {
    return element;
  }


  @JsonProperty(value = JSON_PROPERTY_ELEMENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setElement(@jakarta.annotation.Nullable Boolean element) {
    this.element = element;
  }


  public CreateReportTemplateRequestFormValuesOneOf1 path(@jakarta.annotation.Nullable Boolean path) {
    this.path = path;
    return this;
  }

  /**
   * Get path
   * @return path
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PATH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getPath() {
    return path;
  }


  @JsonProperty(value = JSON_PROPERTY_PATH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPath(@jakarta.annotation.Nullable Boolean path) {
    this.path = path;
  }


  public CreateReportTemplateRequestFormValuesOneOf1 line(@jakarta.annotation.Nullable Boolean line) {
    this.line = line;
    return this;
  }

  /**
   * Get line
   * @return line
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LINE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getLine() {
    return line;
  }


  @JsonProperty(value = JSON_PROPERTY_LINE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLine(@jakarta.annotation.Nullable Boolean line) {
    this.line = line;
  }


  public CreateReportTemplateRequestFormValuesOneOf1 hostIdentifier(@jakarta.annotation.Nullable Boolean hostIdentifier) {
    this.hostIdentifier = hostIdentifier;
    return this;
  }

  /**
   * Get hostIdentifier
   * @return hostIdentifier
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_HOST_IDENTIFIER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getHostIdentifier() {
    return hostIdentifier;
  }


  @JsonProperty(value = JSON_PROPERTY_HOST_IDENTIFIER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHostIdentifier(@jakarta.annotation.Nullable Boolean hostIdentifier) {
    this.hostIdentifier = hostIdentifier;
  }


  public CreateReportTemplateRequestFormValuesOneOf1 containerNormalizedImageAlias(@jakarta.annotation.Nullable Boolean containerNormalizedImageAlias) {
    this.containerNormalizedImageAlias = containerNormalizedImageAlias;
    return this;
  }

  /**
   * Get containerNormalizedImageAlias
   * @return containerNormalizedImageAlias
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CONTAINER_NORMALIZED_IMAGE_ALIAS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getContainerNormalizedImageAlias() {
    return containerNormalizedImageAlias;
  }


  @JsonProperty(value = JSON_PROPERTY_CONTAINER_NORMALIZED_IMAGE_ALIAS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setContainerNormalizedImageAlias(@jakarta.annotation.Nullable Boolean containerNormalizedImageAlias) {
    this.containerNormalizedImageAlias = containerNormalizedImageAlias;
  }


  public CreateReportTemplateRequestFormValuesOneOf1 containerImageDigest(@jakarta.annotation.Nullable Boolean containerImageDigest) {
    this.containerImageDigest = containerImageDigest;
    return this;
  }

  /**
   * Get containerImageDigest
   * @return containerImageDigest
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CONTAINER_IMAGE_DIGEST, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getContainerImageDigest() {
    return containerImageDigest;
  }


  @JsonProperty(value = JSON_PROPERTY_CONTAINER_IMAGE_DIGEST, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setContainerImageDigest(@jakarta.annotation.Nullable Boolean containerImageDigest) {
    this.containerImageDigest = containerImageDigest;
  }


  public CreateReportTemplateRequestFormValuesOneOf1 predictedStatus(@jakarta.annotation.Nullable Boolean predictedStatus) {
    this.predictedStatus = predictedStatus;
    return this;
  }

  /**
   * Get predictedStatus
   * @return predictedStatus
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PREDICTED_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getPredictedStatus() {
    return predictedStatus;
  }


  @JsonProperty(value = JSON_PROPERTY_PREDICTED_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPredictedStatus(@jakarta.annotation.Nullable Boolean predictedStatus) {
    this.predictedStatus = predictedStatus;
  }


  public CreateReportTemplateRequestFormValuesOneOf1 resultCve(@jakarta.annotation.Nullable Boolean resultCve) {
    this.resultCve = resultCve;
    return this;
  }

  /**
   * Get resultCve
   * @return resultCve
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_RESULT_CVE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getResultCve() {
    return resultCve;
  }


  @JsonProperty(value = JSON_PROPERTY_RESULT_CVE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setResultCve(@jakarta.annotation.Nullable Boolean resultCve) {
    this.resultCve = resultCve;
  }


  public CreateReportTemplateRequestFormValuesOneOf1 resultVuln(@jakarta.annotation.Nullable Boolean resultVuln) {
    this.resultVuln = resultVuln;
    return this;
  }

  /**
   * Get resultVuln
   * @return resultVuln
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_RESULT_VULN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getResultVuln() {
    return resultVuln;
  }


  @JsonProperty(value = JSON_PROPERTY_RESULT_VULN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setResultVuln(@jakarta.annotation.Nullable Boolean resultVuln) {
    this.resultVuln = resultVuln;
  }


  public CreateReportTemplateRequestFormValuesOneOf1 allAdditionalValues(@jakarta.annotation.Nullable Boolean allAdditionalValues) {
    this.allAdditionalValues = allAdditionalValues;
    return this;
  }

  /**
   * Get allAdditionalValues
   * @return allAdditionalValues
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ALL_ADDITIONAL_VALUES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getAllAdditionalValues() {
    return allAdditionalValues;
  }


  @JsonProperty(value = JSON_PROPERTY_ALL_ADDITIONAL_VALUES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAllAdditionalValues(@jakarta.annotation.Nullable Boolean allAdditionalValues) {
    this.allAdditionalValues = allAdditionalValues;
  }


  public CreateReportTemplateRequestFormValuesOneOf1 allIssueTracker(@jakarta.annotation.Nullable Boolean allIssueTracker) {
    this.allIssueTracker = allIssueTracker;
    return this;
  }

  /**
   * Get allIssueTracker
   * @return allIssueTracker
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ALL_ISSUE_TRACKER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getAllIssueTracker() {
    return allIssueTracker;
  }


  @JsonProperty(value = JSON_PROPERTY_ALL_ISSUE_TRACKER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAllIssueTracker(@jakarta.annotation.Nullable Boolean allIssueTracker) {
    this.allIssueTracker = allIssueTracker;
  }


  /**
   * Return true if this createReportTemplate_request_formValues_oneOf_1 object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateReportTemplateRequestFormValuesOneOf1 createReportTemplateRequestFormValuesOneOf1 = (CreateReportTemplateRequestFormValuesOneOf1) o;
    return Objects.equals(this.projectHierarchy, createReportTemplateRequestFormValuesOneOf1.projectHierarchy) &&
        Objects.equals(this.id, createReportTemplateRequestFormValuesOneOf1.id) &&
        Objects.equals(this.creationTime, createReportTemplateRequestFormValuesOneOf1.creationTime) &&
        Objects.equals(this.updateTime, createReportTemplateRequestFormValuesOneOf1.updateTime) &&
        Objects.equals(this.severity, createReportTemplateRequestFormValuesOneOf1.severity) &&
        Objects.equals(this.triageStatus, createReportTemplateRequestFormValuesOneOf1.triageStatus) &&
        Objects.equals(this.findingStatus, createReportTemplateRequestFormValuesOneOf1.findingStatus) &&
        Objects.equals(this.assignee, createReportTemplateRequestFormValuesOneOf1.assignee) &&
        Objects.equals(this.cwe, createReportTemplateRequestFormValuesOneOf1.cwe) &&
        Objects.equals(this.type, createReportTemplateRequestFormValuesOneOf1.type) &&
        Objects.equals(this.tool, createReportTemplateRequestFormValuesOneOf1.tool) &&
        Objects.equals(this.location, createReportTemplateRequestFormValuesOneOf1.location) &&
        Objects.equals(this.tag, createReportTemplateRequestFormValuesOneOf1.tag) &&
        Objects.equals(this.element, createReportTemplateRequestFormValuesOneOf1.element) &&
        Objects.equals(this.path, createReportTemplateRequestFormValuesOneOf1.path) &&
        Objects.equals(this.line, createReportTemplateRequestFormValuesOneOf1.line) &&
        Objects.equals(this.hostIdentifier, createReportTemplateRequestFormValuesOneOf1.hostIdentifier) &&
        Objects.equals(this.containerNormalizedImageAlias, createReportTemplateRequestFormValuesOneOf1.containerNormalizedImageAlias) &&
        Objects.equals(this.containerImageDigest, createReportTemplateRequestFormValuesOneOf1.containerImageDigest) &&
        Objects.equals(this.predictedStatus, createReportTemplateRequestFormValuesOneOf1.predictedStatus) &&
        Objects.equals(this.resultCve, createReportTemplateRequestFormValuesOneOf1.resultCve) &&
        Objects.equals(this.resultVuln, createReportTemplateRequestFormValuesOneOf1.resultVuln) &&
        Objects.equals(this.allAdditionalValues, createReportTemplateRequestFormValuesOneOf1.allAdditionalValues) &&
        Objects.equals(this.allIssueTracker, createReportTemplateRequestFormValuesOneOf1.allIssueTracker);
  }

  @Override
  public int hashCode() {
    return Objects.hash(projectHierarchy, id, creationTime, updateTime, severity, triageStatus, findingStatus, assignee, cwe, type, tool, location, tag, element, path, line, hostIdentifier, containerNormalizedImageAlias, containerImageDigest, predictedStatus, resultCve, resultVuln, allAdditionalValues, allIssueTracker);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateReportTemplateRequestFormValuesOneOf1 {\n");
    sb.append("    projectHierarchy: ").append(toIndentedString(projectHierarchy)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    creationTime: ").append(toIndentedString(creationTime)).append("\n");
    sb.append("    updateTime: ").append(toIndentedString(updateTime)).append("\n");
    sb.append("    severity: ").append(toIndentedString(severity)).append("\n");
    sb.append("    triageStatus: ").append(toIndentedString(triageStatus)).append("\n");
    sb.append("    findingStatus: ").append(toIndentedString(findingStatus)).append("\n");
    sb.append("    assignee: ").append(toIndentedString(assignee)).append("\n");
    sb.append("    cwe: ").append(toIndentedString(cwe)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    tool: ").append(toIndentedString(tool)).append("\n");
    sb.append("    location: ").append(toIndentedString(location)).append("\n");
    sb.append("    tag: ").append(toIndentedString(tag)).append("\n");
    sb.append("    element: ").append(toIndentedString(element)).append("\n");
    sb.append("    path: ").append(toIndentedString(path)).append("\n");
    sb.append("    line: ").append(toIndentedString(line)).append("\n");
    sb.append("    hostIdentifier: ").append(toIndentedString(hostIdentifier)).append("\n");
    sb.append("    containerNormalizedImageAlias: ").append(toIndentedString(containerNormalizedImageAlias)).append("\n");
    sb.append("    containerImageDigest: ").append(toIndentedString(containerImageDigest)).append("\n");
    sb.append("    predictedStatus: ").append(toIndentedString(predictedStatus)).append("\n");
    sb.append("    resultCve: ").append(toIndentedString(resultCve)).append("\n");
    sb.append("    resultVuln: ").append(toIndentedString(resultVuln)).append("\n");
    sb.append("    allAdditionalValues: ").append(toIndentedString(allAdditionalValues)).append("\n");
    sb.append("    allIssueTracker: ").append(toIndentedString(allIssueTracker)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

