/*
 * Software Risk Manager API Guide
 * Software Risk Manager provides a variety of REST APIs, allowing external applications and scripts to interface with core functionality. This guide documents the various REST resources provided by Software Risk Manager.  ## Authentication  Authentication is a requirement when accessing API endpoints. There are two methods by which authentication may be performed.  ### API Keys  The primary method for authentication is passing an `API-Key` header containing a valid API key with all requests, i.e.  `API-Key: <key goes here>`  API Keys come in two possible forms:   - `api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24` - latest format  - `550e8400-e29b-41d4-a716-44665544000` - legacy format  For example:  `API-Key: api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24`  `API-Key: 550e8400-e29b-41d4-a716-44665544000`  API keys may be generated by Software Risk Manager admins. Once they are generated, in most cases, they behave like regular users. They will need to be assigned user roles for any projects they will be used with. Although it is possible to assign the *admin* [role](../user_guide/Project-Management/user_role_configuration.html) to an API key, the recommendation is to avoid doing so unless absolutely necessary.  See the user guide for an overview about how to create and manage [API keys](../user_guide/Settings/api_keys_administration.html).  ### Personal Access Tokens  Personal Access Tokens can be used as [bearer tokens](https://swagger.io/docs/specification/authentication/bearer-authentication/), e.g.  `Authorization: Bearer secret-token:qRuXr1BqgoTWXNxUhYQ8H_Yl2zfy6vxuqMIRnkGO`  Personal Access Tokens can be created by any user, and represent a subset of that user's permissions.   ### HTTP Basic Authentication  HTTP Basic authentication may be used to authenticate with the API as a regular user. This is accomplished by including an `Authorization` header containing a typical authorization credential.  ## Error Handling  ### Bad Requests  For API calls that accept input, invalid values will trigger an HTTP 400 Bad Request status code.  ### Server Errors  For any API call, if an unexpected error occurs, an HTTP 500 Internal Server Error status code will be returned. If an error message is available, the response will include a basic message body describing the error:  ` {   \"error\": \"error message\" } `  The error property will contain a string message indicating the nature of the error.  ### Errors with Third-Party Applications  Sometimes Software Risk Manager must communicate with third-party applications like JIRA, Git, and certain enterprise tools. Some users may have in-house versions of these with self-signed certificates which may not be \"trusted\". In these cases, the API will respond with an HTTP 502 BAD GATEWAY status. If this happens, refer to [Trusting Certificates](../install_guide/Installation/trusting-certs.html) in the install guide.  ### API Unavailable  In special circumstances, particularly during the installation and update phases, the API will be unavailable. When the API is unavailable, all calls will return an HTTP 503 Service Unavailable status, and no actions or side effects will occur as a result of the calls.  ## Examples  Software Risk Manager's API uses REST over HTTP. As such, you can use any language/utility that supports making HTTP requests to interact with the API. The examples below use <a href=\"https://curl.haxx.se/\" target=\"_blank\">curl</a>, a popular command-line utility, to do so.  First, you'll need to [generate an API Key](../user_guide/Settings/api_keys_administration.html). Second, while you can create projects through the API, these examples will assume that you've already created one. You'll need to know its project id number, which you can find by looking at the URL for the [Findings Page](../user_guide/Findings/findings_overview.html), which will end in a number.  **Note:** Many API endpoints require a JSON body in the request. Most JSON will contain double-quotes (`\"`) and spaces, which have special meaning when used on the command line. In order to ensure your JSON body is interpreted as a single argument, you must <a href=\"https://en.wikipedia.org/wiki/Escape_character\" target=\"_blank\">escape</a> it properly. For example, if you wanted to `POST` the following JSON body:  ```{ \"name\": \"John Doe\" }```  You would put a backslash (`\\`) before each double-quote (`\"`), and surround the whole thing with double-quotes:  ```\"{ \\\"name\\\": \\\"John Doe\\\" }\"```  The outermost double-quotes tell the command-line interpreter that everything within them is to be treated as a single argument (as opposed to the usual space-separated behavior). The backslash before each inner double-quote tells the command-line interpreter that you mean the literal double-quote character, and not the end of the quoted argument.  In many *non-Windows* operating systems, you can also use a single-quote (`'`) to surround the argument, and skip the backslashes:  ```'{ \"name\": \"John Doe\" }'```  The examples below will use the double-quotes and backslashes style, as it works on most (if not all) operating systems.  ### Running an Analysis  To start an analysis, you can run  ```curl -F file1=@src.zip -H \"API-Key: api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24\" https://<yoursrmserver>/srm/api/projects/<project id>/analysis```  Make sure you use your own values for the `src.zip` file, the API Key, the hostname for your Software Risk Manager server, and the project id.  ### Retrieving Finding Data  There is a wide variety of data available for the findings of a project after running an analysis. Two examples are provided here.  ### Findings Table Data  You can retrieve the data that's used to populate the [findings table](../user_guide/Findings/findings_table.html):  ```curl -H \"Content-Type: application/json\" -X POST -d \"{\\\"filter\\\":{},\\\"sort\\\":{\\\"by\\\":\\\"id\\\",\\\"direction\\\":\\\"ascending\\\"},\\\"pagination\\\":{\\\"page\\\":1,\\\"perPage\\\":10}}\" -H \"API-Key: api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24\" https://<yoursrmserver>/srm/api/projects/<project id>/findings/table```  Additional information about how to construct more useful filter and sort requests can be found in the documentation.  ### Finding Metadata  You can retrieve metadata for a finding, if you know the finding ID. You can take the ID for a finding from the Findings Table:  ```curl -H \"API-Key: api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24\" https://<yoursrmserver>/srm/api/findings/<finding id>```  ### Generating a Report  You can use the API to generate a PDF [report](../user_guide/Findings/generate_report.html).  ```curl -H \"Content-Type: application/json\" -X POST -d \"{\\\"filter\\\":{},\\\"config\\\":{\\\"summaryMode\\\":\\\"simple\\\",\\\"detailsMode\\\":\\\"simple\\\",\\\"includeResultDetails\\\":true,\\\"includeComments\\\":false}}\" -H \"API-Key: api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24\" https://<yoursrmserver>/srm/api/projects/<project id>/report/pdf```  ## Generating a Client SDK  If you require a client SDK for Software Risk Manager, you can generate one using [OpenAPI Generator](https://openapi-generator.tech/). Detailed instructions are available on the [GitHub page](https://github.com/OpenAPITools/openapi-generator) and our OpenAPI spec can be found [here](swagger/swagger.json). 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.codedx.client.model;

import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.codedx.client.model.CreateReportTemplateRequestFormValuesOneOf;
import com.codedx.client.model.CreateReportTemplateRequestFormValuesOneOf1;
import com.codedx.client.model.CreateReportTemplateRequestFormValuesOneOf2;
import com.codedx.client.model.CreateReportTemplateRequestFormValuesOneOf3;
import com.codedx.client.model.CreateReportTemplateRequestFormValuesOneOf4;
import com.codedx.client.model.CreateReportTemplateRequestFormValuesOneOf5;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.codedx.client.JSON;

import com.fasterxml.jackson.core.type.TypeReference;

import jakarta.ws.rs.core.GenericType;
import jakarta.ws.rs.core.Response;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;

import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.JsonToken;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonMappingException;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.MapperFeature;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import com.fasterxml.jackson.databind.ser.std.StdSerializer;
import com.codedx.client.JSON;

@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-02T11:55:06.722228-04:00[America/New_York]", comments = "Generator version: 7.21.0")
@JsonDeserialize(using = CreateReportTemplateRequestFormValues.CreateReportTemplateRequestFormValuesDeserializer.class)
@JsonSerialize(using = CreateReportTemplateRequestFormValues.CreateReportTemplateRequestFormValuesSerializer.class)
public class CreateReportTemplateRequestFormValues extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(CreateReportTemplateRequestFormValues.class.getName());

    public static class CreateReportTemplateRequestFormValuesSerializer extends StdSerializer<CreateReportTemplateRequestFormValues> {
        public CreateReportTemplateRequestFormValuesSerializer(Class<CreateReportTemplateRequestFormValues> t) {
            super(t);
        }

        public CreateReportTemplateRequestFormValuesSerializer() {
            this(null);
        }

        @Override
        public void serialize(CreateReportTemplateRequestFormValues value, JsonGenerator jgen, SerializerProvider provider) throws IOException, JsonProcessingException {
            jgen.writeObject(value.getActualInstance());
        }
    }

    public static class CreateReportTemplateRequestFormValuesDeserializer extends StdDeserializer<CreateReportTemplateRequestFormValues> {
        public CreateReportTemplateRequestFormValuesDeserializer() {
            this(CreateReportTemplateRequestFormValues.class);
        }

        public CreateReportTemplateRequestFormValuesDeserializer(Class<?> vc) {
            super(vc);
        }

        @Override
        public CreateReportTemplateRequestFormValues deserialize(JsonParser jp, DeserializationContext ctxt) throws IOException, JsonProcessingException {
            JsonNode tree = ctxt.readTree(jp);
            Object deserialized = null;
            boolean typeCoercion = ctxt.isEnabled(MapperFeature.ALLOW_COERCION_OF_SCALARS);
            int match = 0;
            JsonToken token = tree.traverse(jp.getCodec()).nextToken();
            // deserialize CreateReportTemplateRequestFormValuesOneOf
            try {
                boolean attemptParsing = true;
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(CreateReportTemplateRequestFormValuesOneOf.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'CreateReportTemplateRequestFormValuesOneOf'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'CreateReportTemplateRequestFormValuesOneOf'", e);
            }

            // deserialize CreateReportTemplateRequestFormValuesOneOf1
            try {
                boolean attemptParsing = true;
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(CreateReportTemplateRequestFormValuesOneOf1.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'CreateReportTemplateRequestFormValuesOneOf1'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'CreateReportTemplateRequestFormValuesOneOf1'", e);
            }

            // deserialize CreateReportTemplateRequestFormValuesOneOf2
            try {
                boolean attemptParsing = true;
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(CreateReportTemplateRequestFormValuesOneOf2.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'CreateReportTemplateRequestFormValuesOneOf2'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'CreateReportTemplateRequestFormValuesOneOf2'", e);
            }

            // deserialize CreateReportTemplateRequestFormValuesOneOf3
            try {
                boolean attemptParsing = true;
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(CreateReportTemplateRequestFormValuesOneOf3.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'CreateReportTemplateRequestFormValuesOneOf3'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'CreateReportTemplateRequestFormValuesOneOf3'", e);
            }

            // deserialize CreateReportTemplateRequestFormValuesOneOf4
            try {
                boolean attemptParsing = true;
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(CreateReportTemplateRequestFormValuesOneOf4.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'CreateReportTemplateRequestFormValuesOneOf4'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'CreateReportTemplateRequestFormValuesOneOf4'", e);
            }

            // deserialize CreateReportTemplateRequestFormValuesOneOf5
            try {
                boolean attemptParsing = true;
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(CreateReportTemplateRequestFormValuesOneOf5.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'CreateReportTemplateRequestFormValuesOneOf5'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'CreateReportTemplateRequestFormValuesOneOf5'", e);
            }

            if (match == 1) {
                CreateReportTemplateRequestFormValues ret = new CreateReportTemplateRequestFormValues();
                ret.setActualInstance(deserialized);
                return ret;
            }
            throw new IOException(String.format(java.util.Locale.ROOT, "Failed deserialization for CreateReportTemplateRequestFormValues: %d classes match result, expected 1", match));
        }

        /**
         * Handle deserialization of the 'null' value.
         */
        @Override
        public CreateReportTemplateRequestFormValues getNullValue(DeserializationContext ctxt) throws JsonMappingException {
            throw new JsonMappingException(ctxt.getParser(), "CreateReportTemplateRequestFormValues cannot be null");
        }
    }

    // store a list of schema names defined in oneOf
    public static final Map<String, GenericType<?>> schemas = new HashMap<>();

    public CreateReportTemplateRequestFormValues() {
        super("oneOf", Boolean.FALSE);
    }
  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   */
  @JsonAnySetter
  public CreateReportTemplateRequestFormValues putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   */
  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }

    /**
     * Return true if this createReportTemplate_request_formValues object is equal to o.
     */
    @Override
    public boolean equals(Object o) {
        return super.equals(o) && Objects.equals(this.additionalProperties, ((CreateReportTemplateRequestFormValues)o).additionalProperties);
    }

    @Override
    public int hashCode() {
        return Objects.hash(getActualInstance(), isNullable(), getSchemaType(), additionalProperties);
    }
    public CreateReportTemplateRequestFormValues(CreateReportTemplateRequestFormValuesOneOf o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public CreateReportTemplateRequestFormValues(CreateReportTemplateRequestFormValuesOneOf1 o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public CreateReportTemplateRequestFormValues(CreateReportTemplateRequestFormValuesOneOf2 o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public CreateReportTemplateRequestFormValues(CreateReportTemplateRequestFormValuesOneOf3 o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public CreateReportTemplateRequestFormValues(CreateReportTemplateRequestFormValuesOneOf4 o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public CreateReportTemplateRequestFormValues(CreateReportTemplateRequestFormValuesOneOf5 o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    static {
        schemas.put("CreateReportTemplateRequestFormValuesOneOf", new GenericType<CreateReportTemplateRequestFormValuesOneOf>() {
        });
        schemas.put("CreateReportTemplateRequestFormValuesOneOf1", new GenericType<CreateReportTemplateRequestFormValuesOneOf1>() {
        });
        schemas.put("CreateReportTemplateRequestFormValuesOneOf2", new GenericType<CreateReportTemplateRequestFormValuesOneOf2>() {
        });
        schemas.put("CreateReportTemplateRequestFormValuesOneOf3", new GenericType<CreateReportTemplateRequestFormValuesOneOf3>() {
        });
        schemas.put("CreateReportTemplateRequestFormValuesOneOf4", new GenericType<CreateReportTemplateRequestFormValuesOneOf4>() {
        });
        schemas.put("CreateReportTemplateRequestFormValuesOneOf5", new GenericType<CreateReportTemplateRequestFormValuesOneOf5>() {
        });
        JSON.registerDescendants(CreateReportTemplateRequestFormValues.class, Collections.unmodifiableMap(schemas));
    }

    @Override
    public Map<String, GenericType<?>> getSchemas() {
        return CreateReportTemplateRequestFormValues.schemas;
    }

    /**
     * Set the instance that matches the oneOf child schema, check
     * the instance parameter is valid against the oneOf child schemas:
     * CreateReportTemplateRequestFormValuesOneOf, CreateReportTemplateRequestFormValuesOneOf1, CreateReportTemplateRequestFormValuesOneOf2, CreateReportTemplateRequestFormValuesOneOf3, CreateReportTemplateRequestFormValuesOneOf4, CreateReportTemplateRequestFormValuesOneOf5
     *
     * It could be an instance of the 'oneOf' schemas.
     * The oneOf child schemas may themselves be a composed schema (allOf, anyOf, oneOf).
     */
    @Override
    public void setActualInstance(Object instance) {
        if (JSON.isInstanceOf(CreateReportTemplateRequestFormValuesOneOf.class, instance, new HashSet<>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(CreateReportTemplateRequestFormValuesOneOf1.class, instance, new HashSet<>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(CreateReportTemplateRequestFormValuesOneOf2.class, instance, new HashSet<>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(CreateReportTemplateRequestFormValuesOneOf3.class, instance, new HashSet<>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(CreateReportTemplateRequestFormValuesOneOf4.class, instance, new HashSet<>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(CreateReportTemplateRequestFormValuesOneOf5.class, instance, new HashSet<>())) {
            super.setActualInstance(instance);
            return;
        }

        throw new RuntimeException("Invalid instance type. Must be CreateReportTemplateRequestFormValuesOneOf, CreateReportTemplateRequestFormValuesOneOf1, CreateReportTemplateRequestFormValuesOneOf2, CreateReportTemplateRequestFormValuesOneOf3, CreateReportTemplateRequestFormValuesOneOf4, CreateReportTemplateRequestFormValuesOneOf5");
    }

    /**
     * Get the actual instance, which can be the following:
     * CreateReportTemplateRequestFormValuesOneOf, CreateReportTemplateRequestFormValuesOneOf1, CreateReportTemplateRequestFormValuesOneOf2, CreateReportTemplateRequestFormValuesOneOf3, CreateReportTemplateRequestFormValuesOneOf4, CreateReportTemplateRequestFormValuesOneOf5
     *
     * @return The actual instance (CreateReportTemplateRequestFormValuesOneOf, CreateReportTemplateRequestFormValuesOneOf1, CreateReportTemplateRequestFormValuesOneOf2, CreateReportTemplateRequestFormValuesOneOf3, CreateReportTemplateRequestFormValuesOneOf4, CreateReportTemplateRequestFormValuesOneOf5)
     */
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `CreateReportTemplateRequestFormValuesOneOf`. If the actual instance is not `CreateReportTemplateRequestFormValuesOneOf`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `CreateReportTemplateRequestFormValuesOneOf`
     * @throws ClassCastException if the instance is not `CreateReportTemplateRequestFormValuesOneOf`
     */
    public CreateReportTemplateRequestFormValuesOneOf getCreateReportTemplateRequestFormValuesOneOf() throws ClassCastException {
        return (CreateReportTemplateRequestFormValuesOneOf)super.getActualInstance();
    }

    /**
     * Get the actual instance of `CreateReportTemplateRequestFormValuesOneOf1`. If the actual instance is not `CreateReportTemplateRequestFormValuesOneOf1`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `CreateReportTemplateRequestFormValuesOneOf1`
     * @throws ClassCastException if the instance is not `CreateReportTemplateRequestFormValuesOneOf1`
     */
    public CreateReportTemplateRequestFormValuesOneOf1 getCreateReportTemplateRequestFormValuesOneOf1() throws ClassCastException {
        return (CreateReportTemplateRequestFormValuesOneOf1)super.getActualInstance();
    }

    /**
     * Get the actual instance of `CreateReportTemplateRequestFormValuesOneOf2`. If the actual instance is not `CreateReportTemplateRequestFormValuesOneOf2`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `CreateReportTemplateRequestFormValuesOneOf2`
     * @throws ClassCastException if the instance is not `CreateReportTemplateRequestFormValuesOneOf2`
     */
    public CreateReportTemplateRequestFormValuesOneOf2 getCreateReportTemplateRequestFormValuesOneOf2() throws ClassCastException {
        return (CreateReportTemplateRequestFormValuesOneOf2)super.getActualInstance();
    }

    /**
     * Get the actual instance of `CreateReportTemplateRequestFormValuesOneOf3`. If the actual instance is not `CreateReportTemplateRequestFormValuesOneOf3`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `CreateReportTemplateRequestFormValuesOneOf3`
     * @throws ClassCastException if the instance is not `CreateReportTemplateRequestFormValuesOneOf3`
     */
    public CreateReportTemplateRequestFormValuesOneOf3 getCreateReportTemplateRequestFormValuesOneOf3() throws ClassCastException {
        return (CreateReportTemplateRequestFormValuesOneOf3)super.getActualInstance();
    }

    /**
     * Get the actual instance of `CreateReportTemplateRequestFormValuesOneOf4`. If the actual instance is not `CreateReportTemplateRequestFormValuesOneOf4`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `CreateReportTemplateRequestFormValuesOneOf4`
     * @throws ClassCastException if the instance is not `CreateReportTemplateRequestFormValuesOneOf4`
     */
    public CreateReportTemplateRequestFormValuesOneOf4 getCreateReportTemplateRequestFormValuesOneOf4() throws ClassCastException {
        return (CreateReportTemplateRequestFormValuesOneOf4)super.getActualInstance();
    }

    /**
     * Get the actual instance of `CreateReportTemplateRequestFormValuesOneOf5`. If the actual instance is not `CreateReportTemplateRequestFormValuesOneOf5`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `CreateReportTemplateRequestFormValuesOneOf5`
     * @throws ClassCastException if the instance is not `CreateReportTemplateRequestFormValuesOneOf5`
     */
    public CreateReportTemplateRequestFormValuesOneOf5 getCreateReportTemplateRequestFormValuesOneOf5() throws ClassCastException {
        return (CreateReportTemplateRequestFormValuesOneOf5)super.getActualInstance();
    }

}

