/*
 * Software Risk Manager API Guide
 * Software Risk Manager provides a variety of REST APIs, allowing external applications and scripts to interface with core functionality. This guide documents the various REST resources provided by Software Risk Manager.  ## Authentication  Authentication is a requirement when accessing API endpoints. There are two methods by which authentication may be performed.  ### API Keys  The primary method for authentication is passing an `API-Key` header containing a valid API key with all requests, i.e.  `API-Key: <key goes here>`  API Keys come in two possible forms:   - `api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24` - latest format  - `550e8400-e29b-41d4-a716-44665544000` - legacy format  For example:  `API-Key: api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24`  `API-Key: 550e8400-e29b-41d4-a716-44665544000`  API keys may be generated by Software Risk Manager admins. Once they are generated, in most cases, they behave like regular users. They will need to be assigned user roles for any projects they will be used with. Although it is possible to assign the *admin* [role](../user_guide/Project-Management/user_role_configuration.html) to an API key, the recommendation is to avoid doing so unless absolutely necessary.  See the user guide for an overview about how to create and manage [API keys](../user_guide/Settings/api_keys_administration.html).  ### Personal Access Tokens  Personal Access Tokens can be used as [bearer tokens](https://swagger.io/docs/specification/authentication/bearer-authentication/), e.g.  `Authorization: Bearer secret-token:qRuXr1BqgoTWXNxUhYQ8H_Yl2zfy6vxuqMIRnkGO`  Personal Access Tokens can be created by any user, and represent a subset of that user's permissions.   ### HTTP Basic Authentication  HTTP Basic authentication may be used to authenticate with the API as a regular user. This is accomplished by including an `Authorization` header containing a typical authorization credential.  ## Error Handling  ### Bad Requests  For API calls that accept input, invalid values will trigger an HTTP 400 Bad Request status code.  ### Server Errors  For any API call, if an unexpected error occurs, an HTTP 500 Internal Server Error status code will be returned. If an error message is available, the response will include a basic message body describing the error:  ` {   \"error\": \"error message\" } `  The error property will contain a string message indicating the nature of the error.  ### Errors with Third-Party Applications  Sometimes Software Risk Manager must communicate with third-party applications like JIRA, Git, and certain enterprise tools. Some users may have in-house versions of these with self-signed certificates which may not be \"trusted\". In these cases, the API will respond with an HTTP 502 BAD GATEWAY status. If this happens, refer to [Trusting Certificates](../install_guide/Installation/trusting-certs.html) in the install guide.  ### API Unavailable  In special circumstances, particularly during the installation and update phases, the API will be unavailable. When the API is unavailable, all calls will return an HTTP 503 Service Unavailable status, and no actions or side effects will occur as a result of the calls.  ## Examples  Software Risk Manager's API uses REST over HTTP. As such, you can use any language/utility that supports making HTTP requests to interact with the API. The examples below use <a href=\"https://curl.haxx.se/\" target=\"_blank\">curl</a>, a popular command-line utility, to do so.  First, you'll need to [generate an API Key](../user_guide/Settings/api_keys_administration.html). Second, while you can create projects through the API, these examples will assume that you've already created one. You'll need to know its project id number, which you can find by looking at the URL for the [Findings Page](../user_guide/Findings/findings_overview.html), which will end in a number.  **Note:** Many API endpoints require a JSON body in the request. Most JSON will contain double-quotes (`\"`) and spaces, which have special meaning when used on the command line. In order to ensure your JSON body is interpreted as a single argument, you must <a href=\"https://en.wikipedia.org/wiki/Escape_character\" target=\"_blank\">escape</a> it properly. For example, if you wanted to `POST` the following JSON body:  ```{ \"name\": \"John Doe\" }```  You would put a backslash (`\\`) before each double-quote (`\"`), and surround the whole thing with double-quotes:  ```\"{ \\\"name\\\": \\\"John Doe\\\" }\"```  The outermost double-quotes tell the command-line interpreter that everything within them is to be treated as a single argument (as opposed to the usual space-separated behavior). The backslash before each inner double-quote tells the command-line interpreter that you mean the literal double-quote character, and not the end of the quoted argument.  In many *non-Windows* operating systems, you can also use a single-quote (`'`) to surround the argument, and skip the backslashes:  ```'{ \"name\": \"John Doe\" }'```  The examples below will use the double-quotes and backslashes style, as it works on most (if not all) operating systems.  ### Running an Analysis  To start an analysis, you can run  ```curl -F file1=@src.zip -H \"API-Key: api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24\" https://<yoursrmserver>/srm/api/projects/<project id>/analysis```  Make sure you use your own values for the `src.zip` file, the API Key, the hostname for your Software Risk Manager server, and the project id.  ### Retrieving Finding Data  There is a wide variety of data available for the findings of a project after running an analysis. Two examples are provided here.  ### Findings Table Data  You can retrieve the data that's used to populate the [findings table](../user_guide/Findings/findings_table.html):  ```curl -H \"Content-Type: application/json\" -X POST -d \"{\\\"filter\\\":{},\\\"sort\\\":{\\\"by\\\":\\\"id\\\",\\\"direction\\\":\\\"ascending\\\"},\\\"pagination\\\":{\\\"page\\\":1,\\\"perPage\\\":10}}\" -H \"API-Key: api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24\" https://<yoursrmserver>/srm/api/projects/<project id>/findings/table```  Additional information about how to construct more useful filter and sort requests can be found in the documentation.  ### Finding Metadata  You can retrieve metadata for a finding, if you know the finding ID. You can take the ID for a finding from the Findings Table:  ```curl -H \"API-Key: api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24\" https://<yoursrmserver>/srm/api/findings/<finding id>```  ### Generating a Report  You can use the API to generate a PDF [report](../user_guide/Findings/generate_report.html).  ```curl -H \"Content-Type: application/json\" -X POST -d \"{\\\"filter\\\":{},\\\"config\\\":{\\\"summaryMode\\\":\\\"simple\\\",\\\"detailsMode\\\":\\\"simple\\\",\\\"includeResultDetails\\\":true,\\\"includeComments\\\":false}}\" -H \"API-Key: api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24\" https://<yoursrmserver>/srm/api/projects/<project id>/report/pdf```  ## Generating a Client SDK  If you require a client SDK for Software Risk Manager, you can generate one using [OpenAPI Generator](https://openapi-generator.tech/). Detailed instructions are available on the [GitHub page](https://github.com/OpenAPITools/openapi-generator) and our OpenAPI spec can be found [here](swagger/swagger.json). 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.codedx.client.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.codedx.client.model.DashboardDataRange;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.codedx.client.JSON;


/**
 * DashboardQueryFields
 */
@JsonPropertyOrder({
  DashboardQueryFields.JSON_PROPERTY_ANALYSIS_COUNTS_BY_METHOD,
  DashboardQueryFields.JSON_PROPERTY_AVERAGE_RESOLUTION_TIME,
  DashboardQueryFields.JSON_PROPERTY_CODE_METRICS,
  DashboardQueryFields.JSON_PROPERTY_CREATED_VS_RESOLVED,
  DashboardQueryFields.JSON_PROPERTY_DX_SCORE,
  DashboardQueryFields.JSON_PROPERTY_FINDING_COUNTS_BY_DESCRIPTOR,
  DashboardQueryFields.JSON_PROPERTY_FINDING_COUNTS_BY_DETECTION,
  DashboardQueryFields.JSON_PROPERTY_FINDINGS_PERCENT_TRIAGED,
  DashboardQueryFields.JSON_PROPERTY_OPEN_FINDING_TYPES,
  DashboardQueryFields.JSON_PROPERTY_RECENT_ANALYSIS_STATS,
  DashboardQueryFields.JSON_PROPERTY_RECENT_TOOL_STATS,
  DashboardQueryFields.JSON_PROPERTY_SEVERITY_AGE_BREAKDOWN
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-02T11:55:06.722228-04:00[America/New_York]", comments = "Generator version: 7.21.0")
public class DashboardQueryFields {
  public static final String JSON_PROPERTY_ANALYSIS_COUNTS_BY_METHOD = "analysisCountsByMethod";
  @jakarta.annotation.Nullable
  private DashboardDataRange analysisCountsByMethod;

  public static final String JSON_PROPERTY_AVERAGE_RESOLUTION_TIME = "averageResolutionTime";
  @jakarta.annotation.Nullable
  private DashboardDataRange averageResolutionTime;

  public static final String JSON_PROPERTY_CODE_METRICS = "codeMetrics";
  @jakarta.annotation.Nullable
  private DashboardDataRange codeMetrics;

  public static final String JSON_PROPERTY_CREATED_VS_RESOLVED = "createdVsResolved";
  @jakarta.annotation.Nullable
  private DashboardDataRange createdVsResolved;

  public static final String JSON_PROPERTY_DX_SCORE = "dxScore";
  @jakarta.annotation.Nullable
  private DashboardDataRange dxScore;

  public static final String JSON_PROPERTY_FINDING_COUNTS_BY_DESCRIPTOR = "findingCountsByDescriptor";
  @jakarta.annotation.Nullable
  private DashboardDataRange findingCountsByDescriptor;

  public static final String JSON_PROPERTY_FINDING_COUNTS_BY_DETECTION = "findingCountsByDetection";
  @jakarta.annotation.Nullable
  private DashboardDataRange findingCountsByDetection;

  public static final String JSON_PROPERTY_FINDINGS_PERCENT_TRIAGED = "findingsPercentTriaged";
  @jakarta.annotation.Nullable
  private DashboardDataRange findingsPercentTriaged;

  public static final String JSON_PROPERTY_OPEN_FINDING_TYPES = "openFindingTypes";
  @jakarta.annotation.Nullable
  private DashboardDataRange openFindingTypes;

  public static final String JSON_PROPERTY_RECENT_ANALYSIS_STATS = "recentAnalysisStats";
  @jakarta.annotation.Nullable
  private DashboardDataRange recentAnalysisStats;

  public static final String JSON_PROPERTY_RECENT_TOOL_STATS = "recentToolStats";
  @jakarta.annotation.Nullable
  private DashboardDataRange recentToolStats;

  public static final String JSON_PROPERTY_SEVERITY_AGE_BREAKDOWN = "severityAgeBreakdown";
  @jakarta.annotation.Nullable
  private DashboardDataRange severityAgeBreakdown;

  public DashboardQueryFields() { 
  }

  public DashboardQueryFields analysisCountsByMethod(@jakarta.annotation.Nullable DashboardDataRange analysisCountsByMethod) {
    this.analysisCountsByMethod = analysisCountsByMethod;
    return this;
  }

  /**
   * Get analysisCountsByMethod
   * @return analysisCountsByMethod
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ANALYSIS_COUNTS_BY_METHOD, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public DashboardDataRange getAnalysisCountsByMethod() {
    return analysisCountsByMethod;
  }


  @JsonProperty(value = JSON_PROPERTY_ANALYSIS_COUNTS_BY_METHOD, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAnalysisCountsByMethod(@jakarta.annotation.Nullable DashboardDataRange analysisCountsByMethod) {
    this.analysisCountsByMethod = analysisCountsByMethod;
  }


  public DashboardQueryFields averageResolutionTime(@jakarta.annotation.Nullable DashboardDataRange averageResolutionTime) {
    this.averageResolutionTime = averageResolutionTime;
    return this;
  }

  /**
   * Get averageResolutionTime
   * @return averageResolutionTime
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_AVERAGE_RESOLUTION_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public DashboardDataRange getAverageResolutionTime() {
    return averageResolutionTime;
  }


  @JsonProperty(value = JSON_PROPERTY_AVERAGE_RESOLUTION_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAverageResolutionTime(@jakarta.annotation.Nullable DashboardDataRange averageResolutionTime) {
    this.averageResolutionTime = averageResolutionTime;
  }


  public DashboardQueryFields codeMetrics(@jakarta.annotation.Nullable DashboardDataRange codeMetrics) {
    this.codeMetrics = codeMetrics;
    return this;
  }

  /**
   * Get codeMetrics
   * @return codeMetrics
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CODE_METRICS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public DashboardDataRange getCodeMetrics() {
    return codeMetrics;
  }


  @JsonProperty(value = JSON_PROPERTY_CODE_METRICS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCodeMetrics(@jakarta.annotation.Nullable DashboardDataRange codeMetrics) {
    this.codeMetrics = codeMetrics;
  }


  public DashboardQueryFields createdVsResolved(@jakarta.annotation.Nullable DashboardDataRange createdVsResolved) {
    this.createdVsResolved = createdVsResolved;
    return this;
  }

  /**
   * Get createdVsResolved
   * @return createdVsResolved
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CREATED_VS_RESOLVED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public DashboardDataRange getCreatedVsResolved() {
    return createdVsResolved;
  }


  @JsonProperty(value = JSON_PROPERTY_CREATED_VS_RESOLVED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreatedVsResolved(@jakarta.annotation.Nullable DashboardDataRange createdVsResolved) {
    this.createdVsResolved = createdVsResolved;
  }


  public DashboardQueryFields dxScore(@jakarta.annotation.Nullable DashboardDataRange dxScore) {
    this.dxScore = dxScore;
    return this;
  }

  /**
   * Get dxScore
   * @return dxScore
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DX_SCORE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public DashboardDataRange getDxScore() {
    return dxScore;
  }


  @JsonProperty(value = JSON_PROPERTY_DX_SCORE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDxScore(@jakarta.annotation.Nullable DashboardDataRange dxScore) {
    this.dxScore = dxScore;
  }


  public DashboardQueryFields findingCountsByDescriptor(@jakarta.annotation.Nullable DashboardDataRange findingCountsByDescriptor) {
    this.findingCountsByDescriptor = findingCountsByDescriptor;
    return this;
  }

  /**
   * Get findingCountsByDescriptor
   * @return findingCountsByDescriptor
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FINDING_COUNTS_BY_DESCRIPTOR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public DashboardDataRange getFindingCountsByDescriptor() {
    return findingCountsByDescriptor;
  }


  @JsonProperty(value = JSON_PROPERTY_FINDING_COUNTS_BY_DESCRIPTOR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFindingCountsByDescriptor(@jakarta.annotation.Nullable DashboardDataRange findingCountsByDescriptor) {
    this.findingCountsByDescriptor = findingCountsByDescriptor;
  }


  public DashboardQueryFields findingCountsByDetection(@jakarta.annotation.Nullable DashboardDataRange findingCountsByDetection) {
    this.findingCountsByDetection = findingCountsByDetection;
    return this;
  }

  /**
   * Get findingCountsByDetection
   * @return findingCountsByDetection
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FINDING_COUNTS_BY_DETECTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public DashboardDataRange getFindingCountsByDetection() {
    return findingCountsByDetection;
  }


  @JsonProperty(value = JSON_PROPERTY_FINDING_COUNTS_BY_DETECTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFindingCountsByDetection(@jakarta.annotation.Nullable DashboardDataRange findingCountsByDetection) {
    this.findingCountsByDetection = findingCountsByDetection;
  }


  public DashboardQueryFields findingsPercentTriaged(@jakarta.annotation.Nullable DashboardDataRange findingsPercentTriaged) {
    this.findingsPercentTriaged = findingsPercentTriaged;
    return this;
  }

  /**
   * Get findingsPercentTriaged
   * @return findingsPercentTriaged
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FINDINGS_PERCENT_TRIAGED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public DashboardDataRange getFindingsPercentTriaged() {
    return findingsPercentTriaged;
  }


  @JsonProperty(value = JSON_PROPERTY_FINDINGS_PERCENT_TRIAGED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFindingsPercentTriaged(@jakarta.annotation.Nullable DashboardDataRange findingsPercentTriaged) {
    this.findingsPercentTriaged = findingsPercentTriaged;
  }


  public DashboardQueryFields openFindingTypes(@jakarta.annotation.Nullable DashboardDataRange openFindingTypes) {
    this.openFindingTypes = openFindingTypes;
    return this;
  }

  /**
   * Get openFindingTypes
   * @return openFindingTypes
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_OPEN_FINDING_TYPES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public DashboardDataRange getOpenFindingTypes() {
    return openFindingTypes;
  }


  @JsonProperty(value = JSON_PROPERTY_OPEN_FINDING_TYPES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOpenFindingTypes(@jakarta.annotation.Nullable DashboardDataRange openFindingTypes) {
    this.openFindingTypes = openFindingTypes;
  }


  public DashboardQueryFields recentAnalysisStats(@jakarta.annotation.Nullable DashboardDataRange recentAnalysisStats) {
    this.recentAnalysisStats = recentAnalysisStats;
    return this;
  }

  /**
   * Get recentAnalysisStats
   * @return recentAnalysisStats
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_RECENT_ANALYSIS_STATS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public DashboardDataRange getRecentAnalysisStats() {
    return recentAnalysisStats;
  }


  @JsonProperty(value = JSON_PROPERTY_RECENT_ANALYSIS_STATS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRecentAnalysisStats(@jakarta.annotation.Nullable DashboardDataRange recentAnalysisStats) {
    this.recentAnalysisStats = recentAnalysisStats;
  }


  public DashboardQueryFields recentToolStats(@jakarta.annotation.Nullable DashboardDataRange recentToolStats) {
    this.recentToolStats = recentToolStats;
    return this;
  }

  /**
   * Get recentToolStats
   * @return recentToolStats
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_RECENT_TOOL_STATS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public DashboardDataRange getRecentToolStats() {
    return recentToolStats;
  }


  @JsonProperty(value = JSON_PROPERTY_RECENT_TOOL_STATS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRecentToolStats(@jakarta.annotation.Nullable DashboardDataRange recentToolStats) {
    this.recentToolStats = recentToolStats;
  }


  public DashboardQueryFields severityAgeBreakdown(@jakarta.annotation.Nullable DashboardDataRange severityAgeBreakdown) {
    this.severityAgeBreakdown = severityAgeBreakdown;
    return this;
  }

  /**
   * Get severityAgeBreakdown
   * @return severityAgeBreakdown
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SEVERITY_AGE_BREAKDOWN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public DashboardDataRange getSeverityAgeBreakdown() {
    return severityAgeBreakdown;
  }


  @JsonProperty(value = JSON_PROPERTY_SEVERITY_AGE_BREAKDOWN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSeverityAgeBreakdown(@jakarta.annotation.Nullable DashboardDataRange severityAgeBreakdown) {
    this.severityAgeBreakdown = severityAgeBreakdown;
  }


  /**
   * Return true if this DashboardQueryFields object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DashboardQueryFields dashboardQueryFields = (DashboardQueryFields) o;
    return Objects.equals(this.analysisCountsByMethod, dashboardQueryFields.analysisCountsByMethod) &&
        Objects.equals(this.averageResolutionTime, dashboardQueryFields.averageResolutionTime) &&
        Objects.equals(this.codeMetrics, dashboardQueryFields.codeMetrics) &&
        Objects.equals(this.createdVsResolved, dashboardQueryFields.createdVsResolved) &&
        Objects.equals(this.dxScore, dashboardQueryFields.dxScore) &&
        Objects.equals(this.findingCountsByDescriptor, dashboardQueryFields.findingCountsByDescriptor) &&
        Objects.equals(this.findingCountsByDetection, dashboardQueryFields.findingCountsByDetection) &&
        Objects.equals(this.findingsPercentTriaged, dashboardQueryFields.findingsPercentTriaged) &&
        Objects.equals(this.openFindingTypes, dashboardQueryFields.openFindingTypes) &&
        Objects.equals(this.recentAnalysisStats, dashboardQueryFields.recentAnalysisStats) &&
        Objects.equals(this.recentToolStats, dashboardQueryFields.recentToolStats) &&
        Objects.equals(this.severityAgeBreakdown, dashboardQueryFields.severityAgeBreakdown);
  }

  @Override
  public int hashCode() {
    return Objects.hash(analysisCountsByMethod, averageResolutionTime, codeMetrics, createdVsResolved, dxScore, findingCountsByDescriptor, findingCountsByDetection, findingsPercentTriaged, openFindingTypes, recentAnalysisStats, recentToolStats, severityAgeBreakdown);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DashboardQueryFields {\n");
    sb.append("    analysisCountsByMethod: ").append(toIndentedString(analysisCountsByMethod)).append("\n");
    sb.append("    averageResolutionTime: ").append(toIndentedString(averageResolutionTime)).append("\n");
    sb.append("    codeMetrics: ").append(toIndentedString(codeMetrics)).append("\n");
    sb.append("    createdVsResolved: ").append(toIndentedString(createdVsResolved)).append("\n");
    sb.append("    dxScore: ").append(toIndentedString(dxScore)).append("\n");
    sb.append("    findingCountsByDescriptor: ").append(toIndentedString(findingCountsByDescriptor)).append("\n");
    sb.append("    findingCountsByDetection: ").append(toIndentedString(findingCountsByDetection)).append("\n");
    sb.append("    findingsPercentTriaged: ").append(toIndentedString(findingsPercentTriaged)).append("\n");
    sb.append("    openFindingTypes: ").append(toIndentedString(openFindingTypes)).append("\n");
    sb.append("    recentAnalysisStats: ").append(toIndentedString(recentAnalysisStats)).append("\n");
    sb.append("    recentToolStats: ").append(toIndentedString(recentToolStats)).append("\n");
    sb.append("    severityAgeBreakdown: ").append(toIndentedString(severityAgeBreakdown)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

