/*
 * Software Risk Manager API Guide
 * Software Risk Manager provides a variety of REST APIs, allowing external applications and scripts to interface with core functionality. This guide documents the various REST resources provided by Software Risk Manager.  ## Authentication  Authentication is a requirement when accessing API endpoints. There are two methods by which authentication may be performed.  ### API Keys  The primary method for authentication is passing an `API-Key` header containing a valid API key with all requests, i.e.  `API-Key: <key goes here>`  API Keys come in two possible forms:   - `api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24` - latest format  - `550e8400-e29b-41d4-a716-44665544000` - legacy format  For example:  `API-Key: api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24`  `API-Key: 550e8400-e29b-41d4-a716-44665544000`  API keys may be generated by Software Risk Manager admins. Once they are generated, in most cases, they behave like regular users. They will need to be assigned user roles for any projects they will be used with. Although it is possible to assign the *admin* [role](../user_guide/Project-Management/user_role_configuration.html) to an API key, the recommendation is to avoid doing so unless absolutely necessary.  See the user guide for an overview about how to create and manage [API keys](../user_guide/Settings/api_keys_administration.html).  ### Personal Access Tokens  Personal Access Tokens can be used as [bearer tokens](https://swagger.io/docs/specification/authentication/bearer-authentication/), e.g.  `Authorization: Bearer secret-token:qRuXr1BqgoTWXNxUhYQ8H_Yl2zfy6vxuqMIRnkGO`  Personal Access Tokens can be created by any user, and represent a subset of that user's permissions.   ### HTTP Basic Authentication  HTTP Basic authentication may be used to authenticate with the API as a regular user. This is accomplished by including an `Authorization` header containing a typical authorization credential.  ## Error Handling  ### Bad Requests  For API calls that accept input, invalid values will trigger an HTTP 400 Bad Request status code.  ### Server Errors  For any API call, if an unexpected error occurs, an HTTP 500 Internal Server Error status code will be returned. If an error message is available, the response will include a basic message body describing the error:  ` {   \"error\": \"error message\" } `  The error property will contain a string message indicating the nature of the error.  ### Errors with Third-Party Applications  Sometimes Software Risk Manager must communicate with third-party applications like JIRA, Git, and certain enterprise tools. Some users may have in-house versions of these with self-signed certificates which may not be \"trusted\". In these cases, the API will respond with an HTTP 502 BAD GATEWAY status. If this happens, refer to [Trusting Certificates](../install_guide/Installation/trusting-certs.html) in the install guide.  ### API Unavailable  In special circumstances, particularly during the installation and update phases, the API will be unavailable. When the API is unavailable, all calls will return an HTTP 503 Service Unavailable status, and no actions or side effects will occur as a result of the calls.  ## Examples  Software Risk Manager's API uses REST over HTTP. As such, you can use any language/utility that supports making HTTP requests to interact with the API. The examples below use <a href=\"https://curl.haxx.se/\" target=\"_blank\">curl</a>, a popular command-line utility, to do so.  First, you'll need to [generate an API Key](../user_guide/Settings/api_keys_administration.html). Second, while you can create projects through the API, these examples will assume that you've already created one. You'll need to know its project id number, which you can find by looking at the URL for the [Findings Page](../user_guide/Findings/findings_overview.html), which will end in a number.  **Note:** Many API endpoints require a JSON body in the request. Most JSON will contain double-quotes (`\"`) and spaces, which have special meaning when used on the command line. In order to ensure your JSON body is interpreted as a single argument, you must <a href=\"https://en.wikipedia.org/wiki/Escape_character\" target=\"_blank\">escape</a> it properly. For example, if you wanted to `POST` the following JSON body:  ```{ \"name\": \"John Doe\" }```  You would put a backslash (`\\`) before each double-quote (`\"`), and surround the whole thing with double-quotes:  ```\"{ \\\"name\\\": \\\"John Doe\\\" }\"```  The outermost double-quotes tell the command-line interpreter that everything within them is to be treated as a single argument (as opposed to the usual space-separated behavior). The backslash before each inner double-quote tells the command-line interpreter that you mean the literal double-quote character, and not the end of the quoted argument.  In many *non-Windows* operating systems, you can also use a single-quote (`'`) to surround the argument, and skip the backslashes:  ```'{ \"name\": \"John Doe\" }'```  The examples below will use the double-quotes and backslashes style, as it works on most (if not all) operating systems.  ### Running an Analysis  To start an analysis, you can run  ```curl -F file1=@src.zip -H \"API-Key: api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24\" https://<yoursrmserver>/srm/api/projects/<project id>/analysis```  Make sure you use your own values for the `src.zip` file, the API Key, the hostname for your Software Risk Manager server, and the project id.  ### Retrieving Finding Data  There is a wide variety of data available for the findings of a project after running an analysis. Two examples are provided here.  ### Findings Table Data  You can retrieve the data that's used to populate the [findings table](../user_guide/Findings/findings_table.html):  ```curl -H \"Content-Type: application/json\" -X POST -d \"{\\\"filter\\\":{},\\\"sort\\\":{\\\"by\\\":\\\"id\\\",\\\"direction\\\":\\\"ascending\\\"},\\\"pagination\\\":{\\\"page\\\":1,\\\"perPage\\\":10}}\" -H \"API-Key: api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24\" https://<yoursrmserver>/srm/api/projects/<project id>/findings/table```  Additional information about how to construct more useful filter and sort requests can be found in the documentation.  ### Finding Metadata  You can retrieve metadata for a finding, if you know the finding ID. You can take the ID for a finding from the Findings Table:  ```curl -H \"API-Key: api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24\" https://<yoursrmserver>/srm/api/findings/<finding id>```  ### Generating a Report  You can use the API to generate a PDF [report](../user_guide/Findings/generate_report.html).  ```curl -H \"Content-Type: application/json\" -X POST -d \"{\\\"filter\\\":{},\\\"config\\\":{\\\"summaryMode\\\":\\\"simple\\\",\\\"detailsMode\\\":\\\"simple\\\",\\\"includeResultDetails\\\":true,\\\"includeComments\\\":false}}\" -H \"API-Key: api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24\" https://<yoursrmserver>/srm/api/projects/<project id>/report/pdf```  ## Generating a Client SDK  If you require a client SDK for Software Risk Manager, you can generate one using [OpenAPI Generator](https://openapi-generator.tech/). Detailed instructions are available on the [GitHub page](https://github.com/OpenAPITools/openapi-generator) and our OpenAPI spec can be found [here](swagger/swagger.json). 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.codedx.client.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.codedx.client.model.DashboardDataAnalysisCountsByMethodInner;
import com.codedx.client.model.DashboardDataAverageResolutionTimeInner;
import com.codedx.client.model.DashboardDataCodeMetricsInner;
import com.codedx.client.model.DashboardDataCreatedVsResolvedInner;
import com.codedx.client.model.DashboardDataDxScoreInner;
import com.codedx.client.model.DashboardDataFindingCountsByDescriptorInner;
import com.codedx.client.model.DashboardDataFindingCountsByDetectionInner;
import com.codedx.client.model.DashboardDataFindingsPercentTriagedInner;
import com.codedx.client.model.DashboardDataOpenFindingTypesInner;
import com.codedx.client.model.DashboardDataRecentAnalysisStatsInner;
import com.codedx.client.model.DashboardDataRecentToolStatsInner;
import com.codedx.client.model.DashboardDataSeverityAgeBreakdownInner;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.codedx.client.JSON;


/**
 * DashboardData
 */
@JsonPropertyOrder({
  DashboardData.JSON_PROPERTY_ANALYSIS_COUNTS_BY_METHOD,
  DashboardData.JSON_PROPERTY_AVERAGE_RESOLUTION_TIME,
  DashboardData.JSON_PROPERTY_CODE_METRICS,
  DashboardData.JSON_PROPERTY_CREATED_VS_RESOLVED,
  DashboardData.JSON_PROPERTY_DX_SCORE,
  DashboardData.JSON_PROPERTY_FINDING_COUNTS_BY_DESCRIPTOR,
  DashboardData.JSON_PROPERTY_FINDING_COUNTS_BY_DETECTION,
  DashboardData.JSON_PROPERTY_FINDINGS_PERCENT_TRIAGED,
  DashboardData.JSON_PROPERTY_OPEN_FINDING_TYPES,
  DashboardData.JSON_PROPERTY_RECENT_ANALYSIS_STATS,
  DashboardData.JSON_PROPERTY_RECENT_TOOL_STATS,
  DashboardData.JSON_PROPERTY_SEVERITY_AGE_BREAKDOWN
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-02T11:55:06.722228-04:00[America/New_York]", comments = "Generator version: 7.21.0")
public class DashboardData {
  public static final String JSON_PROPERTY_ANALYSIS_COUNTS_BY_METHOD = "analysisCountsByMethod";
  @jakarta.annotation.Nullable
  private List<DashboardDataAnalysisCountsByMethodInner> analysisCountsByMethod = new ArrayList<>();

  public static final String JSON_PROPERTY_AVERAGE_RESOLUTION_TIME = "averageResolutionTime";
  @jakarta.annotation.Nullable
  private List<DashboardDataAverageResolutionTimeInner> averageResolutionTime = new ArrayList<>();

  public static final String JSON_PROPERTY_CODE_METRICS = "codeMetrics";
  @jakarta.annotation.Nullable
  private List<DashboardDataCodeMetricsInner> codeMetrics = new ArrayList<>();

  public static final String JSON_PROPERTY_CREATED_VS_RESOLVED = "createdVsResolved";
  @jakarta.annotation.Nullable
  private List<DashboardDataCreatedVsResolvedInner> createdVsResolved = new ArrayList<>();

  public static final String JSON_PROPERTY_DX_SCORE = "dxScore";
  @jakarta.annotation.Nullable
  private List<DashboardDataDxScoreInner> dxScore = new ArrayList<>();

  public static final String JSON_PROPERTY_FINDING_COUNTS_BY_DESCRIPTOR = "findingCountsByDescriptor";
  @jakarta.annotation.Nullable
  private List<DashboardDataFindingCountsByDescriptorInner> findingCountsByDescriptor = new ArrayList<>();

  public static final String JSON_PROPERTY_FINDING_COUNTS_BY_DETECTION = "findingCountsByDetection";
  @jakarta.annotation.Nullable
  private List<DashboardDataFindingCountsByDetectionInner> findingCountsByDetection = new ArrayList<>();

  public static final String JSON_PROPERTY_FINDINGS_PERCENT_TRIAGED = "findingsPercentTriaged";
  @jakarta.annotation.Nullable
  private List<DashboardDataFindingsPercentTriagedInner> findingsPercentTriaged = new ArrayList<>();

  public static final String JSON_PROPERTY_OPEN_FINDING_TYPES = "openFindingTypes";
  @jakarta.annotation.Nullable
  private List<DashboardDataOpenFindingTypesInner> openFindingTypes = new ArrayList<>();

  public static final String JSON_PROPERTY_RECENT_ANALYSIS_STATS = "recentAnalysisStats";
  @jakarta.annotation.Nullable
  private List<DashboardDataRecentAnalysisStatsInner> recentAnalysisStats = new ArrayList<>();

  public static final String JSON_PROPERTY_RECENT_TOOL_STATS = "recentToolStats";
  @jakarta.annotation.Nullable
  private List<DashboardDataRecentToolStatsInner> recentToolStats = new ArrayList<>();

  public static final String JSON_PROPERTY_SEVERITY_AGE_BREAKDOWN = "severityAgeBreakdown";
  @jakarta.annotation.Nullable
  private List<DashboardDataSeverityAgeBreakdownInner> severityAgeBreakdown = new ArrayList<>();

  public DashboardData() { 
  }

  public DashboardData analysisCountsByMethod(@jakarta.annotation.Nullable List<DashboardDataAnalysisCountsByMethodInner> analysisCountsByMethod) {
    this.analysisCountsByMethod = analysisCountsByMethod;
    return this;
  }

  public DashboardData addAnalysisCountsByMethodItem(DashboardDataAnalysisCountsByMethodInner analysisCountsByMethodItem) {
    if (this.analysisCountsByMethod == null) {
      this.analysisCountsByMethod = new ArrayList<>();
    }
    this.analysisCountsByMethod.add(analysisCountsByMethodItem);
    return this;
  }

  /**
   * Get analysisCountsByMethod
   * @return analysisCountsByMethod
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ANALYSIS_COUNTS_BY_METHOD, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<DashboardDataAnalysisCountsByMethodInner> getAnalysisCountsByMethod() {
    return analysisCountsByMethod;
  }


  @JsonProperty(value = JSON_PROPERTY_ANALYSIS_COUNTS_BY_METHOD, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAnalysisCountsByMethod(@jakarta.annotation.Nullable List<DashboardDataAnalysisCountsByMethodInner> analysisCountsByMethod) {
    this.analysisCountsByMethod = analysisCountsByMethod;
  }


  public DashboardData averageResolutionTime(@jakarta.annotation.Nullable List<DashboardDataAverageResolutionTimeInner> averageResolutionTime) {
    this.averageResolutionTime = averageResolutionTime;
    return this;
  }

  public DashboardData addAverageResolutionTimeItem(DashboardDataAverageResolutionTimeInner averageResolutionTimeItem) {
    if (this.averageResolutionTime == null) {
      this.averageResolutionTime = new ArrayList<>();
    }
    this.averageResolutionTime.add(averageResolutionTimeItem);
    return this;
  }

  /**
   * Get averageResolutionTime
   * @return averageResolutionTime
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_AVERAGE_RESOLUTION_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<DashboardDataAverageResolutionTimeInner> getAverageResolutionTime() {
    return averageResolutionTime;
  }


  @JsonProperty(value = JSON_PROPERTY_AVERAGE_RESOLUTION_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAverageResolutionTime(@jakarta.annotation.Nullable List<DashboardDataAverageResolutionTimeInner> averageResolutionTime) {
    this.averageResolutionTime = averageResolutionTime;
  }


  public DashboardData codeMetrics(@jakarta.annotation.Nullable List<DashboardDataCodeMetricsInner> codeMetrics) {
    this.codeMetrics = codeMetrics;
    return this;
  }

  public DashboardData addCodeMetricsItem(DashboardDataCodeMetricsInner codeMetricsItem) {
    if (this.codeMetrics == null) {
      this.codeMetrics = new ArrayList<>();
    }
    this.codeMetrics.add(codeMetricsItem);
    return this;
  }

  /**
   * Get codeMetrics
   * @return codeMetrics
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CODE_METRICS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<DashboardDataCodeMetricsInner> getCodeMetrics() {
    return codeMetrics;
  }


  @JsonProperty(value = JSON_PROPERTY_CODE_METRICS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCodeMetrics(@jakarta.annotation.Nullable List<DashboardDataCodeMetricsInner> codeMetrics) {
    this.codeMetrics = codeMetrics;
  }


  public DashboardData createdVsResolved(@jakarta.annotation.Nullable List<DashboardDataCreatedVsResolvedInner> createdVsResolved) {
    this.createdVsResolved = createdVsResolved;
    return this;
  }

  public DashboardData addCreatedVsResolvedItem(DashboardDataCreatedVsResolvedInner createdVsResolvedItem) {
    if (this.createdVsResolved == null) {
      this.createdVsResolved = new ArrayList<>();
    }
    this.createdVsResolved.add(createdVsResolvedItem);
    return this;
  }

  /**
   * Get createdVsResolved
   * @return createdVsResolved
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CREATED_VS_RESOLVED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<DashboardDataCreatedVsResolvedInner> getCreatedVsResolved() {
    return createdVsResolved;
  }


  @JsonProperty(value = JSON_PROPERTY_CREATED_VS_RESOLVED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreatedVsResolved(@jakarta.annotation.Nullable List<DashboardDataCreatedVsResolvedInner> createdVsResolved) {
    this.createdVsResolved = createdVsResolved;
  }


  public DashboardData dxScore(@jakarta.annotation.Nullable List<DashboardDataDxScoreInner> dxScore) {
    this.dxScore = dxScore;
    return this;
  }

  public DashboardData addDxScoreItem(DashboardDataDxScoreInner dxScoreItem) {
    if (this.dxScore == null) {
      this.dxScore = new ArrayList<>();
    }
    this.dxScore.add(dxScoreItem);
    return this;
  }

  /**
   * Get dxScore
   * @return dxScore
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DX_SCORE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<DashboardDataDxScoreInner> getDxScore() {
    return dxScore;
  }


  @JsonProperty(value = JSON_PROPERTY_DX_SCORE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDxScore(@jakarta.annotation.Nullable List<DashboardDataDxScoreInner> dxScore) {
    this.dxScore = dxScore;
  }


  public DashboardData findingCountsByDescriptor(@jakarta.annotation.Nullable List<DashboardDataFindingCountsByDescriptorInner> findingCountsByDescriptor) {
    this.findingCountsByDescriptor = findingCountsByDescriptor;
    return this;
  }

  public DashboardData addFindingCountsByDescriptorItem(DashboardDataFindingCountsByDescriptorInner findingCountsByDescriptorItem) {
    if (this.findingCountsByDescriptor == null) {
      this.findingCountsByDescriptor = new ArrayList<>();
    }
    this.findingCountsByDescriptor.add(findingCountsByDescriptorItem);
    return this;
  }

  /**
   * Get findingCountsByDescriptor
   * @return findingCountsByDescriptor
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FINDING_COUNTS_BY_DESCRIPTOR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<DashboardDataFindingCountsByDescriptorInner> getFindingCountsByDescriptor() {
    return findingCountsByDescriptor;
  }


  @JsonProperty(value = JSON_PROPERTY_FINDING_COUNTS_BY_DESCRIPTOR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFindingCountsByDescriptor(@jakarta.annotation.Nullable List<DashboardDataFindingCountsByDescriptorInner> findingCountsByDescriptor) {
    this.findingCountsByDescriptor = findingCountsByDescriptor;
  }


  public DashboardData findingCountsByDetection(@jakarta.annotation.Nullable List<DashboardDataFindingCountsByDetectionInner> findingCountsByDetection) {
    this.findingCountsByDetection = findingCountsByDetection;
    return this;
  }

  public DashboardData addFindingCountsByDetectionItem(DashboardDataFindingCountsByDetectionInner findingCountsByDetectionItem) {
    if (this.findingCountsByDetection == null) {
      this.findingCountsByDetection = new ArrayList<>();
    }
    this.findingCountsByDetection.add(findingCountsByDetectionItem);
    return this;
  }

  /**
   * Get findingCountsByDetection
   * @return findingCountsByDetection
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FINDING_COUNTS_BY_DETECTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<DashboardDataFindingCountsByDetectionInner> getFindingCountsByDetection() {
    return findingCountsByDetection;
  }


  @JsonProperty(value = JSON_PROPERTY_FINDING_COUNTS_BY_DETECTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFindingCountsByDetection(@jakarta.annotation.Nullable List<DashboardDataFindingCountsByDetectionInner> findingCountsByDetection) {
    this.findingCountsByDetection = findingCountsByDetection;
  }


  public DashboardData findingsPercentTriaged(@jakarta.annotation.Nullable List<DashboardDataFindingsPercentTriagedInner> findingsPercentTriaged) {
    this.findingsPercentTriaged = findingsPercentTriaged;
    return this;
  }

  public DashboardData addFindingsPercentTriagedItem(DashboardDataFindingsPercentTriagedInner findingsPercentTriagedItem) {
    if (this.findingsPercentTriaged == null) {
      this.findingsPercentTriaged = new ArrayList<>();
    }
    this.findingsPercentTriaged.add(findingsPercentTriagedItem);
    return this;
  }

  /**
   * Get findingsPercentTriaged
   * @return findingsPercentTriaged
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FINDINGS_PERCENT_TRIAGED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<DashboardDataFindingsPercentTriagedInner> getFindingsPercentTriaged() {
    return findingsPercentTriaged;
  }


  @JsonProperty(value = JSON_PROPERTY_FINDINGS_PERCENT_TRIAGED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFindingsPercentTriaged(@jakarta.annotation.Nullable List<DashboardDataFindingsPercentTriagedInner> findingsPercentTriaged) {
    this.findingsPercentTriaged = findingsPercentTriaged;
  }


  public DashboardData openFindingTypes(@jakarta.annotation.Nullable List<DashboardDataOpenFindingTypesInner> openFindingTypes) {
    this.openFindingTypes = openFindingTypes;
    return this;
  }

  public DashboardData addOpenFindingTypesItem(DashboardDataOpenFindingTypesInner openFindingTypesItem) {
    if (this.openFindingTypes == null) {
      this.openFindingTypes = new ArrayList<>();
    }
    this.openFindingTypes.add(openFindingTypesItem);
    return this;
  }

  /**
   * Get openFindingTypes
   * @return openFindingTypes
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_OPEN_FINDING_TYPES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<DashboardDataOpenFindingTypesInner> getOpenFindingTypes() {
    return openFindingTypes;
  }


  @JsonProperty(value = JSON_PROPERTY_OPEN_FINDING_TYPES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOpenFindingTypes(@jakarta.annotation.Nullable List<DashboardDataOpenFindingTypesInner> openFindingTypes) {
    this.openFindingTypes = openFindingTypes;
  }


  public DashboardData recentAnalysisStats(@jakarta.annotation.Nullable List<DashboardDataRecentAnalysisStatsInner> recentAnalysisStats) {
    this.recentAnalysisStats = recentAnalysisStats;
    return this;
  }

  public DashboardData addRecentAnalysisStatsItem(DashboardDataRecentAnalysisStatsInner recentAnalysisStatsItem) {
    if (this.recentAnalysisStats == null) {
      this.recentAnalysisStats = new ArrayList<>();
    }
    this.recentAnalysisStats.add(recentAnalysisStatsItem);
    return this;
  }

  /**
   * Get recentAnalysisStats
   * @return recentAnalysisStats
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_RECENT_ANALYSIS_STATS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<DashboardDataRecentAnalysisStatsInner> getRecentAnalysisStats() {
    return recentAnalysisStats;
  }


  @JsonProperty(value = JSON_PROPERTY_RECENT_ANALYSIS_STATS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRecentAnalysisStats(@jakarta.annotation.Nullable List<DashboardDataRecentAnalysisStatsInner> recentAnalysisStats) {
    this.recentAnalysisStats = recentAnalysisStats;
  }


  public DashboardData recentToolStats(@jakarta.annotation.Nullable List<DashboardDataRecentToolStatsInner> recentToolStats) {
    this.recentToolStats = recentToolStats;
    return this;
  }

  public DashboardData addRecentToolStatsItem(DashboardDataRecentToolStatsInner recentToolStatsItem) {
    if (this.recentToolStats == null) {
      this.recentToolStats = new ArrayList<>();
    }
    this.recentToolStats.add(recentToolStatsItem);
    return this;
  }

  /**
   * Get recentToolStats
   * @return recentToolStats
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_RECENT_TOOL_STATS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<DashboardDataRecentToolStatsInner> getRecentToolStats() {
    return recentToolStats;
  }


  @JsonProperty(value = JSON_PROPERTY_RECENT_TOOL_STATS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRecentToolStats(@jakarta.annotation.Nullable List<DashboardDataRecentToolStatsInner> recentToolStats) {
    this.recentToolStats = recentToolStats;
  }


  public DashboardData severityAgeBreakdown(@jakarta.annotation.Nullable List<DashboardDataSeverityAgeBreakdownInner> severityAgeBreakdown) {
    this.severityAgeBreakdown = severityAgeBreakdown;
    return this;
  }

  public DashboardData addSeverityAgeBreakdownItem(DashboardDataSeverityAgeBreakdownInner severityAgeBreakdownItem) {
    if (this.severityAgeBreakdown == null) {
      this.severityAgeBreakdown = new ArrayList<>();
    }
    this.severityAgeBreakdown.add(severityAgeBreakdownItem);
    return this;
  }

  /**
   * Get severityAgeBreakdown
   * @return severityAgeBreakdown
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SEVERITY_AGE_BREAKDOWN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<DashboardDataSeverityAgeBreakdownInner> getSeverityAgeBreakdown() {
    return severityAgeBreakdown;
  }


  @JsonProperty(value = JSON_PROPERTY_SEVERITY_AGE_BREAKDOWN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSeverityAgeBreakdown(@jakarta.annotation.Nullable List<DashboardDataSeverityAgeBreakdownInner> severityAgeBreakdown) {
    this.severityAgeBreakdown = severityAgeBreakdown;
  }


  /**
   * Return true if this DashboardData object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DashboardData dashboardData = (DashboardData) o;
    return Objects.equals(this.analysisCountsByMethod, dashboardData.analysisCountsByMethod) &&
        Objects.equals(this.averageResolutionTime, dashboardData.averageResolutionTime) &&
        Objects.equals(this.codeMetrics, dashboardData.codeMetrics) &&
        Objects.equals(this.createdVsResolved, dashboardData.createdVsResolved) &&
        Objects.equals(this.dxScore, dashboardData.dxScore) &&
        Objects.equals(this.findingCountsByDescriptor, dashboardData.findingCountsByDescriptor) &&
        Objects.equals(this.findingCountsByDetection, dashboardData.findingCountsByDetection) &&
        Objects.equals(this.findingsPercentTriaged, dashboardData.findingsPercentTriaged) &&
        Objects.equals(this.openFindingTypes, dashboardData.openFindingTypes) &&
        Objects.equals(this.recentAnalysisStats, dashboardData.recentAnalysisStats) &&
        Objects.equals(this.recentToolStats, dashboardData.recentToolStats) &&
        Objects.equals(this.severityAgeBreakdown, dashboardData.severityAgeBreakdown);
  }

  @Override
  public int hashCode() {
    return Objects.hash(analysisCountsByMethod, averageResolutionTime, codeMetrics, createdVsResolved, dxScore, findingCountsByDescriptor, findingCountsByDetection, findingsPercentTriaged, openFindingTypes, recentAnalysisStats, recentToolStats, severityAgeBreakdown);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DashboardData {\n");
    sb.append("    analysisCountsByMethod: ").append(toIndentedString(analysisCountsByMethod)).append("\n");
    sb.append("    averageResolutionTime: ").append(toIndentedString(averageResolutionTime)).append("\n");
    sb.append("    codeMetrics: ").append(toIndentedString(codeMetrics)).append("\n");
    sb.append("    createdVsResolved: ").append(toIndentedString(createdVsResolved)).append("\n");
    sb.append("    dxScore: ").append(toIndentedString(dxScore)).append("\n");
    sb.append("    findingCountsByDescriptor: ").append(toIndentedString(findingCountsByDescriptor)).append("\n");
    sb.append("    findingCountsByDetection: ").append(toIndentedString(findingCountsByDetection)).append("\n");
    sb.append("    findingsPercentTriaged: ").append(toIndentedString(findingsPercentTriaged)).append("\n");
    sb.append("    openFindingTypes: ").append(toIndentedString(openFindingTypes)).append("\n");
    sb.append("    recentAnalysisStats: ").append(toIndentedString(recentAnalysisStats)).append("\n");
    sb.append("    recentToolStats: ").append(toIndentedString(recentToolStats)).append("\n");
    sb.append("    severityAgeBreakdown: ").append(toIndentedString(severityAgeBreakdown)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

