/*
 * Software Risk Manager API Guide
 * Software Risk Manager provides a variety of REST APIs, allowing external applications and scripts to interface with core functionality. This guide documents the various REST resources provided by Software Risk Manager.  ## Authentication  Authentication is a requirement when accessing API endpoints. There are two methods by which authentication may be performed.  ### API Keys  The primary method for authentication is passing an `API-Key` header containing a valid API key with all requests, i.e.  `API-Key: <key goes here>`  API Keys come in two possible forms:   - `api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24` - latest format  - `550e8400-e29b-41d4-a716-44665544000` - legacy format  For example:  `API-Key: api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24`  `API-Key: 550e8400-e29b-41d4-a716-44665544000`  API keys may be generated by Software Risk Manager admins. Once they are generated, in most cases, they behave like regular users. They will need to be assigned user roles for any projects they will be used with. Although it is possible to assign the *admin* [role](../user_guide/Project-Management/user_role_configuration.html) to an API key, the recommendation is to avoid doing so unless absolutely necessary.  See the user guide for an overview about how to create and manage [API keys](../user_guide/Settings/api_keys_administration.html).  ### Personal Access Tokens  Personal Access Tokens can be used as [bearer tokens](https://swagger.io/docs/specification/authentication/bearer-authentication/), e.g.  `Authorization: Bearer secret-token:qRuXr1BqgoTWXNxUhYQ8H_Yl2zfy6vxuqMIRnkGO`  Personal Access Tokens can be created by any user, and represent a subset of that user's permissions.   ### HTTP Basic Authentication  HTTP Basic authentication may be used to authenticate with the API as a regular user. This is accomplished by including an `Authorization` header containing a typical authorization credential.  ## Error Handling  ### Bad Requests  For API calls that accept input, invalid values will trigger an HTTP 400 Bad Request status code.  ### Server Errors  For any API call, if an unexpected error occurs, an HTTP 500 Internal Server Error status code will be returned. If an error message is available, the response will include a basic message body describing the error:  ` {   \"error\": \"error message\" } `  The error property will contain a string message indicating the nature of the error.  ### Errors with Third-Party Applications  Sometimes Software Risk Manager must communicate with third-party applications like JIRA, Git, and certain enterprise tools. Some users may have in-house versions of these with self-signed certificates which may not be \"trusted\". In these cases, the API will respond with an HTTP 502 BAD GATEWAY status. If this happens, refer to [Trusting Certificates](../install_guide/Installation/trusting-certs.html) in the install guide.  ### API Unavailable  In special circumstances, particularly during the installation and update phases, the API will be unavailable. When the API is unavailable, all calls will return an HTTP 503 Service Unavailable status, and no actions or side effects will occur as a result of the calls.  ## Examples  Software Risk Manager's API uses REST over HTTP. As such, you can use any language/utility that supports making HTTP requests to interact with the API. The examples below use <a href=\"https://curl.haxx.se/\" target=\"_blank\">curl</a>, a popular command-line utility, to do so.  First, you'll need to [generate an API Key](../user_guide/Settings/api_keys_administration.html). Second, while you can create projects through the API, these examples will assume that you've already created one. You'll need to know its project id number, which you can find by looking at the URL for the [Findings Page](../user_guide/Findings/findings_overview.html), which will end in a number.  **Note:** Many API endpoints require a JSON body in the request. Most JSON will contain double-quotes (`\"`) and spaces, which have special meaning when used on the command line. In order to ensure your JSON body is interpreted as a single argument, you must <a href=\"https://en.wikipedia.org/wiki/Escape_character\" target=\"_blank\">escape</a> it properly. For example, if you wanted to `POST` the following JSON body:  ```{ \"name\": \"John Doe\" }```  You would put a backslash (`\\`) before each double-quote (`\"`), and surround the whole thing with double-quotes:  ```\"{ \\\"name\\\": \\\"John Doe\\\" }\"```  The outermost double-quotes tell the command-line interpreter that everything within them is to be treated as a single argument (as opposed to the usual space-separated behavior). The backslash before each inner double-quote tells the command-line interpreter that you mean the literal double-quote character, and not the end of the quoted argument.  In many *non-Windows* operating systems, you can also use a single-quote (`'`) to surround the argument, and skip the backslashes:  ```'{ \"name\": \"John Doe\" }'```  The examples below will use the double-quotes and backslashes style, as it works on most (if not all) operating systems.  ### Running an Analysis  To start an analysis, you can run  ```curl -F file1=@src.zip -H \"API-Key: api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24\" https://<yoursrmserver>/srm/api/projects/<project id>/analysis```  Make sure you use your own values for the `src.zip` file, the API Key, the hostname for your Software Risk Manager server, and the project id.  ### Retrieving Finding Data  There is a wide variety of data available for the findings of a project after running an analysis. Two examples are provided here.  ### Findings Table Data  You can retrieve the data that's used to populate the [findings table](../user_guide/Findings/findings_table.html):  ```curl -H \"Content-Type: application/json\" -X POST -d \"{\\\"filter\\\":{},\\\"sort\\\":{\\\"by\\\":\\\"id\\\",\\\"direction\\\":\\\"ascending\\\"},\\\"pagination\\\":{\\\"page\\\":1,\\\"perPage\\\":10}}\" -H \"API-Key: api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24\" https://<yoursrmserver>/srm/api/projects/<project id>/findings/table```  Additional information about how to construct more useful filter and sort requests can be found in the documentation.  ### Finding Metadata  You can retrieve metadata for a finding, if you know the finding ID. You can take the ID for a finding from the Findings Table:  ```curl -H \"API-Key: api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24\" https://<yoursrmserver>/srm/api/findings/<finding id>```  ### Generating a Report  You can use the API to generate a PDF [report](../user_guide/Findings/generate_report.html).  ```curl -H \"Content-Type: application/json\" -X POST -d \"{\\\"filter\\\":{},\\\"config\\\":{\\\"summaryMode\\\":\\\"simple\\\",\\\"detailsMode\\\":\\\"simple\\\",\\\"includeResultDetails\\\":true,\\\"includeComments\\\":false}}\" -H \"API-Key: api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24\" https://<yoursrmserver>/srm/api/projects/<project id>/report/pdf```  ## Generating a Client SDK  If you require a client SDK for Software Risk Manager, you can generate one using [OpenAPI Generator](https://openapi-generator.tech/). Detailed instructions are available on the [GitHub page](https://github.com/OpenAPITools/openapi-generator) and our OpenAPI spec can be found [here](swagger/swagger.json). 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.codedx.client.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.codedx.client.JSON;


/**
 * DisplayTagState
 */
@JsonPropertyOrder({
  DisplayTagState.JSON_PROPERTY_SOURCE,
  DisplayTagState.JSON_PROPERTY_BINARY,
  DisplayTagState.JSON_PROPERTY_BUILD_META,
  DisplayTagState.JSON_PROPERTY_TOOL_OUTPUT,
  DisplayTagState.JSON_PROPERTY_TOOL_INPUT,
  DisplayTagState.JSON_PROPERTY_IS_NESTED,
  DisplayTagState.JSON_PROPERTY_ID,
  DisplayTagState.JSON_PROPERTY_ENABLED,
  DisplayTagState.JSON_PROPERTY_ENABLED_REASON
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-02T11:55:06.722228-04:00[America/New_York]", comments = "Generator version: 7.21.0")
public class DisplayTagState {
  public static final String JSON_PROPERTY_SOURCE = "source";
  @jakarta.annotation.Nullable
  private String source;

  public static final String JSON_PROPERTY_BINARY = "binary";
  @jakarta.annotation.Nullable
  private String binary;

  public static final String JSON_PROPERTY_BUILD_META = "buildMeta";
  @jakarta.annotation.Nullable
  private String buildMeta;

  public static final String JSON_PROPERTY_TOOL_OUTPUT = "toolOutput";
  @jakarta.annotation.Nullable
  private String toolOutput;

  public static final String JSON_PROPERTY_TOOL_INPUT = "toolInput";
  @jakarta.annotation.Nullable
  private String toolInput;

  public static final String JSON_PROPERTY_IS_NESTED = "isNested";
  @jakarta.annotation.Nullable
  private Boolean isNested;

  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nullable
  private String id;

  public static final String JSON_PROPERTY_ENABLED = "enabled";
  @jakarta.annotation.Nullable
  private Boolean enabled;

  public static final String JSON_PROPERTY_ENABLED_REASON = "enabledReason";
  @jakarta.annotation.Nullable
  private String enabledReason;

  public DisplayTagState() { 
  }

  public DisplayTagState source(@jakarta.annotation.Nullable String source) {
    this.source = source;
    return this;
  }

  /**
   * if the file appears to be a zip file that includes source files, the value of this field will be the name of the language of that source (e.g. \&quot;C#\&quot;)
   * @return source
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SOURCE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSource() {
    return source;
  }


  @JsonProperty(value = JSON_PROPERTY_SOURCE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSource(@jakarta.annotation.Nullable String source) {
    this.source = source;
  }


  public DisplayTagState binary(@jakarta.annotation.Nullable String binary) {
    this.binary = binary;
    return this;
  }

  /**
   * if the file appears to be a zip file that includes compiled \&quot;binary\&quot; files, the value of this field will be the name of the platform on which they run (e.g. \&quot;CLR\&quot;)
   * @return binary
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BINARY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getBinary() {
    return binary;
  }


  @JsonProperty(value = JSON_PROPERTY_BINARY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBinary(@jakarta.annotation.Nullable String binary) {
    this.binary = binary;
  }


  public DisplayTagState buildMeta(@jakarta.annotation.Nullable String buildMeta) {
    this.buildMeta = buildMeta;
    return this;
  }

  /**
   * if the file appears to be a zip file that includes some kind of build metadata (e.g. an npm package.json file), the value of this field will be a string describing what type of file was found
   * @return buildMeta
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BUILD_META, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getBuildMeta() {
    return buildMeta;
  }


  @JsonProperty(value = JSON_PROPERTY_BUILD_META, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBuildMeta(@jakarta.annotation.Nullable String buildMeta) {
    this.buildMeta = buildMeta;
  }


  public DisplayTagState toolOutput(@jakarta.annotation.Nullable String toolOutput) {
    this.toolOutput = toolOutput;
    return this;
  }

  /**
   * if the file appears to be an output of a tool (i.e. a file containing Findings), the value of this field will be the name of that tool.
   * @return toolOutput
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TOOL_OUTPUT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getToolOutput() {
    return toolOutput;
  }


  @JsonProperty(value = JSON_PROPERTY_TOOL_OUTPUT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setToolOutput(@jakarta.annotation.Nullable String toolOutput) {
    this.toolOutput = toolOutput;
  }


  public DisplayTagState toolInput(@jakarta.annotation.Nullable String toolInput) {
    this.toolInput = toolInput;
    return this;
  }

  /**
   * if the file appears to be usable as an input to a tool that Software Risk Manager can automatically run, the value of this field will be that tool.
   * @return toolInput
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TOOL_INPUT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getToolInput() {
    return toolInput;
  }


  @JsonProperty(value = JSON_PROPERTY_TOOL_INPUT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setToolInput(@jakarta.annotation.Nullable String toolInput) {
    this.toolInput = toolInput;
  }


  public DisplayTagState isNested(@jakarta.annotation.Nullable Boolean isNested) {
    this.isNested = isNested;
    return this;
  }

  /**
   * indicates whether or not the tagged content is nested in multiple layers of ZIP files, eg Javascript within a JAR within a WAR.
   * @return isNested
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_IS_NESTED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getIsNested() {
    return isNested;
  }


  @JsonProperty(value = JSON_PROPERTY_IS_NESTED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsNested(@jakarta.annotation.Nullable Boolean isNested) {
    this.isNested = isNested;
  }


  public DisplayTagState id(@jakarta.annotation.Nullable String id) {
    this.id = id;
    return this;
  }

  /**
   * a semi-random identifier which can be assumed to be unique within the context of an Analysis Prep. This identifier can be used when constructing URLs to interact with a specific Display Tag State.
   * @return id
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@jakarta.annotation.Nullable String id) {
    this.id = id;
  }


  public DisplayTagState enabled(@jakarta.annotation.Nullable Boolean enabled) {
    this.enabled = enabled;
    return this;
  }

  /**
   * a boolean, indicating whether the tag is enabled. If not enabled, the content described by the tag will be treated as if it wasn&#39;t there. In the case of toolInput, that could mean that the particular tool would not be run.
   * @return enabled
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ENABLED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getEnabled() {
    return enabled;
  }


  @JsonProperty(value = JSON_PROPERTY_ENABLED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEnabled(@jakarta.annotation.Nullable Boolean enabled) {
    this.enabled = enabled;
  }


  public DisplayTagState enabledReason(@jakarta.annotation.Nullable String enabledReason) {
    this.enabledReason = enabledReason;
    return this;
  }

  /**
   * a string, either \&quot;user\&quot;, \&quot;orchestration-config\&quot;, or \&quot;rule-config\&quot;. If the associated project has disabled a particular tool by configuration, toolInput tags for that tool will be disabled by \&quot;rule-config\&quot;. If the tool in question is an add-in tool that is disabled in the project&#39;s orchestration config, it will be disabled by \&quot;orchestration-config\&quot;. If the API is used to enable or disable a tag, it will be disabled by \&quot;user\&quot;.
   * @return enabledReason
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ENABLED_REASON, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEnabledReason() {
    return enabledReason;
  }


  @JsonProperty(value = JSON_PROPERTY_ENABLED_REASON, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEnabledReason(@jakarta.annotation.Nullable String enabledReason) {
    this.enabledReason = enabledReason;
  }


  /**
   * Return true if this DisplayTagState object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DisplayTagState displayTagState = (DisplayTagState) o;
    return Objects.equals(this.source, displayTagState.source) &&
        Objects.equals(this.binary, displayTagState.binary) &&
        Objects.equals(this.buildMeta, displayTagState.buildMeta) &&
        Objects.equals(this.toolOutput, displayTagState.toolOutput) &&
        Objects.equals(this.toolInput, displayTagState.toolInput) &&
        Objects.equals(this.isNested, displayTagState.isNested) &&
        Objects.equals(this.id, displayTagState.id) &&
        Objects.equals(this.enabled, displayTagState.enabled) &&
        Objects.equals(this.enabledReason, displayTagState.enabledReason);
  }

  @Override
  public int hashCode() {
    return Objects.hash(source, binary, buildMeta, toolOutput, toolInput, isNested, id, enabled, enabledReason);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DisplayTagState {\n");
    sb.append("    source: ").append(toIndentedString(source)).append("\n");
    sb.append("    binary: ").append(toIndentedString(binary)).append("\n");
    sb.append("    buildMeta: ").append(toIndentedString(buildMeta)).append("\n");
    sb.append("    toolOutput: ").append(toIndentedString(toolOutput)).append("\n");
    sb.append("    toolInput: ").append(toIndentedString(toolInput)).append("\n");
    sb.append("    isNested: ").append(toIndentedString(isNested)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    enabled: ").append(toIndentedString(enabled)).append("\n");
    sb.append("    enabledReason: ").append(toIndentedString(enabledReason)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

