/*
 * Software Risk Manager API Guide
 * Software Risk Manager provides a variety of REST APIs, allowing external applications and scripts to interface with core functionality. This guide documents the various REST resources provided by Software Risk Manager.  ## Authentication  Authentication is a requirement when accessing API endpoints. There are two methods by which authentication may be performed.  ### API Keys  The primary method for authentication is passing an `API-Key` header containing a valid API key with all requests, i.e.  `API-Key: <key goes here>`  API Keys come in two possible forms:   - `api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24` - latest format  - `550e8400-e29b-41d4-a716-44665544000` - legacy format  For example:  `API-Key: api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24`  `API-Key: 550e8400-e29b-41d4-a716-44665544000`  API keys may be generated by Software Risk Manager admins. Once they are generated, in most cases, they behave like regular users. They will need to be assigned user roles for any projects they will be used with. Although it is possible to assign the *admin* [role](../user_guide/Project-Management/user_role_configuration.html) to an API key, the recommendation is to avoid doing so unless absolutely necessary.  See the user guide for an overview about how to create and manage [API keys](../user_guide/Settings/api_keys_administration.html).  ### Personal Access Tokens  Personal Access Tokens can be used as [bearer tokens](https://swagger.io/docs/specification/authentication/bearer-authentication/), e.g.  `Authorization: Bearer secret-token:qRuXr1BqgoTWXNxUhYQ8H_Yl2zfy6vxuqMIRnkGO`  Personal Access Tokens can be created by any user, and represent a subset of that user's permissions.   ### HTTP Basic Authentication  HTTP Basic authentication may be used to authenticate with the API as a regular user. This is accomplished by including an `Authorization` header containing a typical authorization credential.  ## Error Handling  ### Bad Requests  For API calls that accept input, invalid values will trigger an HTTP 400 Bad Request status code.  ### Server Errors  For any API call, if an unexpected error occurs, an HTTP 500 Internal Server Error status code will be returned. If an error message is available, the response will include a basic message body describing the error:  ` {   \"error\": \"error message\" } `  The error property will contain a string message indicating the nature of the error.  ### Errors with Third-Party Applications  Sometimes Software Risk Manager must communicate with third-party applications like JIRA, Git, and certain enterprise tools. Some users may have in-house versions of these with self-signed certificates which may not be \"trusted\". In these cases, the API will respond with an HTTP 502 BAD GATEWAY status. If this happens, refer to [Trusting Certificates](../install_guide/Installation/trusting-certs.html) in the install guide.  ### API Unavailable  In special circumstances, particularly during the installation and update phases, the API will be unavailable. When the API is unavailable, all calls will return an HTTP 503 Service Unavailable status, and no actions or side effects will occur as a result of the calls.  ## Examples  Software Risk Manager's API uses REST over HTTP. As such, you can use any language/utility that supports making HTTP requests to interact with the API. The examples below use <a href=\"https://curl.haxx.se/\" target=\"_blank\">curl</a>, a popular command-line utility, to do so.  First, you'll need to [generate an API Key](../user_guide/Settings/api_keys_administration.html). Second, while you can create projects through the API, these examples will assume that you've already created one. You'll need to know its project id number, which you can find by looking at the URL for the [Findings Page](../user_guide/Findings/findings_overview.html), which will end in a number.  **Note:** Many API endpoints require a JSON body in the request. Most JSON will contain double-quotes (`\"`) and spaces, which have special meaning when used on the command line. In order to ensure your JSON body is interpreted as a single argument, you must <a href=\"https://en.wikipedia.org/wiki/Escape_character\" target=\"_blank\">escape</a> it properly. For example, if you wanted to `POST` the following JSON body:  ```{ \"name\": \"John Doe\" }```  You would put a backslash (`\\`) before each double-quote (`\"`), and surround the whole thing with double-quotes:  ```\"{ \\\"name\\\": \\\"John Doe\\\" }\"```  The outermost double-quotes tell the command-line interpreter that everything within them is to be treated as a single argument (as opposed to the usual space-separated behavior). The backslash before each inner double-quote tells the command-line interpreter that you mean the literal double-quote character, and not the end of the quoted argument.  In many *non-Windows* operating systems, you can also use a single-quote (`'`) to surround the argument, and skip the backslashes:  ```'{ \"name\": \"John Doe\" }'```  The examples below will use the double-quotes and backslashes style, as it works on most (if not all) operating systems.  ### Running an Analysis  To start an analysis, you can run  ```curl -F file1=@src.zip -H \"API-Key: api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24\" https://<yoursrmserver>/srm/api/projects/<project id>/analysis```  Make sure you use your own values for the `src.zip` file, the API Key, the hostname for your Software Risk Manager server, and the project id.  ### Retrieving Finding Data  There is a wide variety of data available for the findings of a project after running an analysis. Two examples are provided here.  ### Findings Table Data  You can retrieve the data that's used to populate the [findings table](../user_guide/Findings/findings_table.html):  ```curl -H \"Content-Type: application/json\" -X POST -d \"{\\\"filter\\\":{},\\\"sort\\\":{\\\"by\\\":\\\"id\\\",\\\"direction\\\":\\\"ascending\\\"},\\\"pagination\\\":{\\\"page\\\":1,\\\"perPage\\\":10}}\" -H \"API-Key: api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24\" https://<yoursrmserver>/srm/api/projects/<project id>/findings/table```  Additional information about how to construct more useful filter and sort requests can be found in the documentation.  ### Finding Metadata  You can retrieve metadata for a finding, if you know the finding ID. You can take the ID for a finding from the Findings Table:  ```curl -H \"API-Key: api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24\" https://<yoursrmserver>/srm/api/findings/<finding id>```  ### Generating a Report  You can use the API to generate a PDF [report](../user_guide/Findings/generate_report.html).  ```curl -H \"Content-Type: application/json\" -X POST -d \"{\\\"filter\\\":{},\\\"config\\\":{\\\"summaryMode\\\":\\\"simple\\\",\\\"detailsMode\\\":\\\"simple\\\",\\\"includeResultDetails\\\":true,\\\"includeComments\\\":false}}\" -H \"API-Key: api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24\" https://<yoursrmserver>/srm/api/projects/<project id>/report/pdf```  ## Generating a Client SDK  If you require a client SDK for Software Risk Manager, you can generate one using [OpenAPI Generator](https://openapi-generator.tech/). Detailed instructions are available on the [GitHub page](https://github.com/OpenAPITools/openapi-generator) and our OpenAPI spec can be found [here](swagger/swagger.json). 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.codedx.client.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.codedx.client.model.LocationFilterSelections;
import com.codedx.client.model.NamePath;
import com.codedx.client.model.PredictedStatusSelection;
import com.codedx.client.model.ProjectFilterSelections;
import com.codedx.client.model.TimeFilterSelection;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.codedx.client.JSON;


/**
 * Represents the state of filter selections on the findings page UI, for use with Saved Filters. Each field on the object is optional and may be omitted to represent &#39;no selection&#39; in that field. When sending a &#x60;FilterSelections&#x60; as part of an HTTP request, you can omit any field whose value would otherwise be &#x60;null&#x60; or &#x60;[]&#x60;; however when receiving a &#x60;FilterSelections&#x60; as part of an HTTP response, each field will be provided, with &#39;empty&#39; fields represented as either &#x60;[]&#x60; (for arrays) or &#x60;null&#x60; (for objects). Most fields (e.g. \&quot;type\&quot;, \&quot;severity\&quot;, and \&quot;triageStatus\&quot;) expect an array of &#x60;NamePath&#x60;s, representing selections in a normal filter. Several fields expect special objects which are tailored to the individual aspects of those filters; e.g. \&quot;standard\&quot; and \&quot;project\&quot; nest the &#x60;NamePath&#x60; array under an object field that represents their respective grouping menu selections.
 */
@JsonPropertyOrder({
  FilterSelections.JSON_PROPERTY_SEARCH,
  FilterSelections.JSON_PROPERTY_TYPE,
  FilterSelections.JSON_PROPERTY_PROJECT,
  FilterSelections.JSON_PROPERTY_TOOL,
  FilterSelections.JSON_PROPERTY_DETECTION_METHOD,
  FilterSelections.JSON_PROPERTY_SEVERITY,
  FilterSelections.JSON_PROPERTY_LOCATION,
  FilterSelections.JSON_PROPERTY_CONTAINER_IMAGE,
  FilterSelections.JSON_PROPERTY_AGE,
  FilterSelections.JSON_PROPERTY_FIRST_SEEN,
  FilterSelections.JSON_PROPERTY_LAST_MODIFIED,
  FilterSelections.JSON_PROPERTY_TOOL_OVERLAP,
  FilterSelections.JSON_PROPERTY_STANDARD,
  FilterSelections.JSON_PROPERTY_TAGS,
  FilterSelections.JSON_PROPERTY_PREDICTED_STATUS,
  FilterSelections.JSON_PROPERTY_STATUS,
  FilterSelections.JSON_PROPERTY_FINDING_STATUS,
  FilterSelections.JSON_PROPERTY_ISSUE_TRACKER_ASSOCIATION,
  FilterSelections.JSON_PROPERTY_ISSUE_TRACKER_RESOLUTION
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-02T11:55:06.722228-04:00[America/New_York]", comments = "Generator version: 7.21.0")
public class FilterSelections {
  public static final String JSON_PROPERTY_SEARCH = "search";
  private JsonNullable<Map<String, String>> search = JsonNullable.<Map<String, String>>undefined();

  public static final String JSON_PROPERTY_TYPE = "type";
  private JsonNullable<List<NamePath>> type = JsonNullable.<List<NamePath>>undefined();

  public static final String JSON_PROPERTY_PROJECT = "project";
  private JsonNullable<ProjectFilterSelections> project = JsonNullable.<ProjectFilterSelections>undefined();

  public static final String JSON_PROPERTY_TOOL = "tool";
  private JsonNullable<List<NamePath>> tool = JsonNullable.<List<NamePath>>undefined();

  public static final String JSON_PROPERTY_DETECTION_METHOD = "detectionMethod";
  private JsonNullable<List<NamePath>> detectionMethod = JsonNullable.<List<NamePath>>undefined();

  public static final String JSON_PROPERTY_SEVERITY = "severity";
  private JsonNullable<List<NamePath>> severity = JsonNullable.<List<NamePath>>undefined();

  public static final String JSON_PROPERTY_LOCATION = "location";
  private JsonNullable<LocationFilterSelections> location = JsonNullable.<LocationFilterSelections>undefined();

  public static final String JSON_PROPERTY_CONTAINER_IMAGE = "containerImage";
  private JsonNullable<List<NamePath>> containerImage = JsonNullable.<List<NamePath>>undefined();

  public static final String JSON_PROPERTY_AGE = "age";
  private JsonNullable<List<NamePath>> age = JsonNullable.<List<NamePath>>undefined();

  public static final String JSON_PROPERTY_FIRST_SEEN = "firstSeen";
  private JsonNullable<TimeFilterSelection> firstSeen = JsonNullable.<TimeFilterSelection>undefined();

  public static final String JSON_PROPERTY_LAST_MODIFIED = "lastModified";
  private JsonNullable<TimeFilterSelection> lastModified = JsonNullable.<TimeFilterSelection>undefined();

  public static final String JSON_PROPERTY_TOOL_OVERLAP = "toolOverlap";
  private JsonNullable<List<NamePath>> toolOverlap = JsonNullable.<List<NamePath>>undefined();

  public static final String JSON_PROPERTY_STANDARD = "standard";
  private JsonNullable<Map<String, List<NamePath>>> standard = JsonNullable.<Map<String, List<NamePath>>>undefined();

  public static final String JSON_PROPERTY_TAGS = "tags";
  private JsonNullable<List<NamePath>> tags = JsonNullable.<List<NamePath>>undefined();

  public static final String JSON_PROPERTY_PREDICTED_STATUS = "predictedStatus";
  private JsonNullable<PredictedStatusSelection> predictedStatus = JsonNullable.<PredictedStatusSelection>undefined();

  public static final String JSON_PROPERTY_STATUS = "status";
  private JsonNullable<List<NamePath>> status = JsonNullable.<List<NamePath>>undefined();

  public static final String JSON_PROPERTY_FINDING_STATUS = "findingStatus";
  private JsonNullable<List<NamePath>> findingStatus = JsonNullable.<List<NamePath>>undefined();

  public static final String JSON_PROPERTY_ISSUE_TRACKER_ASSOCIATION = "issueTrackerAssociation";
  private JsonNullable<List<NamePath>> issueTrackerAssociation = JsonNullable.<List<NamePath>>undefined();

  public static final String JSON_PROPERTY_ISSUE_TRACKER_RESOLUTION = "issueTrackerResolution";
  private JsonNullable<List<NamePath>> issueTrackerResolution = JsonNullable.<List<NamePath>>undefined();

  public FilterSelections() { 
  }

  public FilterSelections search(@jakarta.annotation.Nullable Map<String, String> search) {
    this.search = JsonNullable.<Map<String, String>>of(search);
    return this;
  }

  public FilterSelections putSearchItem(String key, String searchItem) {
    if (this.search == null || !this.search.isPresent()) {
      this.search = JsonNullable.<Map<String, String>>of(new HashMap<>());
    }
    try {
      this.search.get().put(key, searchItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * An object representing the state of the &#39;Search&#39; form on the findings page. Should contain exactly one key, representing the &#39;search by&#39; dropdown menu selection. The value of that field should be the text input for the search.
   * @return search
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Map<String, String> getSearch() {
        return search.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_SEARCH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Map<String, String>> getSearch_JsonNullable() {
    return search;
  }
  
  @JsonProperty(JSON_PROPERTY_SEARCH)
  public void setSearch_JsonNullable(JsonNullable<Map<String, String>> search) {
    this.search = search;
  }

  public void setSearch(@jakarta.annotation.Nullable Map<String, String> search) {
    this.search = JsonNullable.<Map<String, String>>of(search);
  }


  public FilterSelections type(@jakarta.annotation.Nullable List<NamePath> type) {
    this.type = JsonNullable.<List<NamePath>>of(type);
    return this;
  }

  public FilterSelections addTypeItem(NamePath typeItem) {
    if (this.type == null || !this.type.isPresent()) {
      this.type = JsonNullable.<List<NamePath>>of(new ArrayList<>());
    }
    try {
      this.type.get().add(typeItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public List<NamePath> getType() {
        return type.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<List<NamePath>> getType_JsonNullable() {
    return type;
  }
  
  @JsonProperty(JSON_PROPERTY_TYPE)
  public void setType_JsonNullable(JsonNullable<List<NamePath>> type) {
    this.type = type;
  }

  public void setType(@jakarta.annotation.Nullable List<NamePath> type) {
    this.type = JsonNullable.<List<NamePath>>of(type);
  }


  public FilterSelections project(@jakarta.annotation.Nullable ProjectFilterSelections project) {
    this.project = JsonNullable.<ProjectFilterSelections>of(project);
    return this;
  }

  /**
   * Get project
   * @return project
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public ProjectFilterSelections getProject() {
        return project.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_PROJECT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<ProjectFilterSelections> getProject_JsonNullable() {
    return project;
  }
  
  @JsonProperty(JSON_PROPERTY_PROJECT)
  public void setProject_JsonNullable(JsonNullable<ProjectFilterSelections> project) {
    this.project = project;
  }

  public void setProject(@jakarta.annotation.Nullable ProjectFilterSelections project) {
    this.project = JsonNullable.<ProjectFilterSelections>of(project);
  }


  public FilterSelections tool(@jakarta.annotation.Nullable List<NamePath> tool) {
    this.tool = JsonNullable.<List<NamePath>>of(tool);
    return this;
  }

  public FilterSelections addToolItem(NamePath toolItem) {
    if (this.tool == null || !this.tool.isPresent()) {
      this.tool = JsonNullable.<List<NamePath>>of(new ArrayList<>());
    }
    try {
      this.tool.get().add(toolItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Get tool
   * @return tool
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public List<NamePath> getTool() {
        return tool.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_TOOL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<List<NamePath>> getTool_JsonNullable() {
    return tool;
  }
  
  @JsonProperty(JSON_PROPERTY_TOOL)
  public void setTool_JsonNullable(JsonNullable<List<NamePath>> tool) {
    this.tool = tool;
  }

  public void setTool(@jakarta.annotation.Nullable List<NamePath> tool) {
    this.tool = JsonNullable.<List<NamePath>>of(tool);
  }


  public FilterSelections detectionMethod(@jakarta.annotation.Nullable List<NamePath> detectionMethod) {
    this.detectionMethod = JsonNullable.<List<NamePath>>of(detectionMethod);
    return this;
  }

  public FilterSelections addDetectionMethodItem(NamePath detectionMethodItem) {
    if (this.detectionMethod == null || !this.detectionMethod.isPresent()) {
      this.detectionMethod = JsonNullable.<List<NamePath>>of(new ArrayList<>());
    }
    try {
      this.detectionMethod.get().add(detectionMethodItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Get detectionMethod
   * @return detectionMethod
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public List<NamePath> getDetectionMethod() {
        return detectionMethod.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_DETECTION_METHOD, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<List<NamePath>> getDetectionMethod_JsonNullable() {
    return detectionMethod;
  }
  
  @JsonProperty(JSON_PROPERTY_DETECTION_METHOD)
  public void setDetectionMethod_JsonNullable(JsonNullable<List<NamePath>> detectionMethod) {
    this.detectionMethod = detectionMethod;
  }

  public void setDetectionMethod(@jakarta.annotation.Nullable List<NamePath> detectionMethod) {
    this.detectionMethod = JsonNullable.<List<NamePath>>of(detectionMethod);
  }


  public FilterSelections severity(@jakarta.annotation.Nullable List<NamePath> severity) {
    this.severity = JsonNullable.<List<NamePath>>of(severity);
    return this;
  }

  public FilterSelections addSeverityItem(NamePath severityItem) {
    if (this.severity == null || !this.severity.isPresent()) {
      this.severity = JsonNullable.<List<NamePath>>of(new ArrayList<>());
    }
    try {
      this.severity.get().add(severityItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Get severity
   * @return severity
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public List<NamePath> getSeverity() {
        return severity.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_SEVERITY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<List<NamePath>> getSeverity_JsonNullable() {
    return severity;
  }
  
  @JsonProperty(JSON_PROPERTY_SEVERITY)
  public void setSeverity_JsonNullable(JsonNullable<List<NamePath>> severity) {
    this.severity = severity;
  }

  public void setSeverity(@jakarta.annotation.Nullable List<NamePath> severity) {
    this.severity = JsonNullable.<List<NamePath>>of(severity);
  }


  public FilterSelections location(@jakarta.annotation.Nullable LocationFilterSelections location) {
    this.location = JsonNullable.<LocationFilterSelections>of(location);
    return this;
  }

  /**
   * Get location
   * @return location
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public LocationFilterSelections getLocation() {
        return location.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_LOCATION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<LocationFilterSelections> getLocation_JsonNullable() {
    return location;
  }
  
  @JsonProperty(JSON_PROPERTY_LOCATION)
  public void setLocation_JsonNullable(JsonNullable<LocationFilterSelections> location) {
    this.location = location;
  }

  public void setLocation(@jakarta.annotation.Nullable LocationFilterSelections location) {
    this.location = JsonNullable.<LocationFilterSelections>of(location);
  }


  public FilterSelections containerImage(@jakarta.annotation.Nullable List<NamePath> containerImage) {
    this.containerImage = JsonNullable.<List<NamePath>>of(containerImage);
    return this;
  }

  public FilterSelections addContainerImageItem(NamePath containerImageItem) {
    if (this.containerImage == null || !this.containerImage.isPresent()) {
      this.containerImage = JsonNullable.<List<NamePath>>of(new ArrayList<>());
    }
    try {
      this.containerImage.get().add(containerImageItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Get containerImage
   * @return containerImage
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public List<NamePath> getContainerImage() {
        return containerImage.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_CONTAINER_IMAGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<List<NamePath>> getContainerImage_JsonNullable() {
    return containerImage;
  }
  
  @JsonProperty(JSON_PROPERTY_CONTAINER_IMAGE)
  public void setContainerImage_JsonNullable(JsonNullable<List<NamePath>> containerImage) {
    this.containerImage = containerImage;
  }

  public void setContainerImage(@jakarta.annotation.Nullable List<NamePath> containerImage) {
    this.containerImage = JsonNullable.<List<NamePath>>of(containerImage);
  }


  public FilterSelections age(@jakarta.annotation.Nullable List<NamePath> age) {
    this.age = JsonNullable.<List<NamePath>>of(age);
    return this;
  }

  public FilterSelections addAgeItem(NamePath ageItem) {
    if (this.age == null || !this.age.isPresent()) {
      this.age = JsonNullable.<List<NamePath>>of(new ArrayList<>());
    }
    try {
      this.age.get().add(ageItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Get age
   * @return age
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public List<NamePath> getAge() {
        return age.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_AGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<List<NamePath>> getAge_JsonNullable() {
    return age;
  }
  
  @JsonProperty(JSON_PROPERTY_AGE)
  public void setAge_JsonNullable(JsonNullable<List<NamePath>> age) {
    this.age = age;
  }

  public void setAge(@jakarta.annotation.Nullable List<NamePath> age) {
    this.age = JsonNullable.<List<NamePath>>of(age);
  }


  public FilterSelections firstSeen(@jakarta.annotation.Nullable TimeFilterSelection firstSeen) {
    this.firstSeen = JsonNullable.<TimeFilterSelection>of(firstSeen);
    return this;
  }

  /**
   * Get firstSeen
   * @return firstSeen
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public TimeFilterSelection getFirstSeen() {
        return firstSeen.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_FIRST_SEEN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<TimeFilterSelection> getFirstSeen_JsonNullable() {
    return firstSeen;
  }
  
  @JsonProperty(JSON_PROPERTY_FIRST_SEEN)
  public void setFirstSeen_JsonNullable(JsonNullable<TimeFilterSelection> firstSeen) {
    this.firstSeen = firstSeen;
  }

  public void setFirstSeen(@jakarta.annotation.Nullable TimeFilterSelection firstSeen) {
    this.firstSeen = JsonNullable.<TimeFilterSelection>of(firstSeen);
  }


  public FilterSelections lastModified(@jakarta.annotation.Nullable TimeFilterSelection lastModified) {
    this.lastModified = JsonNullable.<TimeFilterSelection>of(lastModified);
    return this;
  }

  /**
   * Get lastModified
   * @return lastModified
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public TimeFilterSelection getLastModified() {
        return lastModified.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_LAST_MODIFIED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<TimeFilterSelection> getLastModified_JsonNullable() {
    return lastModified;
  }
  
  @JsonProperty(JSON_PROPERTY_LAST_MODIFIED)
  public void setLastModified_JsonNullable(JsonNullable<TimeFilterSelection> lastModified) {
    this.lastModified = lastModified;
  }

  public void setLastModified(@jakarta.annotation.Nullable TimeFilterSelection lastModified) {
    this.lastModified = JsonNullable.<TimeFilterSelection>of(lastModified);
  }


  public FilterSelections toolOverlap(@jakarta.annotation.Nullable List<NamePath> toolOverlap) {
    this.toolOverlap = JsonNullable.<List<NamePath>>of(toolOverlap);
    return this;
  }

  public FilterSelections addToolOverlapItem(NamePath toolOverlapItem) {
    if (this.toolOverlap == null || !this.toolOverlap.isPresent()) {
      this.toolOverlap = JsonNullable.<List<NamePath>>of(new ArrayList<>());
    }
    try {
      this.toolOverlap.get().add(toolOverlapItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Get toolOverlap
   * @return toolOverlap
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public List<NamePath> getToolOverlap() {
        return toolOverlap.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_TOOL_OVERLAP, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<List<NamePath>> getToolOverlap_JsonNullable() {
    return toolOverlap;
  }
  
  @JsonProperty(JSON_PROPERTY_TOOL_OVERLAP)
  public void setToolOverlap_JsonNullable(JsonNullable<List<NamePath>> toolOverlap) {
    this.toolOverlap = toolOverlap;
  }

  public void setToolOverlap(@jakarta.annotation.Nullable List<NamePath> toolOverlap) {
    this.toolOverlap = JsonNullable.<List<NamePath>>of(toolOverlap);
  }


  public FilterSelections standard(@jakarta.annotation.Nullable Map<String, List<NamePath>> standard) {
    this.standard = JsonNullable.<Map<String, List<NamePath>>>of(standard);
    return this;
  }

  public FilterSelections putStandardItem(String key, List<NamePath> standardItem) {
    if (this.standard == null || !this.standard.isPresent()) {
      this.standard = JsonNullable.<Map<String, List<NamePath>>>of(new HashMap<>());
    }
    try {
      this.standard.get().put(key, standardItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Special &#39;filter selections&#39; object for the Standards filter, where the array of selected items is nested in an object, under a field named after the selected standard. The object must contain exactly one field; no more, no less. I.e. you can do &#x60;{ \&quot;CWE All\&quot;: [...] }&#x60; or &#x60;{ \&quot;HIPAA\&quot;: [...] }&#x60; but not &#x60;{ \&quot;CWE All\&quot;: [...], \&quot;HIPAA\&quot;: [...] }&#x60;.
   * @return standard
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Map<String, List<NamePath>> getStandard() {
        return standard.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_STANDARD, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Map<String, List<NamePath>>> getStandard_JsonNullable() {
    return standard;
  }
  
  @JsonProperty(JSON_PROPERTY_STANDARD)
  public void setStandard_JsonNullable(JsonNullable<Map<String, List<NamePath>>> standard) {
    this.standard = standard;
  }

  public void setStandard(@jakarta.annotation.Nullable Map<String, List<NamePath>> standard) {
    this.standard = JsonNullable.<Map<String, List<NamePath>>>of(standard);
  }


  public FilterSelections tags(@jakarta.annotation.Nullable List<NamePath> tags) {
    this.tags = JsonNullable.<List<NamePath>>of(tags);
    return this;
  }

  public FilterSelections addTagsItem(NamePath tagsItem) {
    if (this.tags == null || !this.tags.isPresent()) {
      this.tags = JsonNullable.<List<NamePath>>of(new ArrayList<>());
    }
    try {
      this.tags.get().add(tagsItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Get tags
   * @return tags
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public List<NamePath> getTags() {
        return tags.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_TAGS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<List<NamePath>> getTags_JsonNullable() {
    return tags;
  }
  
  @JsonProperty(JSON_PROPERTY_TAGS)
  public void setTags_JsonNullable(JsonNullable<List<NamePath>> tags) {
    this.tags = tags;
  }

  public void setTags(@jakarta.annotation.Nullable List<NamePath> tags) {
    this.tags = JsonNullable.<List<NamePath>>of(tags);
  }


  public FilterSelections predictedStatus(@jakarta.annotation.Nullable PredictedStatusSelection predictedStatus) {
    this.predictedStatus = JsonNullable.<PredictedStatusSelection>of(predictedStatus);
    return this;
  }

  /**
   * Get predictedStatus
   * @return predictedStatus
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public PredictedStatusSelection getPredictedStatus() {
        return predictedStatus.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_PREDICTED_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<PredictedStatusSelection> getPredictedStatus_JsonNullable() {
    return predictedStatus;
  }
  
  @JsonProperty(JSON_PROPERTY_PREDICTED_STATUS)
  public void setPredictedStatus_JsonNullable(JsonNullable<PredictedStatusSelection> predictedStatus) {
    this.predictedStatus = predictedStatus;
  }

  public void setPredictedStatus(@jakarta.annotation.Nullable PredictedStatusSelection predictedStatus) {
    this.predictedStatus = JsonNullable.<PredictedStatusSelection>of(predictedStatus);
  }


  public FilterSelections status(@jakarta.annotation.Nullable List<NamePath> status) {
    this.status = JsonNullable.<List<NamePath>>of(status);
    return this;
  }

  public FilterSelections addStatusItem(NamePath statusItem) {
    if (this.status == null || !this.status.isPresent()) {
      this.status = JsonNullable.<List<NamePath>>of(new ArrayList<>());
    }
    try {
      this.status.get().add(statusItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * An array of Triage Statuses (e.g. \&quot;mitigated\&quot; , \&quot;fixed\&quot;, etc.) 
   * @return status
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public List<NamePath> getStatus() {
        return status.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<List<NamePath>> getStatus_JsonNullable() {
    return status;
  }
  
  @JsonProperty(JSON_PROPERTY_STATUS)
  public void setStatus_JsonNullable(JsonNullable<List<NamePath>> status) {
    this.status = status;
  }

  public void setStatus(@jakarta.annotation.Nullable List<NamePath> status) {
    this.status = JsonNullable.<List<NamePath>>of(status);
  }


  public FilterSelections findingStatus(@jakarta.annotation.Nullable List<NamePath> findingStatus) {
    this.findingStatus = JsonNullable.<List<NamePath>>of(findingStatus);
    return this;
  }

  public FilterSelections addFindingStatusItem(NamePath findingStatusItem) {
    if (this.findingStatus == null || !this.findingStatus.isPresent()) {
      this.findingStatus = JsonNullable.<List<NamePath>>of(new ArrayList<>());
    }
    try {
      this.findingStatus.get().add(findingStatusItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Get findingStatus
   * @return findingStatus
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public List<NamePath> getFindingStatus() {
        return findingStatus.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_FINDING_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<List<NamePath>> getFindingStatus_JsonNullable() {
    return findingStatus;
  }
  
  @JsonProperty(JSON_PROPERTY_FINDING_STATUS)
  public void setFindingStatus_JsonNullable(JsonNullable<List<NamePath>> findingStatus) {
    this.findingStatus = findingStatus;
  }

  public void setFindingStatus(@jakarta.annotation.Nullable List<NamePath> findingStatus) {
    this.findingStatus = JsonNullable.<List<NamePath>>of(findingStatus);
  }


  public FilterSelections issueTrackerAssociation(@jakarta.annotation.Nullable List<NamePath> issueTrackerAssociation) {
    this.issueTrackerAssociation = JsonNullable.<List<NamePath>>of(issueTrackerAssociation);
    return this;
  }

  public FilterSelections addIssueTrackerAssociationItem(NamePath issueTrackerAssociationItem) {
    if (this.issueTrackerAssociation == null || !this.issueTrackerAssociation.isPresent()) {
      this.issueTrackerAssociation = JsonNullable.<List<NamePath>>of(new ArrayList<>());
    }
    try {
      this.issueTrackerAssociation.get().add(issueTrackerAssociationItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Get issueTrackerAssociation
   * @return issueTrackerAssociation
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public List<NamePath> getIssueTrackerAssociation() {
        return issueTrackerAssociation.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_ISSUE_TRACKER_ASSOCIATION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<List<NamePath>> getIssueTrackerAssociation_JsonNullable() {
    return issueTrackerAssociation;
  }
  
  @JsonProperty(JSON_PROPERTY_ISSUE_TRACKER_ASSOCIATION)
  public void setIssueTrackerAssociation_JsonNullable(JsonNullable<List<NamePath>> issueTrackerAssociation) {
    this.issueTrackerAssociation = issueTrackerAssociation;
  }

  public void setIssueTrackerAssociation(@jakarta.annotation.Nullable List<NamePath> issueTrackerAssociation) {
    this.issueTrackerAssociation = JsonNullable.<List<NamePath>>of(issueTrackerAssociation);
  }


  public FilterSelections issueTrackerResolution(@jakarta.annotation.Nullable List<NamePath> issueTrackerResolution) {
    this.issueTrackerResolution = JsonNullable.<List<NamePath>>of(issueTrackerResolution);
    return this;
  }

  public FilterSelections addIssueTrackerResolutionItem(NamePath issueTrackerResolutionItem) {
    if (this.issueTrackerResolution == null || !this.issueTrackerResolution.isPresent()) {
      this.issueTrackerResolution = JsonNullable.<List<NamePath>>of(new ArrayList<>());
    }
    try {
      this.issueTrackerResolution.get().add(issueTrackerResolutionItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Get issueTrackerResolution
   * @return issueTrackerResolution
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public List<NamePath> getIssueTrackerResolution() {
        return issueTrackerResolution.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_ISSUE_TRACKER_RESOLUTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<List<NamePath>> getIssueTrackerResolution_JsonNullable() {
    return issueTrackerResolution;
  }
  
  @JsonProperty(JSON_PROPERTY_ISSUE_TRACKER_RESOLUTION)
  public void setIssueTrackerResolution_JsonNullable(JsonNullable<List<NamePath>> issueTrackerResolution) {
    this.issueTrackerResolution = issueTrackerResolution;
  }

  public void setIssueTrackerResolution(@jakarta.annotation.Nullable List<NamePath> issueTrackerResolution) {
    this.issueTrackerResolution = JsonNullable.<List<NamePath>>of(issueTrackerResolution);
  }


  /**
   * Return true if this FilterSelections object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FilterSelections filterSelections = (FilterSelections) o;
    return equalsNullable(this.search, filterSelections.search) &&
        equalsNullable(this.type, filterSelections.type) &&
        equalsNullable(this.project, filterSelections.project) &&
        equalsNullable(this.tool, filterSelections.tool) &&
        equalsNullable(this.detectionMethod, filterSelections.detectionMethod) &&
        equalsNullable(this.severity, filterSelections.severity) &&
        equalsNullable(this.location, filterSelections.location) &&
        equalsNullable(this.containerImage, filterSelections.containerImage) &&
        equalsNullable(this.age, filterSelections.age) &&
        equalsNullable(this.firstSeen, filterSelections.firstSeen) &&
        equalsNullable(this.lastModified, filterSelections.lastModified) &&
        equalsNullable(this.toolOverlap, filterSelections.toolOverlap) &&
        equalsNullable(this.standard, filterSelections.standard) &&
        equalsNullable(this.tags, filterSelections.tags) &&
        equalsNullable(this.predictedStatus, filterSelections.predictedStatus) &&
        equalsNullable(this.status, filterSelections.status) &&
        equalsNullable(this.findingStatus, filterSelections.findingStatus) &&
        equalsNullable(this.issueTrackerAssociation, filterSelections.issueTrackerAssociation) &&
        equalsNullable(this.issueTrackerResolution, filterSelections.issueTrackerResolution);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(hashCodeNullable(search), hashCodeNullable(type), hashCodeNullable(project), hashCodeNullable(tool), hashCodeNullable(detectionMethod), hashCodeNullable(severity), hashCodeNullable(location), hashCodeNullable(containerImage), hashCodeNullable(age), hashCodeNullable(firstSeen), hashCodeNullable(lastModified), hashCodeNullable(toolOverlap), hashCodeNullable(standard), hashCodeNullable(tags), hashCodeNullable(predictedStatus), hashCodeNullable(status), hashCodeNullable(findingStatus), hashCodeNullable(issueTrackerAssociation), hashCodeNullable(issueTrackerResolution));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FilterSelections {\n");
    sb.append("    search: ").append(toIndentedString(search)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    project: ").append(toIndentedString(project)).append("\n");
    sb.append("    tool: ").append(toIndentedString(tool)).append("\n");
    sb.append("    detectionMethod: ").append(toIndentedString(detectionMethod)).append("\n");
    sb.append("    severity: ").append(toIndentedString(severity)).append("\n");
    sb.append("    location: ").append(toIndentedString(location)).append("\n");
    sb.append("    containerImage: ").append(toIndentedString(containerImage)).append("\n");
    sb.append("    age: ").append(toIndentedString(age)).append("\n");
    sb.append("    firstSeen: ").append(toIndentedString(firstSeen)).append("\n");
    sb.append("    lastModified: ").append(toIndentedString(lastModified)).append("\n");
    sb.append("    toolOverlap: ").append(toIndentedString(toolOverlap)).append("\n");
    sb.append("    standard: ").append(toIndentedString(standard)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    predictedStatus: ").append(toIndentedString(predictedStatus)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    findingStatus: ").append(toIndentedString(findingStatus)).append("\n");
    sb.append("    issueTrackerAssociation: ").append(toIndentedString(issueTrackerAssociation)).append("\n");
    sb.append("    issueTrackerResolution: ").append(toIndentedString(issueTrackerResolution)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

