/*
 * Software Risk Manager API Guide
 * Software Risk Manager provides a variety of REST APIs, allowing external applications and scripts to interface with core functionality. This guide documents the various REST resources provided by Software Risk Manager.  ## Authentication  Authentication is a requirement when accessing API endpoints. There are two methods by which authentication may be performed.  ### API Keys  The primary method for authentication is passing an `API-Key` header containing a valid API key with all requests, i.e.  `API-Key: <key goes here>`  API Keys come in two possible forms:   - `api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24` - latest format  - `550e8400-e29b-41d4-a716-44665544000` - legacy format  For example:  `API-Key: api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24`  `API-Key: 550e8400-e29b-41d4-a716-44665544000`  API keys may be generated by Software Risk Manager admins. Once they are generated, in most cases, they behave like regular users. They will need to be assigned user roles for any projects they will be used with. Although it is possible to assign the *admin* [role](../user_guide/Project-Management/user_role_configuration.html) to an API key, the recommendation is to avoid doing so unless absolutely necessary.  See the user guide for an overview about how to create and manage [API keys](../user_guide/Settings/api_keys_administration.html).  ### Personal Access Tokens  Personal Access Tokens can be used as [bearer tokens](https://swagger.io/docs/specification/authentication/bearer-authentication/), e.g.  `Authorization: Bearer secret-token:qRuXr1BqgoTWXNxUhYQ8H_Yl2zfy6vxuqMIRnkGO`  Personal Access Tokens can be created by any user, and represent a subset of that user's permissions.   ### HTTP Basic Authentication  HTTP Basic authentication may be used to authenticate with the API as a regular user. This is accomplished by including an `Authorization` header containing a typical authorization credential.  ## Error Handling  ### Bad Requests  For API calls that accept input, invalid values will trigger an HTTP 400 Bad Request status code.  ### Server Errors  For any API call, if an unexpected error occurs, an HTTP 500 Internal Server Error status code will be returned. If an error message is available, the response will include a basic message body describing the error:  ` {   \"error\": \"error message\" } `  The error property will contain a string message indicating the nature of the error.  ### Errors with Third-Party Applications  Sometimes Software Risk Manager must communicate with third-party applications like JIRA, Git, and certain enterprise tools. Some users may have in-house versions of these with self-signed certificates which may not be \"trusted\". In these cases, the API will respond with an HTTP 502 BAD GATEWAY status. If this happens, refer to [Trusting Certificates](../install_guide/Installation/trusting-certs.html) in the install guide.  ### API Unavailable  In special circumstances, particularly during the installation and update phases, the API will be unavailable. When the API is unavailable, all calls will return an HTTP 503 Service Unavailable status, and no actions or side effects will occur as a result of the calls.  ## Examples  Software Risk Manager's API uses REST over HTTP. As such, you can use any language/utility that supports making HTTP requests to interact with the API. The examples below use <a href=\"https://curl.haxx.se/\" target=\"_blank\">curl</a>, a popular command-line utility, to do so.  First, you'll need to [generate an API Key](../user_guide/Settings/api_keys_administration.html). Second, while you can create projects through the API, these examples will assume that you've already created one. You'll need to know its project id number, which you can find by looking at the URL for the [Findings Page](../user_guide/Findings/findings_overview.html), which will end in a number.  **Note:** Many API endpoints require a JSON body in the request. Most JSON will contain double-quotes (`\"`) and spaces, which have special meaning when used on the command line. In order to ensure your JSON body is interpreted as a single argument, you must <a href=\"https://en.wikipedia.org/wiki/Escape_character\" target=\"_blank\">escape</a> it properly. For example, if you wanted to `POST` the following JSON body:  ```{ \"name\": \"John Doe\" }```  You would put a backslash (`\\`) before each double-quote (`\"`), and surround the whole thing with double-quotes:  ```\"{ \\\"name\\\": \\\"John Doe\\\" }\"```  The outermost double-quotes tell the command-line interpreter that everything within them is to be treated as a single argument (as opposed to the usual space-separated behavior). The backslash before each inner double-quote tells the command-line interpreter that you mean the literal double-quote character, and not the end of the quoted argument.  In many *non-Windows* operating systems, you can also use a single-quote (`'`) to surround the argument, and skip the backslashes:  ```'{ \"name\": \"John Doe\" }'```  The examples below will use the double-quotes and backslashes style, as it works on most (if not all) operating systems.  ### Running an Analysis  To start an analysis, you can run  ```curl -F file1=@src.zip -H \"API-Key: api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24\" https://<yoursrmserver>/srm/api/projects/<project id>/analysis```  Make sure you use your own values for the `src.zip` file, the API Key, the hostname for your Software Risk Manager server, and the project id.  ### Retrieving Finding Data  There is a wide variety of data available for the findings of a project after running an analysis. Two examples are provided here.  ### Findings Table Data  You can retrieve the data that's used to populate the [findings table](../user_guide/Findings/findings_table.html):  ```curl -H \"Content-Type: application/json\" -X POST -d \"{\\\"filter\\\":{},\\\"sort\\\":{\\\"by\\\":\\\"id\\\",\\\"direction\\\":\\\"ascending\\\"},\\\"pagination\\\":{\\\"page\\\":1,\\\"perPage\\\":10}}\" -H \"API-Key: api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24\" https://<yoursrmserver>/srm/api/projects/<project id>/findings/table```  Additional information about how to construct more useful filter and sort requests can be found in the documentation.  ### Finding Metadata  You can retrieve metadata for a finding, if you know the finding ID. You can take the ID for a finding from the Findings Table:  ```curl -H \"API-Key: api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24\" https://<yoursrmserver>/srm/api/findings/<finding id>```  ### Generating a Report  You can use the API to generate a PDF [report](../user_guide/Findings/generate_report.html).  ```curl -H \"Content-Type: application/json\" -X POST -d \"{\\\"filter\\\":{},\\\"config\\\":{\\\"summaryMode\\\":\\\"simple\\\",\\\"detailsMode\\\":\\\"simple\\\",\\\"includeResultDetails\\\":true,\\\"includeComments\\\":false}}\" -H \"API-Key: api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24\" https://<yoursrmserver>/srm/api/projects/<project id>/report/pdf```  ## Generating a Client SDK  If you require a client SDK for Software Risk Manager, you can generate one using [OpenAPI Generator](https://openapi-generator.tech/). Detailed instructions are available on the [GitHub page](https://github.com/OpenAPITools/openapi-generator) and our OpenAPI spec can be found [here](swagger/swagger.json). 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.codedx.client.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.codedx.client.model.ActionabilityPrediction;
import com.codedx.client.model.Cwe;
import com.codedx.client.model.Descriptions;
import com.codedx.client.model.DetectionMethod;
import com.codedx.client.model.Element;
import com.codedx.client.model.FindingDescriptor;
import com.codedx.client.model.FindingStatus;
import com.codedx.client.model.HostIdentifier;
import com.codedx.client.model.Issue;
import com.codedx.client.model.Location;
import com.codedx.client.model.Severity;
import com.codedx.client.model.ToolResult;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.codedx.client.JSON;


/**
 * Finding
 */
@JsonPropertyOrder({
  Finding.JSON_PROPERTY_ID,
  Finding.JSON_PROPERTY_IS_ACTIVE,
  Finding.JSON_PROPERTY_PROJECT_ID,
  Finding.JSON_PROPERTY_DETECTION_METHOD,
  Finding.JSON_PROPERTY_DESCRIPTOR,
  Finding.JSON_PROPERTY_LOCATION,
  Finding.JSON_PROPERTY_HOST_IDENTIFIER,
  Finding.JSON_PROPERTY_SEVERITY,
  Finding.JSON_PROPERTY_SEVERITY_DEFAULT,
  Finding.JSON_PROPERTY_SEVERITY_OVERRIDE,
  Finding.JSON_PROPERTY_FIRST_SEEN_ON,
  Finding.JSON_PROPERTY_CWE,
  Finding.JSON_PROPERTY_ELEMENT,
  Finding.JSON_PROPERTY_STATUS,
  Finding.JSON_PROPERTY_STATUS_NAME,
  Finding.JSON_PROPERTY_TRIAGE_TIME,
  Finding.JSON_PROPERTY_ISSUE,
  Finding.JSON_PROPERTY_DESCRIPTIONS,
  Finding.JSON_PROPERTY_RESULTS,
  Finding.JSON_PROPERTY_METADATA,
  Finding.JSON_PROPERTY_SIMPLE_DETECTION_TYPE,
  Finding.JSON_PROPERTY_ACTIONABILITY_PREDICTION,
  Finding.JSON_PROPERTY_FINDING_STATUS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-02T11:55:06.722228-04:00[America/New_York]", comments = "Generator version: 7.21.0")
public class Finding {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nullable
  private Integer id;

  public static final String JSON_PROPERTY_IS_ACTIVE = "isActive";
  @jakarta.annotation.Nullable
  private Boolean isActive;

  public static final String JSON_PROPERTY_PROJECT_ID = "projectId";
  @jakarta.annotation.Nullable
  private Integer projectId;

  public static final String JSON_PROPERTY_DETECTION_METHOD = "detectionMethod";
  @jakarta.annotation.Nullable
  private DetectionMethod detectionMethod;

  public static final String JSON_PROPERTY_DESCRIPTOR = "descriptor";
  @jakarta.annotation.Nullable
  private FindingDescriptor descriptor;

  public static final String JSON_PROPERTY_LOCATION = "location";
  @jakarta.annotation.Nullable
  private Location location;

  public static final String JSON_PROPERTY_HOST_IDENTIFIER = "hostIdentifier";
  @jakarta.annotation.Nullable
  private HostIdentifier hostIdentifier;

  public static final String JSON_PROPERTY_SEVERITY = "severity";
  @jakarta.annotation.Nullable
  private Severity severity;

  public static final String JSON_PROPERTY_SEVERITY_DEFAULT = "severityDefault";
  @jakarta.annotation.Nullable
  private Severity severityDefault;

  public static final String JSON_PROPERTY_SEVERITY_OVERRIDE = "severityOverride";
  @jakarta.annotation.Nullable
  private Severity severityOverride;

  public static final String JSON_PROPERTY_FIRST_SEEN_ON = "firstSeenOn";
  @jakarta.annotation.Nullable
  private String firstSeenOn;

  public static final String JSON_PROPERTY_CWE = "cwe";
  @jakarta.annotation.Nullable
  private Cwe cwe;

  public static final String JSON_PROPERTY_ELEMENT = "element";
  @jakarta.annotation.Nullable
  private Element element;

  public static final String JSON_PROPERTY_STATUS = "status";
  @jakarta.annotation.Nullable
  private String status;

  public static final String JSON_PROPERTY_STATUS_NAME = "statusName";
  @jakarta.annotation.Nullable
  private String statusName;

  public static final String JSON_PROPERTY_TRIAGE_TIME = "triageTime";
  @jakarta.annotation.Nullable
  private String triageTime;

  public static final String JSON_PROPERTY_ISSUE = "issue";
  @jakarta.annotation.Nullable
  private Issue issue;

  public static final String JSON_PROPERTY_DESCRIPTIONS = "descriptions";
  @jakarta.annotation.Nullable
  private Descriptions descriptions;

  public static final String JSON_PROPERTY_RESULTS = "results";
  @jakarta.annotation.Nullable
  private List<ToolResult> results = new ArrayList<>();

  public static final String JSON_PROPERTY_METADATA = "metadata";
  @jakarta.annotation.Nullable
  private Map<String, Object> metadata = new HashMap<>();

  public static final String JSON_PROPERTY_SIMPLE_DETECTION_TYPE = "simpleDetectionType";
  @jakarta.annotation.Nullable
  private String simpleDetectionType;

  public static final String JSON_PROPERTY_ACTIONABILITY_PREDICTION = "actionabilityPrediction";
  @jakarta.annotation.Nullable
  private ActionabilityPrediction actionabilityPrediction;

  public static final String JSON_PROPERTY_FINDING_STATUS = "findingStatus";
  @jakarta.annotation.Nullable
  private FindingStatus findingStatus;

  public Finding() { 
  }

  public Finding id(@jakarta.annotation.Nullable Integer id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@jakarta.annotation.Nullable Integer id) {
    this.id = id;
  }


  public Finding isActive(@jakarta.annotation.Nullable Boolean isActive) {
    this.isActive = isActive;
    return this;
  }

  /**
   * Get isActive
   * @return isActive
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_IS_ACTIVE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getIsActive() {
    return isActive;
  }


  @JsonProperty(value = JSON_PROPERTY_IS_ACTIVE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsActive(@jakarta.annotation.Nullable Boolean isActive) {
    this.isActive = isActive;
  }


  public Finding projectId(@jakarta.annotation.Nullable Integer projectId) {
    this.projectId = projectId;
    return this;
  }

  /**
   * Get projectId
   * @return projectId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PROJECT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getProjectId() {
    return projectId;
  }


  @JsonProperty(value = JSON_PROPERTY_PROJECT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProjectId(@jakarta.annotation.Nullable Integer projectId) {
    this.projectId = projectId;
  }


  public Finding detectionMethod(@jakarta.annotation.Nullable DetectionMethod detectionMethod) {
    this.detectionMethod = detectionMethod;
    return this;
  }

  /**
   * Get detectionMethod
   * @return detectionMethod
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DETECTION_METHOD, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public DetectionMethod getDetectionMethod() {
    return detectionMethod;
  }


  @JsonProperty(value = JSON_PROPERTY_DETECTION_METHOD, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDetectionMethod(@jakarta.annotation.Nullable DetectionMethod detectionMethod) {
    this.detectionMethod = detectionMethod;
  }


  public Finding descriptor(@jakarta.annotation.Nullable FindingDescriptor descriptor) {
    this.descriptor = descriptor;
    return this;
  }

  /**
   * Get descriptor
   * @return descriptor
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DESCRIPTOR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public FindingDescriptor getDescriptor() {
    return descriptor;
  }


  @JsonProperty(value = JSON_PROPERTY_DESCRIPTOR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescriptor(@jakarta.annotation.Nullable FindingDescriptor descriptor) {
    this.descriptor = descriptor;
  }


  public Finding location(@jakarta.annotation.Nullable Location location) {
    this.location = location;
    return this;
  }

  /**
   * Get location
   * @return location
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LOCATION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Location getLocation() {
    return location;
  }


  @JsonProperty(value = JSON_PROPERTY_LOCATION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLocation(@jakarta.annotation.Nullable Location location) {
    this.location = location;
  }


  public Finding hostIdentifier(@jakarta.annotation.Nullable HostIdentifier hostIdentifier) {
    this.hostIdentifier = hostIdentifier;
    return this;
  }

  /**
   * Get hostIdentifier
   * @return hostIdentifier
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_HOST_IDENTIFIER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public HostIdentifier getHostIdentifier() {
    return hostIdentifier;
  }


  @JsonProperty(value = JSON_PROPERTY_HOST_IDENTIFIER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHostIdentifier(@jakarta.annotation.Nullable HostIdentifier hostIdentifier) {
    this.hostIdentifier = hostIdentifier;
  }


  public Finding severity(@jakarta.annotation.Nullable Severity severity) {
    this.severity = severity;
    return this;
  }

  /**
   * Get severity
   * @return severity
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SEVERITY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Severity getSeverity() {
    return severity;
  }


  @JsonProperty(value = JSON_PROPERTY_SEVERITY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSeverity(@jakarta.annotation.Nullable Severity severity) {
    this.severity = severity;
  }


  public Finding severityDefault(@jakarta.annotation.Nullable Severity severityDefault) {
    this.severityDefault = severityDefault;
    return this;
  }

  /**
   * Get severityDefault
   * @return severityDefault
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SEVERITY_DEFAULT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Severity getSeverityDefault() {
    return severityDefault;
  }


  @JsonProperty(value = JSON_PROPERTY_SEVERITY_DEFAULT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSeverityDefault(@jakarta.annotation.Nullable Severity severityDefault) {
    this.severityDefault = severityDefault;
  }


  public Finding severityOverride(@jakarta.annotation.Nullable Severity severityOverride) {
    this.severityOverride = severityOverride;
    return this;
  }

  /**
   * Get severityOverride
   * @return severityOverride
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SEVERITY_OVERRIDE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Severity getSeverityOverride() {
    return severityOverride;
  }


  @JsonProperty(value = JSON_PROPERTY_SEVERITY_OVERRIDE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSeverityOverride(@jakarta.annotation.Nullable Severity severityOverride) {
    this.severityOverride = severityOverride;
  }


  public Finding firstSeenOn(@jakarta.annotation.Nullable String firstSeenOn) {
    this.firstSeenOn = firstSeenOn;
    return this;
  }

  /**
   * Get firstSeenOn
   * @return firstSeenOn
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FIRST_SEEN_ON, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFirstSeenOn() {
    return firstSeenOn;
  }


  @JsonProperty(value = JSON_PROPERTY_FIRST_SEEN_ON, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFirstSeenOn(@jakarta.annotation.Nullable String firstSeenOn) {
    this.firstSeenOn = firstSeenOn;
  }


  public Finding cwe(@jakarta.annotation.Nullable Cwe cwe) {
    this.cwe = cwe;
    return this;
  }

  /**
   * Get cwe
   * @return cwe
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CWE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Cwe getCwe() {
    return cwe;
  }


  @JsonProperty(value = JSON_PROPERTY_CWE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCwe(@jakarta.annotation.Nullable Cwe cwe) {
    this.cwe = cwe;
  }


  public Finding element(@jakarta.annotation.Nullable Element element) {
    this.element = element;
    return this;
  }

  /**
   * Get element
   * @return element
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ELEMENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Element getElement() {
    return element;
  }


  @JsonProperty(value = JSON_PROPERTY_ELEMENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setElement(@jakarta.annotation.Nullable Element element) {
    this.element = element;
  }


  public Finding status(@jakarta.annotation.Nullable String status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getStatus() {
    return status;
  }


  @JsonProperty(value = JSON_PROPERTY_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatus(@jakarta.annotation.Nullable String status) {
    this.status = status;
  }


  public Finding statusName(@jakarta.annotation.Nullable String statusName) {
    this.statusName = statusName;
    return this;
  }

  /**
   * Get statusName
   * @return statusName
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_STATUS_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getStatusName() {
    return statusName;
  }


  @JsonProperty(value = JSON_PROPERTY_STATUS_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatusName(@jakarta.annotation.Nullable String statusName) {
    this.statusName = statusName;
  }


  public Finding triageTime(@jakarta.annotation.Nullable String triageTime) {
    this.triageTime = triageTime;
    return this;
  }

  /**
   * Get triageTime
   * @return triageTime
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TRIAGE_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTriageTime() {
    return triageTime;
  }


  @JsonProperty(value = JSON_PROPERTY_TRIAGE_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTriageTime(@jakarta.annotation.Nullable String triageTime) {
    this.triageTime = triageTime;
  }


  public Finding issue(@jakarta.annotation.Nullable Issue issue) {
    this.issue = issue;
    return this;
  }

  /**
   * Get issue
   * @return issue
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ISSUE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Issue getIssue() {
    return issue;
  }


  @JsonProperty(value = JSON_PROPERTY_ISSUE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIssue(@jakarta.annotation.Nullable Issue issue) {
    this.issue = issue;
  }


  public Finding descriptions(@jakarta.annotation.Nullable Descriptions descriptions) {
    this.descriptions = descriptions;
    return this;
  }

  /**
   * Get descriptions
   * @return descriptions
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DESCRIPTIONS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Descriptions getDescriptions() {
    return descriptions;
  }


  @JsonProperty(value = JSON_PROPERTY_DESCRIPTIONS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescriptions(@jakarta.annotation.Nullable Descriptions descriptions) {
    this.descriptions = descriptions;
  }


  public Finding results(@jakarta.annotation.Nullable List<ToolResult> results) {
    this.results = results;
    return this;
  }

  public Finding addResultsItem(ToolResult resultsItem) {
    if (this.results == null) {
      this.results = new ArrayList<>();
    }
    this.results.add(resultsItem);
    return this;
  }

  /**
   * Get results
   * @return results
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_RESULTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<ToolResult> getResults() {
    return results;
  }


  @JsonProperty(value = JSON_PROPERTY_RESULTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setResults(@jakarta.annotation.Nullable List<ToolResult> results) {
    this.results = results;
  }


  public Finding metadata(@jakarta.annotation.Nullable Map<String, Object> metadata) {
    this.metadata = metadata;
    return this;
  }

  public Finding putMetadataItem(String key, Object metadataItem) {
    if (this.metadata == null) {
      this.metadata = new HashMap<>();
    }
    this.metadata.put(key, metadataItem);
    return this;
  }

  /**
   * Get metadata
   * @return metadata
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_METADATA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, Object> getMetadata() {
    return metadata;
  }


  @JsonProperty(value = JSON_PROPERTY_METADATA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMetadata(@jakarta.annotation.Nullable Map<String, Object> metadata) {
    this.metadata = metadata;
  }


  public Finding simpleDetectionType(@jakarta.annotation.Nullable String simpleDetectionType) {
    this.simpleDetectionType = simpleDetectionType;
    return this;
  }

  /**
   * Get simpleDetectionType
   * @return simpleDetectionType
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SIMPLE_DETECTION_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSimpleDetectionType() {
    return simpleDetectionType;
  }


  @JsonProperty(value = JSON_PROPERTY_SIMPLE_DETECTION_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSimpleDetectionType(@jakarta.annotation.Nullable String simpleDetectionType) {
    this.simpleDetectionType = simpleDetectionType;
  }


  public Finding actionabilityPrediction(@jakarta.annotation.Nullable ActionabilityPrediction actionabilityPrediction) {
    this.actionabilityPrediction = actionabilityPrediction;
    return this;
  }

  /**
   * Get actionabilityPrediction
   * @return actionabilityPrediction
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ACTIONABILITY_PREDICTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ActionabilityPrediction getActionabilityPrediction() {
    return actionabilityPrediction;
  }


  @JsonProperty(value = JSON_PROPERTY_ACTIONABILITY_PREDICTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setActionabilityPrediction(@jakarta.annotation.Nullable ActionabilityPrediction actionabilityPrediction) {
    this.actionabilityPrediction = actionabilityPrediction;
  }


  public Finding findingStatus(@jakarta.annotation.Nullable FindingStatus findingStatus) {
    this.findingStatus = findingStatus;
    return this;
  }

  /**
   * Get findingStatus
   * @return findingStatus
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FINDING_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public FindingStatus getFindingStatus() {
    return findingStatus;
  }


  @JsonProperty(value = JSON_PROPERTY_FINDING_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFindingStatus(@jakarta.annotation.Nullable FindingStatus findingStatus) {
    this.findingStatus = findingStatus;
  }


  /**
   * Return true if this Finding object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Finding finding = (Finding) o;
    return Objects.equals(this.id, finding.id) &&
        Objects.equals(this.isActive, finding.isActive) &&
        Objects.equals(this.projectId, finding.projectId) &&
        Objects.equals(this.detectionMethod, finding.detectionMethod) &&
        Objects.equals(this.descriptor, finding.descriptor) &&
        Objects.equals(this.location, finding.location) &&
        Objects.equals(this.hostIdentifier, finding.hostIdentifier) &&
        Objects.equals(this.severity, finding.severity) &&
        Objects.equals(this.severityDefault, finding.severityDefault) &&
        Objects.equals(this.severityOverride, finding.severityOverride) &&
        Objects.equals(this.firstSeenOn, finding.firstSeenOn) &&
        Objects.equals(this.cwe, finding.cwe) &&
        Objects.equals(this.element, finding.element) &&
        Objects.equals(this.status, finding.status) &&
        Objects.equals(this.statusName, finding.statusName) &&
        Objects.equals(this.triageTime, finding.triageTime) &&
        Objects.equals(this.issue, finding.issue) &&
        Objects.equals(this.descriptions, finding.descriptions) &&
        Objects.equals(this.results, finding.results) &&
        Objects.equals(this.metadata, finding.metadata) &&
        Objects.equals(this.simpleDetectionType, finding.simpleDetectionType) &&
        Objects.equals(this.actionabilityPrediction, finding.actionabilityPrediction) &&
        Objects.equals(this.findingStatus, finding.findingStatus);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, isActive, projectId, detectionMethod, descriptor, location, hostIdentifier, severity, severityDefault, severityOverride, firstSeenOn, cwe, element, status, statusName, triageTime, issue, descriptions, results, metadata, simpleDetectionType, actionabilityPrediction, findingStatus);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Finding {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    isActive: ").append(toIndentedString(isActive)).append("\n");
    sb.append("    projectId: ").append(toIndentedString(projectId)).append("\n");
    sb.append("    detectionMethod: ").append(toIndentedString(detectionMethod)).append("\n");
    sb.append("    descriptor: ").append(toIndentedString(descriptor)).append("\n");
    sb.append("    location: ").append(toIndentedString(location)).append("\n");
    sb.append("    hostIdentifier: ").append(toIndentedString(hostIdentifier)).append("\n");
    sb.append("    severity: ").append(toIndentedString(severity)).append("\n");
    sb.append("    severityDefault: ").append(toIndentedString(severityDefault)).append("\n");
    sb.append("    severityOverride: ").append(toIndentedString(severityOverride)).append("\n");
    sb.append("    firstSeenOn: ").append(toIndentedString(firstSeenOn)).append("\n");
    sb.append("    cwe: ").append(toIndentedString(cwe)).append("\n");
    sb.append("    element: ").append(toIndentedString(element)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    statusName: ").append(toIndentedString(statusName)).append("\n");
    sb.append("    triageTime: ").append(toIndentedString(triageTime)).append("\n");
    sb.append("    issue: ").append(toIndentedString(issue)).append("\n");
    sb.append("    descriptions: ").append(toIndentedString(descriptions)).append("\n");
    sb.append("    results: ").append(toIndentedString(results)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    simpleDetectionType: ").append(toIndentedString(simpleDetectionType)).append("\n");
    sb.append("    actionabilityPrediction: ").append(toIndentedString(actionabilityPrediction)).append("\n");
    sb.append("    findingStatus: ").append(toIndentedString(findingStatus)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

