/*
 * Software Risk Manager API Guide
 * Software Risk Manager provides a variety of REST APIs, allowing external applications and scripts to interface with core functionality. This guide documents the various REST resources provided by Software Risk Manager.  ## Authentication  Authentication is a requirement when accessing API endpoints. There are two methods by which authentication may be performed.  ### API Keys  The primary method for authentication is passing an `API-Key` header containing a valid API key with all requests, i.e.  `API-Key: <key goes here>`  API Keys come in two possible forms:   - `api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24` - latest format  - `550e8400-e29b-41d4-a716-44665544000` - legacy format  For example:  `API-Key: api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24`  `API-Key: 550e8400-e29b-41d4-a716-44665544000`  API keys may be generated by Software Risk Manager admins. Once they are generated, in most cases, they behave like regular users. They will need to be assigned user roles for any projects they will be used with. Although it is possible to assign the *admin* [role](../user_guide/Project-Management/user_role_configuration.html) to an API key, the recommendation is to avoid doing so unless absolutely necessary.  See the user guide for an overview about how to create and manage [API keys](../user_guide/Settings/api_keys_administration.html).  ### Personal Access Tokens  Personal Access Tokens can be used as [bearer tokens](https://swagger.io/docs/specification/authentication/bearer-authentication/), e.g.  `Authorization: Bearer secret-token:qRuXr1BqgoTWXNxUhYQ8H_Yl2zfy6vxuqMIRnkGO`  Personal Access Tokens can be created by any user, and represent a subset of that user's permissions.   ### HTTP Basic Authentication  HTTP Basic authentication may be used to authenticate with the API as a regular user. This is accomplished by including an `Authorization` header containing a typical authorization credential.  ## Error Handling  ### Bad Requests  For API calls that accept input, invalid values will trigger an HTTP 400 Bad Request status code.  ### Server Errors  For any API call, if an unexpected error occurs, an HTTP 500 Internal Server Error status code will be returned. If an error message is available, the response will include a basic message body describing the error:  ` {   \"error\": \"error message\" } `  The error property will contain a string message indicating the nature of the error.  ### Errors with Third-Party Applications  Sometimes Software Risk Manager must communicate with third-party applications like JIRA, Git, and certain enterprise tools. Some users may have in-house versions of these with self-signed certificates which may not be \"trusted\". In these cases, the API will respond with an HTTP 502 BAD GATEWAY status. If this happens, refer to [Trusting Certificates](../install_guide/Installation/trusting-certs.html) in the install guide.  ### API Unavailable  In special circumstances, particularly during the installation and update phases, the API will be unavailable. When the API is unavailable, all calls will return an HTTP 503 Service Unavailable status, and no actions or side effects will occur as a result of the calls.  ## Examples  Software Risk Manager's API uses REST over HTTP. As such, you can use any language/utility that supports making HTTP requests to interact with the API. The examples below use <a href=\"https://curl.haxx.se/\" target=\"_blank\">curl</a>, a popular command-line utility, to do so.  First, you'll need to [generate an API Key](../user_guide/Settings/api_keys_administration.html). Second, while you can create projects through the API, these examples will assume that you've already created one. You'll need to know its project id number, which you can find by looking at the URL for the [Findings Page](../user_guide/Findings/findings_overview.html), which will end in a number.  **Note:** Many API endpoints require a JSON body in the request. Most JSON will contain double-quotes (`\"`) and spaces, which have special meaning when used on the command line. In order to ensure your JSON body is interpreted as a single argument, you must <a href=\"https://en.wikipedia.org/wiki/Escape_character\" target=\"_blank\">escape</a> it properly. For example, if you wanted to `POST` the following JSON body:  ```{ \"name\": \"John Doe\" }```  You would put a backslash (`\\`) before each double-quote (`\"`), and surround the whole thing with double-quotes:  ```\"{ \\\"name\\\": \\\"John Doe\\\" }\"```  The outermost double-quotes tell the command-line interpreter that everything within them is to be treated as a single argument (as opposed to the usual space-separated behavior). The backslash before each inner double-quote tells the command-line interpreter that you mean the literal double-quote character, and not the end of the quoted argument.  In many *non-Windows* operating systems, you can also use a single-quote (`'`) to surround the argument, and skip the backslashes:  ```'{ \"name\": \"John Doe\" }'```  The examples below will use the double-quotes and backslashes style, as it works on most (if not all) operating systems.  ### Running an Analysis  To start an analysis, you can run  ```curl -F file1=@src.zip -H \"API-Key: api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24\" https://<yoursrmserver>/srm/api/projects/<project id>/analysis```  Make sure you use your own values for the `src.zip` file, the API Key, the hostname for your Software Risk Manager server, and the project id.  ### Retrieving Finding Data  There is a wide variety of data available for the findings of a project after running an analysis. Two examples are provided here.  ### Findings Table Data  You can retrieve the data that's used to populate the [findings table](../user_guide/Findings/findings_table.html):  ```curl -H \"Content-Type: application/json\" -X POST -d \"{\\\"filter\\\":{},\\\"sort\\\":{\\\"by\\\":\\\"id\\\",\\\"direction\\\":\\\"ascending\\\"},\\\"pagination\\\":{\\\"page\\\":1,\\\"perPage\\\":10}}\" -H \"API-Key: api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24\" https://<yoursrmserver>/srm/api/projects/<project id>/findings/table```  Additional information about how to construct more useful filter and sort requests can be found in the documentation.  ### Finding Metadata  You can retrieve metadata for a finding, if you know the finding ID. You can take the ID for a finding from the Findings Table:  ```curl -H \"API-Key: api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24\" https://<yoursrmserver>/srm/api/findings/<finding id>```  ### Generating a Report  You can use the API to generate a PDF [report](../user_guide/Findings/generate_report.html).  ```curl -H \"Content-Type: application/json\" -X POST -d \"{\\\"filter\\\":{},\\\"config\\\":{\\\"summaryMode\\\":\\\"simple\\\",\\\"detailsMode\\\":\\\"simple\\\",\\\"includeResultDetails\\\":true,\\\"includeComments\\\":false}}\" -H \"API-Key: api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24\" https://<yoursrmserver>/srm/api/projects/<project id>/report/pdf```  ## Generating a Client SDK  If you require a client SDK for Software Risk Manager, you can generate one using [OpenAPI Generator](https://openapi-generator.tech/). Detailed instructions are available on the [GitHub page](https://github.com/OpenAPITools/openapi-generator) and our OpenAPI spec can be found [here](swagger/swagger.json). 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.codedx.client.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.codedx.client.model.DisplayTagState;
import com.codedx.client.model.ScmInfo;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.codedx.client.JSON;


/**
 * InputDisplayInfo
 */
@JsonPropertyOrder({
  InputDisplayInfo.JSON_PROPERTY_TAGS,
  InputDisplayInfo.JSON_PROPERTY_SCM_INFO,
  InputDisplayInfo.JSON_PROPERTY_FILE_SIZE,
  InputDisplayInfo.JSON_PROPERTY_SOURCE_AVAILABLE,
  InputDisplayInfo.JSON_PROPERTY_WARNINGS,
  InputDisplayInfo.JSON_PROPERTY_ERRORS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-02T11:55:06.722228-04:00[America/New_York]", comments = "Generator version: 7.21.0")
public class InputDisplayInfo {
  public static final String JSON_PROPERTY_TAGS = "tags";
  @jakarta.annotation.Nullable
  private List<DisplayTagState> tags = new ArrayList<>();

  public static final String JSON_PROPERTY_SCM_INFO = "scmInfo";
  @jakarta.annotation.Nullable
  private ScmInfo scmInfo;

  public static final String JSON_PROPERTY_FILE_SIZE = "fileSize";
  @jakarta.annotation.Nullable
  private Integer fileSize;

  public static final String JSON_PROPERTY_SOURCE_AVAILABLE = "sourceAvailable";
  @jakarta.annotation.Nullable
  private Boolean sourceAvailable;

  public static final String JSON_PROPERTY_WARNINGS = "warnings";
  @jakarta.annotation.Nullable
  private List<String> warnings = new ArrayList<>();

  public static final String JSON_PROPERTY_ERRORS = "errors";
  @jakarta.annotation.Nullable
  private List<String> errors = new ArrayList<>();

  public InputDisplayInfo() { 
  }

  public InputDisplayInfo tags(@jakarta.annotation.Nullable List<DisplayTagState> tags) {
    this.tags = tags;
    return this;
  }

  public InputDisplayInfo addTagsItem(DisplayTagState tagsItem) {
    if (this.tags == null) {
      this.tags = new ArrayList<>();
    }
    this.tags.add(tagsItem);
    return this;
  }

  /**
   * Get tags
   * @return tags
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TAGS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<DisplayTagState> getTags() {
    return tags;
  }


  @JsonProperty(value = JSON_PROPERTY_TAGS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTags(@jakarta.annotation.Nullable List<DisplayTagState> tags) {
    this.tags = tags;
  }


  public InputDisplayInfo scmInfo(@jakarta.annotation.Nullable ScmInfo scmInfo) {
    this.scmInfo = scmInfo;
    return this;
  }

  /**
   * Get scmInfo
   * @return scmInfo
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SCM_INFO, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ScmInfo getScmInfo() {
    return scmInfo;
  }


  @JsonProperty(value = JSON_PROPERTY_SCM_INFO, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setScmInfo(@jakarta.annotation.Nullable ScmInfo scmInfo) {
    this.scmInfo = scmInfo;
  }


  public InputDisplayInfo fileSize(@jakarta.annotation.Nullable Integer fileSize) {
    this.fileSize = fileSize;
    return this;
  }

  /**
   * Get fileSize
   * @return fileSize
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FILE_SIZE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getFileSize() {
    return fileSize;
  }


  @JsonProperty(value = JSON_PROPERTY_FILE_SIZE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFileSize(@jakarta.annotation.Nullable Integer fileSize) {
    this.fileSize = fileSize;
  }


  public InputDisplayInfo sourceAvailable(@jakarta.annotation.Nullable Boolean sourceAvailable) {
    this.sourceAvailable = sourceAvailable;
    return this;
  }

  /**
   * Get sourceAvailable
   * @return sourceAvailable
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SOURCE_AVAILABLE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getSourceAvailable() {
    return sourceAvailable;
  }


  @JsonProperty(value = JSON_PROPERTY_SOURCE_AVAILABLE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSourceAvailable(@jakarta.annotation.Nullable Boolean sourceAvailable) {
    this.sourceAvailable = sourceAvailable;
  }


  public InputDisplayInfo warnings(@jakarta.annotation.Nullable List<String> warnings) {
    this.warnings = warnings;
    return this;
  }

  public InputDisplayInfo addWarningsItem(String warningsItem) {
    if (this.warnings == null) {
      this.warnings = new ArrayList<>();
    }
    this.warnings.add(warningsItem);
    return this;
  }

  /**
   * An array of strings that describe problems that may want to be addressed, but will not prevent analysis from starting
   * @return warnings
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_WARNINGS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getWarnings() {
    return warnings;
  }


  @JsonProperty(value = JSON_PROPERTY_WARNINGS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWarnings(@jakarta.annotation.Nullable List<String> warnings) {
    this.warnings = warnings;
  }


  public InputDisplayInfo errors(@jakarta.annotation.Nullable List<String> errors) {
    this.errors = errors;
    return this;
  }

  public InputDisplayInfo addErrorsItem(String errorsItem) {
    if (this.errors == null) {
      this.errors = new ArrayList<>();
    }
    this.errors.add(errorsItem);
    return this;
  }

  /**
   * An array of strings that describe problems that should be addressed before analysis can begin.
   * @return errors
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ERRORS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getErrors() {
    return errors;
  }


  @JsonProperty(value = JSON_PROPERTY_ERRORS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setErrors(@jakarta.annotation.Nullable List<String> errors) {
    this.errors = errors;
  }


  /**
   * Return true if this InputDisplayInfo object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InputDisplayInfo inputDisplayInfo = (InputDisplayInfo) o;
    return Objects.equals(this.tags, inputDisplayInfo.tags) &&
        Objects.equals(this.scmInfo, inputDisplayInfo.scmInfo) &&
        Objects.equals(this.fileSize, inputDisplayInfo.fileSize) &&
        Objects.equals(this.sourceAvailable, inputDisplayInfo.sourceAvailable) &&
        Objects.equals(this.warnings, inputDisplayInfo.warnings) &&
        Objects.equals(this.errors, inputDisplayInfo.errors);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tags, scmInfo, fileSize, sourceAvailable, warnings, errors);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InputDisplayInfo {\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    scmInfo: ").append(toIndentedString(scmInfo)).append("\n");
    sb.append("    fileSize: ").append(toIndentedString(fileSize)).append("\n");
    sb.append("    sourceAvailable: ").append(toIndentedString(sourceAvailable)).append("\n");
    sb.append("    warnings: ").append(toIndentedString(warnings)).append("\n");
    sb.append("    errors: ").append(toIndentedString(errors)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

