/*
 * Software Risk Manager API Guide
 * Software Risk Manager provides a variety of REST APIs, allowing external applications and scripts to interface with core functionality. This guide documents the various REST resources provided by Software Risk Manager.  ## Authentication  Authentication is a requirement when accessing API endpoints. There are two methods by which authentication may be performed.  ### API Keys  The primary method for authentication is passing an `API-Key` header containing a valid API key with all requests, i.e.  `API-Key: <key goes here>`  API Keys come in two possible forms:   - `api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24` - latest format  - `550e8400-e29b-41d4-a716-44665544000` - legacy format  For example:  `API-Key: api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24`  `API-Key: 550e8400-e29b-41d4-a716-44665544000`  API keys may be generated by Software Risk Manager admins. Once they are generated, in most cases, they behave like regular users. They will need to be assigned user roles for any projects they will be used with. Although it is possible to assign the *admin* [role](../user_guide/Project-Management/user_role_configuration.html) to an API key, the recommendation is to avoid doing so unless absolutely necessary.  See the user guide for an overview about how to create and manage [API keys](../user_guide/Settings/api_keys_administration.html).  ### Personal Access Tokens  Personal Access Tokens can be used as [bearer tokens](https://swagger.io/docs/specification/authentication/bearer-authentication/), e.g.  `Authorization: Bearer secret-token:qRuXr1BqgoTWXNxUhYQ8H_Yl2zfy6vxuqMIRnkGO`  Personal Access Tokens can be created by any user, and represent a subset of that user's permissions.   ### HTTP Basic Authentication  HTTP Basic authentication may be used to authenticate with the API as a regular user. This is accomplished by including an `Authorization` header containing a typical authorization credential.  ## Error Handling  ### Bad Requests  For API calls that accept input, invalid values will trigger an HTTP 400 Bad Request status code.  ### Server Errors  For any API call, if an unexpected error occurs, an HTTP 500 Internal Server Error status code will be returned. If an error message is available, the response will include a basic message body describing the error:  ` {   \"error\": \"error message\" } `  The error property will contain a string message indicating the nature of the error.  ### Errors with Third-Party Applications  Sometimes Software Risk Manager must communicate with third-party applications like JIRA, Git, and certain enterprise tools. Some users may have in-house versions of these with self-signed certificates which may not be \"trusted\". In these cases, the API will respond with an HTTP 502 BAD GATEWAY status. If this happens, refer to [Trusting Certificates](../install_guide/Installation/trusting-certs.html) in the install guide.  ### API Unavailable  In special circumstances, particularly during the installation and update phases, the API will be unavailable. When the API is unavailable, all calls will return an HTTP 503 Service Unavailable status, and no actions or side effects will occur as a result of the calls.  ## Examples  Software Risk Manager's API uses REST over HTTP. As such, you can use any language/utility that supports making HTTP requests to interact with the API. The examples below use <a href=\"https://curl.haxx.se/\" target=\"_blank\">curl</a>, a popular command-line utility, to do so.  First, you'll need to [generate an API Key](../user_guide/Settings/api_keys_administration.html). Second, while you can create projects through the API, these examples will assume that you've already created one. You'll need to know its project id number, which you can find by looking at the URL for the [Findings Page](../user_guide/Findings/findings_overview.html), which will end in a number.  **Note:** Many API endpoints require a JSON body in the request. Most JSON will contain double-quotes (`\"`) and spaces, which have special meaning when used on the command line. In order to ensure your JSON body is interpreted as a single argument, you must <a href=\"https://en.wikipedia.org/wiki/Escape_character\" target=\"_blank\">escape</a> it properly. For example, if you wanted to `POST` the following JSON body:  ```{ \"name\": \"John Doe\" }```  You would put a backslash (`\\`) before each double-quote (`\"`), and surround the whole thing with double-quotes:  ```\"{ \\\"name\\\": \\\"John Doe\\\" }\"```  The outermost double-quotes tell the command-line interpreter that everything within them is to be treated as a single argument (as opposed to the usual space-separated behavior). The backslash before each inner double-quote tells the command-line interpreter that you mean the literal double-quote character, and not the end of the quoted argument.  In many *non-Windows* operating systems, you can also use a single-quote (`'`) to surround the argument, and skip the backslashes:  ```'{ \"name\": \"John Doe\" }'```  The examples below will use the double-quotes and backslashes style, as it works on most (if not all) operating systems.  ### Running an Analysis  To start an analysis, you can run  ```curl -F file1=@src.zip -H \"API-Key: api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24\" https://<yoursrmserver>/srm/api/projects/<project id>/analysis```  Make sure you use your own values for the `src.zip` file, the API Key, the hostname for your Software Risk Manager server, and the project id.  ### Retrieving Finding Data  There is a wide variety of data available for the findings of a project after running an analysis. Two examples are provided here.  ### Findings Table Data  You can retrieve the data that's used to populate the [findings table](../user_guide/Findings/findings_table.html):  ```curl -H \"Content-Type: application/json\" -X POST -d \"{\\\"filter\\\":{},\\\"sort\\\":{\\\"by\\\":\\\"id\\\",\\\"direction\\\":\\\"ascending\\\"},\\\"pagination\\\":{\\\"page\\\":1,\\\"perPage\\\":10}}\" -H \"API-Key: api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24\" https://<yoursrmserver>/srm/api/projects/<project id>/findings/table```  Additional information about how to construct more useful filter and sort requests can be found in the documentation.  ### Finding Metadata  You can retrieve metadata for a finding, if you know the finding ID. You can take the ID for a finding from the Findings Table:  ```curl -H \"API-Key: api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24\" https://<yoursrmserver>/srm/api/findings/<finding id>```  ### Generating a Report  You can use the API to generate a PDF [report](../user_guide/Findings/generate_report.html).  ```curl -H \"Content-Type: application/json\" -X POST -d \"{\\\"filter\\\":{},\\\"config\\\":{\\\"summaryMode\\\":\\\"simple\\\",\\\"detailsMode\\\":\\\"simple\\\",\\\"includeResultDetails\\\":true,\\\"includeComments\\\":false}}\" -H \"API-Key: api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24\" https://<yoursrmserver>/srm/api/projects/<project id>/report/pdf```  ## Generating a Client SDK  If you require a client SDK for Software Risk Manager, you can generate one using [OpenAPI Generator](https://openapi-generator.tech/). Detailed instructions are available on the [GitHub page](https://github.com/OpenAPITools/openapi-generator) and our OpenAPI spec can be found [here](swagger/swagger.json). 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.codedx.client.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.codedx.client.model.FormStateExpression;
import com.codedx.client.model.InputFieldOptionsProvider;
import com.codedx.client.model.InputFieldWidthRatio;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.codedx.client.JSON;


/**
 * InputField
 */
@JsonPropertyOrder({
  InputField.JSON_PROPERTY_TYPE,
  InputField.JSON_PROPERTY_DEFAULT_VALUE,
  InputField.JSON_PROPERTY_LABEL,
  InputField.JSON_PROPERTY_PLACEHOLDER,
  InputField.JSON_PROPERTY_DESCRIPTION,
  InputField.JSON_PROPERTY_WIDTH_RATIO,
  InputField.JSON_PROPERTY_HIDDEN_UNLESS,
  InputField.JSON_PROPERTY_SECTION_HEADER,
  InputField.JSON_PROPERTY_SHOULD_TRIM,
  InputField.JSON_PROPERTY_OPTIONS_PROVIDER,
  InputField.JSON_PROPERTY_CHECKBOX_LABEL,
  InputField.JSON_PROPERTY_DROPDOWN_LABEL
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-02T11:55:06.722228-04:00[America/New_York]", comments = "Generator version: 7.21.0")
public class InputField {
  /**
   * Gets or Sets type
   */
  public enum TypeEnum {
    URL(String.valueOf("url")),
    
    TEXT(String.valueOf("text")),
    
    CREDENTIAL(String.valueOf("credential")),
    
    CHECKBOX(String.valueOf("checkbox")),
    
    DROPDOWN(String.valueOf("dropdown")),
    
    OPTIONAL_DROPDOWN(String.valueOf("optional-dropdown")),
    
    MULTISELECT(String.valueOf("multiselect")),
    
    OPTIONAL_MULTISELECT(String.valueOf("optional-multiselect")),
    
    TIME_INTERVAL(String.valueOf("time-interval")),
    
    DATE_INTERVAL(String.valueOf("date-interval")),
    
    CREDENTIAL_FILE(String.valueOf("credential-file"));

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TYPE = "type";
  @jakarta.annotation.Nonnull
  private TypeEnum type;

  public static final String JSON_PROPERTY_DEFAULT_VALUE = "defaultValue";
  private JsonNullable<Object> defaultValue = JsonNullable.<Object>of(null);

  public static final String JSON_PROPERTY_LABEL = "label";
  private JsonNullable<String> label = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_PLACEHOLDER = "placeholder";
  private JsonNullable<String> placeholder = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  private JsonNullable<String> description = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_WIDTH_RATIO = "widthRatio";
  private JsonNullable<InputFieldWidthRatio> widthRatio = JsonNullable.<InputFieldWidthRatio>undefined();

  public static final String JSON_PROPERTY_HIDDEN_UNLESS = "hiddenUnless";
  @jakarta.annotation.Nullable
  private FormStateExpression hiddenUnless;

  public static final String JSON_PROPERTY_SECTION_HEADER = "sectionHeader";
  private JsonNullable<String> sectionHeader = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_SHOULD_TRIM = "shouldTrim";
  @jakarta.annotation.Nullable
  private Boolean shouldTrim;

  public static final String JSON_PROPERTY_OPTIONS_PROVIDER = "optionsProvider";
  @jakarta.annotation.Nullable
  private InputFieldOptionsProvider optionsProvider;

  public static final String JSON_PROPERTY_CHECKBOX_LABEL = "checkboxLabel";
  @jakarta.annotation.Nullable
  private String checkboxLabel;

  public static final String JSON_PROPERTY_DROPDOWN_LABEL = "dropdownLabel";
  private JsonNullable<String> dropdownLabel = JsonNullable.<String>undefined();

  public InputField() { 
  }

  public InputField type(@jakarta.annotation.Nonnull TypeEnum type) {
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public TypeEnum getType() {
    return type;
  }


  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType(@jakarta.annotation.Nonnull TypeEnum type) {
    this.type = type;
  }


  public InputField defaultValue(@jakarta.annotation.Nullable Object defaultValue) {
    this.defaultValue = JsonNullable.<Object>of(defaultValue);
    return this;
  }

  /**
   * The default value for this input. The shape of this value will depend on this input&#39;s &#x60;type&#x60;, and may be null if no default is available.
   * @return defaultValue
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Object getDefaultValue() {
        return defaultValue.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_DEFAULT_VALUE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Object> getDefaultValue_JsonNullable() {
    return defaultValue;
  }
  
  @JsonProperty(JSON_PROPERTY_DEFAULT_VALUE)
  public void setDefaultValue_JsonNullable(JsonNullable<Object> defaultValue) {
    this.defaultValue = defaultValue;
  }

  public void setDefaultValue(@jakarta.annotation.Nullable Object defaultValue) {
    this.defaultValue = JsonNullable.<Object>of(defaultValue);
  }


  public InputField label(@jakarta.annotation.Nullable String label) {
    this.label = JsonNullable.<String>of(label);
    return this;
  }

  /**
   * A label for this field, or null if none is provided
   * @return label
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getLabel() {
        return label.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_LABEL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getLabel_JsonNullable() {
    return label;
  }
  
  @JsonProperty(JSON_PROPERTY_LABEL)
  public void setLabel_JsonNullable(JsonNullable<String> label) {
    this.label = label;
  }

  public void setLabel(@jakarta.annotation.Nullable String label) {
    this.label = JsonNullable.<String>of(label);
  }


  public InputField placeholder(@jakarta.annotation.Nullable String placeholder) {
    this.placeholder = JsonNullable.<String>of(placeholder);
    return this;
  }

  /**
   * Placeholder text for &#39;url&#39;, &#39;text&#39;, and &#39;credential&#39; inputs. Omitted with other types. May be null.
   * @return placeholder
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getPlaceholder() {
        return placeholder.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_PLACEHOLDER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getPlaceholder_JsonNullable() {
    return placeholder;
  }
  
  @JsonProperty(JSON_PROPERTY_PLACEHOLDER)
  public void setPlaceholder_JsonNullable(JsonNullable<String> placeholder) {
    this.placeholder = placeholder;
  }

  public void setPlaceholder(@jakarta.annotation.Nullable String placeholder) {
    this.placeholder = JsonNullable.<String>of(placeholder);
  }


  public InputField description(@jakarta.annotation.Nullable String description) {
    this.description = JsonNullable.<String>of(description);
    return this;
  }

  /**
   * A longer description for this field, typically accompanying the &#39;label&#39;, or null if none is provided
   * @return description
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getDescription() {
        return description.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getDescription_JsonNullable() {
    return description;
  }
  
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  public void setDescription_JsonNullable(JsonNullable<String> description) {
    this.description = description;
  }

  public void setDescription(@jakarta.annotation.Nullable String description) {
    this.description = JsonNullable.<String>of(description);
  }


  public InputField widthRatio(@jakarta.annotation.Nullable InputFieldWidthRatio widthRatio) {
    this.widthRatio = JsonNullable.<InputFieldWidthRatio>of(widthRatio);
    return this;
  }

  /**
   * Get widthRatio
   * @return widthRatio
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public InputFieldWidthRatio getWidthRatio() {
        return widthRatio.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_WIDTH_RATIO, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<InputFieldWidthRatio> getWidthRatio_JsonNullable() {
    return widthRatio;
  }
  
  @JsonProperty(JSON_PROPERTY_WIDTH_RATIO)
  public void setWidthRatio_JsonNullable(JsonNullable<InputFieldWidthRatio> widthRatio) {
    this.widthRatio = widthRatio;
  }

  public void setWidthRatio(@jakarta.annotation.Nullable InputFieldWidthRatio widthRatio) {
    this.widthRatio = JsonNullable.<InputFieldWidthRatio>of(widthRatio);
  }


  public InputField hiddenUnless(@jakarta.annotation.Nullable FormStateExpression hiddenUnless) {
    this.hiddenUnless = hiddenUnless;
    return this;
  }

  /**
   * Get hiddenUnless
   * @return hiddenUnless
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_HIDDEN_UNLESS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public FormStateExpression getHiddenUnless() {
    return hiddenUnless;
  }


  @JsonProperty(value = JSON_PROPERTY_HIDDEN_UNLESS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHiddenUnless(@jakarta.annotation.Nullable FormStateExpression hiddenUnless) {
    this.hiddenUnless = hiddenUnless;
  }


  public InputField sectionHeader(@jakarta.annotation.Nullable String sectionHeader) {
    this.sectionHeader = JsonNullable.<String>of(sectionHeader);
    return this;
  }

  /**
   * An optional string representing a header above a &#39;section&#39; that this field should appear under. May be null.
   * @return sectionHeader
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getSectionHeader() {
        return sectionHeader.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_SECTION_HEADER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getSectionHeader_JsonNullable() {
    return sectionHeader;
  }
  
  @JsonProperty(JSON_PROPERTY_SECTION_HEADER)
  public void setSectionHeader_JsonNullable(JsonNullable<String> sectionHeader) {
    this.sectionHeader = sectionHeader;
  }

  public void setSectionHeader(@jakarta.annotation.Nullable String sectionHeader) {
    this.sectionHeader = JsonNullable.<String>of(sectionHeader);
  }


  public InputField shouldTrim(@jakarta.annotation.Nullable Boolean shouldTrim) {
    this.shouldTrim = shouldTrim;
    return this;
  }

  /**
   * Used with &#39;text&#39; and &#39;credential&#39; inputs, indicating whether the raw user input should be trimmed of leading and trailing whitespace
   * @return shouldTrim
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SHOULD_TRIM, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getShouldTrim() {
    return shouldTrim;
  }


  @JsonProperty(value = JSON_PROPERTY_SHOULD_TRIM, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setShouldTrim(@jakarta.annotation.Nullable Boolean shouldTrim) {
    this.shouldTrim = shouldTrim;
  }


  public InputField optionsProvider(@jakarta.annotation.Nullable InputFieldOptionsProvider optionsProvider) {
    this.optionsProvider = optionsProvider;
    return this;
  }

  /**
   * Get optionsProvider
   * @return optionsProvider
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_OPTIONS_PROVIDER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public InputFieldOptionsProvider getOptionsProvider() {
    return optionsProvider;
  }


  @JsonProperty(value = JSON_PROPERTY_OPTIONS_PROVIDER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOptionsProvider(@jakarta.annotation.Nullable InputFieldOptionsProvider optionsProvider) {
    this.optionsProvider = optionsProvider;
  }


  public InputField checkboxLabel(@jakarta.annotation.Nullable String checkboxLabel) {
    this.checkboxLabel = checkboxLabel;
    return this;
  }

  /**
   * A label for the checkbox used in &#39;optional-dropdown&#39; and &#39;optional-multiselect&#39; fields
   * @return checkboxLabel
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CHECKBOX_LABEL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCheckboxLabel() {
    return checkboxLabel;
  }


  @JsonProperty(value = JSON_PROPERTY_CHECKBOX_LABEL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCheckboxLabel(@jakarta.annotation.Nullable String checkboxLabel) {
    this.checkboxLabel = checkboxLabel;
  }


  public InputField dropdownLabel(@jakarta.annotation.Nullable String dropdownLabel) {
    this.dropdownLabel = JsonNullable.<String>of(dropdownLabel);
    return this;
  }

  /**
   * A separate label to be shown with the underlying dropdown control in &#39;optional-dropdown&#39; and &#39;optional-multiselect&#39; fields
   * @return dropdownLabel
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getDropdownLabel() {
        return dropdownLabel.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_DROPDOWN_LABEL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getDropdownLabel_JsonNullable() {
    return dropdownLabel;
  }
  
  @JsonProperty(JSON_PROPERTY_DROPDOWN_LABEL)
  public void setDropdownLabel_JsonNullable(JsonNullable<String> dropdownLabel) {
    this.dropdownLabel = dropdownLabel;
  }

  public void setDropdownLabel(@jakarta.annotation.Nullable String dropdownLabel) {
    this.dropdownLabel = JsonNullable.<String>of(dropdownLabel);
  }


  /**
   * Return true if this InputField object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InputField inputField = (InputField) o;
    return Objects.equals(this.type, inputField.type) &&
        equalsNullable(this.defaultValue, inputField.defaultValue) &&
        equalsNullable(this.label, inputField.label) &&
        equalsNullable(this.placeholder, inputField.placeholder) &&
        equalsNullable(this.description, inputField.description) &&
        equalsNullable(this.widthRatio, inputField.widthRatio) &&
        Objects.equals(this.hiddenUnless, inputField.hiddenUnless) &&
        equalsNullable(this.sectionHeader, inputField.sectionHeader) &&
        Objects.equals(this.shouldTrim, inputField.shouldTrim) &&
        Objects.equals(this.optionsProvider, inputField.optionsProvider) &&
        Objects.equals(this.checkboxLabel, inputField.checkboxLabel) &&
        equalsNullable(this.dropdownLabel, inputField.dropdownLabel);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, hashCodeNullable(defaultValue), hashCodeNullable(label), hashCodeNullable(placeholder), hashCodeNullable(description), hashCodeNullable(widthRatio), hiddenUnless, hashCodeNullable(sectionHeader), shouldTrim, optionsProvider, checkboxLabel, hashCodeNullable(dropdownLabel));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InputField {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    defaultValue: ").append(toIndentedString(defaultValue)).append("\n");
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("    placeholder: ").append(toIndentedString(placeholder)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    widthRatio: ").append(toIndentedString(widthRatio)).append("\n");
    sb.append("    hiddenUnless: ").append(toIndentedString(hiddenUnless)).append("\n");
    sb.append("    sectionHeader: ").append(toIndentedString(sectionHeader)).append("\n");
    sb.append("    shouldTrim: ").append(toIndentedString(shouldTrim)).append("\n");
    sb.append("    optionsProvider: ").append(toIndentedString(optionsProvider)).append("\n");
    sb.append("    checkboxLabel: ").append(toIndentedString(checkboxLabel)).append("\n");
    sb.append("    dropdownLabel: ").append(toIndentedString(dropdownLabel)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

