/*
 * Software Risk Manager API Guide
 * Software Risk Manager provides a variety of REST APIs, allowing external applications and scripts to interface with core functionality. This guide documents the various REST resources provided by Software Risk Manager.  ## Authentication  Authentication is a requirement when accessing API endpoints. There are two methods by which authentication may be performed.  ### API Keys  The primary method for authentication is passing an `API-Key` header containing a valid API key with all requests, i.e.  `API-Key: <key goes here>`  API Keys come in two possible forms:   - `api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24` - latest format  - `550e8400-e29b-41d4-a716-44665544000` - legacy format  For example:  `API-Key: api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24`  `API-Key: 550e8400-e29b-41d4-a716-44665544000`  API keys may be generated by Software Risk Manager admins. Once they are generated, in most cases, they behave like regular users. They will need to be assigned user roles for any projects they will be used with. Although it is possible to assign the *admin* [role](../user_guide/Project-Management/user_role_configuration.html) to an API key, the recommendation is to avoid doing so unless absolutely necessary.  See the user guide for an overview about how to create and manage [API keys](../user_guide/Settings/api_keys_administration.html).  ### Personal Access Tokens  Personal Access Tokens can be used as [bearer tokens](https://swagger.io/docs/specification/authentication/bearer-authentication/), e.g.  `Authorization: Bearer secret-token:qRuXr1BqgoTWXNxUhYQ8H_Yl2zfy6vxuqMIRnkGO`  Personal Access Tokens can be created by any user, and represent a subset of that user's permissions.   ### HTTP Basic Authentication  HTTP Basic authentication may be used to authenticate with the API as a regular user. This is accomplished by including an `Authorization` header containing a typical authorization credential.  ## Error Handling  ### Bad Requests  For API calls that accept input, invalid values will trigger an HTTP 400 Bad Request status code.  ### Server Errors  For any API call, if an unexpected error occurs, an HTTP 500 Internal Server Error status code will be returned. If an error message is available, the response will include a basic message body describing the error:  ` {   \"error\": \"error message\" } `  The error property will contain a string message indicating the nature of the error.  ### Errors with Third-Party Applications  Sometimes Software Risk Manager must communicate with third-party applications like JIRA, Git, and certain enterprise tools. Some users may have in-house versions of these with self-signed certificates which may not be \"trusted\". In these cases, the API will respond with an HTTP 502 BAD GATEWAY status. If this happens, refer to [Trusting Certificates](../install_guide/Installation/trusting-certs.html) in the install guide.  ### API Unavailable  In special circumstances, particularly during the installation and update phases, the API will be unavailable. When the API is unavailable, all calls will return an HTTP 503 Service Unavailable status, and no actions or side effects will occur as a result of the calls.  ## Examples  Software Risk Manager's API uses REST over HTTP. As such, you can use any language/utility that supports making HTTP requests to interact with the API. The examples below use <a href=\"https://curl.haxx.se/\" target=\"_blank\">curl</a>, a popular command-line utility, to do so.  First, you'll need to [generate an API Key](../user_guide/Settings/api_keys_administration.html). Second, while you can create projects through the API, these examples will assume that you've already created one. You'll need to know its project id number, which you can find by looking at the URL for the [Findings Page](../user_guide/Findings/findings_overview.html), which will end in a number.  **Note:** Many API endpoints require a JSON body in the request. Most JSON will contain double-quotes (`\"`) and spaces, which have special meaning when used on the command line. In order to ensure your JSON body is interpreted as a single argument, you must <a href=\"https://en.wikipedia.org/wiki/Escape_character\" target=\"_blank\">escape</a> it properly. For example, if you wanted to `POST` the following JSON body:  ```{ \"name\": \"John Doe\" }```  You would put a backslash (`\\`) before each double-quote (`\"`), and surround the whole thing with double-quotes:  ```\"{ \\\"name\\\": \\\"John Doe\\\" }\"```  The outermost double-quotes tell the command-line interpreter that everything within them is to be treated as a single argument (as opposed to the usual space-separated behavior). The backslash before each inner double-quote tells the command-line interpreter that you mean the literal double-quote character, and not the end of the quoted argument.  In many *non-Windows* operating systems, you can also use a single-quote (`'`) to surround the argument, and skip the backslashes:  ```'{ \"name\": \"John Doe\" }'```  The examples below will use the double-quotes and backslashes style, as it works on most (if not all) operating systems.  ### Running an Analysis  To start an analysis, you can run  ```curl -F file1=@src.zip -H \"API-Key: api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24\" https://<yoursrmserver>/srm/api/projects/<project id>/analysis```  Make sure you use your own values for the `src.zip` file, the API Key, the hostname for your Software Risk Manager server, and the project id.  ### Retrieving Finding Data  There is a wide variety of data available for the findings of a project after running an analysis. Two examples are provided here.  ### Findings Table Data  You can retrieve the data that's used to populate the [findings table](../user_guide/Findings/findings_table.html):  ```curl -H \"Content-Type: application/json\" -X POST -d \"{\\\"filter\\\":{},\\\"sort\\\":{\\\"by\\\":\\\"id\\\",\\\"direction\\\":\\\"ascending\\\"},\\\"pagination\\\":{\\\"page\\\":1,\\\"perPage\\\":10}}\" -H \"API-Key: api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24\" https://<yoursrmserver>/srm/api/projects/<project id>/findings/table```  Additional information about how to construct more useful filter and sort requests can be found in the documentation.  ### Finding Metadata  You can retrieve metadata for a finding, if you know the finding ID. You can take the ID for a finding from the Findings Table:  ```curl -H \"API-Key: api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24\" https://<yoursrmserver>/srm/api/findings/<finding id>```  ### Generating a Report  You can use the API to generate a PDF [report](../user_guide/Findings/generate_report.html).  ```curl -H \"Content-Type: application/json\" -X POST -d \"{\\\"filter\\\":{},\\\"config\\\":{\\\"summaryMode\\\":\\\"simple\\\",\\\"detailsMode\\\":\\\"simple\\\",\\\"includeResultDetails\\\":true,\\\"includeComments\\\":false}}\" -H \"API-Key: api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24\" https://<yoursrmserver>/srm/api/projects/<project id>/report/pdf```  ## Generating a Client SDK  If you require a client SDK for Software Risk Manager, you can generate one using [OpenAPI Generator](https://openapi-generator.tech/). Detailed instructions are available on the [GitHub page](https://github.com/OpenAPITools/openapi-generator) and our OpenAPI spec can be found [here](swagger/swagger.json). 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.codedx.client.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.codedx.client.model.AutoCreateConfig;
import com.codedx.client.model.FieldMappingInner;
import com.codedx.client.model.IssueTrackerConfigPassword;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.codedx.client.JSON;


/**
 * IssueTrackerConfigurationPost
 */
@JsonPropertyOrder({
  IssueTrackerConfigurationPost.JSON_PROPERTY_AUTO_CREATE_CONFIG,
  IssueTrackerConfigurationPost.JSON_PROPERTY_AUTO_CREATE_ENABLED,
  IssueTrackerConfigurationPost.JSON_PROPERTY_CODE_DX_FIELD_MAPPING,
  IssueTrackerConfigurationPost.JSON_PROPERTY_FIELD_MAPPING,
  IssueTrackerConfigurationPost.JSON_PROPERTY_USERNAME,
  IssueTrackerConfigurationPost.JSON_PROPERTY_PASSWORD,
  IssueTrackerConfigurationPost.JSON_PROPERTY_PROJECT_KEY,
  IssueTrackerConfigurationPost.JSON_PROPERTY_REFRESH_INTERVAL,
  IssueTrackerConfigurationPost.JSON_PROPERTY_STATUS_MAPPING,
  IssueTrackerConfigurationPost.JSON_PROPERTY_STATUS_MAPPING_ENABLED,
  IssueTrackerConfigurationPost.JSON_PROPERTY_TRACKER_TYPE,
  IssueTrackerConfigurationPost.JSON_PROPERTY_URL,
  IssueTrackerConfigurationPost.JSON_PROPERTY_AUTH_TYPE,
  IssueTrackerConfigurationPost.JSON_PROPERTY_HOST_AND_PATH
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-02T11:55:06.722228-04:00[America/New_York]", comments = "Generator version: 7.21.0")
public class IssueTrackerConfigurationPost {
  public static final String JSON_PROPERTY_AUTO_CREATE_CONFIG = "autoCreateConfig";
  @jakarta.annotation.Nullable
  private AutoCreateConfig autoCreateConfig;

  public static final String JSON_PROPERTY_AUTO_CREATE_ENABLED = "autoCreateEnabled";
  @jakarta.annotation.Nullable
  private Boolean autoCreateEnabled;

  public static final String JSON_PROPERTY_CODE_DX_FIELD_MAPPING = "codeDxFieldMapping";
  @jakarta.annotation.Nullable
  private Map<String, String> codeDxFieldMapping = new HashMap<>();

  public static final String JSON_PROPERTY_FIELD_MAPPING = "fieldMapping";
  @jakarta.annotation.Nullable
  private List<FieldMappingInner> fieldMapping = new ArrayList<>();

  public static final String JSON_PROPERTY_USERNAME = "username";
  @jakarta.annotation.Nullable
  private String username;

  public static final String JSON_PROPERTY_PASSWORD = "password";
  @jakarta.annotation.Nullable
  private IssueTrackerConfigPassword password;

  public static final String JSON_PROPERTY_PROJECT_KEY = "projectKey";
  @jakarta.annotation.Nullable
  private String projectKey;

  public static final String JSON_PROPERTY_REFRESH_INTERVAL = "refreshInterval";
  @jakarta.annotation.Nullable
  private Integer refreshInterval;

  public static final String JSON_PROPERTY_STATUS_MAPPING = "statusMapping";
  @jakarta.annotation.Nullable
  private Map<String, String> statusMapping = new HashMap<>();

  public static final String JSON_PROPERTY_STATUS_MAPPING_ENABLED = "statusMappingEnabled";
  @jakarta.annotation.Nullable
  private Boolean statusMappingEnabled;

  public static final String JSON_PROPERTY_TRACKER_TYPE = "trackerType";
  @jakarta.annotation.Nullable
  private String trackerType;

  public static final String JSON_PROPERTY_URL = "url";
  @jakarta.annotation.Nullable
  private String url;

  public static final String JSON_PROPERTY_AUTH_TYPE = "authType";
  @jakarta.annotation.Nullable
  private String authType;

  public static final String JSON_PROPERTY_HOST_AND_PATH = "hostAndPath";
  @jakarta.annotation.Nullable
  private String hostAndPath;

  public IssueTrackerConfigurationPost() { 
  }

  public IssueTrackerConfigurationPost autoCreateConfig(@jakarta.annotation.Nullable AutoCreateConfig autoCreateConfig) {
    this.autoCreateConfig = autoCreateConfig;
    return this;
  }

  /**
   * Get autoCreateConfig
   * @return autoCreateConfig
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_AUTO_CREATE_CONFIG, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AutoCreateConfig getAutoCreateConfig() {
    return autoCreateConfig;
  }


  @JsonProperty(value = JSON_PROPERTY_AUTO_CREATE_CONFIG, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAutoCreateConfig(@jakarta.annotation.Nullable AutoCreateConfig autoCreateConfig) {
    this.autoCreateConfig = autoCreateConfig;
  }


  public IssueTrackerConfigurationPost autoCreateEnabled(@jakarta.annotation.Nullable Boolean autoCreateEnabled) {
    this.autoCreateEnabled = autoCreateEnabled;
    return this;
  }

  /**
   * Get autoCreateEnabled
   * @return autoCreateEnabled
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_AUTO_CREATE_ENABLED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getAutoCreateEnabled() {
    return autoCreateEnabled;
  }


  @JsonProperty(value = JSON_PROPERTY_AUTO_CREATE_ENABLED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAutoCreateEnabled(@jakarta.annotation.Nullable Boolean autoCreateEnabled) {
    this.autoCreateEnabled = autoCreateEnabled;
  }


  public IssueTrackerConfigurationPost codeDxFieldMapping(@jakarta.annotation.Nullable Map<String, String> codeDxFieldMapping) {
    this.codeDxFieldMapping = codeDxFieldMapping;
    return this;
  }

  public IssueTrackerConfigurationPost putCodeDxFieldMappingItem(String key, String codeDxFieldMappingItem) {
    if (this.codeDxFieldMapping == null) {
      this.codeDxFieldMapping = new HashMap<>();
    }
    this.codeDxFieldMapping.put(key, codeDxFieldMappingItem);
    return this;
  }

  /**
   * Get codeDxFieldMapping
   * @return codeDxFieldMapping
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CODE_DX_FIELD_MAPPING, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, String> getCodeDxFieldMapping() {
    return codeDxFieldMapping;
  }


  @JsonProperty(value = JSON_PROPERTY_CODE_DX_FIELD_MAPPING, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCodeDxFieldMapping(@jakarta.annotation.Nullable Map<String, String> codeDxFieldMapping) {
    this.codeDxFieldMapping = codeDxFieldMapping;
  }


  public IssueTrackerConfigurationPost fieldMapping(@jakarta.annotation.Nullable List<FieldMappingInner> fieldMapping) {
    this.fieldMapping = fieldMapping;
    return this;
  }

  public IssueTrackerConfigurationPost addFieldMappingItem(FieldMappingInner fieldMappingItem) {
    if (this.fieldMapping == null) {
      this.fieldMapping = new ArrayList<>();
    }
    this.fieldMapping.add(fieldMappingItem);
    return this;
  }

  /**
   * Get fieldMapping
   * @return fieldMapping
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FIELD_MAPPING, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<FieldMappingInner> getFieldMapping() {
    return fieldMapping;
  }


  @JsonProperty(value = JSON_PROPERTY_FIELD_MAPPING, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFieldMapping(@jakarta.annotation.Nullable List<FieldMappingInner> fieldMapping) {
    this.fieldMapping = fieldMapping;
  }


  public IssueTrackerConfigurationPost username(@jakarta.annotation.Nullable String username) {
    this.username = username;
    return this;
  }

  /**
   * Get username
   * @return username
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_USERNAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUsername() {
    return username;
  }


  @JsonProperty(value = JSON_PROPERTY_USERNAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUsername(@jakarta.annotation.Nullable String username) {
    this.username = username;
  }


  public IssueTrackerConfigurationPost password(@jakarta.annotation.Nullable IssueTrackerConfigPassword password) {
    this.password = password;
    return this;
  }

  /**
   * Get password
   * @return password
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PASSWORD, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public IssueTrackerConfigPassword getPassword() {
    return password;
  }


  @JsonProperty(value = JSON_PROPERTY_PASSWORD, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPassword(@jakarta.annotation.Nullable IssueTrackerConfigPassword password) {
    this.password = password;
  }


  public IssueTrackerConfigurationPost projectKey(@jakarta.annotation.Nullable String projectKey) {
    this.projectKey = projectKey;
    return this;
  }

  /**
   * Get projectKey
   * @return projectKey
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PROJECT_KEY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getProjectKey() {
    return projectKey;
  }


  @JsonProperty(value = JSON_PROPERTY_PROJECT_KEY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProjectKey(@jakarta.annotation.Nullable String projectKey) {
    this.projectKey = projectKey;
  }


  public IssueTrackerConfigurationPost refreshInterval(@jakarta.annotation.Nullable Integer refreshInterval) {
    this.refreshInterval = refreshInterval;
    return this;
  }

  /**
   * Get refreshInterval
   * @return refreshInterval
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_REFRESH_INTERVAL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getRefreshInterval() {
    return refreshInterval;
  }


  @JsonProperty(value = JSON_PROPERTY_REFRESH_INTERVAL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRefreshInterval(@jakarta.annotation.Nullable Integer refreshInterval) {
    this.refreshInterval = refreshInterval;
  }


  public IssueTrackerConfigurationPost statusMapping(@jakarta.annotation.Nullable Map<String, String> statusMapping) {
    this.statusMapping = statusMapping;
    return this;
  }

  public IssueTrackerConfigurationPost putStatusMappingItem(String key, String statusMappingItem) {
    if (this.statusMapping == null) {
      this.statusMapping = new HashMap<>();
    }
    this.statusMapping.put(key, statusMappingItem);
    return this;
  }

  /**
   * Get statusMapping
   * @return statusMapping
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_STATUS_MAPPING, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, String> getStatusMapping() {
    return statusMapping;
  }


  @JsonProperty(value = JSON_PROPERTY_STATUS_MAPPING, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatusMapping(@jakarta.annotation.Nullable Map<String, String> statusMapping) {
    this.statusMapping = statusMapping;
  }


  public IssueTrackerConfigurationPost statusMappingEnabled(@jakarta.annotation.Nullable Boolean statusMappingEnabled) {
    this.statusMappingEnabled = statusMappingEnabled;
    return this;
  }

  /**
   * Get statusMappingEnabled
   * @return statusMappingEnabled
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_STATUS_MAPPING_ENABLED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getStatusMappingEnabled() {
    return statusMappingEnabled;
  }


  @JsonProperty(value = JSON_PROPERTY_STATUS_MAPPING_ENABLED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatusMappingEnabled(@jakarta.annotation.Nullable Boolean statusMappingEnabled) {
    this.statusMappingEnabled = statusMappingEnabled;
  }


  public IssueTrackerConfigurationPost trackerType(@jakarta.annotation.Nullable String trackerType) {
    this.trackerType = trackerType;
    return this;
  }

  /**
   * Can be \&quot;jira\&quot;, \&quot;servicenow\&quot;, \&quot;gitlab\&quot;, or \&quot;azure\&quot;
   * @return trackerType
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TRACKER_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTrackerType() {
    return trackerType;
  }


  @JsonProperty(value = JSON_PROPERTY_TRACKER_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTrackerType(@jakarta.annotation.Nullable String trackerType) {
    this.trackerType = trackerType;
  }


  public IssueTrackerConfigurationPost url(@jakarta.annotation.Nullable String url) {
    this.url = url;
    return this;
  }

  /**
   * Get url
   * @return url
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_URL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUrl() {
    return url;
  }


  @JsonProperty(value = JSON_PROPERTY_URL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUrl(@jakarta.annotation.Nullable String url) {
    this.url = url;
  }


  public IssueTrackerConfigurationPost authType(@jakarta.annotation.Nullable String authType) {
    this.authType = authType;
    return this;
  }

  /**
   * Get authType
   * @return authType
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_AUTH_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAuthType() {
    return authType;
  }


  @JsonProperty(value = JSON_PROPERTY_AUTH_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAuthType(@jakarta.annotation.Nullable String authType) {
    this.authType = authType;
  }


  public IssueTrackerConfigurationPost hostAndPath(@jakarta.annotation.Nullable String hostAndPath) {
    this.hostAndPath = hostAndPath;
    return this;
  }

  /**
   * Get hostAndPath
   * @return hostAndPath
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_HOST_AND_PATH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getHostAndPath() {
    return hostAndPath;
  }


  @JsonProperty(value = JSON_PROPERTY_HOST_AND_PATH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHostAndPath(@jakarta.annotation.Nullable String hostAndPath) {
    this.hostAndPath = hostAndPath;
  }


  /**
   * Return true if this IssueTrackerConfigurationPost object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IssueTrackerConfigurationPost issueTrackerConfigurationPost = (IssueTrackerConfigurationPost) o;
    return Objects.equals(this.autoCreateConfig, issueTrackerConfigurationPost.autoCreateConfig) &&
        Objects.equals(this.autoCreateEnabled, issueTrackerConfigurationPost.autoCreateEnabled) &&
        Objects.equals(this.codeDxFieldMapping, issueTrackerConfigurationPost.codeDxFieldMapping) &&
        Objects.equals(this.fieldMapping, issueTrackerConfigurationPost.fieldMapping) &&
        Objects.equals(this.username, issueTrackerConfigurationPost.username) &&
        Objects.equals(this.password, issueTrackerConfigurationPost.password) &&
        Objects.equals(this.projectKey, issueTrackerConfigurationPost.projectKey) &&
        Objects.equals(this.refreshInterval, issueTrackerConfigurationPost.refreshInterval) &&
        Objects.equals(this.statusMapping, issueTrackerConfigurationPost.statusMapping) &&
        Objects.equals(this.statusMappingEnabled, issueTrackerConfigurationPost.statusMappingEnabled) &&
        Objects.equals(this.trackerType, issueTrackerConfigurationPost.trackerType) &&
        Objects.equals(this.url, issueTrackerConfigurationPost.url) &&
        Objects.equals(this.authType, issueTrackerConfigurationPost.authType) &&
        Objects.equals(this.hostAndPath, issueTrackerConfigurationPost.hostAndPath);
  }

  @Override
  public int hashCode() {
    return Objects.hash(autoCreateConfig, autoCreateEnabled, codeDxFieldMapping, fieldMapping, username, password, projectKey, refreshInterval, statusMapping, statusMappingEnabled, trackerType, url, authType, hostAndPath);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IssueTrackerConfigurationPost {\n");
    sb.append("    autoCreateConfig: ").append(toIndentedString(autoCreateConfig)).append("\n");
    sb.append("    autoCreateEnabled: ").append(toIndentedString(autoCreateEnabled)).append("\n");
    sb.append("    codeDxFieldMapping: ").append(toIndentedString(codeDxFieldMapping)).append("\n");
    sb.append("    fieldMapping: ").append(toIndentedString(fieldMapping)).append("\n");
    sb.append("    username: ").append(toIndentedString(username)).append("\n");
    sb.append("    password: ").append(toIndentedString(password)).append("\n");
    sb.append("    projectKey: ").append(toIndentedString(projectKey)).append("\n");
    sb.append("    refreshInterval: ").append(toIndentedString(refreshInterval)).append("\n");
    sb.append("    statusMapping: ").append(toIndentedString(statusMapping)).append("\n");
    sb.append("    statusMappingEnabled: ").append(toIndentedString(statusMappingEnabled)).append("\n");
    sb.append("    trackerType: ").append(toIndentedString(trackerType)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    authType: ").append(toIndentedString(authType)).append("\n");
    sb.append("    hostAndPath: ").append(toIndentedString(hostAndPath)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

