/*
 * Software Risk Manager API Guide
 * Software Risk Manager provides a variety of REST APIs, allowing external applications and scripts to interface with core functionality. This guide documents the various REST resources provided by Software Risk Manager.  ## Authentication  Authentication is a requirement when accessing API endpoints. There are two methods by which authentication may be performed.  ### API Keys  The primary method for authentication is passing an `API-Key` header containing a valid API key with all requests, i.e.  `API-Key: <key goes here>`  API Keys come in two possible forms:   - `api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24` - latest format  - `550e8400-e29b-41d4-a716-44665544000` - legacy format  For example:  `API-Key: api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24`  `API-Key: 550e8400-e29b-41d4-a716-44665544000`  API keys may be generated by Software Risk Manager admins. Once they are generated, in most cases, they behave like regular users. They will need to be assigned user roles for any projects they will be used with. Although it is possible to assign the *admin* [role](../user_guide/Project-Management/user_role_configuration.html) to an API key, the recommendation is to avoid doing so unless absolutely necessary.  See the user guide for an overview about how to create and manage [API keys](../user_guide/Settings/api_keys_administration.html).  ### Personal Access Tokens  Personal Access Tokens can be used as [bearer tokens](https://swagger.io/docs/specification/authentication/bearer-authentication/), e.g.  `Authorization: Bearer secret-token:qRuXr1BqgoTWXNxUhYQ8H_Yl2zfy6vxuqMIRnkGO`  Personal Access Tokens can be created by any user, and represent a subset of that user's permissions.   ### HTTP Basic Authentication  HTTP Basic authentication may be used to authenticate with the API as a regular user. This is accomplished by including an `Authorization` header containing a typical authorization credential.  ## Error Handling  ### Bad Requests  For API calls that accept input, invalid values will trigger an HTTP 400 Bad Request status code.  ### Server Errors  For any API call, if an unexpected error occurs, an HTTP 500 Internal Server Error status code will be returned. If an error message is available, the response will include a basic message body describing the error:  ` {   \"error\": \"error message\" } `  The error property will contain a string message indicating the nature of the error.  ### Errors with Third-Party Applications  Sometimes Software Risk Manager must communicate with third-party applications like JIRA, Git, and certain enterprise tools. Some users may have in-house versions of these with self-signed certificates which may not be \"trusted\". In these cases, the API will respond with an HTTP 502 BAD GATEWAY status. If this happens, refer to [Trusting Certificates](../install_guide/Installation/trusting-certs.html) in the install guide.  ### API Unavailable  In special circumstances, particularly during the installation and update phases, the API will be unavailable. When the API is unavailable, all calls will return an HTTP 503 Service Unavailable status, and no actions or side effects will occur as a result of the calls.  ## Examples  Software Risk Manager's API uses REST over HTTP. As such, you can use any language/utility that supports making HTTP requests to interact with the API. The examples below use <a href=\"https://curl.haxx.se/\" target=\"_blank\">curl</a>, a popular command-line utility, to do so.  First, you'll need to [generate an API Key](../user_guide/Settings/api_keys_administration.html). Second, while you can create projects through the API, these examples will assume that you've already created one. You'll need to know its project id number, which you can find by looking at the URL for the [Findings Page](../user_guide/Findings/findings_overview.html), which will end in a number.  **Note:** Many API endpoints require a JSON body in the request. Most JSON will contain double-quotes (`\"`) and spaces, which have special meaning when used on the command line. In order to ensure your JSON body is interpreted as a single argument, you must <a href=\"https://en.wikipedia.org/wiki/Escape_character\" target=\"_blank\">escape</a> it properly. For example, if you wanted to `POST` the following JSON body:  ```{ \"name\": \"John Doe\" }```  You would put a backslash (`\\`) before each double-quote (`\"`), and surround the whole thing with double-quotes:  ```\"{ \\\"name\\\": \\\"John Doe\\\" }\"```  The outermost double-quotes tell the command-line interpreter that everything within them is to be treated as a single argument (as opposed to the usual space-separated behavior). The backslash before each inner double-quote tells the command-line interpreter that you mean the literal double-quote character, and not the end of the quoted argument.  In many *non-Windows* operating systems, you can also use a single-quote (`'`) to surround the argument, and skip the backslashes:  ```'{ \"name\": \"John Doe\" }'```  The examples below will use the double-quotes and backslashes style, as it works on most (if not all) operating systems.  ### Running an Analysis  To start an analysis, you can run  ```curl -F file1=@src.zip -H \"API-Key: api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24\" https://<yoursrmserver>/srm/api/projects/<project id>/analysis```  Make sure you use your own values for the `src.zip` file, the API Key, the hostname for your Software Risk Manager server, and the project id.  ### Retrieving Finding Data  There is a wide variety of data available for the findings of a project after running an analysis. Two examples are provided here.  ### Findings Table Data  You can retrieve the data that's used to populate the [findings table](../user_guide/Findings/findings_table.html):  ```curl -H \"Content-Type: application/json\" -X POST -d \"{\\\"filter\\\":{},\\\"sort\\\":{\\\"by\\\":\\\"id\\\",\\\"direction\\\":\\\"ascending\\\"},\\\"pagination\\\":{\\\"page\\\":1,\\\"perPage\\\":10}}\" -H \"API-Key: api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24\" https://<yoursrmserver>/srm/api/projects/<project id>/findings/table```  Additional information about how to construct more useful filter and sort requests can be found in the documentation.  ### Finding Metadata  You can retrieve metadata for a finding, if you know the finding ID. You can take the ID for a finding from the Findings Table:  ```curl -H \"API-Key: api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24\" https://<yoursrmserver>/srm/api/findings/<finding id>```  ### Generating a Report  You can use the API to generate a PDF [report](../user_guide/Findings/generate_report.html).  ```curl -H \"Content-Type: application/json\" -X POST -d \"{\\\"filter\\\":{},\\\"config\\\":{\\\"summaryMode\\\":\\\"simple\\\",\\\"detailsMode\\\":\\\"simple\\\",\\\"includeResultDetails\\\":true,\\\"includeComments\\\":false}}\" -H \"API-Key: api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24\" https://<yoursrmserver>/srm/api/projects/<project id>/report/pdf```  ## Generating a Client SDK  If you require a client SDK for Software Risk Manager, you can generate one using [OpenAPI Generator](https://openapi-generator.tech/). Detailed instructions are available on the [GitHub page](https://github.com/OpenAPITools/openapi-generator) and our OpenAPI spec can be found [here](swagger/swagger.json). 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.codedx.client.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.codedx.client.JSON;


/**
 * MlTriageServerStatus
 */
@JsonPropertyOrder({
  MlTriageServerStatus.JSON_PROPERTY_IS_SERVER_AVAILABLE,
  MlTriageServerStatus.JSON_PROPERTY_IS_ML_ENABLED,
  MlTriageServerStatus.JSON_PROPERTY_ML_MODEL_EXISTS,
  MlTriageServerStatus.JSON_PROPERTY_NUM_TRIAGED_FINDINGS,
  MlTriageServerStatus.JSON_PROPERTY_ML_REQUIREMENTS_SATISFIED,
  MlTriageServerStatus.JSON_PROPERTY_CURRENTLY_TRAINING,
  MlTriageServerStatus.JSON_PROPERTY_TRAINING_START_TIME,
  MlTriageServerStatus.JSON_PROPERTY_TRAINING_END_TIME,
  MlTriageServerStatus.JSON_PROPERTY_TRAINING_WAS_SUCCESSFUL
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-02T11:55:06.722228-04:00[America/New_York]", comments = "Generator version: 7.21.0")
public class MlTriageServerStatus {
  public static final String JSON_PROPERTY_IS_SERVER_AVAILABLE = "isServerAvailable";
  @jakarta.annotation.Nonnull
  private Boolean isServerAvailable;

  public static final String JSON_PROPERTY_IS_ML_ENABLED = "isMlEnabled";
  @jakarta.annotation.Nonnull
  private Boolean isMlEnabled;

  public static final String JSON_PROPERTY_ML_MODEL_EXISTS = "mlModelExists";
  @jakarta.annotation.Nonnull
  private Boolean mlModelExists;

  public static final String JSON_PROPERTY_NUM_TRIAGED_FINDINGS = "numTriagedFindings";
  @jakarta.annotation.Nullable
  private Integer numTriagedFindings;

  public static final String JSON_PROPERTY_ML_REQUIREMENTS_SATISFIED = "mlRequirementsSatisfied";
  @jakarta.annotation.Nonnull
  private Boolean mlRequirementsSatisfied;

  public static final String JSON_PROPERTY_CURRENTLY_TRAINING = "currentlyTraining";
  @jakarta.annotation.Nonnull
  private Boolean currentlyTraining;

  public static final String JSON_PROPERTY_TRAINING_START_TIME = "trainingStartTime";
  private JsonNullable<OffsetDateTime> trainingStartTime = JsonNullable.<OffsetDateTime>undefined();

  public static final String JSON_PROPERTY_TRAINING_END_TIME = "trainingEndTime";
  @jakarta.annotation.Nullable
  private OffsetDateTime trainingEndTime;

  public static final String JSON_PROPERTY_TRAINING_WAS_SUCCESSFUL = "trainingWasSuccessful";
  @jakarta.annotation.Nonnull
  private Boolean trainingWasSuccessful;

  public MlTriageServerStatus() { 
  }

  public MlTriageServerStatus isServerAvailable(@jakarta.annotation.Nonnull Boolean isServerAvailable) {
    this.isServerAvailable = isServerAvailable;
    return this;
  }

  /**
   * Whether or not the ML Triage server is up and running
   * @return isServerAvailable
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_IS_SERVER_AVAILABLE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getIsServerAvailable() {
    return isServerAvailable;
  }


  @JsonProperty(value = JSON_PROPERTY_IS_SERVER_AVAILABLE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setIsServerAvailable(@jakarta.annotation.Nonnull Boolean isServerAvailable) {
    this.isServerAvailable = isServerAvailable;
  }


  public MlTriageServerStatus isMlEnabled(@jakarta.annotation.Nonnull Boolean isMlEnabled) {
    this.isMlEnabled = isMlEnabled;
    return this;
  }

  /**
   * Whether or not Machine Learning capabilities are enabled on the Machine Learning Control Panel
   * @return isMlEnabled
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_IS_ML_ENABLED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getIsMlEnabled() {
    return isMlEnabled;
  }


  @JsonProperty(value = JSON_PROPERTY_IS_ML_ENABLED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setIsMlEnabled(@jakarta.annotation.Nonnull Boolean isMlEnabled) {
    this.isMlEnabled = isMlEnabled;
  }


  public MlTriageServerStatus mlModelExists(@jakarta.annotation.Nonnull Boolean mlModelExists) {
    this.mlModelExists = mlModelExists;
    return this;
  }

  /**
   * Whether or not a prediction model has been trained
   * @return mlModelExists
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ML_MODEL_EXISTS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getMlModelExists() {
    return mlModelExists;
  }


  @JsonProperty(value = JSON_PROPERTY_ML_MODEL_EXISTS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMlModelExists(@jakarta.annotation.Nonnull Boolean mlModelExists) {
    this.mlModelExists = mlModelExists;
  }


  public MlTriageServerStatus numTriagedFindings(@jakarta.annotation.Nullable Integer numTriagedFindings) {
    this.numTriagedFindings = numTriagedFindings;
    return this;
  }

  /**
   * The number of findings that have been actively triaged
   * @return numTriagedFindings
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_NUM_TRIAGED_FINDINGS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getNumTriagedFindings() {
    return numTriagedFindings;
  }


  @JsonProperty(value = JSON_PROPERTY_NUM_TRIAGED_FINDINGS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNumTriagedFindings(@jakarta.annotation.Nullable Integer numTriagedFindings) {
    this.numTriagedFindings = numTriagedFindings;
  }


  public MlTriageServerStatus mlRequirementsSatisfied(@jakarta.annotation.Nonnull Boolean mlRequirementsSatisfied) {
    this.mlRequirementsSatisfied = mlRequirementsSatisfied;
    return this;
  }

  /**
   * Whether or not the requires for Machine Learning have been satisfied
   * @return mlRequirementsSatisfied
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ML_REQUIREMENTS_SATISFIED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getMlRequirementsSatisfied() {
    return mlRequirementsSatisfied;
  }


  @JsonProperty(value = JSON_PROPERTY_ML_REQUIREMENTS_SATISFIED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMlRequirementsSatisfied(@jakarta.annotation.Nonnull Boolean mlRequirementsSatisfied) {
    this.mlRequirementsSatisfied = mlRequirementsSatisfied;
  }


  public MlTriageServerStatus currentlyTraining(@jakarta.annotation.Nonnull Boolean currentlyTraining) {
    this.currentlyTraining = currentlyTraining;
    return this;
  }

  /**
   * Whether or not a prediction model is being trained
   * @return currentlyTraining
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CURRENTLY_TRAINING, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getCurrentlyTraining() {
    return currentlyTraining;
  }


  @JsonProperty(value = JSON_PROPERTY_CURRENTLY_TRAINING, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCurrentlyTraining(@jakarta.annotation.Nonnull Boolean currentlyTraining) {
    this.currentlyTraining = currentlyTraining;
  }


  public MlTriageServerStatus trainingStartTime(@jakarta.annotation.Nullable OffsetDateTime trainingStartTime) {
    this.trainingStartTime = JsonNullable.<OffsetDateTime>of(trainingStartTime);
    return this;
  }

  /**
   * The time at which the most recent training job started
   * @return trainingStartTime
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public OffsetDateTime getTrainingStartTime() {
        return trainingStartTime.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_TRAINING_START_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<OffsetDateTime> getTrainingStartTime_JsonNullable() {
    return trainingStartTime;
  }
  
  @JsonProperty(JSON_PROPERTY_TRAINING_START_TIME)
  public void setTrainingStartTime_JsonNullable(JsonNullable<OffsetDateTime> trainingStartTime) {
    this.trainingStartTime = trainingStartTime;
  }

  public void setTrainingStartTime(@jakarta.annotation.Nullable OffsetDateTime trainingStartTime) {
    this.trainingStartTime = JsonNullable.<OffsetDateTime>of(trainingStartTime);
  }


  public MlTriageServerStatus trainingEndTime(@jakarta.annotation.Nullable OffsetDateTime trainingEndTime) {
    this.trainingEndTime = trainingEndTime;
    return this;
  }

  /**
   * The time at which the most recent training job ended
   * @return trainingEndTime
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TRAINING_END_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OffsetDateTime getTrainingEndTime() {
    return trainingEndTime;
  }


  @JsonProperty(value = JSON_PROPERTY_TRAINING_END_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTrainingEndTime(@jakarta.annotation.Nullable OffsetDateTime trainingEndTime) {
    this.trainingEndTime = trainingEndTime;
  }


  public MlTriageServerStatus trainingWasSuccessful(@jakarta.annotation.Nonnull Boolean trainingWasSuccessful) {
    this.trainingWasSuccessful = trainingWasSuccessful;
    return this;
  }

  /**
   * Whether or not the most recent training job succeeded
   * @return trainingWasSuccessful
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TRAINING_WAS_SUCCESSFUL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getTrainingWasSuccessful() {
    return trainingWasSuccessful;
  }


  @JsonProperty(value = JSON_PROPERTY_TRAINING_WAS_SUCCESSFUL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTrainingWasSuccessful(@jakarta.annotation.Nonnull Boolean trainingWasSuccessful) {
    this.trainingWasSuccessful = trainingWasSuccessful;
  }


  /**
   * Return true if this MlTriageServerStatus object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MlTriageServerStatus mlTriageServerStatus = (MlTriageServerStatus) o;
    return Objects.equals(this.isServerAvailable, mlTriageServerStatus.isServerAvailable) &&
        Objects.equals(this.isMlEnabled, mlTriageServerStatus.isMlEnabled) &&
        Objects.equals(this.mlModelExists, mlTriageServerStatus.mlModelExists) &&
        Objects.equals(this.numTriagedFindings, mlTriageServerStatus.numTriagedFindings) &&
        Objects.equals(this.mlRequirementsSatisfied, mlTriageServerStatus.mlRequirementsSatisfied) &&
        Objects.equals(this.currentlyTraining, mlTriageServerStatus.currentlyTraining) &&
        equalsNullable(this.trainingStartTime, mlTriageServerStatus.trainingStartTime) &&
        Objects.equals(this.trainingEndTime, mlTriageServerStatus.trainingEndTime) &&
        Objects.equals(this.trainingWasSuccessful, mlTriageServerStatus.trainingWasSuccessful);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(isServerAvailable, isMlEnabled, mlModelExists, numTriagedFindings, mlRequirementsSatisfied, currentlyTraining, hashCodeNullable(trainingStartTime), trainingEndTime, trainingWasSuccessful);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MlTriageServerStatus {\n");
    sb.append("    isServerAvailable: ").append(toIndentedString(isServerAvailable)).append("\n");
    sb.append("    isMlEnabled: ").append(toIndentedString(isMlEnabled)).append("\n");
    sb.append("    mlModelExists: ").append(toIndentedString(mlModelExists)).append("\n");
    sb.append("    numTriagedFindings: ").append(toIndentedString(numTriagedFindings)).append("\n");
    sb.append("    mlRequirementsSatisfied: ").append(toIndentedString(mlRequirementsSatisfied)).append("\n");
    sb.append("    currentlyTraining: ").append(toIndentedString(currentlyTraining)).append("\n");
    sb.append("    trainingStartTime: ").append(toIndentedString(trainingStartTime)).append("\n");
    sb.append("    trainingEndTime: ").append(toIndentedString(trainingEndTime)).append("\n");
    sb.append("    trainingWasSuccessful: ").append(toIndentedString(trainingWasSuccessful)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

