/*
 * Software Risk Manager API Guide
 * Software Risk Manager provides a variety of REST APIs, allowing external applications and scripts to interface with core functionality. This guide documents the various REST resources provided by Software Risk Manager.  ## Authentication  Authentication is a requirement when accessing API endpoints. There are two methods by which authentication may be performed.  ### API Keys  The primary method for authentication is passing an `API-Key` header containing a valid API key with all requests, i.e.  `API-Key: <key goes here>`  API Keys come in two possible forms:   - `api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24` - latest format  - `550e8400-e29b-41d4-a716-44665544000` - legacy format  For example:  `API-Key: api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24`  `API-Key: 550e8400-e29b-41d4-a716-44665544000`  API keys may be generated by Software Risk Manager admins. Once they are generated, in most cases, they behave like regular users. They will need to be assigned user roles for any projects they will be used with. Although it is possible to assign the *admin* [role](../user_guide/Project-Management/user_role_configuration.html) to an API key, the recommendation is to avoid doing so unless absolutely necessary.  See the user guide for an overview about how to create and manage [API keys](../user_guide/Settings/api_keys_administration.html).  ### Personal Access Tokens  Personal Access Tokens can be used as [bearer tokens](https://swagger.io/docs/specification/authentication/bearer-authentication/), e.g.  `Authorization: Bearer secret-token:qRuXr1BqgoTWXNxUhYQ8H_Yl2zfy6vxuqMIRnkGO`  Personal Access Tokens can be created by any user, and represent a subset of that user's permissions.   ### HTTP Basic Authentication  HTTP Basic authentication may be used to authenticate with the API as a regular user. This is accomplished by including an `Authorization` header containing a typical authorization credential.  ## Error Handling  ### Bad Requests  For API calls that accept input, invalid values will trigger an HTTP 400 Bad Request status code.  ### Server Errors  For any API call, if an unexpected error occurs, an HTTP 500 Internal Server Error status code will be returned. If an error message is available, the response will include a basic message body describing the error:  ` {   \"error\": \"error message\" } `  The error property will contain a string message indicating the nature of the error.  ### Errors with Third-Party Applications  Sometimes Software Risk Manager must communicate with third-party applications like JIRA, Git, and certain enterprise tools. Some users may have in-house versions of these with self-signed certificates which may not be \"trusted\". In these cases, the API will respond with an HTTP 502 BAD GATEWAY status. If this happens, refer to [Trusting Certificates](../install_guide/Installation/trusting-certs.html) in the install guide.  ### API Unavailable  In special circumstances, particularly during the installation and update phases, the API will be unavailable. When the API is unavailable, all calls will return an HTTP 503 Service Unavailable status, and no actions or side effects will occur as a result of the calls.  ## Examples  Software Risk Manager's API uses REST over HTTP. As such, you can use any language/utility that supports making HTTP requests to interact with the API. The examples below use <a href=\"https://curl.haxx.se/\" target=\"_blank\">curl</a>, a popular command-line utility, to do so.  First, you'll need to [generate an API Key](../user_guide/Settings/api_keys_administration.html). Second, while you can create projects through the API, these examples will assume that you've already created one. You'll need to know its project id number, which you can find by looking at the URL for the [Findings Page](../user_guide/Findings/findings_overview.html), which will end in a number.  **Note:** Many API endpoints require a JSON body in the request. Most JSON will contain double-quotes (`\"`) and spaces, which have special meaning when used on the command line. In order to ensure your JSON body is interpreted as a single argument, you must <a href=\"https://en.wikipedia.org/wiki/Escape_character\" target=\"_blank\">escape</a> it properly. For example, if you wanted to `POST` the following JSON body:  ```{ \"name\": \"John Doe\" }```  You would put a backslash (`\\`) before each double-quote (`\"`), and surround the whole thing with double-quotes:  ```\"{ \\\"name\\\": \\\"John Doe\\\" }\"```  The outermost double-quotes tell the command-line interpreter that everything within them is to be treated as a single argument (as opposed to the usual space-separated behavior). The backslash before each inner double-quote tells the command-line interpreter that you mean the literal double-quote character, and not the end of the quoted argument.  In many *non-Windows* operating systems, you can also use a single-quote (`'`) to surround the argument, and skip the backslashes:  ```'{ \"name\": \"John Doe\" }'```  The examples below will use the double-quotes and backslashes style, as it works on most (if not all) operating systems.  ### Running an Analysis  To start an analysis, you can run  ```curl -F file1=@src.zip -H \"API-Key: api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24\" https://<yoursrmserver>/srm/api/projects/<project id>/analysis```  Make sure you use your own values for the `src.zip` file, the API Key, the hostname for your Software Risk Manager server, and the project id.  ### Retrieving Finding Data  There is a wide variety of data available for the findings of a project after running an analysis. Two examples are provided here.  ### Findings Table Data  You can retrieve the data that's used to populate the [findings table](../user_guide/Findings/findings_table.html):  ```curl -H \"Content-Type: application/json\" -X POST -d \"{\\\"filter\\\":{},\\\"sort\\\":{\\\"by\\\":\\\"id\\\",\\\"direction\\\":\\\"ascending\\\"},\\\"pagination\\\":{\\\"page\\\":1,\\\"perPage\\\":10}}\" -H \"API-Key: api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24\" https://<yoursrmserver>/srm/api/projects/<project id>/findings/table```  Additional information about how to construct more useful filter and sort requests can be found in the documentation.  ### Finding Metadata  You can retrieve metadata for a finding, if you know the finding ID. You can take the ID for a finding from the Findings Table:  ```curl -H \"API-Key: api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24\" https://<yoursrmserver>/srm/api/findings/<finding id>```  ### Generating a Report  You can use the API to generate a PDF [report](../user_guide/Findings/generate_report.html).  ```curl -H \"Content-Type: application/json\" -X POST -d \"{\\\"filter\\\":{},\\\"config\\\":{\\\"summaryMode\\\":\\\"simple\\\",\\\"detailsMode\\\":\\\"simple\\\",\\\"includeResultDetails\\\":true,\\\"includeComments\\\":false}}\" -H \"API-Key: api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24\" https://<yoursrmserver>/srm/api/projects/<project id>/report/pdf```  ## Generating a Client SDK  If you require a client SDK for Software Risk Manager, you can generate one using [OpenAPI Generator](https://openapi-generator.tech/). Detailed instructions are available on the [GitHub page](https://github.com/OpenAPITools/openapi-generator) and our OpenAPI spec can be found [here](swagger/swagger.json). 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.codedx.client.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.codedx.client.model.AnalysisDetails;
import com.codedx.client.model.MetadataValue;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.codedx.client.JSON;


/**
 * ProjectDetails
 */
@JsonPropertyOrder({
  ProjectDetails.JSON_PROPERTY_ID,
  ProjectDetails.JSON_PROPERTY_NAME,
  ProjectDetails.JSON_PROPERTY_PARENT_ID,
  ProjectDetails.JSON_PROPERTY_HIERARCHY_IDS,
  ProjectDetails.JSON_PROPERTY_HAS_CHILDREN,
  ProjectDetails.JSON_PROPERTY_LATEST_COMPLETE_ANALYSIS,
  ProjectDetails.JSON_PROPERTY_LATEST_FAILED_ANALYSIS,
  ProjectDetails.JSON_PROPERTY_HAS_BINARY_CLASSES,
  ProjectDetails.JSON_PROPERTY_HAS_SOURCE_CLASSES,
  ProjectDetails.JSON_PROPERTY_HAS_CODEBASE_TREE,
  ProjectDetails.JSON_PROPERTY_METADATA,
  ProjectDetails.JSON_PROPERTY_HAS_ANALYSIS_CONFIG,
  ProjectDetails.JSON_PROPERTY_HAS_PROJECT_METADATA,
  ProjectDetails.JSON_PROPERTY_HAS_GIT_CONFIG,
  ProjectDetails.JSON_PROPERTY_HAS_JIRA_CONFIG,
  ProjectDetails.JSON_PROPERTY_HAS_TOOL_CONNECTORS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-02T11:55:06.722228-04:00[America/New_York]", comments = "Generator version: 7.21.0")
public class ProjectDetails {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nullable
  private Integer id;

  public static final String JSON_PROPERTY_NAME = "name";
  @jakarta.annotation.Nullable
  private String name;

  public static final String JSON_PROPERTY_PARENT_ID = "parentId";
  @jakarta.annotation.Nullable
  private Integer parentId;

  public static final String JSON_PROPERTY_HIERARCHY_IDS = "hierarchyIds";
  @jakarta.annotation.Nullable
  private List<Integer> hierarchyIds = new ArrayList<>();

  public static final String JSON_PROPERTY_HAS_CHILDREN = "hasChildren";
  @jakarta.annotation.Nullable
  private Boolean hasChildren;

  public static final String JSON_PROPERTY_LATEST_COMPLETE_ANALYSIS = "latestCompleteAnalysis";
  @jakarta.annotation.Nullable
  private AnalysisDetails latestCompleteAnalysis;

  public static final String JSON_PROPERTY_LATEST_FAILED_ANALYSIS = "latestFailedAnalysis";
  @jakarta.annotation.Nullable
  private AnalysisDetails latestFailedAnalysis;

  public static final String JSON_PROPERTY_HAS_BINARY_CLASSES = "hasBinaryClasses";
  @jakarta.annotation.Nullable
  private Boolean hasBinaryClasses;

  public static final String JSON_PROPERTY_HAS_SOURCE_CLASSES = "hasSourceClasses";
  @jakarta.annotation.Nullable
  private Boolean hasSourceClasses;

  public static final String JSON_PROPERTY_HAS_CODEBASE_TREE = "hasCodebaseTree";
  @jakarta.annotation.Nullable
  private Boolean hasCodebaseTree;

  public static final String JSON_PROPERTY_METADATA = "metadata";
  @jakarta.annotation.Nullable
  private List<MetadataValue> metadata = new ArrayList<>();

  public static final String JSON_PROPERTY_HAS_ANALYSIS_CONFIG = "hasAnalysisConfig";
  @jakarta.annotation.Nullable
  private Boolean hasAnalysisConfig;

  public static final String JSON_PROPERTY_HAS_PROJECT_METADATA = "hasProjectMetadata";
  @jakarta.annotation.Nullable
  private Boolean hasProjectMetadata;

  public static final String JSON_PROPERTY_HAS_GIT_CONFIG = "hasGitConfig";
  @jakarta.annotation.Nullable
  private Boolean hasGitConfig;

  public static final String JSON_PROPERTY_HAS_JIRA_CONFIG = "hasJiraConfig";
  @jakarta.annotation.Nullable
  private Boolean hasJiraConfig;

  public static final String JSON_PROPERTY_HAS_TOOL_CONNECTORS = "hasToolConnectors";
  @jakarta.annotation.Nullable
  private Boolean hasToolConnectors;

  public ProjectDetails() { 
  }

  public ProjectDetails id(@jakarta.annotation.Nullable Integer id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@jakarta.annotation.Nullable Integer id) {
    this.id = id;
  }


  public ProjectDetails name(@jakarta.annotation.Nullable String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(@jakarta.annotation.Nullable String name) {
    this.name = name;
  }


  public ProjectDetails parentId(@jakarta.annotation.Nullable Integer parentId) {
    this.parentId = parentId;
    return this;
  }

  /**
   * Get parentId
   * @return parentId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PARENT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getParentId() {
    return parentId;
  }


  @JsonProperty(value = JSON_PROPERTY_PARENT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setParentId(@jakarta.annotation.Nullable Integer parentId) {
    this.parentId = parentId;
  }


  public ProjectDetails hierarchyIds(@jakarta.annotation.Nullable List<Integer> hierarchyIds) {
    this.hierarchyIds = hierarchyIds;
    return this;
  }

  public ProjectDetails addHierarchyIdsItem(Integer hierarchyIdsItem) {
    if (this.hierarchyIds == null) {
      this.hierarchyIds = new ArrayList<>();
    }
    this.hierarchyIds.add(hierarchyIdsItem);
    return this;
  }

  /**
   * Get hierarchyIds
   * @return hierarchyIds
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_HIERARCHY_IDS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Integer> getHierarchyIds() {
    return hierarchyIds;
  }


  @JsonProperty(value = JSON_PROPERTY_HIERARCHY_IDS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHierarchyIds(@jakarta.annotation.Nullable List<Integer> hierarchyIds) {
    this.hierarchyIds = hierarchyIds;
  }


  public ProjectDetails hasChildren(@jakarta.annotation.Nullable Boolean hasChildren) {
    this.hasChildren = hasChildren;
    return this;
  }

  /**
   * Get hasChildren
   * @return hasChildren
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_HAS_CHILDREN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getHasChildren() {
    return hasChildren;
  }


  @JsonProperty(value = JSON_PROPERTY_HAS_CHILDREN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHasChildren(@jakarta.annotation.Nullable Boolean hasChildren) {
    this.hasChildren = hasChildren;
  }


  public ProjectDetails latestCompleteAnalysis(@jakarta.annotation.Nullable AnalysisDetails latestCompleteAnalysis) {
    this.latestCompleteAnalysis = latestCompleteAnalysis;
    return this;
  }

  /**
   * Get latestCompleteAnalysis
   * @return latestCompleteAnalysis
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LATEST_COMPLETE_ANALYSIS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AnalysisDetails getLatestCompleteAnalysis() {
    return latestCompleteAnalysis;
  }


  @JsonProperty(value = JSON_PROPERTY_LATEST_COMPLETE_ANALYSIS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLatestCompleteAnalysis(@jakarta.annotation.Nullable AnalysisDetails latestCompleteAnalysis) {
    this.latestCompleteAnalysis = latestCompleteAnalysis;
  }


  public ProjectDetails latestFailedAnalysis(@jakarta.annotation.Nullable AnalysisDetails latestFailedAnalysis) {
    this.latestFailedAnalysis = latestFailedAnalysis;
    return this;
  }

  /**
   * Get latestFailedAnalysis
   * @return latestFailedAnalysis
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LATEST_FAILED_ANALYSIS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AnalysisDetails getLatestFailedAnalysis() {
    return latestFailedAnalysis;
  }


  @JsonProperty(value = JSON_PROPERTY_LATEST_FAILED_ANALYSIS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLatestFailedAnalysis(@jakarta.annotation.Nullable AnalysisDetails latestFailedAnalysis) {
    this.latestFailedAnalysis = latestFailedAnalysis;
  }


  public ProjectDetails hasBinaryClasses(@jakarta.annotation.Nullable Boolean hasBinaryClasses) {
    this.hasBinaryClasses = hasBinaryClasses;
    return this;
  }

  /**
   * Get hasBinaryClasses
   * @return hasBinaryClasses
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_HAS_BINARY_CLASSES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getHasBinaryClasses() {
    return hasBinaryClasses;
  }


  @JsonProperty(value = JSON_PROPERTY_HAS_BINARY_CLASSES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHasBinaryClasses(@jakarta.annotation.Nullable Boolean hasBinaryClasses) {
    this.hasBinaryClasses = hasBinaryClasses;
  }


  public ProjectDetails hasSourceClasses(@jakarta.annotation.Nullable Boolean hasSourceClasses) {
    this.hasSourceClasses = hasSourceClasses;
    return this;
  }

  /**
   * Get hasSourceClasses
   * @return hasSourceClasses
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_HAS_SOURCE_CLASSES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getHasSourceClasses() {
    return hasSourceClasses;
  }


  @JsonProperty(value = JSON_PROPERTY_HAS_SOURCE_CLASSES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHasSourceClasses(@jakarta.annotation.Nullable Boolean hasSourceClasses) {
    this.hasSourceClasses = hasSourceClasses;
  }


  public ProjectDetails hasCodebaseTree(@jakarta.annotation.Nullable Boolean hasCodebaseTree) {
    this.hasCodebaseTree = hasCodebaseTree;
    return this;
  }

  /**
   * Get hasCodebaseTree
   * @return hasCodebaseTree
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_HAS_CODEBASE_TREE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getHasCodebaseTree() {
    return hasCodebaseTree;
  }


  @JsonProperty(value = JSON_PROPERTY_HAS_CODEBASE_TREE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHasCodebaseTree(@jakarta.annotation.Nullable Boolean hasCodebaseTree) {
    this.hasCodebaseTree = hasCodebaseTree;
  }


  public ProjectDetails metadata(@jakarta.annotation.Nullable List<MetadataValue> metadata) {
    this.metadata = metadata;
    return this;
  }

  public ProjectDetails addMetadataItem(MetadataValue metadataItem) {
    if (this.metadata == null) {
      this.metadata = new ArrayList<>();
    }
    this.metadata.add(metadataItem);
    return this;
  }

  /**
   * Get metadata
   * @return metadata
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_METADATA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<MetadataValue> getMetadata() {
    return metadata;
  }


  @JsonProperty(value = JSON_PROPERTY_METADATA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMetadata(@jakarta.annotation.Nullable List<MetadataValue> metadata) {
    this.metadata = metadata;
  }


  public ProjectDetails hasAnalysisConfig(@jakarta.annotation.Nullable Boolean hasAnalysisConfig) {
    this.hasAnalysisConfig = hasAnalysisConfig;
    return this;
  }

  /**
   * Get hasAnalysisConfig
   * @return hasAnalysisConfig
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_HAS_ANALYSIS_CONFIG, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getHasAnalysisConfig() {
    return hasAnalysisConfig;
  }


  @JsonProperty(value = JSON_PROPERTY_HAS_ANALYSIS_CONFIG, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHasAnalysisConfig(@jakarta.annotation.Nullable Boolean hasAnalysisConfig) {
    this.hasAnalysisConfig = hasAnalysisConfig;
  }


  public ProjectDetails hasProjectMetadata(@jakarta.annotation.Nullable Boolean hasProjectMetadata) {
    this.hasProjectMetadata = hasProjectMetadata;
    return this;
  }

  /**
   * Get hasProjectMetadata
   * @return hasProjectMetadata
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_HAS_PROJECT_METADATA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getHasProjectMetadata() {
    return hasProjectMetadata;
  }


  @JsonProperty(value = JSON_PROPERTY_HAS_PROJECT_METADATA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHasProjectMetadata(@jakarta.annotation.Nullable Boolean hasProjectMetadata) {
    this.hasProjectMetadata = hasProjectMetadata;
  }


  public ProjectDetails hasGitConfig(@jakarta.annotation.Nullable Boolean hasGitConfig) {
    this.hasGitConfig = hasGitConfig;
    return this;
  }

  /**
   * Get hasGitConfig
   * @return hasGitConfig
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_HAS_GIT_CONFIG, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getHasGitConfig() {
    return hasGitConfig;
  }


  @JsonProperty(value = JSON_PROPERTY_HAS_GIT_CONFIG, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHasGitConfig(@jakarta.annotation.Nullable Boolean hasGitConfig) {
    this.hasGitConfig = hasGitConfig;
  }


  public ProjectDetails hasJiraConfig(@jakarta.annotation.Nullable Boolean hasJiraConfig) {
    this.hasJiraConfig = hasJiraConfig;
    return this;
  }

  /**
   * Get hasJiraConfig
   * @return hasJiraConfig
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_HAS_JIRA_CONFIG, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getHasJiraConfig() {
    return hasJiraConfig;
  }


  @JsonProperty(value = JSON_PROPERTY_HAS_JIRA_CONFIG, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHasJiraConfig(@jakarta.annotation.Nullable Boolean hasJiraConfig) {
    this.hasJiraConfig = hasJiraConfig;
  }


  public ProjectDetails hasToolConnectors(@jakarta.annotation.Nullable Boolean hasToolConnectors) {
    this.hasToolConnectors = hasToolConnectors;
    return this;
  }

  /**
   * Get hasToolConnectors
   * @return hasToolConnectors
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_HAS_TOOL_CONNECTORS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getHasToolConnectors() {
    return hasToolConnectors;
  }


  @JsonProperty(value = JSON_PROPERTY_HAS_TOOL_CONNECTORS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHasToolConnectors(@jakarta.annotation.Nullable Boolean hasToolConnectors) {
    this.hasToolConnectors = hasToolConnectors;
  }


  /**
   * Return true if this ProjectDetails object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProjectDetails projectDetails = (ProjectDetails) o;
    return Objects.equals(this.id, projectDetails.id) &&
        Objects.equals(this.name, projectDetails.name) &&
        Objects.equals(this.parentId, projectDetails.parentId) &&
        Objects.equals(this.hierarchyIds, projectDetails.hierarchyIds) &&
        Objects.equals(this.hasChildren, projectDetails.hasChildren) &&
        Objects.equals(this.latestCompleteAnalysis, projectDetails.latestCompleteAnalysis) &&
        Objects.equals(this.latestFailedAnalysis, projectDetails.latestFailedAnalysis) &&
        Objects.equals(this.hasBinaryClasses, projectDetails.hasBinaryClasses) &&
        Objects.equals(this.hasSourceClasses, projectDetails.hasSourceClasses) &&
        Objects.equals(this.hasCodebaseTree, projectDetails.hasCodebaseTree) &&
        Objects.equals(this.metadata, projectDetails.metadata) &&
        Objects.equals(this.hasAnalysisConfig, projectDetails.hasAnalysisConfig) &&
        Objects.equals(this.hasProjectMetadata, projectDetails.hasProjectMetadata) &&
        Objects.equals(this.hasGitConfig, projectDetails.hasGitConfig) &&
        Objects.equals(this.hasJiraConfig, projectDetails.hasJiraConfig) &&
        Objects.equals(this.hasToolConnectors, projectDetails.hasToolConnectors);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, parentId, hierarchyIds, hasChildren, latestCompleteAnalysis, latestFailedAnalysis, hasBinaryClasses, hasSourceClasses, hasCodebaseTree, metadata, hasAnalysisConfig, hasProjectMetadata, hasGitConfig, hasJiraConfig, hasToolConnectors);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProjectDetails {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    parentId: ").append(toIndentedString(parentId)).append("\n");
    sb.append("    hierarchyIds: ").append(toIndentedString(hierarchyIds)).append("\n");
    sb.append("    hasChildren: ").append(toIndentedString(hasChildren)).append("\n");
    sb.append("    latestCompleteAnalysis: ").append(toIndentedString(latestCompleteAnalysis)).append("\n");
    sb.append("    latestFailedAnalysis: ").append(toIndentedString(latestFailedAnalysis)).append("\n");
    sb.append("    hasBinaryClasses: ").append(toIndentedString(hasBinaryClasses)).append("\n");
    sb.append("    hasSourceClasses: ").append(toIndentedString(hasSourceClasses)).append("\n");
    sb.append("    hasCodebaseTree: ").append(toIndentedString(hasCodebaseTree)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    hasAnalysisConfig: ").append(toIndentedString(hasAnalysisConfig)).append("\n");
    sb.append("    hasProjectMetadata: ").append(toIndentedString(hasProjectMetadata)).append("\n");
    sb.append("    hasGitConfig: ").append(toIndentedString(hasGitConfig)).append("\n");
    sb.append("    hasJiraConfig: ").append(toIndentedString(hasJiraConfig)).append("\n");
    sb.append("    hasToolConnectors: ").append(toIndentedString(hasToolConnectors)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

