/*
 * Software Risk Manager API Guide
 * Software Risk Manager provides a variety of REST APIs, allowing external applications and scripts to interface with core functionality. This guide documents the various REST resources provided by Software Risk Manager.  ## Authentication  Authentication is a requirement when accessing API endpoints. There are two methods by which authentication may be performed.  ### API Keys  The primary method for authentication is passing an `API-Key` header containing a valid API key with all requests, i.e.  `API-Key: <key goes here>`  API Keys come in two possible forms:   - `api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24` - latest format  - `550e8400-e29b-41d4-a716-44665544000` - legacy format  For example:  `API-Key: api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24`  `API-Key: 550e8400-e29b-41d4-a716-44665544000`  API keys may be generated by Software Risk Manager admins. Once they are generated, in most cases, they behave like regular users. They will need to be assigned user roles for any projects they will be used with. Although it is possible to assign the *admin* [role](../user_guide/Project-Management/user_role_configuration.html) to an API key, the recommendation is to avoid doing so unless absolutely necessary.  See the user guide for an overview about how to create and manage [API keys](../user_guide/Settings/api_keys_administration.html).  ### Personal Access Tokens  Personal Access Tokens can be used as [bearer tokens](https://swagger.io/docs/specification/authentication/bearer-authentication/), e.g.  `Authorization: Bearer secret-token:qRuXr1BqgoTWXNxUhYQ8H_Yl2zfy6vxuqMIRnkGO`  Personal Access Tokens can be created by any user, and represent a subset of that user's permissions.   ### HTTP Basic Authentication  HTTP Basic authentication may be used to authenticate with the API as a regular user. This is accomplished by including an `Authorization` header containing a typical authorization credential.  ## Error Handling  ### Bad Requests  For API calls that accept input, invalid values will trigger an HTTP 400 Bad Request status code.  ### Server Errors  For any API call, if an unexpected error occurs, an HTTP 500 Internal Server Error status code will be returned. If an error message is available, the response will include a basic message body describing the error:  ` {   \"error\": \"error message\" } `  The error property will contain a string message indicating the nature of the error.  ### Errors with Third-Party Applications  Sometimes Software Risk Manager must communicate with third-party applications like JIRA, Git, and certain enterprise tools. Some users may have in-house versions of these with self-signed certificates which may not be \"trusted\". In these cases, the API will respond with an HTTP 502 BAD GATEWAY status. If this happens, refer to [Trusting Certificates](../install_guide/Installation/trusting-certs.html) in the install guide.  ### API Unavailable  In special circumstances, particularly during the installation and update phases, the API will be unavailable. When the API is unavailable, all calls will return an HTTP 503 Service Unavailable status, and no actions or side effects will occur as a result of the calls.  ## Examples  Software Risk Manager's API uses REST over HTTP. As such, you can use any language/utility that supports making HTTP requests to interact with the API. The examples below use <a href=\"https://curl.haxx.se/\" target=\"_blank\">curl</a>, a popular command-line utility, to do so.  First, you'll need to [generate an API Key](../user_guide/Settings/api_keys_administration.html). Second, while you can create projects through the API, these examples will assume that you've already created one. You'll need to know its project id number, which you can find by looking at the URL for the [Findings Page](../user_guide/Findings/findings_overview.html), which will end in a number.  **Note:** Many API endpoints require a JSON body in the request. Most JSON will contain double-quotes (`\"`) and spaces, which have special meaning when used on the command line. In order to ensure your JSON body is interpreted as a single argument, you must <a href=\"https://en.wikipedia.org/wiki/Escape_character\" target=\"_blank\">escape</a> it properly. For example, if you wanted to `POST` the following JSON body:  ```{ \"name\": \"John Doe\" }```  You would put a backslash (`\\`) before each double-quote (`\"`), and surround the whole thing with double-quotes:  ```\"{ \\\"name\\\": \\\"John Doe\\\" }\"```  The outermost double-quotes tell the command-line interpreter that everything within them is to be treated as a single argument (as opposed to the usual space-separated behavior). The backslash before each inner double-quote tells the command-line interpreter that you mean the literal double-quote character, and not the end of the quoted argument.  In many *non-Windows* operating systems, you can also use a single-quote (`'`) to surround the argument, and skip the backslashes:  ```'{ \"name\": \"John Doe\" }'```  The examples below will use the double-quotes and backslashes style, as it works on most (if not all) operating systems.  ### Running an Analysis  To start an analysis, you can run  ```curl -F file1=@src.zip -H \"API-Key: api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24\" https://<yoursrmserver>/srm/api/projects/<project id>/analysis```  Make sure you use your own values for the `src.zip` file, the API Key, the hostname for your Software Risk Manager server, and the project id.  ### Retrieving Finding Data  There is a wide variety of data available for the findings of a project after running an analysis. Two examples are provided here.  ### Findings Table Data  You can retrieve the data that's used to populate the [findings table](../user_guide/Findings/findings_table.html):  ```curl -H \"Content-Type: application/json\" -X POST -d \"{\\\"filter\\\":{},\\\"sort\\\":{\\\"by\\\":\\\"id\\\",\\\"direction\\\":\\\"ascending\\\"},\\\"pagination\\\":{\\\"page\\\":1,\\\"perPage\\\":10}}\" -H \"API-Key: api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24\" https://<yoursrmserver>/srm/api/projects/<project id>/findings/table```  Additional information about how to construct more useful filter and sort requests can be found in the documentation.  ### Finding Metadata  You can retrieve metadata for a finding, if you know the finding ID. You can take the ID for a finding from the Findings Table:  ```curl -H \"API-Key: api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24\" https://<yoursrmserver>/srm/api/findings/<finding id>```  ### Generating a Report  You can use the API to generate a PDF [report](../user_guide/Findings/generate_report.html).  ```curl -H \"Content-Type: application/json\" -X POST -d \"{\\\"filter\\\":{},\\\"config\\\":{\\\"summaryMode\\\":\\\"simple\\\",\\\"detailsMode\\\":\\\"simple\\\",\\\"includeResultDetails\\\":true,\\\"includeComments\\\":false}}\" -H \"API-Key: api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24\" https://<yoursrmserver>/srm/api/projects/<project id>/report/pdf```  ## Generating a Client SDK  If you require a client SDK for Software Risk Manager, you can generate one using [OpenAPI Generator](https://openapi-generator.tech/). Detailed instructions are available on the [GitHub page](https://github.com/OpenAPITools/openapi-generator) and our OpenAPI spec can be found [here](swagger/swagger.json). 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.codedx.client.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.codedx.client.model.ReportTemplateSavedFilter;
import com.codedx.client.model.SimpleUser;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.codedx.client.JSON;


/**
 * ReportTemplateListItem
 */
@JsonPropertyOrder({
  ReportTemplateListItem.JSON_PROPERTY_ID,
  ReportTemplateListItem.JSON_PROPERTY_NAME,
  ReportTemplateListItem.JSON_PROPERTY_OWNER,
  ReportTemplateListItem.JSON_PROPERTY_DESCRIPTION,
  ReportTemplateListItem.JSON_PROPERTY_SAVED_FILTER,
  ReportTemplateListItem.JSON_PROPERTY_REPORT_TYPE,
  ReportTemplateListItem.JSON_PROPERTY_SCHEDULE,
  ReportTemplateListItem.JSON_PROPERTY_RECIPIENTS,
  ReportTemplateListItem.JSON_PROPERTY_PROJECT_IDS,
  ReportTemplateListItem.JSON_PROPERTY_CAN_EDIT
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-02T11:55:06.722228-04:00[America/New_York]", comments = "Generator version: 7.21.0")
public class ReportTemplateListItem {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nullable
  private Integer id;

  public static final String JSON_PROPERTY_NAME = "name";
  @jakarta.annotation.Nullable
  private String name;

  public static final String JSON_PROPERTY_OWNER = "owner";
  @jakarta.annotation.Nullable
  private SimpleUser owner;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @jakarta.annotation.Nullable
  private String description;

  public static final String JSON_PROPERTY_SAVED_FILTER = "savedFilter";
  @jakarta.annotation.Nullable
  private ReportTemplateSavedFilter savedFilter;

  /**
   * Gets or Sets reportType
   */
  public enum ReportTypeEnum {
    PDF(String.valueOf("pdf")),
    
    COMPLIANCE_PDF(String.valueOf("compliance-pdf")),
    
    XML(String.valueOf("xml")),
    
    CSV(String.valueOf("csv")),
    
    NESSUS(String.valueOf("nessus")),
    
    NBE(String.valueOf("nbe"));

    private String value;

    ReportTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ReportTypeEnum fromValue(String value) {
      for (ReportTypeEnum b : ReportTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_REPORT_TYPE = "reportType";
  @jakarta.annotation.Nullable
  private ReportTypeEnum reportType;

  public static final String JSON_PROPERTY_SCHEDULE = "schedule";
  @jakarta.annotation.Nullable
  private Map<String, Object> schedule = new HashMap<>();

  public static final String JSON_PROPERTY_RECIPIENTS = "recipients";
  @jakarta.annotation.Nullable
  private List<String> recipients = new ArrayList<>();

  public static final String JSON_PROPERTY_PROJECT_IDS = "projectIds";
  @jakarta.annotation.Nullable
  private List<Integer> projectIds = new ArrayList<>();

  public static final String JSON_PROPERTY_CAN_EDIT = "canEdit";
  @jakarta.annotation.Nullable
  private Boolean canEdit;

  public ReportTemplateListItem() { 
  }

  public ReportTemplateListItem id(@jakarta.annotation.Nullable Integer id) {
    this.id = id;
    return this;
  }

  /**
   * The id or the report
   * @return id
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@jakarta.annotation.Nullable Integer id) {
    this.id = id;
  }


  public ReportTemplateListItem name(@jakarta.annotation.Nullable String name) {
    this.name = name;
    return this;
  }

  /**
   * The report template name
   * @return name
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(@jakarta.annotation.Nullable String name) {
    this.name = name;
  }


  public ReportTemplateListItem owner(@jakarta.annotation.Nullable SimpleUser owner) {
    this.owner = owner;
    return this;
  }

  /**
   * Get owner
   * @return owner
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_OWNER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SimpleUser getOwner() {
    return owner;
  }


  @JsonProperty(value = JSON_PROPERTY_OWNER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOwner(@jakarta.annotation.Nullable SimpleUser owner) {
    this.owner = owner;
  }


  public ReportTemplateListItem description(@jakarta.annotation.Nullable String description) {
    this.description = description;
    return this;
  }

  /**
   * A description for the report template
   * @return description
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescription() {
    return description;
  }


  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(@jakarta.annotation.Nullable String description) {
    this.description = description;
  }


  public ReportTemplateListItem savedFilter(@jakarta.annotation.Nullable ReportTemplateSavedFilter savedFilter) {
    this.savedFilter = savedFilter;
    return this;
  }

  /**
   * Get savedFilter
   * @return savedFilter
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SAVED_FILTER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ReportTemplateSavedFilter getSavedFilter() {
    return savedFilter;
  }


  @JsonProperty(value = JSON_PROPERTY_SAVED_FILTER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSavedFilter(@jakarta.annotation.Nullable ReportTemplateSavedFilter savedFilter) {
    this.savedFilter = savedFilter;
  }


  public ReportTemplateListItem reportType(@jakarta.annotation.Nullable ReportTypeEnum reportType) {
    this.reportType = reportType;
    return this;
  }

  /**
   * Get reportType
   * @return reportType
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_REPORT_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ReportTypeEnum getReportType() {
    return reportType;
  }


  @JsonProperty(value = JSON_PROPERTY_REPORT_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReportType(@jakarta.annotation.Nullable ReportTypeEnum reportType) {
    this.reportType = reportType;
  }


  public ReportTemplateListItem schedule(@jakarta.annotation.Nullable Map<String, Object> schedule) {
    this.schedule = schedule;
    return this;
  }

  public ReportTemplateListItem putScheduleItem(String key, Object scheduleItem) {
    if (this.schedule == null) {
      this.schedule = new HashMap<>();
    }
    this.schedule.put(key, scheduleItem);
    return this;
  }

  /**
   * Get schedule
   * @return schedule
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SCHEDULE, required = false)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, Object> getSchedule() {
    return schedule;
  }


  @JsonProperty(value = JSON_PROPERTY_SCHEDULE, required = false)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)
  public void setSchedule(@jakarta.annotation.Nullable Map<String, Object> schedule) {
    this.schedule = schedule;
  }


  public ReportTemplateListItem recipients(@jakarta.annotation.Nullable List<String> recipients) {
    this.recipients = recipients;
    return this;
  }

  public ReportTemplateListItem addRecipientsItem(String recipientsItem) {
    if (this.recipients == null) {
      this.recipients = new ArrayList<>();
    }
    this.recipients.add(recipientsItem);
    return this;
  }

  /**
   * A list of email addresses
   * @return recipients
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_RECIPIENTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getRecipients() {
    return recipients;
  }


  @JsonProperty(value = JSON_PROPERTY_RECIPIENTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRecipients(@jakarta.annotation.Nullable List<String> recipients) {
    this.recipients = recipients;
  }


  public ReportTemplateListItem projectIds(@jakarta.annotation.Nullable List<Integer> projectIds) {
    this.projectIds = projectIds;
    return this;
  }

  public ReportTemplateListItem addProjectIdsItem(Integer projectIdsItem) {
    if (this.projectIds == null) {
      this.projectIds = new ArrayList<>();
    }
    this.projectIds.add(projectIdsItem);
    return this;
  }

  /**
   * A list of project IDs
   * @return projectIds
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PROJECT_IDS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Integer> getProjectIds() {
    return projectIds;
  }


  @JsonProperty(value = JSON_PROPERTY_PROJECT_IDS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProjectIds(@jakarta.annotation.Nullable List<Integer> projectIds) {
    this.projectIds = projectIds;
  }


  public ReportTemplateListItem canEdit(@jakarta.annotation.Nullable Boolean canEdit) {
    this.canEdit = canEdit;
    return this;
  }

  /**
   * A flag indicating whether the current user can edit the template
   * @return canEdit
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CAN_EDIT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getCanEdit() {
    return canEdit;
  }


  @JsonProperty(value = JSON_PROPERTY_CAN_EDIT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCanEdit(@jakarta.annotation.Nullable Boolean canEdit) {
    this.canEdit = canEdit;
  }


  /**
   * Return true if this ReportTemplateListItem object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReportTemplateListItem reportTemplateListItem = (ReportTemplateListItem) o;
    return Objects.equals(this.id, reportTemplateListItem.id) &&
        Objects.equals(this.name, reportTemplateListItem.name) &&
        Objects.equals(this.owner, reportTemplateListItem.owner) &&
        Objects.equals(this.description, reportTemplateListItem.description) &&
        Objects.equals(this.savedFilter, reportTemplateListItem.savedFilter) &&
        Objects.equals(this.reportType, reportTemplateListItem.reportType) &&
        Objects.equals(this.schedule, reportTemplateListItem.schedule) &&
        Objects.equals(this.recipients, reportTemplateListItem.recipients) &&
        Objects.equals(this.projectIds, reportTemplateListItem.projectIds) &&
        Objects.equals(this.canEdit, reportTemplateListItem.canEdit);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, owner, description, savedFilter, reportType, schedule, recipients, projectIds, canEdit);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReportTemplateListItem {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    owner: ").append(toIndentedString(owner)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    savedFilter: ").append(toIndentedString(savedFilter)).append("\n");
    sb.append("    reportType: ").append(toIndentedString(reportType)).append("\n");
    sb.append("    schedule: ").append(toIndentedString(schedule)).append("\n");
    sb.append("    recipients: ").append(toIndentedString(recipients)).append("\n");
    sb.append("    projectIds: ").append(toIndentedString(projectIds)).append("\n");
    sb.append("    canEdit: ").append(toIndentedString(canEdit)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

