/*
 * Software Risk Manager API Guide
 * Software Risk Manager provides a variety of REST APIs, allowing external applications and scripts to interface with core functionality. This guide documents the various REST resources provided by Software Risk Manager.  ## Authentication  Authentication is a requirement when accessing API endpoints. There are two methods by which authentication may be performed.  ### API Keys  The primary method for authentication is passing an `API-Key` header containing a valid API key with all requests, i.e.  `API-Key: <key goes here>`  API Keys come in two possible forms:   - `api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24` - latest format  - `550e8400-e29b-41d4-a716-44665544000` - legacy format  For example:  `API-Key: api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24`  `API-Key: 550e8400-e29b-41d4-a716-44665544000`  API keys may be generated by Software Risk Manager admins. Once they are generated, in most cases, they behave like regular users. They will need to be assigned user roles for any projects they will be used with. Although it is possible to assign the *admin* [role](../user_guide/Project-Management/user_role_configuration.html) to an API key, the recommendation is to avoid doing so unless absolutely necessary.  See the user guide for an overview about how to create and manage [API keys](../user_guide/Settings/api_keys_administration.html).  ### Personal Access Tokens  Personal Access Tokens can be used as [bearer tokens](https://swagger.io/docs/specification/authentication/bearer-authentication/), e.g.  `Authorization: Bearer secret-token:qRuXr1BqgoTWXNxUhYQ8H_Yl2zfy6vxuqMIRnkGO`  Personal Access Tokens can be created by any user, and represent a subset of that user's permissions.   ### HTTP Basic Authentication  HTTP Basic authentication may be used to authenticate with the API as a regular user. This is accomplished by including an `Authorization` header containing a typical authorization credential.  ## Error Handling  ### Bad Requests  For API calls that accept input, invalid values will trigger an HTTP 400 Bad Request status code.  ### Server Errors  For any API call, if an unexpected error occurs, an HTTP 500 Internal Server Error status code will be returned. If an error message is available, the response will include a basic message body describing the error:  ` {   \"error\": \"error message\" } `  The error property will contain a string message indicating the nature of the error.  ### Errors with Third-Party Applications  Sometimes Software Risk Manager must communicate with third-party applications like JIRA, Git, and certain enterprise tools. Some users may have in-house versions of these with self-signed certificates which may not be \"trusted\". In these cases, the API will respond with an HTTP 502 BAD GATEWAY status. If this happens, refer to [Trusting Certificates](../install_guide/Installation/trusting-certs.html) in the install guide.  ### API Unavailable  In special circumstances, particularly during the installation and update phases, the API will be unavailable. When the API is unavailable, all calls will return an HTTP 503 Service Unavailable status, and no actions or side effects will occur as a result of the calls.  ## Examples  Software Risk Manager's API uses REST over HTTP. As such, you can use any language/utility that supports making HTTP requests to interact with the API. The examples below use <a href=\"https://curl.haxx.se/\" target=\"_blank\">curl</a>, a popular command-line utility, to do so.  First, you'll need to [generate an API Key](../user_guide/Settings/api_keys_administration.html). Second, while you can create projects through the API, these examples will assume that you've already created one. You'll need to know its project id number, which you can find by looking at the URL for the [Findings Page](../user_guide/Findings/findings_overview.html), which will end in a number.  **Note:** Many API endpoints require a JSON body in the request. Most JSON will contain double-quotes (`\"`) and spaces, which have special meaning when used on the command line. In order to ensure your JSON body is interpreted as a single argument, you must <a href=\"https://en.wikipedia.org/wiki/Escape_character\" target=\"_blank\">escape</a> it properly. For example, if you wanted to `POST` the following JSON body:  ```{ \"name\": \"John Doe\" }```  You would put a backslash (`\\`) before each double-quote (`\"`), and surround the whole thing with double-quotes:  ```\"{ \\\"name\\\": \\\"John Doe\\\" }\"```  The outermost double-quotes tell the command-line interpreter that everything within them is to be treated as a single argument (as opposed to the usual space-separated behavior). The backslash before each inner double-quote tells the command-line interpreter that you mean the literal double-quote character, and not the end of the quoted argument.  In many *non-Windows* operating systems, you can also use a single-quote (`'`) to surround the argument, and skip the backslashes:  ```'{ \"name\": \"John Doe\" }'```  The examples below will use the double-quotes and backslashes style, as it works on most (if not all) operating systems.  ### Running an Analysis  To start an analysis, you can run  ```curl -F file1=@src.zip -H \"API-Key: api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24\" https://<yoursrmserver>/srm/api/projects/<project id>/analysis```  Make sure you use your own values for the `src.zip` file, the API Key, the hostname for your Software Risk Manager server, and the project id.  ### Retrieving Finding Data  There is a wide variety of data available for the findings of a project after running an analysis. Two examples are provided here.  ### Findings Table Data  You can retrieve the data that's used to populate the [findings table](../user_guide/Findings/findings_table.html):  ```curl -H \"Content-Type: application/json\" -X POST -d \"{\\\"filter\\\":{},\\\"sort\\\":{\\\"by\\\":\\\"id\\\",\\\"direction\\\":\\\"ascending\\\"},\\\"pagination\\\":{\\\"page\\\":1,\\\"perPage\\\":10}}\" -H \"API-Key: api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24\" https://<yoursrmserver>/srm/api/projects/<project id>/findings/table```  Additional information about how to construct more useful filter and sort requests can be found in the documentation.  ### Finding Metadata  You can retrieve metadata for a finding, if you know the finding ID. You can take the ID for a finding from the Findings Table:  ```curl -H \"API-Key: api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24\" https://<yoursrmserver>/srm/api/findings/<finding id>```  ### Generating a Report  You can use the API to generate a PDF [report](../user_guide/Findings/generate_report.html).  ```curl -H \"Content-Type: application/json\" -X POST -d \"{\\\"filter\\\":{},\\\"config\\\":{\\\"summaryMode\\\":\\\"simple\\\",\\\"detailsMode\\\":\\\"simple\\\",\\\"includeResultDetails\\\":true,\\\"includeComments\\\":false}}\" -H \"API-Key: api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24\" https://<yoursrmserver>/srm/api/projects/<project id>/report/pdf```  ## Generating a Client SDK  If you require a client SDK for Software Risk Manager, you can generate one using [OpenAPI Generator](https://openapi-generator.tech/). Detailed instructions are available on the [GitHub page](https://github.com/OpenAPITools/openapi-generator) and our OpenAPI spec can be found [here](swagger/swagger.json). 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.codedx.client.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.codedx.client.model.Cookie;
import com.codedx.client.model.Header;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.codedx.client.JSON;


/**
 * RequestResponse
 */
@JsonPropertyOrder({
  RequestResponse.JSON_PROPERTY_ID,
  RequestResponse.JSON_PROPERTY_HASH,
  RequestResponse.JSON_PROPERTY_METHOD,
  RequestResponse.JSON_PROPERTY_CODE,
  RequestResponse.JSON_PROPERTY_REASON_PHRASE,
  RequestResponse.JSON_PROPERTY_HTTP_VERSION,
  RequestResponse.JSON_PROPERTY_PATHS,
  RequestResponse.JSON_PROPERTY_QUERY_RAW,
  RequestResponse.JSON_PROPERTY_HEADERS,
  RequestResponse.JSON_PROPERTY_HEADERS_RAW,
  RequestResponse.JSON_PROPERTY_COOKIES,
  RequestResponse.JSON_PROPERTY_BODY_LENGTH,
  RequestResponse.JSON_PROPERTY_BODY_ORIGINAL_LENGTH,
  RequestResponse.JSON_PROPERTY_BODY
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-02T11:55:06.722228-04:00[America/New_York]", comments = "Generator version: 7.21.0")
public class RequestResponse {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nullable
  private Integer id;

  public static final String JSON_PROPERTY_HASH = "hash";
  @jakarta.annotation.Nullable
  private String hash;

  public static final String JSON_PROPERTY_METHOD = "method";
  @jakarta.annotation.Nullable
  private String method;

  public static final String JSON_PROPERTY_CODE = "code";
  @jakarta.annotation.Nullable
  private Integer code;

  public static final String JSON_PROPERTY_REASON_PHRASE = "reason-phrase";
  @jakarta.annotation.Nullable
  private String reasonPhrase;

  public static final String JSON_PROPERTY_HTTP_VERSION = "http-version";
  @jakarta.annotation.Nullable
  private String httpVersion;

  public static final String JSON_PROPERTY_PATHS = "paths";
  @jakarta.annotation.Nullable
  private String paths;

  public static final String JSON_PROPERTY_QUERY_RAW = "query-raw";
  @jakarta.annotation.Nullable
  private String queryRaw;

  public static final String JSON_PROPERTY_HEADERS = "headers";
  @jakarta.annotation.Nullable
  private List<Header> headers = new ArrayList<>();

  public static final String JSON_PROPERTY_HEADERS_RAW = "headers-raw";
  @jakarta.annotation.Nullable
  private String headersRaw;

  public static final String JSON_PROPERTY_COOKIES = "cookies";
  @jakarta.annotation.Nullable
  private List<Cookie> cookies = new ArrayList<>();

  public static final String JSON_PROPERTY_BODY_LENGTH = "bodyLength";
  @jakarta.annotation.Nullable
  private Integer bodyLength;

  public static final String JSON_PROPERTY_BODY_ORIGINAL_LENGTH = "bodyOriginalLength";
  @jakarta.annotation.Nullable
  private Integer bodyOriginalLength;

  public static final String JSON_PROPERTY_BODY = "body";
  @jakarta.annotation.Nullable
  private String body;

  public RequestResponse() { 
  }

  public RequestResponse id(@jakarta.annotation.Nullable Integer id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@jakarta.annotation.Nullable Integer id) {
    this.id = id;
  }


  public RequestResponse hash(@jakarta.annotation.Nullable String hash) {
    this.hash = hash;
    return this;
  }

  /**
   * Get hash
   * @return hash
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_HASH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getHash() {
    return hash;
  }


  @JsonProperty(value = JSON_PROPERTY_HASH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHash(@jakarta.annotation.Nullable String hash) {
    this.hash = hash;
  }


  public RequestResponse method(@jakarta.annotation.Nullable String method) {
    this.method = method;
    return this;
  }

  /**
   * Get method
   * @return method
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_METHOD, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMethod() {
    return method;
  }


  @JsonProperty(value = JSON_PROPERTY_METHOD, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMethod(@jakarta.annotation.Nullable String method) {
    this.method = method;
  }


  public RequestResponse code(@jakarta.annotation.Nullable Integer code) {
    this.code = code;
    return this;
  }

  /**
   * Get code
   * @return code
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CODE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getCode() {
    return code;
  }


  @JsonProperty(value = JSON_PROPERTY_CODE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCode(@jakarta.annotation.Nullable Integer code) {
    this.code = code;
  }


  public RequestResponse reasonPhrase(@jakarta.annotation.Nullable String reasonPhrase) {
    this.reasonPhrase = reasonPhrase;
    return this;
  }

  /**
   * Get reasonPhrase
   * @return reasonPhrase
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_REASON_PHRASE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getReasonPhrase() {
    return reasonPhrase;
  }


  @JsonProperty(value = JSON_PROPERTY_REASON_PHRASE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReasonPhrase(@jakarta.annotation.Nullable String reasonPhrase) {
    this.reasonPhrase = reasonPhrase;
  }


  public RequestResponse httpVersion(@jakarta.annotation.Nullable String httpVersion) {
    this.httpVersion = httpVersion;
    return this;
  }

  /**
   * Get httpVersion
   * @return httpVersion
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_HTTP_VERSION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getHttpVersion() {
    return httpVersion;
  }


  @JsonProperty(value = JSON_PROPERTY_HTTP_VERSION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHttpVersion(@jakarta.annotation.Nullable String httpVersion) {
    this.httpVersion = httpVersion;
  }


  public RequestResponse paths(@jakarta.annotation.Nullable String paths) {
    this.paths = paths;
    return this;
  }

  /**
   * Get paths
   * @return paths
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PATHS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPaths() {
    return paths;
  }


  @JsonProperty(value = JSON_PROPERTY_PATHS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPaths(@jakarta.annotation.Nullable String paths) {
    this.paths = paths;
  }


  public RequestResponse queryRaw(@jakarta.annotation.Nullable String queryRaw) {
    this.queryRaw = queryRaw;
    return this;
  }

  /**
   * Get queryRaw
   * @return queryRaw
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_QUERY_RAW, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getQueryRaw() {
    return queryRaw;
  }


  @JsonProperty(value = JSON_PROPERTY_QUERY_RAW, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setQueryRaw(@jakarta.annotation.Nullable String queryRaw) {
    this.queryRaw = queryRaw;
  }


  public RequestResponse headers(@jakarta.annotation.Nullable List<Header> headers) {
    this.headers = headers;
    return this;
  }

  public RequestResponse addHeadersItem(Header headersItem) {
    if (this.headers == null) {
      this.headers = new ArrayList<>();
    }
    this.headers.add(headersItem);
    return this;
  }

  /**
   * Get headers
   * @return headers
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_HEADERS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Header> getHeaders() {
    return headers;
  }


  @JsonProperty(value = JSON_PROPERTY_HEADERS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHeaders(@jakarta.annotation.Nullable List<Header> headers) {
    this.headers = headers;
  }


  public RequestResponse headersRaw(@jakarta.annotation.Nullable String headersRaw) {
    this.headersRaw = headersRaw;
    return this;
  }

  /**
   * Get headersRaw
   * @return headersRaw
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_HEADERS_RAW, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getHeadersRaw() {
    return headersRaw;
  }


  @JsonProperty(value = JSON_PROPERTY_HEADERS_RAW, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHeadersRaw(@jakarta.annotation.Nullable String headersRaw) {
    this.headersRaw = headersRaw;
  }


  public RequestResponse cookies(@jakarta.annotation.Nullable List<Cookie> cookies) {
    this.cookies = cookies;
    return this;
  }

  public RequestResponse addCookiesItem(Cookie cookiesItem) {
    if (this.cookies == null) {
      this.cookies = new ArrayList<>();
    }
    this.cookies.add(cookiesItem);
    return this;
  }

  /**
   * Get cookies
   * @return cookies
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_COOKIES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Cookie> getCookies() {
    return cookies;
  }


  @JsonProperty(value = JSON_PROPERTY_COOKIES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCookies(@jakarta.annotation.Nullable List<Cookie> cookies) {
    this.cookies = cookies;
  }


  public RequestResponse bodyLength(@jakarta.annotation.Nullable Integer bodyLength) {
    this.bodyLength = bodyLength;
    return this;
  }

  /**
   * Get bodyLength
   * @return bodyLength
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BODY_LENGTH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getBodyLength() {
    return bodyLength;
  }


  @JsonProperty(value = JSON_PROPERTY_BODY_LENGTH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBodyLength(@jakarta.annotation.Nullable Integer bodyLength) {
    this.bodyLength = bodyLength;
  }


  public RequestResponse bodyOriginalLength(@jakarta.annotation.Nullable Integer bodyOriginalLength) {
    this.bodyOriginalLength = bodyOriginalLength;
    return this;
  }

  /**
   * Get bodyOriginalLength
   * @return bodyOriginalLength
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BODY_ORIGINAL_LENGTH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getBodyOriginalLength() {
    return bodyOriginalLength;
  }


  @JsonProperty(value = JSON_PROPERTY_BODY_ORIGINAL_LENGTH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBodyOriginalLength(@jakarta.annotation.Nullable Integer bodyOriginalLength) {
    this.bodyOriginalLength = bodyOriginalLength;
  }


  public RequestResponse body(@jakarta.annotation.Nullable String body) {
    this.body = body;
    return this;
  }

  /**
   * The raw request/response body, encoded with base64
   * @return body
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BODY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getBody() {
    return body;
  }


  @JsonProperty(value = JSON_PROPERTY_BODY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBody(@jakarta.annotation.Nullable String body) {
    this.body = body;
  }


  /**
   * Return true if this RequestResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RequestResponse requestResponse = (RequestResponse) o;
    return Objects.equals(this.id, requestResponse.id) &&
        Objects.equals(this.hash, requestResponse.hash) &&
        Objects.equals(this.method, requestResponse.method) &&
        Objects.equals(this.code, requestResponse.code) &&
        Objects.equals(this.reasonPhrase, requestResponse.reasonPhrase) &&
        Objects.equals(this.httpVersion, requestResponse.httpVersion) &&
        Objects.equals(this.paths, requestResponse.paths) &&
        Objects.equals(this.queryRaw, requestResponse.queryRaw) &&
        Objects.equals(this.headers, requestResponse.headers) &&
        Objects.equals(this.headersRaw, requestResponse.headersRaw) &&
        Objects.equals(this.cookies, requestResponse.cookies) &&
        Objects.equals(this.bodyLength, requestResponse.bodyLength) &&
        Objects.equals(this.bodyOriginalLength, requestResponse.bodyOriginalLength) &&
        Objects.equals(this.body, requestResponse.body);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, hash, method, code, reasonPhrase, httpVersion, paths, queryRaw, headers, headersRaw, cookies, bodyLength, bodyOriginalLength, body);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RequestResponse {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    hash: ").append(toIndentedString(hash)).append("\n");
    sb.append("    method: ").append(toIndentedString(method)).append("\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    reasonPhrase: ").append(toIndentedString(reasonPhrase)).append("\n");
    sb.append("    httpVersion: ").append(toIndentedString(httpVersion)).append("\n");
    sb.append("    paths: ").append(toIndentedString(paths)).append("\n");
    sb.append("    queryRaw: ").append(toIndentedString(queryRaw)).append("\n");
    sb.append("    headers: ").append(toIndentedString(headers)).append("\n");
    sb.append("    headersRaw: ").append(toIndentedString(headersRaw)).append("\n");
    sb.append("    cookies: ").append(toIndentedString(cookies)).append("\n");
    sb.append("    bodyLength: ").append(toIndentedString(bodyLength)).append("\n");
    sb.append("    bodyOriginalLength: ").append(toIndentedString(bodyOriginalLength)).append("\n");
    sb.append("    body: ").append(toIndentedString(body)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

