/*
 * Software Risk Manager API Guide
 * Software Risk Manager provides a variety of REST APIs, allowing external applications and scripts to interface with core functionality. This guide documents the various REST resources provided by Software Risk Manager.  ## Authentication  Authentication is a requirement when accessing API endpoints. There are two methods by which authentication may be performed.  ### API Keys  The primary method for authentication is passing an `API-Key` header containing a valid API key with all requests, i.e.  `API-Key: <key goes here>`  API Keys come in two possible forms:   - `api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24` - latest format  - `550e8400-e29b-41d4-a716-44665544000` - legacy format  For example:  `API-Key: api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24`  `API-Key: 550e8400-e29b-41d4-a716-44665544000`  API keys may be generated by Software Risk Manager admins. Once they are generated, in most cases, they behave like regular users. They will need to be assigned user roles for any projects they will be used with. Although it is possible to assign the *admin* [role](../user_guide/Project-Management/user_role_configuration.html) to an API key, the recommendation is to avoid doing so unless absolutely necessary.  See the user guide for an overview about how to create and manage [API keys](../user_guide/Settings/api_keys_administration.html).  ### Personal Access Tokens  Personal Access Tokens can be used as [bearer tokens](https://swagger.io/docs/specification/authentication/bearer-authentication/), e.g.  `Authorization: Bearer secret-token:qRuXr1BqgoTWXNxUhYQ8H_Yl2zfy6vxuqMIRnkGO`  Personal Access Tokens can be created by any user, and represent a subset of that user's permissions.   ### HTTP Basic Authentication  HTTP Basic authentication may be used to authenticate with the API as a regular user. This is accomplished by including an `Authorization` header containing a typical authorization credential.  ## Error Handling  ### Bad Requests  For API calls that accept input, invalid values will trigger an HTTP 400 Bad Request status code.  ### Server Errors  For any API call, if an unexpected error occurs, an HTTP 500 Internal Server Error status code will be returned. If an error message is available, the response will include a basic message body describing the error:  ` {   \"error\": \"error message\" } `  The error property will contain a string message indicating the nature of the error.  ### Errors with Third-Party Applications  Sometimes Software Risk Manager must communicate with third-party applications like JIRA, Git, and certain enterprise tools. Some users may have in-house versions of these with self-signed certificates which may not be \"trusted\". In these cases, the API will respond with an HTTP 502 BAD GATEWAY status. If this happens, refer to [Trusting Certificates](../install_guide/Installation/trusting-certs.html) in the install guide.  ### API Unavailable  In special circumstances, particularly during the installation and update phases, the API will be unavailable. When the API is unavailable, all calls will return an HTTP 503 Service Unavailable status, and no actions or side effects will occur as a result of the calls.  ## Examples  Software Risk Manager's API uses REST over HTTP. As such, you can use any language/utility that supports making HTTP requests to interact with the API. The examples below use <a href=\"https://curl.haxx.se/\" target=\"_blank\">curl</a>, a popular command-line utility, to do so.  First, you'll need to [generate an API Key](../user_guide/Settings/api_keys_administration.html). Second, while you can create projects through the API, these examples will assume that you've already created one. You'll need to know its project id number, which you can find by looking at the URL for the [Findings Page](../user_guide/Findings/findings_overview.html), which will end in a number.  **Note:** Many API endpoints require a JSON body in the request. Most JSON will contain double-quotes (`\"`) and spaces, which have special meaning when used on the command line. In order to ensure your JSON body is interpreted as a single argument, you must <a href=\"https://en.wikipedia.org/wiki/Escape_character\" target=\"_blank\">escape</a> it properly. For example, if you wanted to `POST` the following JSON body:  ```{ \"name\": \"John Doe\" }```  You would put a backslash (`\\`) before each double-quote (`\"`), and surround the whole thing with double-quotes:  ```\"{ \\\"name\\\": \\\"John Doe\\\" }\"```  The outermost double-quotes tell the command-line interpreter that everything within them is to be treated as a single argument (as opposed to the usual space-separated behavior). The backslash before each inner double-quote tells the command-line interpreter that you mean the literal double-quote character, and not the end of the quoted argument.  In many *non-Windows* operating systems, you can also use a single-quote (`'`) to surround the argument, and skip the backslashes:  ```'{ \"name\": \"John Doe\" }'```  The examples below will use the double-quotes and backslashes style, as it works on most (if not all) operating systems.  ### Running an Analysis  To start an analysis, you can run  ```curl -F file1=@src.zip -H \"API-Key: api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24\" https://<yoursrmserver>/srm/api/projects/<project id>/analysis```  Make sure you use your own values for the `src.zip` file, the API Key, the hostname for your Software Risk Manager server, and the project id.  ### Retrieving Finding Data  There is a wide variety of data available for the findings of a project after running an analysis. Two examples are provided here.  ### Findings Table Data  You can retrieve the data that's used to populate the [findings table](../user_guide/Findings/findings_table.html):  ```curl -H \"Content-Type: application/json\" -X POST -d \"{\\\"filter\\\":{},\\\"sort\\\":{\\\"by\\\":\\\"id\\\",\\\"direction\\\":\\\"ascending\\\"},\\\"pagination\\\":{\\\"page\\\":1,\\\"perPage\\\":10}}\" -H \"API-Key: api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24\" https://<yoursrmserver>/srm/api/projects/<project id>/findings/table```  Additional information about how to construct more useful filter and sort requests can be found in the documentation.  ### Finding Metadata  You can retrieve metadata for a finding, if you know the finding ID. You can take the ID for a finding from the Findings Table:  ```curl -H \"API-Key: api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24\" https://<yoursrmserver>/srm/api/findings/<finding id>```  ### Generating a Report  You can use the API to generate a PDF [report](../user_guide/Findings/generate_report.html).  ```curl -H \"Content-Type: application/json\" -X POST -d \"{\\\"filter\\\":{},\\\"config\\\":{\\\"summaryMode\\\":\\\"simple\\\",\\\"detailsMode\\\":\\\"simple\\\",\\\"includeResultDetails\\\":true,\\\"includeComments\\\":false}}\" -H \"API-Key: api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24\" https://<yoursrmserver>/srm/api/projects/<project id>/report/pdf```  ## Generating a Client SDK  If you require a client SDK for Software Risk Manager, you can generate one using [OpenAPI Generator](https://openapi-generator.tech/). Detailed instructions are available on the [GitHub page](https://github.com/OpenAPITools/openapi-generator) and our OpenAPI spec can be found [here](swagger/swagger.json). 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.codedx.client.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.codedx.client.model.Cwe;
import com.codedx.client.model.Descriptions;
import com.codedx.client.model.DetectionMethod;
import com.codedx.client.model.FindingDescriptor;
import com.codedx.client.model.ResultComponent;
import com.codedx.client.model.Severity;
import com.codedx.client.model.ToolResultLocation;
import com.codedx.client.model.Variant;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.codedx.client.JSON;


/**
 * ToolResult
 */
@JsonPropertyOrder({
  ToolResult.JSON_PROPERTY_ID,
  ToolResult.JSON_PROPERTY_IS_MANUAL,
  ToolResult.JSON_PROPERTY_DETECTION_METHOD,
  ToolResult.JSON_PROPERTY_TOOL,
  ToolResult.JSON_PROPERTY_SEVERITY,
  ToolResult.JSON_PROPERTY_CONTEXTUAL_SEVERITY,
  ToolResult.JSON_PROPERTY_CWE,
  ToolResult.JSON_PROPERTY_CONTEXTUAL_CWE,
  ToolResult.JSON_PROPERTY_TOOL_HIERARCHY,
  ToolResult.JSON_PROPERTY_DESCRIPTOR,
  ToolResult.JSON_PROPERTY_LOCATION,
  ToolResult.JSON_PROPERTY_METADATA,
  ToolResult.JSON_PROPERTY_DESCRIPTIONS,
  ToolResult.JSON_PROPERTY_VARIANTS,
  ToolResult.JSON_PROPERTY_COMPONENT
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-02T11:55:06.722228-04:00[America/New_York]", comments = "Generator version: 7.21.0")
public class ToolResult {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nullable
  private Integer id;

  public static final String JSON_PROPERTY_IS_MANUAL = "isManual";
  @jakarta.annotation.Nullable
  private Boolean isManual;

  public static final String JSON_PROPERTY_DETECTION_METHOD = "detectionMethod";
  @jakarta.annotation.Nullable
  private DetectionMethod detectionMethod;

  public static final String JSON_PROPERTY_TOOL = "tool";
  @jakarta.annotation.Nullable
  private String tool;

  public static final String JSON_PROPERTY_SEVERITY = "severity";
  @jakarta.annotation.Nullable
  private Severity severity;

  public static final String JSON_PROPERTY_CONTEXTUAL_SEVERITY = "contextualSeverity";
  @jakarta.annotation.Nullable
  private Severity contextualSeverity;

  public static final String JSON_PROPERTY_CWE = "cwe";
  @jakarta.annotation.Nullable
  private Cwe cwe;

  public static final String JSON_PROPERTY_CONTEXTUAL_CWE = "contextualCwe";
  @jakarta.annotation.Nullable
  private Cwe contextualCwe;

  public static final String JSON_PROPERTY_TOOL_HIERARCHY = "toolHierarchy";
  @jakarta.annotation.Nullable
  private List<String> toolHierarchy = new ArrayList<>();

  public static final String JSON_PROPERTY_DESCRIPTOR = "descriptor";
  @jakarta.annotation.Nullable
  private FindingDescriptor descriptor;

  public static final String JSON_PROPERTY_LOCATION = "location";
  @jakarta.annotation.Nullable
  private ToolResultLocation location;

  public static final String JSON_PROPERTY_METADATA = "metadata";
  @jakarta.annotation.Nullable
  private Map<String, Object> metadata = new HashMap<>();

  public static final String JSON_PROPERTY_DESCRIPTIONS = "descriptions";
  @jakarta.annotation.Nullable
  private Descriptions descriptions;

  public static final String JSON_PROPERTY_VARIANTS = "variants";
  @jakarta.annotation.Nullable
  private List<Variant> variants = new ArrayList<>();

  public static final String JSON_PROPERTY_COMPONENT = "component";
  @jakarta.annotation.Nullable
  private ResultComponent component;

  public ToolResult() { 
  }

  public ToolResult id(@jakarta.annotation.Nullable Integer id) {
    this.id = id;
    return this;
  }

  /**
   * hello
   * @return id
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@jakarta.annotation.Nullable Integer id) {
    this.id = id;
  }


  public ToolResult isManual(@jakarta.annotation.Nullable Boolean isManual) {
    this.isManual = isManual;
    return this;
  }

  /**
   * Get isManual
   * @return isManual
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_IS_MANUAL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getIsManual() {
    return isManual;
  }


  @JsonProperty(value = JSON_PROPERTY_IS_MANUAL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsManual(@jakarta.annotation.Nullable Boolean isManual) {
    this.isManual = isManual;
  }


  public ToolResult detectionMethod(@jakarta.annotation.Nullable DetectionMethod detectionMethod) {
    this.detectionMethod = detectionMethod;
    return this;
  }

  /**
   * Get detectionMethod
   * @return detectionMethod
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DETECTION_METHOD, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public DetectionMethod getDetectionMethod() {
    return detectionMethod;
  }


  @JsonProperty(value = JSON_PROPERTY_DETECTION_METHOD, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDetectionMethod(@jakarta.annotation.Nullable DetectionMethod detectionMethod) {
    this.detectionMethod = detectionMethod;
  }


  public ToolResult tool(@jakarta.annotation.Nullable String tool) {
    this.tool = tool;
    return this;
  }

  /**
   * Get tool
   * @return tool
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TOOL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTool() {
    return tool;
  }


  @JsonProperty(value = JSON_PROPERTY_TOOL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTool(@jakarta.annotation.Nullable String tool) {
    this.tool = tool;
  }


  public ToolResult severity(@jakarta.annotation.Nullable Severity severity) {
    this.severity = severity;
    return this;
  }

  /**
   * Get severity
   * @return severity
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SEVERITY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Severity getSeverity() {
    return severity;
  }


  @JsonProperty(value = JSON_PROPERTY_SEVERITY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSeverity(@jakarta.annotation.Nullable Severity severity) {
    this.severity = severity;
  }


  public ToolResult contextualSeverity(@jakarta.annotation.Nullable Severity contextualSeverity) {
    this.contextualSeverity = contextualSeverity;
    return this;
  }

  /**
   * Get contextualSeverity
   * @return contextualSeverity
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CONTEXTUAL_SEVERITY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Severity getContextualSeverity() {
    return contextualSeverity;
  }


  @JsonProperty(value = JSON_PROPERTY_CONTEXTUAL_SEVERITY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setContextualSeverity(@jakarta.annotation.Nullable Severity contextualSeverity) {
    this.contextualSeverity = contextualSeverity;
  }


  public ToolResult cwe(@jakarta.annotation.Nullable Cwe cwe) {
    this.cwe = cwe;
    return this;
  }

  /**
   * Get cwe
   * @return cwe
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CWE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Cwe getCwe() {
    return cwe;
  }


  @JsonProperty(value = JSON_PROPERTY_CWE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCwe(@jakarta.annotation.Nullable Cwe cwe) {
    this.cwe = cwe;
  }


  public ToolResult contextualCwe(@jakarta.annotation.Nullable Cwe contextualCwe) {
    this.contextualCwe = contextualCwe;
    return this;
  }

  /**
   * Get contextualCwe
   * @return contextualCwe
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CONTEXTUAL_CWE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Cwe getContextualCwe() {
    return contextualCwe;
  }


  @JsonProperty(value = JSON_PROPERTY_CONTEXTUAL_CWE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setContextualCwe(@jakarta.annotation.Nullable Cwe contextualCwe) {
    this.contextualCwe = contextualCwe;
  }


  public ToolResult toolHierarchy(@jakarta.annotation.Nullable List<String> toolHierarchy) {
    this.toolHierarchy = toolHierarchy;
    return this;
  }

  public ToolResult addToolHierarchyItem(String toolHierarchyItem) {
    if (this.toolHierarchy == null) {
      this.toolHierarchy = new ArrayList<>();
    }
    this.toolHierarchy.add(toolHierarchyItem);
    return this;
  }

  /**
   * Get toolHierarchy
   * @return toolHierarchy
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TOOL_HIERARCHY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getToolHierarchy() {
    return toolHierarchy;
  }


  @JsonProperty(value = JSON_PROPERTY_TOOL_HIERARCHY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setToolHierarchy(@jakarta.annotation.Nullable List<String> toolHierarchy) {
    this.toolHierarchy = toolHierarchy;
  }


  public ToolResult descriptor(@jakarta.annotation.Nullable FindingDescriptor descriptor) {
    this.descriptor = descriptor;
    return this;
  }

  /**
   * Get descriptor
   * @return descriptor
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DESCRIPTOR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public FindingDescriptor getDescriptor() {
    return descriptor;
  }


  @JsonProperty(value = JSON_PROPERTY_DESCRIPTOR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescriptor(@jakarta.annotation.Nullable FindingDescriptor descriptor) {
    this.descriptor = descriptor;
  }


  public ToolResult location(@jakarta.annotation.Nullable ToolResultLocation location) {
    this.location = location;
    return this;
  }

  /**
   * Get location
   * @return location
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LOCATION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ToolResultLocation getLocation() {
    return location;
  }


  @JsonProperty(value = JSON_PROPERTY_LOCATION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLocation(@jakarta.annotation.Nullable ToolResultLocation location) {
    this.location = location;
  }


  public ToolResult metadata(@jakarta.annotation.Nullable Map<String, Object> metadata) {
    this.metadata = metadata;
    return this;
  }

  public ToolResult putMetadataItem(String key, Object metadataItem) {
    if (this.metadata == null) {
      this.metadata = new HashMap<>();
    }
    this.metadata.put(key, metadataItem);
    return this;
  }

  /**
   * Get metadata
   * @return metadata
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_METADATA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, Object> getMetadata() {
    return metadata;
  }


  @JsonProperty(value = JSON_PROPERTY_METADATA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMetadata(@jakarta.annotation.Nullable Map<String, Object> metadata) {
    this.metadata = metadata;
  }


  public ToolResult descriptions(@jakarta.annotation.Nullable Descriptions descriptions) {
    this.descriptions = descriptions;
    return this;
  }

  /**
   * Get descriptions
   * @return descriptions
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DESCRIPTIONS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Descriptions getDescriptions() {
    return descriptions;
  }


  @JsonProperty(value = JSON_PROPERTY_DESCRIPTIONS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescriptions(@jakarta.annotation.Nullable Descriptions descriptions) {
    this.descriptions = descriptions;
  }


  public ToolResult variants(@jakarta.annotation.Nullable List<Variant> variants) {
    this.variants = variants;
    return this;
  }

  public ToolResult addVariantsItem(Variant variantsItem) {
    if (this.variants == null) {
      this.variants = new ArrayList<>();
    }
    this.variants.add(variantsItem);
    return this;
  }

  /**
   * Get variants
   * @return variants
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_VARIANTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Variant> getVariants() {
    return variants;
  }


  @JsonProperty(value = JSON_PROPERTY_VARIANTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVariants(@jakarta.annotation.Nullable List<Variant> variants) {
    this.variants = variants;
  }


  public ToolResult component(@jakarta.annotation.Nullable ResultComponent component) {
    this.component = component;
    return this;
  }

  /**
   * Get component
   * @return component
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_COMPONENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ResultComponent getComponent() {
    return component;
  }


  @JsonProperty(value = JSON_PROPERTY_COMPONENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setComponent(@jakarta.annotation.Nullable ResultComponent component) {
    this.component = component;
  }


  /**
   * Return true if this ToolResult object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ToolResult toolResult = (ToolResult) o;
    return Objects.equals(this.id, toolResult.id) &&
        Objects.equals(this.isManual, toolResult.isManual) &&
        Objects.equals(this.detectionMethod, toolResult.detectionMethod) &&
        Objects.equals(this.tool, toolResult.tool) &&
        Objects.equals(this.severity, toolResult.severity) &&
        Objects.equals(this.contextualSeverity, toolResult.contextualSeverity) &&
        Objects.equals(this.cwe, toolResult.cwe) &&
        Objects.equals(this.contextualCwe, toolResult.contextualCwe) &&
        Objects.equals(this.toolHierarchy, toolResult.toolHierarchy) &&
        Objects.equals(this.descriptor, toolResult.descriptor) &&
        Objects.equals(this.location, toolResult.location) &&
        Objects.equals(this.metadata, toolResult.metadata) &&
        Objects.equals(this.descriptions, toolResult.descriptions) &&
        Objects.equals(this.variants, toolResult.variants) &&
        Objects.equals(this.component, toolResult.component);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, isManual, detectionMethod, tool, severity, contextualSeverity, cwe, contextualCwe, toolHierarchy, descriptor, location, metadata, descriptions, variants, component);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ToolResult {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    isManual: ").append(toIndentedString(isManual)).append("\n");
    sb.append("    detectionMethod: ").append(toIndentedString(detectionMethod)).append("\n");
    sb.append("    tool: ").append(toIndentedString(tool)).append("\n");
    sb.append("    severity: ").append(toIndentedString(severity)).append("\n");
    sb.append("    contextualSeverity: ").append(toIndentedString(contextualSeverity)).append("\n");
    sb.append("    cwe: ").append(toIndentedString(cwe)).append("\n");
    sb.append("    contextualCwe: ").append(toIndentedString(contextualCwe)).append("\n");
    sb.append("    toolHierarchy: ").append(toIndentedString(toolHierarchy)).append("\n");
    sb.append("    descriptor: ").append(toIndentedString(descriptor)).append("\n");
    sb.append("    location: ").append(toIndentedString(location)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    descriptions: ").append(toIndentedString(descriptions)).append("\n");
    sb.append("    variants: ").append(toIndentedString(variants)).append("\n");
    sb.append("    component: ").append(toIndentedString(component)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

