/*
 * Software Risk Manager API Guide
 * Software Risk Manager provides a variety of REST APIs, allowing external applications and scripts to interface with core functionality. This guide documents the various REST resources provided by Software Risk Manager.  ## Authentication  Authentication is a requirement when accessing API endpoints. There are two methods by which authentication may be performed.  ### API Keys  The primary method for authentication is passing an `API-Key` header containing a valid API key with all requests, i.e.  `API-Key: <key goes here>`  API Keys come in two possible forms:   - `api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24` - latest format  - `550e8400-e29b-41d4-a716-44665544000` - legacy format  For example:  `API-Key: api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24`  `API-Key: 550e8400-e29b-41d4-a716-44665544000`  API keys may be generated by Software Risk Manager admins. Once they are generated, in most cases, they behave like regular users. They will need to be assigned user roles for any projects they will be used with. Although it is possible to assign the *admin* [role](../user_guide/Project-Management/user_role_configuration.html) to an API key, the recommendation is to avoid doing so unless absolutely necessary.  See the user guide for an overview about how to create and manage [API keys](../user_guide/Settings/api_keys_administration.html).  ### Personal Access Tokens  Personal Access Tokens can be used as [bearer tokens](https://swagger.io/docs/specification/authentication/bearer-authentication/), e.g.  `Authorization: Bearer secret-token:qRuXr1BqgoTWXNxUhYQ8H_Yl2zfy6vxuqMIRnkGO`  Personal Access Tokens can be created by any user, and represent a subset of that user's permissions.   ### HTTP Basic Authentication  HTTP Basic authentication may be used to authenticate with the API as a regular user. This is accomplished by including an `Authorization` header containing a typical authorization credential.  ## Error Handling  ### Bad Requests  For API calls that accept input, invalid values will trigger an HTTP 400 Bad Request status code.  ### Server Errors  For any API call, if an unexpected error occurs, an HTTP 500 Internal Server Error status code will be returned. If an error message is available, the response will include a basic message body describing the error:  ` {   \"error\": \"error message\" } `  The error property will contain a string message indicating the nature of the error.  ### Errors with Third-Party Applications  Sometimes Software Risk Manager must communicate with third-party applications like JIRA, Git, and certain enterprise tools. Some users may have in-house versions of these with self-signed certificates which may not be \"trusted\". In these cases, the API will respond with an HTTP 502 BAD GATEWAY status. If this happens, refer to [Trusting Certificates](../install_guide/Installation/trusting-certs.html) in the install guide.  ### API Unavailable  In special circumstances, particularly during the installation and update phases, the API will be unavailable. When the API is unavailable, all calls will return an HTTP 503 Service Unavailable status, and no actions or side effects will occur as a result of the calls.  ## Examples  Software Risk Manager's API uses REST over HTTP. As such, you can use any language/utility that supports making HTTP requests to interact with the API. The examples below use <a href=\"https://curl.haxx.se/\" target=\"_blank\">curl</a>, a popular command-line utility, to do so.  First, you'll need to [generate an API Key](../user_guide/Settings/api_keys_administration.html). Second, while you can create projects through the API, these examples will assume that you've already created one. You'll need to know its project id number, which you can find by looking at the URL for the [Findings Page](../user_guide/Findings/findings_overview.html), which will end in a number.  **Note:** Many API endpoints require a JSON body in the request. Most JSON will contain double-quotes (`\"`) and spaces, which have special meaning when used on the command line. In order to ensure your JSON body is interpreted as a single argument, you must <a href=\"https://en.wikipedia.org/wiki/Escape_character\" target=\"_blank\">escape</a> it properly. For example, if you wanted to `POST` the following JSON body:  ```{ \"name\": \"John Doe\" }```  You would put a backslash (`\\`) before each double-quote (`\"`), and surround the whole thing with double-quotes:  ```\"{ \\\"name\\\": \\\"John Doe\\\" }\"```  The outermost double-quotes tell the command-line interpreter that everything within them is to be treated as a single argument (as opposed to the usual space-separated behavior). The backslash before each inner double-quote tells the command-line interpreter that you mean the literal double-quote character, and not the end of the quoted argument.  In many *non-Windows* operating systems, you can also use a single-quote (`'`) to surround the argument, and skip the backslashes:  ```'{ \"name\": \"John Doe\" }'```  The examples below will use the double-quotes and backslashes style, as it works on most (if not all) operating systems.  ### Running an Analysis  To start an analysis, you can run  ```curl -F file1=@src.zip -H \"API-Key: api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24\" https://<yoursrmserver>/srm/api/projects/<project id>/analysis```  Make sure you use your own values for the `src.zip` file, the API Key, the hostname for your Software Risk Manager server, and the project id.  ### Retrieving Finding Data  There is a wide variety of data available for the findings of a project after running an analysis. Two examples are provided here.  ### Findings Table Data  You can retrieve the data that's used to populate the [findings table](../user_guide/Findings/findings_table.html):  ```curl -H \"Content-Type: application/json\" -X POST -d \"{\\\"filter\\\":{},\\\"sort\\\":{\\\"by\\\":\\\"id\\\",\\\"direction\\\":\\\"ascending\\\"},\\\"pagination\\\":{\\\"page\\\":1,\\\"perPage\\\":10}}\" -H \"API-Key: api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24\" https://<yoursrmserver>/srm/api/projects/<project id>/findings/table```  Additional information about how to construct more useful filter and sort requests can be found in the documentation.  ### Finding Metadata  You can retrieve metadata for a finding, if you know the finding ID. You can take the ID for a finding from the Findings Table:  ```curl -H \"API-Key: api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24\" https://<yoursrmserver>/srm/api/findings/<finding id>```  ### Generating a Report  You can use the API to generate a PDF [report](../user_guide/Findings/generate_report.html).  ```curl -H \"Content-Type: application/json\" -X POST -d \"{\\\"filter\\\":{},\\\"config\\\":{\\\"summaryMode\\\":\\\"simple\\\",\\\"detailsMode\\\":\\\"simple\\\",\\\"includeResultDetails\\\":true,\\\"includeComments\\\":false}}\" -H \"API-Key: api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24\" https://<yoursrmserver>/srm/api/projects/<project id>/report/pdf```  ## Generating a Client SDK  If you require a client SDK for Software Risk Manager, you can generate one using [OpenAPI Generator](https://openapi-generator.tech/). Detailed instructions are available on the [GitHub page](https://github.com/OpenAPITools/openapi-generator) and our OpenAPI spec can be found [here](swagger/swagger.json). 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.codedx.client.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.codedx.client.model.OverridableNameEntity;
import com.codedx.client.model.Project;
import com.codedx.client.model.SimpleEntity;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.codedx.client.JSON;


/**
 * ToolConnectorBinding
 */
@JsonPropertyOrder({
  ToolConnectorBinding.JSON_PROPERTY_PROJECT,
  ToolConnectorBinding.JSON_PROPERTY_BRANCH_NAME,
  ToolConnectorBinding.JSON_PROPERTY_CONNECTION_ENTITY,
  ToolConnectorBinding.JSON_PROPERTY_SCHEDULE_ENTITY,
  ToolConnectorBinding.JSON_PROPERTY_OPTION_ENTITY,
  ToolConnectorBinding.JSON_PROPERTY_PROJECT_ENTITY,
  ToolConnectorBinding.JSON_PROPERTY_VERSION_ENTITY,
  ToolConnectorBinding.JSON_PROPERTY_SYNC_PROJECT_NAME,
  ToolConnectorBinding.JSON_PROPERTY_SYNC_VERSION_NAME,
  ToolConnectorBinding.JSON_PROPERTY_ENABLED
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-02T11:55:06.722228-04:00[America/New_York]", comments = "Generator version: 7.21.0")
public class ToolConnectorBinding {
  public static final String JSON_PROPERTY_PROJECT = "project";
  @jakarta.annotation.Nullable
  private Project project;

  public static final String JSON_PROPERTY_BRANCH_NAME = "branchName";
  @jakarta.annotation.Nullable
  private String branchName;

  public static final String JSON_PROPERTY_CONNECTION_ENTITY = "connectionEntity";
  @jakarta.annotation.Nullable
  private SimpleEntity connectionEntity;

  public static final String JSON_PROPERTY_SCHEDULE_ENTITY = "scheduleEntity";
  @jakarta.annotation.Nullable
  private SimpleEntity scheduleEntity;

  public static final String JSON_PROPERTY_OPTION_ENTITY = "optionEntity";
  @jakarta.annotation.Nullable
  private SimpleEntity optionEntity;

  public static final String JSON_PROPERTY_PROJECT_ENTITY = "projectEntity";
  @jakarta.annotation.Nullable
  private OverridableNameEntity projectEntity;

  public static final String JSON_PROPERTY_VERSION_ENTITY = "versionEntity";
  @jakarta.annotation.Nullable
  private OverridableNameEntity versionEntity;

  public static final String JSON_PROPERTY_SYNC_PROJECT_NAME = "syncProjectName";
  @jakarta.annotation.Nullable
  private Boolean syncProjectName;

  public static final String JSON_PROPERTY_SYNC_VERSION_NAME = "syncVersionName";
  @jakarta.annotation.Nullable
  private Boolean syncVersionName;

  public static final String JSON_PROPERTY_ENABLED = "enabled";
  @jakarta.annotation.Nullable
  private Boolean enabled;

  public ToolConnectorBinding() { 
  }

  public ToolConnectorBinding project(@jakarta.annotation.Nullable Project project) {
    this.project = project;
    return this;
  }

  /**
   * Get project
   * @return project
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PROJECT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Project getProject() {
    return project;
  }


  @JsonProperty(value = JSON_PROPERTY_PROJECT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProject(@jakarta.annotation.Nullable Project project) {
    this.project = project;
  }


  public ToolConnectorBinding branchName(@jakarta.annotation.Nullable String branchName) {
    this.branchName = branchName;
    return this;
  }

  /**
   * Get branchName
   * @return branchName
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BRANCH_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getBranchName() {
    return branchName;
  }


  @JsonProperty(value = JSON_PROPERTY_BRANCH_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBranchName(@jakarta.annotation.Nullable String branchName) {
    this.branchName = branchName;
  }


  public ToolConnectorBinding connectionEntity(@jakarta.annotation.Nullable SimpleEntity connectionEntity) {
    this.connectionEntity = connectionEntity;
    return this;
  }

  /**
   * Get connectionEntity
   * @return connectionEntity
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CONNECTION_ENTITY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SimpleEntity getConnectionEntity() {
    return connectionEntity;
  }


  @JsonProperty(value = JSON_PROPERTY_CONNECTION_ENTITY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setConnectionEntity(@jakarta.annotation.Nullable SimpleEntity connectionEntity) {
    this.connectionEntity = connectionEntity;
  }


  public ToolConnectorBinding scheduleEntity(@jakarta.annotation.Nullable SimpleEntity scheduleEntity) {
    this.scheduleEntity = scheduleEntity;
    return this;
  }

  /**
   * Get scheduleEntity
   * @return scheduleEntity
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SCHEDULE_ENTITY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SimpleEntity getScheduleEntity() {
    return scheduleEntity;
  }


  @JsonProperty(value = JSON_PROPERTY_SCHEDULE_ENTITY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setScheduleEntity(@jakarta.annotation.Nullable SimpleEntity scheduleEntity) {
    this.scheduleEntity = scheduleEntity;
  }


  public ToolConnectorBinding optionEntity(@jakarta.annotation.Nullable SimpleEntity optionEntity) {
    this.optionEntity = optionEntity;
    return this;
  }

  /**
   * Get optionEntity
   * @return optionEntity
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_OPTION_ENTITY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SimpleEntity getOptionEntity() {
    return optionEntity;
  }


  @JsonProperty(value = JSON_PROPERTY_OPTION_ENTITY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOptionEntity(@jakarta.annotation.Nullable SimpleEntity optionEntity) {
    this.optionEntity = optionEntity;
  }


  public ToolConnectorBinding projectEntity(@jakarta.annotation.Nullable OverridableNameEntity projectEntity) {
    this.projectEntity = projectEntity;
    return this;
  }

  /**
   * Get projectEntity
   * @return projectEntity
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PROJECT_ENTITY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OverridableNameEntity getProjectEntity() {
    return projectEntity;
  }


  @JsonProperty(value = JSON_PROPERTY_PROJECT_ENTITY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProjectEntity(@jakarta.annotation.Nullable OverridableNameEntity projectEntity) {
    this.projectEntity = projectEntity;
  }


  public ToolConnectorBinding versionEntity(@jakarta.annotation.Nullable OverridableNameEntity versionEntity) {
    this.versionEntity = versionEntity;
    return this;
  }

  /**
   * Get versionEntity
   * @return versionEntity
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_VERSION_ENTITY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OverridableNameEntity getVersionEntity() {
    return versionEntity;
  }


  @JsonProperty(value = JSON_PROPERTY_VERSION_ENTITY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVersionEntity(@jakarta.annotation.Nullable OverridableNameEntity versionEntity) {
    this.versionEntity = versionEntity;
  }


  public ToolConnectorBinding syncProjectName(@jakarta.annotation.Nullable Boolean syncProjectName) {
    this.syncProjectName = syncProjectName;
    return this;
  }

  /**
   * Get syncProjectName
   * @return syncProjectName
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SYNC_PROJECT_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getSyncProjectName() {
    return syncProjectName;
  }


  @JsonProperty(value = JSON_PROPERTY_SYNC_PROJECT_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSyncProjectName(@jakarta.annotation.Nullable Boolean syncProjectName) {
    this.syncProjectName = syncProjectName;
  }


  public ToolConnectorBinding syncVersionName(@jakarta.annotation.Nullable Boolean syncVersionName) {
    this.syncVersionName = syncVersionName;
    return this;
  }

  /**
   * Get syncVersionName
   * @return syncVersionName
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SYNC_VERSION_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getSyncVersionName() {
    return syncVersionName;
  }


  @JsonProperty(value = JSON_PROPERTY_SYNC_VERSION_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSyncVersionName(@jakarta.annotation.Nullable Boolean syncVersionName) {
    this.syncVersionName = syncVersionName;
  }


  public ToolConnectorBinding enabled(@jakarta.annotation.Nullable Boolean enabled) {
    this.enabled = enabled;
    return this;
  }

  /**
   * Get enabled
   * @return enabled
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ENABLED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getEnabled() {
    return enabled;
  }


  @JsonProperty(value = JSON_PROPERTY_ENABLED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEnabled(@jakarta.annotation.Nullable Boolean enabled) {
    this.enabled = enabled;
  }


  /**
   * Return true if this ToolConnectorBinding object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ToolConnectorBinding toolConnectorBinding = (ToolConnectorBinding) o;
    return Objects.equals(this.project, toolConnectorBinding.project) &&
        Objects.equals(this.branchName, toolConnectorBinding.branchName) &&
        Objects.equals(this.connectionEntity, toolConnectorBinding.connectionEntity) &&
        Objects.equals(this.scheduleEntity, toolConnectorBinding.scheduleEntity) &&
        Objects.equals(this.optionEntity, toolConnectorBinding.optionEntity) &&
        Objects.equals(this.projectEntity, toolConnectorBinding.projectEntity) &&
        Objects.equals(this.versionEntity, toolConnectorBinding.versionEntity) &&
        Objects.equals(this.syncProjectName, toolConnectorBinding.syncProjectName) &&
        Objects.equals(this.syncVersionName, toolConnectorBinding.syncVersionName) &&
        Objects.equals(this.enabled, toolConnectorBinding.enabled);
  }

  @Override
  public int hashCode() {
    return Objects.hash(project, branchName, connectionEntity, scheduleEntity, optionEntity, projectEntity, versionEntity, syncProjectName, syncVersionName, enabled);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ToolConnectorBinding {\n");
    sb.append("    project: ").append(toIndentedString(project)).append("\n");
    sb.append("    branchName: ").append(toIndentedString(branchName)).append("\n");
    sb.append("    connectionEntity: ").append(toIndentedString(connectionEntity)).append("\n");
    sb.append("    scheduleEntity: ").append(toIndentedString(scheduleEntity)).append("\n");
    sb.append("    optionEntity: ").append(toIndentedString(optionEntity)).append("\n");
    sb.append("    projectEntity: ").append(toIndentedString(projectEntity)).append("\n");
    sb.append("    versionEntity: ").append(toIndentedString(versionEntity)).append("\n");
    sb.append("    syncProjectName: ").append(toIndentedString(syncProjectName)).append("\n");
    sb.append("    syncVersionName: ").append(toIndentedString(syncVersionName)).append("\n");
    sb.append("    enabled: ").append(toIndentedString(enabled)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

