/*
 * Software Risk Manager API Guide
 * Software Risk Manager provides a variety of REST APIs, allowing external applications and scripts to interface with core functionality. This guide documents the various REST resources provided by Software Risk Manager.  ## Authentication  Authentication is a requirement when accessing API endpoints. There are two methods by which authentication may be performed.  ### API Keys  The primary method for authentication is passing an `API-Key` header containing a valid API key with all requests, i.e.  `API-Key: <key goes here>`  API Keys come in two possible forms:   - `api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24` - latest format  - `550e8400-e29b-41d4-a716-44665544000` - legacy format  For example:  `API-Key: api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24`  `API-Key: 550e8400-e29b-41d4-a716-44665544000`  API keys may be generated by Software Risk Manager admins. Once they are generated, in most cases, they behave like regular users. They will need to be assigned user roles for any projects they will be used with. Although it is possible to assign the *admin* [role](../user_guide/Project-Management/user_role_configuration.html) to an API key, the recommendation is to avoid doing so unless absolutely necessary.  See the user guide for an overview about how to create and manage [API keys](../user_guide/Settings/api_keys_administration.html).  ### Personal Access Tokens  Personal Access Tokens can be used as [bearer tokens](https://swagger.io/docs/specification/authentication/bearer-authentication/), e.g.  `Authorization: Bearer secret-token:qRuXr1BqgoTWXNxUhYQ8H_Yl2zfy6vxuqMIRnkGO`  Personal Access Tokens can be created by any user, and represent a subset of that user's permissions.   ### HTTP Basic Authentication  HTTP Basic authentication may be used to authenticate with the API as a regular user. This is accomplished by including an `Authorization` header containing a typical authorization credential.  ## Error Handling  ### Bad Requests  For API calls that accept input, invalid values will trigger an HTTP 400 Bad Request status code.  ### Server Errors  For any API call, if an unexpected error occurs, an HTTP 500 Internal Server Error status code will be returned. If an error message is available, the response will include a basic message body describing the error:  ` {   \"error\": \"error message\" } `  The error property will contain a string message indicating the nature of the error.  ### Errors with Third-Party Applications  Sometimes Software Risk Manager must communicate with third-party applications like JIRA, Git, and certain enterprise tools. Some users may have in-house versions of these with self-signed certificates which may not be \"trusted\". In these cases, the API will respond with an HTTP 502 BAD GATEWAY status. If this happens, refer to [Trusting Certificates](../install_guide/Installation/trusting-certs.html) in the install guide.  ### API Unavailable  In special circumstances, particularly during the installation and update phases, the API will be unavailable. When the API is unavailable, all calls will return an HTTP 503 Service Unavailable status, and no actions or side effects will occur as a result of the calls.  ## Examples  Software Risk Manager's API uses REST over HTTP. As such, you can use any language/utility that supports making HTTP requests to interact with the API. The examples below use <a href=\"https://curl.haxx.se/\" target=\"_blank\">curl</a>, a popular command-line utility, to do so.  First, you'll need to [generate an API Key](../user_guide/Settings/api_keys_administration.html). Second, while you can create projects through the API, these examples will assume that you've already created one. You'll need to know its project id number, which you can find by looking at the URL for the [Findings Page](../user_guide/Findings/findings_overview.html), which will end in a number.  **Note:** Many API endpoints require a JSON body in the request. Most JSON will contain double-quotes (`\"`) and spaces, which have special meaning when used on the command line. In order to ensure your JSON body is interpreted as a single argument, you must <a href=\"https://en.wikipedia.org/wiki/Escape_character\" target=\"_blank\">escape</a> it properly. For example, if you wanted to `POST` the following JSON body:  ```{ \"name\": \"John Doe\" }```  You would put a backslash (`\\`) before each double-quote (`\"`), and surround the whole thing with double-quotes:  ```\"{ \\\"name\\\": \\\"John Doe\\\" }\"```  The outermost double-quotes tell the command-line interpreter that everything within them is to be treated as a single argument (as opposed to the usual space-separated behavior). The backslash before each inner double-quote tells the command-line interpreter that you mean the literal double-quote character, and not the end of the quoted argument.  In many *non-Windows* operating systems, you can also use a single-quote (`'`) to surround the argument, and skip the backslashes:  ```'{ \"name\": \"John Doe\" }'```  The examples below will use the double-quotes and backslashes style, as it works on most (if not all) operating systems.  ### Running an Analysis  To start an analysis, you can run  ```curl -F file1=@src.zip -H \"API-Key: api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24\" https://<yoursrmserver>/srm/api/projects/<project id>/analysis```  Make sure you use your own values for the `src.zip` file, the API Key, the hostname for your Software Risk Manager server, and the project id.  ### Retrieving Finding Data  There is a wide variety of data available for the findings of a project after running an analysis. Two examples are provided here.  ### Findings Table Data  You can retrieve the data that's used to populate the [findings table](../user_guide/Findings/findings_table.html):  ```curl -H \"Content-Type: application/json\" -X POST -d \"{\\\"filter\\\":{},\\\"sort\\\":{\\\"by\\\":\\\"id\\\",\\\"direction\\\":\\\"ascending\\\"},\\\"pagination\\\":{\\\"page\\\":1,\\\"perPage\\\":10}}\" -H \"API-Key: api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24\" https://<yoursrmserver>/srm/api/projects/<project id>/findings/table```  Additional information about how to construct more useful filter and sort requests can be found in the documentation.  ### Finding Metadata  You can retrieve metadata for a finding, if you know the finding ID. You can take the ID for a finding from the Findings Table:  ```curl -H \"API-Key: api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24\" https://<yoursrmserver>/srm/api/findings/<finding id>```  ### Generating a Report  You can use the API to generate a PDF [report](../user_guide/Findings/generate_report.html).  ```curl -H \"Content-Type: application/json\" -X POST -d \"{\\\"filter\\\":{},\\\"config\\\":{\\\"summaryMode\\\":\\\"simple\\\",\\\"detailsMode\\\":\\\"simple\\\",\\\"includeResultDetails\\\":true,\\\"includeComments\\\":false}}\" -H \"API-Key: api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24\" https://<yoursrmserver>/srm/api/projects/<project id>/report/pdf```  ## Generating a Client SDK  If you require a client SDK for Software Risk Manager, you can generate one using [OpenAPI Generator](https://openapi-generator.tech/). Detailed instructions are available on the [GitHub page](https://github.com/OpenAPITools/openapi-generator) and our OpenAPI spec can be found [here](swagger/swagger.json). 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.codedx.client.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.codedx.client.model.AutoUpdateSetting;
import com.codedx.client.model.ConnectorValidationTokens;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.codedx.client.JSON;


/**
 * UpdateProjectScopedToolConnectorCOnfigEntityRequest
 */
@JsonPropertyOrder({
  UpdateProjectScopedToolConnectorCOnfigEntityRequest.JSON_PROPERTY_NAME,
  UpdateProjectScopedToolConnectorCOnfigEntityRequest.JSON_PROPERTY_BRANCH_SYNC_TARGET,
  UpdateProjectScopedToolConnectorCOnfigEntityRequest.JSON_PROPERTY_USE_DYNAMIC_VERSION,
  UpdateProjectScopedToolConnectorCOnfigEntityRequest.JSON_PROPERTY_AUTO_UPDATE,
  UpdateProjectScopedToolConnectorCOnfigEntityRequest.JSON_PROPERTY_AVAILABLE_DURING_ANALYSIS,
  UpdateProjectScopedToolConnectorCOnfigEntityRequest.JSON_PROPERTY_VALUES,
  UpdateProjectScopedToolConnectorCOnfigEntityRequest.JSON_PROPERTY_VALIDATION
})
@JsonTypeName("updateProjectScopedToolConnectorCOnfigEntity_request")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-02T11:55:06.722228-04:00[America/New_York]", comments = "Generator version: 7.21.0")
public class UpdateProjectScopedToolConnectorCOnfigEntityRequest {
  public static final String JSON_PROPERTY_NAME = "name";
  @jakarta.annotation.Nullable
  private String name;

  public static final String JSON_PROPERTY_BRANCH_SYNC_TARGET = "branchSyncTarget";
  private JsonNullable<String> branchSyncTarget = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_USE_DYNAMIC_VERSION = "useDynamicVersion";
  @jakarta.annotation.Nullable
  private Boolean useDynamicVersion;

  public static final String JSON_PROPERTY_AUTO_UPDATE = "autoUpdate";
  @jakarta.annotation.Nullable
  private AutoUpdateSetting autoUpdate;

  public static final String JSON_PROPERTY_AVAILABLE_DURING_ANALYSIS = "availableDuringAnalysis";
  @jakarta.annotation.Nullable
  private Boolean availableDuringAnalysis;

  public static final String JSON_PROPERTY_VALUES = "values";
  @jakarta.annotation.Nullable
  private Map<String, Object> values = new HashMap<>();

  public static final String JSON_PROPERTY_VALIDATION = "validation";
  @jakarta.annotation.Nullable
  private ConnectorValidationTokens validation;

  public UpdateProjectScopedToolConnectorCOnfigEntityRequest() { 
  }

  public UpdateProjectScopedToolConnectorCOnfigEntityRequest name(@jakarta.annotation.Nullable String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(@jakarta.annotation.Nullable String name) {
    this.name = name;
  }


  public UpdateProjectScopedToolConnectorCOnfigEntityRequest branchSyncTarget(@jakarta.annotation.Nullable String branchSyncTarget) {
    this.branchSyncTarget = JsonNullable.<String>of(branchSyncTarget);
    return this;
  }

  /**
   * The name of an SRM branch, which analyses using this tool connector should run in. If set as &#x60;null&#x60;, the project&#39;s default branch will be used
   * @return branchSyncTarget
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getBranchSyncTarget() {
        return branchSyncTarget.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_BRANCH_SYNC_TARGET, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getBranchSyncTarget_JsonNullable() {
    return branchSyncTarget;
  }
  
  @JsonProperty(JSON_PROPERTY_BRANCH_SYNC_TARGET)
  public void setBranchSyncTarget_JsonNullable(JsonNullable<String> branchSyncTarget) {
    this.branchSyncTarget = branchSyncTarget;
  }

  public void setBranchSyncTarget(@jakarta.annotation.Nullable String branchSyncTarget) {
    this.branchSyncTarget = JsonNullable.<String>of(branchSyncTarget);
  }


  public UpdateProjectScopedToolConnectorCOnfigEntityRequest useDynamicVersion(@jakarta.annotation.Nullable Boolean useDynamicVersion) {
    this.useDynamicVersion = useDynamicVersion;
    return this;
  }

  /**
   * When set as &#x60;true&#x60;, analyses using this tool connector will derive the Version form section information based on the analysis branch name.
   * @return useDynamicVersion
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_USE_DYNAMIC_VERSION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getUseDynamicVersion() {
    return useDynamicVersion;
  }


  @JsonProperty(value = JSON_PROPERTY_USE_DYNAMIC_VERSION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUseDynamicVersion(@jakarta.annotation.Nullable Boolean useDynamicVersion) {
    this.useDynamicVersion = useDynamicVersion;
  }


  public UpdateProjectScopedToolConnectorCOnfigEntityRequest autoUpdate(@jakarta.annotation.Nullable AutoUpdateSetting autoUpdate) {
    this.autoUpdate = autoUpdate;
    return this;
  }

  /**
   * Get autoUpdate
   * @return autoUpdate
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_AUTO_UPDATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AutoUpdateSetting getAutoUpdate() {
    return autoUpdate;
  }


  @JsonProperty(value = JSON_PROPERTY_AUTO_UPDATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAutoUpdate(@jakarta.annotation.Nullable AutoUpdateSetting autoUpdate) {
    this.autoUpdate = autoUpdate;
  }


  public UpdateProjectScopedToolConnectorCOnfigEntityRequest availableDuringAnalysis(@jakarta.annotation.Nullable Boolean availableDuringAnalysis) {
    this.availableDuringAnalysis = availableDuringAnalysis;
    return this;
  }

  /**
   * When set as &#x60;true&#x60;, this tool connector will be offered to run during &#39;normal&#39; analyses in addition to being able to run by itself.
   * @return availableDuringAnalysis
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_AVAILABLE_DURING_ANALYSIS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getAvailableDuringAnalysis() {
    return availableDuringAnalysis;
  }


  @JsonProperty(value = JSON_PROPERTY_AVAILABLE_DURING_ANALYSIS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAvailableDuringAnalysis(@jakarta.annotation.Nullable Boolean availableDuringAnalysis) {
    this.availableDuringAnalysis = availableDuringAnalysis;
  }


  public UpdateProjectScopedToolConnectorCOnfigEntityRequest values(@jakarta.annotation.Nullable Map<String, Object> values) {
    this.values = values;
    return this;
  }

  public UpdateProjectScopedToolConnectorCOnfigEntityRequest putValuesItem(String key, Object valuesItem) {
    if (this.values == null) {
      this.values = new HashMap<>();
    }
    this.values.put(key, valuesItem);
    return this;
  }

  /**
   * A key-value mapping, where each key in this object corresponds to a field key in a FormSpecifier, and each value should have an appropriate shape based on the type of that InputField
   * @return values
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_VALUES, required = false)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, Object> getValues() {
    return values;
  }


  @JsonProperty(value = JSON_PROPERTY_VALUES, required = false)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)
  public void setValues(@jakarta.annotation.Nullable Map<String, Object> values) {
    this.values = values;
  }


  public UpdateProjectScopedToolConnectorCOnfigEntityRequest validation(@jakarta.annotation.Nullable ConnectorValidationTokens validation) {
    this.validation = validation;
    return this;
  }

  /**
   * Get validation
   * @return validation
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_VALIDATION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ConnectorValidationTokens getValidation() {
    return validation;
  }


  @JsonProperty(value = JSON_PROPERTY_VALIDATION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setValidation(@jakarta.annotation.Nullable ConnectorValidationTokens validation) {
    this.validation = validation;
  }


  /**
   * Return true if this updateProjectScopedToolConnectorCOnfigEntity_request object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateProjectScopedToolConnectorCOnfigEntityRequest updateProjectScopedToolConnectorCOnfigEntityRequest = (UpdateProjectScopedToolConnectorCOnfigEntityRequest) o;
    return Objects.equals(this.name, updateProjectScopedToolConnectorCOnfigEntityRequest.name) &&
        equalsNullable(this.branchSyncTarget, updateProjectScopedToolConnectorCOnfigEntityRequest.branchSyncTarget) &&
        Objects.equals(this.useDynamicVersion, updateProjectScopedToolConnectorCOnfigEntityRequest.useDynamicVersion) &&
        Objects.equals(this.autoUpdate, updateProjectScopedToolConnectorCOnfigEntityRequest.autoUpdate) &&
        Objects.equals(this.availableDuringAnalysis, updateProjectScopedToolConnectorCOnfigEntityRequest.availableDuringAnalysis) &&
        Objects.equals(this.values, updateProjectScopedToolConnectorCOnfigEntityRequest.values) &&
        Objects.equals(this.validation, updateProjectScopedToolConnectorCOnfigEntityRequest.validation);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, hashCodeNullable(branchSyncTarget), useDynamicVersion, autoUpdate, availableDuringAnalysis, values, validation);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateProjectScopedToolConnectorCOnfigEntityRequest {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    branchSyncTarget: ").append(toIndentedString(branchSyncTarget)).append("\n");
    sb.append("    useDynamicVersion: ").append(toIndentedString(useDynamicVersion)).append("\n");
    sb.append("    autoUpdate: ").append(toIndentedString(autoUpdate)).append("\n");
    sb.append("    availableDuringAnalysis: ").append(toIndentedString(availableDuringAnalysis)).append("\n");
    sb.append("    values: ").append(toIndentedString(values)).append("\n");
    sb.append("    validation: ").append(toIndentedString(validation)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

