/*
 * Software Risk Manager API Guide
 * Software Risk Manager provides a variety of REST APIs, allowing external applications and scripts to interface with core functionality. This guide documents the various REST resources provided by Software Risk Manager.  ## Authentication  Authentication is a requirement when accessing API endpoints. There are two methods by which authentication may be performed.  ### API Keys  The primary method for authentication is passing an `API-Key` header containing a valid API key with all requests, i.e.  `API-Key: <key goes here>`  API Keys come in two possible forms:   - `api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24` - latest format  - `550e8400-e29b-41d4-a716-44665544000` - legacy format  For example:  `API-Key: api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24`  `API-Key: 550e8400-e29b-41d4-a716-44665544000`  API keys may be generated by Software Risk Manager admins. Once they are generated, in most cases, they behave like regular users. They will need to be assigned user roles for any projects they will be used with. Although it is possible to assign the *admin* [role](../user_guide/Project-Management/user_role_configuration.html) to an API key, the recommendation is to avoid doing so unless absolutely necessary.  See the user guide for an overview about how to create and manage [API keys](../user_guide/Settings/api_keys_administration.html).  ### Personal Access Tokens  Personal Access Tokens can be used as [bearer tokens](https://swagger.io/docs/specification/authentication/bearer-authentication/), e.g.  `Authorization: Bearer secret-token:qRuXr1BqgoTWXNxUhYQ8H_Yl2zfy6vxuqMIRnkGO`  Personal Access Tokens can be created by any user, and represent a subset of that user's permissions.   ### HTTP Basic Authentication  HTTP Basic authentication may be used to authenticate with the API as a regular user. This is accomplished by including an `Authorization` header containing a typical authorization credential.  ## Error Handling  ### Bad Requests  For API calls that accept input, invalid values will trigger an HTTP 400 Bad Request status code.  ### Server Errors  For any API call, if an unexpected error occurs, an HTTP 500 Internal Server Error status code will be returned. If an error message is available, the response will include a basic message body describing the error:  ` {   \"error\": \"error message\" } `  The error property will contain a string message indicating the nature of the error.  ### Errors with Third-Party Applications  Sometimes Software Risk Manager must communicate with third-party applications like JIRA, Git, and certain enterprise tools. Some users may have in-house versions of these with self-signed certificates which may not be \"trusted\". In these cases, the API will respond with an HTTP 502 BAD GATEWAY status. If this happens, refer to [Trusting Certificates](../install_guide/Installation/trusting-certs.html) in the install guide.  ### API Unavailable  In special circumstances, particularly during the installation and update phases, the API will be unavailable. When the API is unavailable, all calls will return an HTTP 503 Service Unavailable status, and no actions or side effects will occur as a result of the calls.  ## Examples  Software Risk Manager's API uses REST over HTTP. As such, you can use any language/utility that supports making HTTP requests to interact with the API. The examples below use <a href=\"https://curl.haxx.se/\" target=\"_blank\">curl</a>, a popular command-line utility, to do so.  First, you'll need to [generate an API Key](../user_guide/Settings/api_keys_administration.html). Second, while you can create projects through the API, these examples will assume that you've already created one. You'll need to know its project id number, which you can find by looking at the URL for the [Findings Page](../user_guide/Findings/findings_overview.html), which will end in a number.  **Note:** Many API endpoints require a JSON body in the request. Most JSON will contain double-quotes (`\"`) and spaces, which have special meaning when used on the command line. In order to ensure your JSON body is interpreted as a single argument, you must <a href=\"https://en.wikipedia.org/wiki/Escape_character\" target=\"_blank\">escape</a> it properly. For example, if you wanted to `POST` the following JSON body:  ```{ \"name\": \"John Doe\" }```  You would put a backslash (`\\`) before each double-quote (`\"`), and surround the whole thing with double-quotes:  ```\"{ \\\"name\\\": \\\"John Doe\\\" }\"```  The outermost double-quotes tell the command-line interpreter that everything within them is to be treated as a single argument (as opposed to the usual space-separated behavior). The backslash before each inner double-quote tells the command-line interpreter that you mean the literal double-quote character, and not the end of the quoted argument.  In many *non-Windows* operating systems, you can also use a single-quote (`'`) to surround the argument, and skip the backslashes:  ```'{ \"name\": \"John Doe\" }'```  The examples below will use the double-quotes and backslashes style, as it works on most (if not all) operating systems.  ### Running an Analysis  To start an analysis, you can run  ```curl -F file1=@src.zip -H \"API-Key: api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24\" https://<yoursrmserver>/srm/api/projects/<project id>/analysis```  Make sure you use your own values for the `src.zip` file, the API Key, the hostname for your Software Risk Manager server, and the project id.  ### Retrieving Finding Data  There is a wide variety of data available for the findings of a project after running an analysis. Two examples are provided here.  ### Findings Table Data  You can retrieve the data that's used to populate the [findings table](../user_guide/Findings/findings_table.html):  ```curl -H \"Content-Type: application/json\" -X POST -d \"{\\\"filter\\\":{},\\\"sort\\\":{\\\"by\\\":\\\"id\\\",\\\"direction\\\":\\\"ascending\\\"},\\\"pagination\\\":{\\\"page\\\":1,\\\"perPage\\\":10}}\" -H \"API-Key: api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24\" https://<yoursrmserver>/srm/api/projects/<project id>/findings/table```  Additional information about how to construct more useful filter and sort requests can be found in the documentation.  ### Finding Metadata  You can retrieve metadata for a finding, if you know the finding ID. You can take the ID for a finding from the Findings Table:  ```curl -H \"API-Key: api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24\" https://<yoursrmserver>/srm/api/findings/<finding id>```  ### Generating a Report  You can use the API to generate a PDF [report](../user_guide/Findings/generate_report.html).  ```curl -H \"Content-Type: application/json\" -X POST -d \"{\\\"filter\\\":{},\\\"config\\\":{\\\"summaryMode\\\":\\\"simple\\\",\\\"detailsMode\\\":\\\"simple\\\",\\\"includeResultDetails\\\":true,\\\"includeComments\\\":false}}\" -H \"API-Key: api-key:stNglRlu0HToJfmZH5EfqcjN6yFjC2ypj_v-jJ24\" https://<yoursrmserver>/srm/api/projects/<project id>/report/pdf```  ## Generating a Client SDK  If you require a client SDK for Software Risk Manager, you can generate one using [OpenAPI Generator](https://openapi-generator.tech/). Detailed instructions are available on the [GitHub page](https://github.com/OpenAPITools/openapi-generator) and our OpenAPI spec can be found [here](swagger/swagger.json). 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.codedx.client.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.codedx.client.JSON;


/**
 * Webhook
 */
@JsonPropertyOrder({
  Webhook.JSON_PROPERTY_ID,
  Webhook.JSON_PROPERTY_NAME,
  Webhook.JSON_PROPERTY_ENABLED,
  Webhook.JSON_PROPERTY_PAYLOAD_URL,
  Webhook.JSON_PROPERTY_SECRET,
  Webhook.JSON_PROPERTY_VERIFY_SSL,
  Webhook.JSON_PROPERTY_TRIGGER,
  Webhook.JSON_PROPERTY_PROJECT_SCOPE,
  Webhook.JSON_PROPERTY_EXPAND
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-02T11:55:06.722228-04:00[America/New_York]", comments = "Generator version: 7.21.0")
public class Webhook {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nullable
  private Integer id;

  public static final String JSON_PROPERTY_NAME = "name";
  @jakarta.annotation.Nullable
  private String name;

  public static final String JSON_PROPERTY_ENABLED = "enabled";
  @jakarta.annotation.Nullable
  private Boolean enabled;

  public static final String JSON_PROPERTY_PAYLOAD_URL = "payloadUrl";
  @jakarta.annotation.Nullable
  private String payloadUrl;

  public static final String JSON_PROPERTY_SECRET = "secret";
  @jakarta.annotation.Nullable
  private String secret;

  public static final String JSON_PROPERTY_VERIFY_SSL = "verifySsl";
  @jakarta.annotation.Nullable
  private Boolean verifySsl;

  /**
   * The event that will trigger this webhook
   */
  public enum TriggerEnum {
    FINDING_STATUS_UPDATE(String.valueOf("finding:status-update"));

    private String value;

    TriggerEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TriggerEnum fromValue(String value) {
      for (TriggerEnum b : TriggerEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TRIGGER = "trigger";
  @jakarta.annotation.Nullable
  private TriggerEnum trigger;

  public static final String JSON_PROPERTY_PROJECT_SCOPE = "projectScope";
  @jakarta.annotation.Nullable
  private String projectScope;

  /**
   * Gets or Sets expand
   */
  public enum ExpandEnum {
    DESCRIPTIONS(String.valueOf("descriptions")),
    
    DESCRIPTOR(String.valueOf("descriptor")),
    
    ISSUE(String.valueOf("issue")),
    
    TRIAGE_TIME(String.valueOf("triage-time")),
    
    HOST(String.valueOf("host")),
    
    METADATA(String.valueOf("metadata")),
    
    STANDARDS(String.valueOf("standards")),
    
    COMMENT_COUNT(String.valueOf("comment-count")),
    
    LAST_COMMENT_ACTION(String.valueOf("last-comment-action")),
    
    TAGS(String.valueOf("tags")),
    
    SOURCE_SNIPPET(String.valueOf("source-snippet")),
    
    PENDING_STATUS(String.valueOf("pending-status")),
    
    DUE_DATE_OVERRIDE(String.valueOf("due-date-override")),
    
    HAS_ATTACHMENTS(String.valueOf("has-attachments")),
    
    VULNERABILITIES(String.valueOf("vulnerabilities")),
    
    RESULTS(String.valueOf("results")),
    
    RESULTS_ACTIVE(String.valueOf("results.active")),
    
    RESULTS_COMPONENT_DETAILS(String.valueOf("results.component-details")),
    
    RESULTS_CONTAINER_IMAGE(String.valueOf("results.container-image")),
    
    RESULTS_CVES(String.valueOf("results.cves")),
    
    RESULTS_DATA_FLOWS(String.valueOf("results.data-flows")),
    
    RESULTS_DESCRIPTIONS(String.valueOf("results.descriptions")),
    
    RESULTS_DESCRIPTOR(String.valueOf("results.descriptor")),
    
    RESULTS_HOST(String.valueOf("results.host")),
    
    RESULTS_METADATA(String.valueOf("results.metadata")),
    
    RESULTS_RESOLVED_LOCATIONS(String.valueOf("results.resolved-locations")),
    
    RESULTS_VARIANTS(String.valueOf("results.variants")),
    
    RESULTS_VARIANTS_WITH_BODY(String.valueOf("results.variants.with-body")),
    
    RESULTS_VULNERABILITIES(String.valueOf("results.vulnerabilities")),
    
    AGGREGATIONS_TOOL_SUMMARY(String.valueOf("aggregations.tool-summary")),
    
    POLICY_VIOLATION_FIX_BY(String.valueOf("policy-violation-fix-by")),
    
    POLICY_VIOLATIONS(String.valueOf("policy-violations")),
    
    RESULT_COUNTS(String.valueOf("result-counts"));

    private String value;

    ExpandEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ExpandEnum fromValue(String value) {
      for (ExpandEnum b : ExpandEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_EXPAND = "expand";
  @jakarta.annotation.Nullable
  private List<ExpandEnum> expand = new ArrayList<>();

  public Webhook() { 
  }

  public Webhook id(@jakarta.annotation.Nullable Integer id) {
    this.id = id;
    return this;
  }

  /**
   * The ID of the webhook - omit when issuing a create or update request
   * @return id
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@jakarta.annotation.Nullable Integer id) {
    this.id = id;
  }


  public Webhook name(@jakarta.annotation.Nullable String name) {
    this.name = name;
    return this;
  }

  /**
   * The name of the webhook
   * @return name
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(@jakarta.annotation.Nullable String name) {
    this.name = name;
  }


  public Webhook enabled(@jakarta.annotation.Nullable Boolean enabled) {
    this.enabled = enabled;
    return this;
  }

  /**
   * Get enabled
   * @return enabled
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ENABLED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getEnabled() {
    return enabled;
  }


  @JsonProperty(value = JSON_PROPERTY_ENABLED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEnabled(@jakarta.annotation.Nullable Boolean enabled) {
    this.enabled = enabled;
  }


  public Webhook payloadUrl(@jakarta.annotation.Nullable String payloadUrl) {
    this.payloadUrl = payloadUrl;
    return this;
  }

  /**
   * The URL to which SRM will issue a POST request with finding data as the request body
   * @return payloadUrl
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PAYLOAD_URL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPayloadUrl() {
    return payloadUrl;
  }


  @JsonProperty(value = JSON_PROPERTY_PAYLOAD_URL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPayloadUrl(@jakarta.annotation.Nullable String payloadUrl) {
    this.payloadUrl = payloadUrl;
  }


  public Webhook secret(@jakarta.annotation.Nullable String secret) {
    this.secret = secret;
    return this;
  }

  /**
   * A secret value SRM will use to configure requests to the payload URL - the value will not be available to read once set
   * @return secret
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SECRET, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSecret() {
    return secret;
  }


  @JsonProperty(value = JSON_PROPERTY_SECRET, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSecret(@jakarta.annotation.Nullable String secret) {
    this.secret = secret;
  }


  public Webhook verifySsl(@jakarta.annotation.Nullable Boolean verifySsl) {
    this.verifySsl = verifySsl;
    return this;
  }

  /**
   * Enables SSL verification
   * @return verifySsl
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_VERIFY_SSL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getVerifySsl() {
    return verifySsl;
  }


  @JsonProperty(value = JSON_PROPERTY_VERIFY_SSL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVerifySsl(@jakarta.annotation.Nullable Boolean verifySsl) {
    this.verifySsl = verifySsl;
  }


  public Webhook trigger(@jakarta.annotation.Nullable TriggerEnum trigger) {
    this.trigger = trigger;
    return this;
  }

  /**
   * The event that will trigger this webhook
   * @return trigger
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TRIGGER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public TriggerEnum getTrigger() {
    return trigger;
  }


  @JsonProperty(value = JSON_PROPERTY_TRIGGER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTrigger(@jakarta.annotation.Nullable TriggerEnum trigger) {
    this.trigger = trigger;
  }


  public Webhook projectScope(@jakarta.annotation.Nullable String projectScope) {
    this.projectScope = projectScope;
    return this;
  }

  /**
   * A project ID or a special string representation of a set of projects:  - To represent a single project, use that project&#39;s ID number, e.g. &#x60;12&#x60; - To represent all projects, use &#x60;all&#x60; - To represent an arbitrary set of projects, join the IDs of each project with an underscore, e.g. &#x60;12_42_123_124&#x60; - To include &#39;descendant&#39; projects, add a &#x60;d&#x60; before the IDs of the main projects, e.g. &#x60;d12&#x60; or &#x60;d12_42_123_124&#x60; (note that there is only one &#x60;d&#x60; needed; it applies to each of the specified projects)
   * @return projectScope
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PROJECT_SCOPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getProjectScope() {
    return projectScope;
  }


  @JsonProperty(value = JSON_PROPERTY_PROJECT_SCOPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProjectScope(@jakarta.annotation.Nullable String projectScope) {
    this.projectScope = projectScope;
  }


  public Webhook expand(@jakarta.annotation.Nullable List<ExpandEnum> expand) {
    this.expand = expand;
    return this;
  }

  public Webhook addExpandItem(ExpandEnum expandItem) {
    if (this.expand == null) {
      this.expand = new ArrayList<>();
    }
    this.expand.add(expandItem);
    return this;
  }

  /**
   * An array of expand keys, each key adds additional data to findings in the request payload
   * @return expand
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_EXPAND, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<ExpandEnum> getExpand() {
    return expand;
  }


  @JsonProperty(value = JSON_PROPERTY_EXPAND, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExpand(@jakarta.annotation.Nullable List<ExpandEnum> expand) {
    this.expand = expand;
  }


  /**
   * Return true if this Webhook object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Webhook webhook = (Webhook) o;
    return Objects.equals(this.id, webhook.id) &&
        Objects.equals(this.name, webhook.name) &&
        Objects.equals(this.enabled, webhook.enabled) &&
        Objects.equals(this.payloadUrl, webhook.payloadUrl) &&
        Objects.equals(this.secret, webhook.secret) &&
        Objects.equals(this.verifySsl, webhook.verifySsl) &&
        Objects.equals(this.trigger, webhook.trigger) &&
        Objects.equals(this.projectScope, webhook.projectScope) &&
        Objects.equals(this.expand, webhook.expand);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, enabled, payloadUrl, secret, verifySsl, trigger, projectScope, expand);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Webhook {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    enabled: ").append(toIndentedString(enabled)).append("\n");
    sb.append("    payloadUrl: ").append(toIndentedString(payloadUrl)).append("\n");
    sb.append("    secret: ").append(toIndentedString(secret)).append("\n");
    sb.append("    verifySsl: ").append(toIndentedString(verifySsl)).append("\n");
    sb.append("    trigger: ").append(toIndentedString(trigger)).append("\n");
    sb.append("    projectScope: ").append(toIndentedString(projectScope)).append("\n");
    sb.append("    expand: ").append(toIndentedString(expand)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

