package com.codedx.client.api;

import com.codedx.client.ApiException;
import com.codedx.client.ApiClient;
import com.codedx.client.ApiResponse;
import com.codedx.client.Configuration;
import com.codedx.client.Pair;

import jakarta.ws.rs.core.GenericType;

import com.codedx.client.model.Metadata;
import com.codedx.client.model.MetadataUpdate;
import com.codedx.client.model.MetadataValue;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-02T11:55:06.722228-04:00[America/New_York]", comments = "Generator version: 7.21.0")
public class ProjectMetadataApi {
  private ApiClient apiClient;

  public ProjectMetadataApi() {
    this(Configuration.getDefaultApiClient());
  }

  public ProjectMetadataApi(ApiClient apiClient) {
    this.apiClient = apiClient;
  }

  /**
   * Get the API client
   *
   * @return API client
   */
  public ApiClient getApiClient() {
    return apiClient;
  }

  /**
   * Set the API client
   *
   * @param apiClient an instance of API client
   */
  public void setApiClient(ApiClient apiClient) {
    this.apiClient = apiClient;
  }

  /**
   * Create Project Metadata Field
   * Creates a project metadata field. The request body should contain a Project Metadata Field object, excluding any ids that should be generated by the API itself.  Requires the \&quot;Admin\&quot; role.
   * @param metadata  (required)
   * @return Metadata
   * @throws ApiException if fails to make API call
   * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
       <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
       <tr><td> 200 </td><td> OK - Contains the field object given by the request body, but with all API-generated ID values filled in </td><td>  -  </td></tr>
       <tr><td> 401 </td><td> Forbidden - User/key does not have read permission for the project </td><td>  -  </td></tr>
       <tr><td> 403 </td><td> Forbidden - One of the following:   - your Software Risk Manager license does not support the Project Metadata Fields feature   - you do not have the necessary permissions to modify fields  </td><td>  -  </td></tr>
       <tr><td> 500 </td><td> Internal Server Error - Unexpected failure </td><td>  -  </td></tr>
     </table>
   */
  public Metadata createMetadataField(@jakarta.annotation.Nonnull Metadata metadata) throws ApiException {
    return createMetadataFieldWithHttpInfo(metadata).getData();
  }

  /**
   * Create Project Metadata Field
   * Creates a project metadata field. The request body should contain a Project Metadata Field object, excluding any ids that should be generated by the API itself.  Requires the \&quot;Admin\&quot; role.
   * @param metadata  (required)
   * @return ApiResponse&lt;Metadata&gt;
   * @throws ApiException if fails to make API call
   * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
       <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
       <tr><td> 200 </td><td> OK - Contains the field object given by the request body, but with all API-generated ID values filled in </td><td>  -  </td></tr>
       <tr><td> 401 </td><td> Forbidden - User/key does not have read permission for the project </td><td>  -  </td></tr>
       <tr><td> 403 </td><td> Forbidden - One of the following:   - your Software Risk Manager license does not support the Project Metadata Fields feature   - you do not have the necessary permissions to modify fields  </td><td>  -  </td></tr>
       <tr><td> 500 </td><td> Internal Server Error - Unexpected failure </td><td>  -  </td></tr>
     </table>
   */
  public ApiResponse<Metadata> createMetadataFieldWithHttpInfo(@jakarta.annotation.Nonnull Metadata metadata) throws ApiException {
    // Check required parameters
    if (metadata == null) {
      throw new ApiException(400, "Missing the required parameter 'metadata' when calling createMetadataField");
    }

    String localVarAccept = apiClient.selectHeaderAccept("application/json");
    String localVarContentType = apiClient.selectHeaderContentType("application/json");
    String[] localVarAuthNames = new String[] {"APIKeyHeader", "basicAuth", "bearerAuth"};
    GenericType<Metadata> localVarReturnType = new GenericType<Metadata>() {};
    return apiClient.invokeAPI("ProjectMetadataApi.createMetadataField", "/api/project-fields", "POST", new ArrayList<>(), metadata,
                               new LinkedHashMap<>(), new LinkedHashMap<>(), new LinkedHashMap<>(), localVarAccept, localVarContentType,
                               localVarAuthNames, localVarReturnType, false);
  }
  /**
   * Delete Project Metadata Field
   * Deletes a project metadata field.  Requires the \&quot;Admin\&quot; role.
   * @param fieldId The ID of the metadata field. (required)
   * @param force If set to &#x60;true&#x60;, this will force the operation. Defaults to &#x60;false&#x60;. (optional)
   * @throws ApiException if fails to make API call
   * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
       <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
       <tr><td> 200 </td><td> OK - Successful delete </td><td>  -  </td></tr>
       <tr><td> 401 </td><td> Forbidden - User/key does not have read permission for the project </td><td>  -  </td></tr>
       <tr><td> 403 </td><td> Forbidden - One of the following:   - your Software Risk Manager license does not support the Project Metadata Fields feature   - you do not have the necessary permissions to modify fields  </td><td>  -  </td></tr>
       <tr><td> 404 </td><td> Not Found - No field with the given id </td><td>  -  </td></tr>
       <tr><td> 409 </td><td> Conflict - At least one project has a value configured for the would-be-deleted field, and force was set to false </td><td>  -  </td></tr>
       <tr><td> 500 </td><td> Internal Server Error - Unexpected failure </td><td>  -  </td></tr>
     </table>
   */
  public void deleteMetadata(@jakarta.annotation.Nonnull Integer fieldId, @jakarta.annotation.Nullable Boolean force) throws ApiException {
    deleteMetadataWithHttpInfo(fieldId, force);
  }

  /**
   * Delete Project Metadata Field
   * Deletes a project metadata field.  Requires the \&quot;Admin\&quot; role.
   * @param fieldId The ID of the metadata field. (required)
   * @param force If set to &#x60;true&#x60;, this will force the operation. Defaults to &#x60;false&#x60;. (optional)
   * @return ApiResponse&lt;Void&gt;
   * @throws ApiException if fails to make API call
   * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
       <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
       <tr><td> 200 </td><td> OK - Successful delete </td><td>  -  </td></tr>
       <tr><td> 401 </td><td> Forbidden - User/key does not have read permission for the project </td><td>  -  </td></tr>
       <tr><td> 403 </td><td> Forbidden - One of the following:   - your Software Risk Manager license does not support the Project Metadata Fields feature   - you do not have the necessary permissions to modify fields  </td><td>  -  </td></tr>
       <tr><td> 404 </td><td> Not Found - No field with the given id </td><td>  -  </td></tr>
       <tr><td> 409 </td><td> Conflict - At least one project has a value configured for the would-be-deleted field, and force was set to false </td><td>  -  </td></tr>
       <tr><td> 500 </td><td> Internal Server Error - Unexpected failure </td><td>  -  </td></tr>
     </table>
   */
  public ApiResponse<Void> deleteMetadataWithHttpInfo(@jakarta.annotation.Nonnull Integer fieldId, @jakarta.annotation.Nullable Boolean force) throws ApiException {
    // Check required parameters
    if (fieldId == null) {
      throw new ApiException(400, "Missing the required parameter 'fieldId' when calling deleteMetadata");
    }

    // Path parameters
    String localVarPath = "/api/project-fields/{field-id}"
            .replaceAll("\\{field-id}", apiClient.escapeString(fieldId.toString()));

    // Query parameters
    List<Pair> localVarQueryParams = new ArrayList<>(
            apiClient.parameterToPairs("", "force", force)
    );

    String localVarAccept = apiClient.selectHeaderAccept();
    String localVarContentType = apiClient.selectHeaderContentType();
    String[] localVarAuthNames = new String[] {"APIKeyHeader", "basicAuth", "bearerAuth"};
    return apiClient.invokeAPI("ProjectMetadataApi.deleteMetadata", localVarPath, "DELETE", localVarQueryParams, null,
                               new LinkedHashMap<>(), new LinkedHashMap<>(), new LinkedHashMap<>(), localVarAccept, localVarContentType,
                               localVarAuthNames, null, false);
  }
  /**
   * Get Project Metadata Fields (list).
   * Returns a list of metadata fields.  Requires no role, all users have sufficient permissions by default.
   * @return List&lt;Metadata&gt;
   * @throws ApiException if fails to make API call
   * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
       <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
       <tr><td> 200 </td><td> OK - Contains a list of Project Metadata Field objects </td><td>  -  </td></tr>
       <tr><td> 401 </td><td> Forbidden - User/key does not have read permission for the project </td><td>  -  </td></tr>
       <tr><td> 403 </td><td> Forbidden - Your Software Risk Manager License does not support the Project Metadata Fields feature </td><td>  -  </td></tr>
       <tr><td> 500 </td><td> Internal Server Error - Unexpected failure </td><td>  -  </td></tr>
     </table>
   */
  public List<Metadata> getAllMetadata() throws ApiException {
    return getAllMetadataWithHttpInfo().getData();
  }

  /**
   * Get Project Metadata Fields (list).
   * Returns a list of metadata fields.  Requires no role, all users have sufficient permissions by default.
   * @return ApiResponse&lt;List&lt;Metadata&gt;&gt;
   * @throws ApiException if fails to make API call
   * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
       <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
       <tr><td> 200 </td><td> OK - Contains a list of Project Metadata Field objects </td><td>  -  </td></tr>
       <tr><td> 401 </td><td> Forbidden - User/key does not have read permission for the project </td><td>  -  </td></tr>
       <tr><td> 403 </td><td> Forbidden - Your Software Risk Manager License does not support the Project Metadata Fields feature </td><td>  -  </td></tr>
       <tr><td> 500 </td><td> Internal Server Error - Unexpected failure </td><td>  -  </td></tr>
     </table>
   */
  public ApiResponse<List<Metadata>> getAllMetadataWithHttpInfo() throws ApiException {
    String localVarAccept = apiClient.selectHeaderAccept("*/*");
    String localVarContentType = apiClient.selectHeaderContentType();
    String[] localVarAuthNames = new String[] {"APIKeyHeader", "basicAuth", "bearerAuth"};
    GenericType<List<Metadata>> localVarReturnType = new GenericType<List<Metadata>>() {};
    return apiClient.invokeAPI("ProjectMetadataApi.getAllMetadata", "/api/project-fields", "GET", new ArrayList<>(), null,
                               new LinkedHashMap<>(), new LinkedHashMap<>(), new LinkedHashMap<>(), localVarAccept, localVarContentType,
                               localVarAuthNames, localVarReturnType, false);
  }
  /**
   * Get Project Metadata Fields (single)
   * Returns a single Project Metadata Field.  Requires no role, all users have sufficient permissions by default.
   * @param fieldId The ID of the metadata field. (required)
   * @return Metadata
   * @throws ApiException if fails to make API call
   * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
       <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
       <tr><td> 200 </td><td> OK - Contains a single Project Metadata Field object </td><td>  -  </td></tr>
       <tr><td> 401 </td><td> Forbidden - User/key does not have read permission for the project </td><td>  -  </td></tr>
       <tr><td> 403 </td><td> Forbidden - Your Software Risk Manager License does not support the Project Metadata Fields feature </td><td>  -  </td></tr>
       <tr><td> 404 </td><td> Not Found - No field with the given id </td><td>  -  </td></tr>
       <tr><td> 500 </td><td> Internal Server Error - Unexpected failure </td><td>  -  </td></tr>
     </table>
   */
  public Metadata getMetadata(@jakarta.annotation.Nonnull Integer fieldId) throws ApiException {
    return getMetadataWithHttpInfo(fieldId).getData();
  }

  /**
   * Get Project Metadata Fields (single)
   * Returns a single Project Metadata Field.  Requires no role, all users have sufficient permissions by default.
   * @param fieldId The ID of the metadata field. (required)
   * @return ApiResponse&lt;Metadata&gt;
   * @throws ApiException if fails to make API call
   * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
       <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
       <tr><td> 200 </td><td> OK - Contains a single Project Metadata Field object </td><td>  -  </td></tr>
       <tr><td> 401 </td><td> Forbidden - User/key does not have read permission for the project </td><td>  -  </td></tr>
       <tr><td> 403 </td><td> Forbidden - Your Software Risk Manager License does not support the Project Metadata Fields feature </td><td>  -  </td></tr>
       <tr><td> 404 </td><td> Not Found - No field with the given id </td><td>  -  </td></tr>
       <tr><td> 500 </td><td> Internal Server Error - Unexpected failure </td><td>  -  </td></tr>
     </table>
   */
  public ApiResponse<Metadata> getMetadataWithHttpInfo(@jakarta.annotation.Nonnull Integer fieldId) throws ApiException {
    // Check required parameters
    if (fieldId == null) {
      throw new ApiException(400, "Missing the required parameter 'fieldId' when calling getMetadata");
    }

    // Path parameters
    String localVarPath = "/api/project-fields/{field-id}"
            .replaceAll("\\{field-id}", apiClient.escapeString(fieldId.toString()));

    String localVarAccept = apiClient.selectHeaderAccept("application/json");
    String localVarContentType = apiClient.selectHeaderContentType();
    String[] localVarAuthNames = new String[] {"APIKeyHeader", "basicAuth", "bearerAuth"};
    GenericType<Metadata> localVarReturnType = new GenericType<Metadata>() {};
    return apiClient.invokeAPI("ProjectMetadataApi.getMetadata", localVarPath, "GET", new ArrayList<>(), null,
                               new LinkedHashMap<>(), new LinkedHashMap<>(), new LinkedHashMap<>(), localVarAccept, localVarContentType,
                               localVarAuthNames, localVarReturnType, false);
  }
  /**
   * Get Project Metadata Field Values
   * Load the Metadata Field values for a given project.  Requires the \&quot;project:view\&quot; permission which is provided by the \&quot;Reader\&quot; role.
   * @param projectId The ID of the project. (required)
   * @return List&lt;MetadataValue&gt;
   * @throws ApiException if fails to make API call
   * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
       <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
       <tr><td> 200 </td><td> OK - Contains an array of Project Metadata Field Value objects </td><td>  -  </td></tr>
       <tr><td> 401 </td><td> Forbidden - User/key does not have read permission for the project </td><td>  -  </td></tr>
       <tr><td> 403 </td><td> Forbidden - One of the following:   - your Software Risk Manager license does not support the Project Metadata Fields feature   - you do not have the necessary permissions to modify fields  </td><td>  -  </td></tr>
       <tr><td> 404 </td><td> Not Found - No project with the given id </td><td>  -  </td></tr>
       <tr><td> 500 </td><td> Internal Server Error - Unexpected failure </td><td>  -  </td></tr>
     </table>
   */
  public List<MetadataValue> getMetadataValue(@jakarta.annotation.Nonnull Integer projectId) throws ApiException {
    return getMetadataValueWithHttpInfo(projectId).getData();
  }

  /**
   * Get Project Metadata Field Values
   * Load the Metadata Field values for a given project.  Requires the \&quot;project:view\&quot; permission which is provided by the \&quot;Reader\&quot; role.
   * @param projectId The ID of the project. (required)
   * @return ApiResponse&lt;List&lt;MetadataValue&gt;&gt;
   * @throws ApiException if fails to make API call
   * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
       <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
       <tr><td> 200 </td><td> OK - Contains an array of Project Metadata Field Value objects </td><td>  -  </td></tr>
       <tr><td> 401 </td><td> Forbidden - User/key does not have read permission for the project </td><td>  -  </td></tr>
       <tr><td> 403 </td><td> Forbidden - One of the following:   - your Software Risk Manager license does not support the Project Metadata Fields feature   - you do not have the necessary permissions to modify fields  </td><td>  -  </td></tr>
       <tr><td> 404 </td><td> Not Found - No project with the given id </td><td>  -  </td></tr>
       <tr><td> 500 </td><td> Internal Server Error - Unexpected failure </td><td>  -  </td></tr>
     </table>
   */
  public ApiResponse<List<MetadataValue>> getMetadataValueWithHttpInfo(@jakarta.annotation.Nonnull Integer projectId) throws ApiException {
    // Check required parameters
    if (projectId == null) {
      throw new ApiException(400, "Missing the required parameter 'projectId' when calling getMetadataValue");
    }

    // Path parameters
    String localVarPath = "/api/projects/{project-id}/metadata"
            .replaceAll("\\{project-id}", apiClient.escapeString(projectId.toString()));

    String localVarAccept = apiClient.selectHeaderAccept("*/*", "application/json");
    String localVarContentType = apiClient.selectHeaderContentType();
    String[] localVarAuthNames = new String[] {"APIKeyHeader", "basicAuth", "bearerAuth"};
    GenericType<List<MetadataValue>> localVarReturnType = new GenericType<List<MetadataValue>>() {};
    return apiClient.invokeAPI("ProjectMetadataApi.getMetadataValue", localVarPath, "GET", new ArrayList<>(), null,
                               new LinkedHashMap<>(), new LinkedHashMap<>(), new LinkedHashMap<>(), localVarAccept, localVarContentType,
                               localVarAuthNames, localVarReturnType, false);
  }
  /**
   * Modify Project Metadata Field
   * Update the name, type, and/or values to match the value specified in the request body. When adding values to the values array, be sure to include all existing values. With this method, you may omit fields that you wish to leave unchanged.  Requires the \&quot;Admin\&quot; role.
   * @param fieldId The ID of the metadata field. (required)
   * @param metadata  (required)
   * @return Metadata
   * @throws ApiException if fails to make API call
   * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
       <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
       <tr><td> 200 </td><td> OK - Contains the field object with updated values, and filled in ids where necessary </td><td>  -  </td></tr>
       <tr><td> 401 </td><td> Forbidden - User/key does not have read permission for the project </td><td>  -  </td></tr>
       <tr><td> 403 </td><td> Forbidden - One of the following:   - your Software Risk Manager license does not support the Project Metadata Fields feature   - you do not have the necessary permissions to modify fields  </td><td>  -  </td></tr>
       <tr><td> 404 </td><td> Not Found - No field with the given id </td><td>  -  </td></tr>
       <tr><td> 409 </td><td> Conflict - A removed value was in use by one or more projects&#39; Metadata Field Values </td><td>  -  </td></tr>
       <tr><td> 422 </td><td> Unprocessable Entity - Incorrect id for pre-existing values </td><td>  -  </td></tr>
       <tr><td> 500 </td><td> Internal Server Error - Unexpected failure </td><td>  -  </td></tr>
     </table>
   */
  public Metadata modifyMetadata(@jakarta.annotation.Nonnull Integer fieldId, @jakarta.annotation.Nonnull Metadata metadata) throws ApiException {
    return modifyMetadataWithHttpInfo(fieldId, metadata).getData();
  }

  /**
   * Modify Project Metadata Field
   * Update the name, type, and/or values to match the value specified in the request body. When adding values to the values array, be sure to include all existing values. With this method, you may omit fields that you wish to leave unchanged.  Requires the \&quot;Admin\&quot; role.
   * @param fieldId The ID of the metadata field. (required)
   * @param metadata  (required)
   * @return ApiResponse&lt;Metadata&gt;
   * @throws ApiException if fails to make API call
   * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
       <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
       <tr><td> 200 </td><td> OK - Contains the field object with updated values, and filled in ids where necessary </td><td>  -  </td></tr>
       <tr><td> 401 </td><td> Forbidden - User/key does not have read permission for the project </td><td>  -  </td></tr>
       <tr><td> 403 </td><td> Forbidden - One of the following:   - your Software Risk Manager license does not support the Project Metadata Fields feature   - you do not have the necessary permissions to modify fields  </td><td>  -  </td></tr>
       <tr><td> 404 </td><td> Not Found - No field with the given id </td><td>  -  </td></tr>
       <tr><td> 409 </td><td> Conflict - A removed value was in use by one or more projects&#39; Metadata Field Values </td><td>  -  </td></tr>
       <tr><td> 422 </td><td> Unprocessable Entity - Incorrect id for pre-existing values </td><td>  -  </td></tr>
       <tr><td> 500 </td><td> Internal Server Error - Unexpected failure </td><td>  -  </td></tr>
     </table>
   */
  public ApiResponse<Metadata> modifyMetadataWithHttpInfo(@jakarta.annotation.Nonnull Integer fieldId, @jakarta.annotation.Nonnull Metadata metadata) throws ApiException {
    // Check required parameters
    if (fieldId == null) {
      throw new ApiException(400, "Missing the required parameter 'fieldId' when calling modifyMetadata");
    }
    if (metadata == null) {
      throw new ApiException(400, "Missing the required parameter 'metadata' when calling modifyMetadata");
    }

    // Path parameters
    String localVarPath = "/api/project-fields/{field-id}"
            .replaceAll("\\{field-id}", apiClient.escapeString(fieldId.toString()));

    String localVarAccept = apiClient.selectHeaderAccept("application/json");
    String localVarContentType = apiClient.selectHeaderContentType("application/json");
    String[] localVarAuthNames = new String[] {"APIKeyHeader", "basicAuth", "bearerAuth"};
    GenericType<Metadata> localVarReturnType = new GenericType<Metadata>() {};
    return apiClient.invokeAPI("ProjectMetadataApi.modifyMetadata", localVarPath, "PUT", new ArrayList<>(), metadata,
                               new LinkedHashMap<>(), new LinkedHashMap<>(), new LinkedHashMap<>(), localVarAccept, localVarContentType,
                               localVarAuthNames, localVarReturnType, false);
  }
  /**
   * Update Project Metadata Field Values
   * Update the project metadata values for a given project. Values are given for fields which have been previously defined as Project Metadata Fields.  Requires the \&quot;project:manage-metadata\&quot; permission which is provided by the \&quot;Manager\&quot; role.
   * @param projectId The ID of the project. (required)
   * @param metadataUpdate  (required)
   * @return List&lt;MetadataValue&gt;
   * @throws ApiException if fails to make API call
   * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
       <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
       <tr><td> 200 </td><td> OK - Contains the updated array of values for the project </td><td>  -  </td></tr>
       <tr><td> 400 </td><td> Bad Request - The request body referenced an invalid field id, or entered an invalid value for a field </td><td>  -  </td></tr>
       <tr><td> 401 </td><td> Forbidden - User/key does not have read permission for the project </td><td>  -  </td></tr>
       <tr><td> 403 </td><td> Forbidden - One of the following:   - your Software Risk Manager license does not support the Project Metadata Fields feature   - you do not have the necessary permissions to modify fields  </td><td>  -  </td></tr>
       <tr><td> 404 </td><td> Not Found - No project with the given id </td><td>  -  </td></tr>
       <tr><td> 500 </td><td> Internal Server Error - Unexpected failure </td><td>  -  </td></tr>
     </table>
   */
  public List<MetadataValue> updateMetadataValue(@jakarta.annotation.Nonnull Integer projectId, @jakarta.annotation.Nonnull List<MetadataUpdate> metadataUpdate) throws ApiException {
    return updateMetadataValueWithHttpInfo(projectId, metadataUpdate).getData();
  }

  /**
   * Update Project Metadata Field Values
   * Update the project metadata values for a given project. Values are given for fields which have been previously defined as Project Metadata Fields.  Requires the \&quot;project:manage-metadata\&quot; permission which is provided by the \&quot;Manager\&quot; role.
   * @param projectId The ID of the project. (required)
   * @param metadataUpdate  (required)
   * @return ApiResponse&lt;List&lt;MetadataValue&gt;&gt;
   * @throws ApiException if fails to make API call
   * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
       <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
       <tr><td> 200 </td><td> OK - Contains the updated array of values for the project </td><td>  -  </td></tr>
       <tr><td> 400 </td><td> Bad Request - The request body referenced an invalid field id, or entered an invalid value for a field </td><td>  -  </td></tr>
       <tr><td> 401 </td><td> Forbidden - User/key does not have read permission for the project </td><td>  -  </td></tr>
       <tr><td> 403 </td><td> Forbidden - One of the following:   - your Software Risk Manager license does not support the Project Metadata Fields feature   - you do not have the necessary permissions to modify fields  </td><td>  -  </td></tr>
       <tr><td> 404 </td><td> Not Found - No project with the given id </td><td>  -  </td></tr>
       <tr><td> 500 </td><td> Internal Server Error - Unexpected failure </td><td>  -  </td></tr>
     </table>
   */
  public ApiResponse<List<MetadataValue>> updateMetadataValueWithHttpInfo(@jakarta.annotation.Nonnull Integer projectId, @jakarta.annotation.Nonnull List<MetadataUpdate> metadataUpdate) throws ApiException {
    // Check required parameters
    if (projectId == null) {
      throw new ApiException(400, "Missing the required parameter 'projectId' when calling updateMetadataValue");
    }
    if (metadataUpdate == null) {
      throw new ApiException(400, "Missing the required parameter 'metadataUpdate' when calling updateMetadataValue");
    }

    // Path parameters
    String localVarPath = "/api/projects/{project-id}/metadata"
            .replaceAll("\\{project-id}", apiClient.escapeString(projectId.toString()));

    String localVarAccept = apiClient.selectHeaderAccept("*/*", "application/json");
    String localVarContentType = apiClient.selectHeaderContentType();
    String[] localVarAuthNames = new String[] {"APIKeyHeader", "basicAuth", "bearerAuth"};
    GenericType<List<MetadataValue>> localVarReturnType = new GenericType<List<MetadataValue>>() {};
    return apiClient.invokeAPI("ProjectMetadataApi.updateMetadataValue", localVarPath, "PUT", new ArrayList<>(), metadataUpdate,
                               new LinkedHashMap<>(), new LinkedHashMap<>(), new LinkedHashMap<>(), localVarAccept, localVarContentType,
                               localVarAuthNames, localVarReturnType, false);
  }
}
